### ISSUE TITLE
(nmap) Failed automated testing

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#1000]
https://chocolatey.org/packages/nmap/7.70

Link to gist output:

https://gist.github.com/choco-bot/e420f6e3c0b2d5587d15b26f3a9c546a

**Comment by AdmiringWorm** [comment]
Seems like it's caused by using the wrong variable when calling Remove-Item.
Easy fix, and I'll look into it tomorrow after work. Unless someone beat me to it of course.

**Comment by AdmiringWorm** [comment]
This have been fixed, and is in the process of forcing an update to the failed package
