### ISSUE TITLE
(curl) package doesn't include x64 libcurl.dll

### ISSUE THREAD

**Issue by LuisGP** [chocolatey/chocolatey-coreteampackages#1004]
As the title stablishes, cURL package for chocolatey doesn't have the precompiled x64 libcurl.dll. 
x32 version is already in the package.

This causes that when installing through choco the cURL package in a x64 environment, you cannot link against libcurl. 

Simply adding the x64 version would be great and will simplify a lot build files and projects that depend on libcurl.

For example, I'm currently working on a project that depends on libcurl. The main diference between build the project on linux versus windows is that in windows we must add curl as a git submodule, compile it by ourselves and link against the generated dll, with the needed changes on our CMakeLists.txt file.
If libcurl.dll x64 would be included by chocolatey, our CMakeLists.txt would be much simplier and clearer, and an entire submodule could be removed.

Thanks!

**Comment by majkinetor** [comment]
A bug actually, now looking at code.

I will fix this soon.
