### ISSUE TITLE
(skype) automatic update

### ISSUE THREAD

**Issue by BobSammers** [chocolatey/chocolatey-coreteampackages#1005]
Looking through the repos here, it seems Skype has been updated to the latest version (7.41) and moved from @ferventcoder's repo to the core team.

The PR for this was merged a couple of weeks ago, but the version Chocolatey attempts to download is still an out-of-date version (7.39). What's more, the installer is missing (404 error), so the package is actually broken. 

Nothing seems to have triggered a release of the new version onto the public server, which means that Skype is still broken some time after the work to fix it was completed.

**Comment by AdmiringWorm** [comment]
I've fixed this locally, just a little testing then I'll push an update out for this.

**Comment by AdmiringWorm** [comment]
I knew I forgot something, I'll get that added again when I get home from work. Sorry about that

**Comment by BobSammers** [comment]
:smiley:

**Comment by AdmiringWorm** [comment]
a new version have been pushed to chocolatey, and should be available automatically in a few hours

**Comment by BobSammers** [comment]
Works perfectly - thank you!
