### ISSUE TITLE
Clover outdated

### ISSUE THREAD

**Issue by vanyasem** [chocolatey/chocolatey-coreteampackages#1006]
The latest Clover version is [3.4.3](http://en.ejie.me/), but the package is [3.2.3](https://chocolatey.org/packages/Clover)

## Possible Solution
Update the package to the latest version

## Context
I was trying to install the latest version of Clover from Chocolatey

## Your Environment
* Operating System and version: Windows 10
* Chocolatey version: 0.10.10

**Comment by AdmiringWorm** [comment]
We're aware, and as it's mentioned in the disqus section of the website, updating have been stopped for this software.

The latest version have 11 positive results for viruses/malware, in which case we won't be updating to this version either.

**Comment by AdmiringWorm** [comment]
I recommend that you find alternatives to clover
