### ISSUE TITLE
Cygwin fails to create pseudo-symlinks

### ISSUE THREAD

**Issue by TomOne** [chocolatey/chocolatey-coreteampackages#101]
Since the recent change of the installation folder to `$PSScriptRoot\cygwin`, Cygwin is no longer able to create symlinks (e. g. for `awk`).

This was reported here: https://chocolatey.org/packages/Cygwin#comment-2419682542

Possible workaround: Switch back to `$env:ChocolateyBinRoot`. But that’s not a really good idea, because binroot is going to be deprecated and makes the package less self contained. In addition, some folks wanted to switch to `$PSScriptRoot` and are certainly not amused if we switch back to binroot.

**Comment by knime** [comment]
I can confirm that this issue is related to Cygwin's installation directory. I tried several different locations via "choco install" starting from C:\cygwin64, over C:\ProgramData\chocolatey\cygwin64, to C:\ProgramData\chocolatey\lib\Cygwin\cygwin64. Only the last location showed the described behaviour with the broken symlinks.
Why isn't Cygwin installed into its standard directory C:\cygwin64 anyway? There are other tools, such as salt, that rely on this standard location (which you can argue if this is correct, of course).

**Comment by ferventcoder** [comment]
BinRoot will be deprecated for ToolsRoot. :+1: It's fine to use binroot for now.

**Comment by TomOne** [comment]
Strange. Reinstalling `gawk` with Cygwin fixed the `awk` -> `gawk` symlink for me. Therefore it only seems to fail during the Cygwin installation.

**Comment by iainnicol** [comment]
The broken symlinks are missing the Windows file attribute called System. I don't know what about the installation directory causes that. But it's definitely this missing attribute which causes the problem:

```powershell
# Fix one symlink from PowerShell:
PS> $link="${env:ProgramData}/chocolatey/lib/cygwin/tools/cygwin/etc/ssl"
PS> $file.Attributes = 'System'
```
```bash
# Verify the fix from Cygwin bash:
$ file /etc/ssl/certs
/etc/ssl/certs: symbolic link to /usr/ssl/certs
```

**Comment by TomOne** [comment]
Thanks @iainnicol, good catch.

I tried to install Cygwin manually in the same directory as the package would install it (`%PROGRAMDATA%\chocolatey\lib\cygwin\tools\cygwin`) and it generated the correct symlinks. So the issue must be somehow related to Chocolatey itself, not to the install directory.

We could include workaround code into the package that iterates over all broken symlinks and adds the system attribute to them. That wouldn’t be the nicest way to solve it, of course.

I’ll investigate this issue further.

**Comment by gpakosz** [comment]
Being a new Chocolatey user, I just stumbled upon this problem. 2 months later, did you agree on an official workaround until this gets fixed?
