### ISSUE TITLE
(gimp) 2.10 autopackage not working

### ISSUE THREAD

**Issue by jongalloway** [chocolatey/chocolatey-coreteampackages#1014]
Gimp 2.10 is out, and they've published a Windows installer. However, it looks like updates to the downloads page have broken the autopackage.

## Expected Behavior
Gimp 2.10 release due to autopackage

## Current Behavior
2.10 release is not listed, status shows [error for Gimp package](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#errors)

## Possible Solution
I think the parsing in [update.ps1](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/gimp/update.ps1) was broken by changes to the Gimp downloads page. They no longer list a 32 bit installer, and they list a torrent with .exe in the filename (https://download.gimp.org/pub/gimp/v2.10/windows/gimp-2.10.0-x64-setup.exe.torrent) which I think is getting picked up by the regex since it looks for .exe.

**Comment by gep13** [comment]
This was resolved here:

https://github.com/chocolatey/chocolatey-coreteampackages/commit/e44b4bbccc27baf6eaea295eb05f86bf451cce12

**Comment by gep13** [comment]
Based on a suggestion from @AdmiringWorm here:

https://gitter.im/chocolatey/chocolatey-coreteampackages?at=5aeb5d25ff26986d082e2ad2
