### ISSUE TITLE
(skype) Package installs older version 7.41

### ISSUE THREAD

**Issue by gotylergo** [chocolatey/chocolatey-coreteampackages#1018]
Skype installer is far out of date.

## Expected Behavior
When running "choco install skype", the newest version of Skype is installed.

## Current Behavior
Older version Skype 7.41 is installed.

## Possible Solution
From my conversation with others in the comments on the package page ( https://chocolatey.org/packages/skype#comment-3883854915 ) the package installer was broken for a bit due to Microsoft removing the msi links from their servers and only including the exe which was causing failures. I was able to correct by grabbing the Skype installer used by Ninite. Steps: go to https://ninite.com , select Skype, download, run installer, while installing, view %temp% folder and copy  the target.exe file that is created, which is the Skype installer that can be made silent. I tested and was able to build a package using it which installed successfully with the args /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-' I verified this installer will also do an upgrade from the previous 7.41 version that's available in the chocolatey repo.

## Your Environment
Package Version used: skype 7.41.0.10101
OS: Windows 7
Chocolatey version: 0.10.10
Nupkg: https://gist.github.com/gotylergo/2345479266df77b36222de0ba679c2c6
chocolateyinstall.ps1: https://gist.github.com/gotylergo/430ae4796c7de0b84248f7c6e2781825

**Comment by majkinetor** [comment]
Design choice ATM, see https://github.com/chocolatey/chocolatey-coreteampackages/pull/995

**Comment by AdmiringWorm** [comment]
@gotylergo technically it isn't outdated, as it's the version they provide on the skype page when you try to download it manually.

While skype perhaps notifies that a new version is available, we can't really do much until they also provide it on their download page.

**Comment by gotylergo** [comment]
@AdmiringWorm When I go to skype.com and click download, it grabs 8.20.0.9.

**Comment by AdmiringWorm** [comment]
@gotylergo that's odd, when I try to download the classic skype manually it just delivers 7.41.
You sure you're not installing the Windows Store edition of Skype? (This is completely different application than the classic skype, and isn't possible to install through chocolatey AFAIK).

**Comment by gotylergo** [comment]
No I'm on Windows 7 downloading from skype.com. No windows store here.

**Comment by gotylergo** [comment]
There's also a Skype Classic available from their website which is an older version: 7.41.0.101? But I don't believe these are different applications. Skype classic is just an older version of the same application offered for compatibility with older machines (Vista or XP) since the newer version doesn't support any OS before Windows 7. Per: https://support.skype.com/en/faq/FA10328/what-are-the-system-requirements-for-skype

**Comment by AdmiringWorm** [comment]
It's different than the one provided on the windows store, but no. Not the one supplied on the homepage of skype when running on windows 7.

I think perhaps we should investigate this a little more before we can say anything conclusive.

**Comment by gotylergo** [comment]
@AdmiringWorm Interesting. I think this has something to do with them trying to force the UWP (Windows Store) version, but then rescinding a bit and offering "Skype Classic" again, and after realizing that a lot of their user base hasn't upgraded to Windows 8 or 10, offering the older version again. I was reading articles about it. But I can't speak for Microsoft of course. And the logic behind offering the older version for everyone when there's a newer version of the desktop app available doesn't make a lot of sense. May have been website design oversight.

I can confirm though that installing Skype 8 (newest version) does indeed replace Skype 7.41 (or classic as Microsoft is calling it).

**Comment by AdmiringWorm** [comment]
@gotylergo before we add any changes, I would like some input from the user that submitted the PR.

@jberezanski why was the decision made to use the classic edition, instead of edition supplied when running on Windows 7?

**Comment by majkinetor** [comment]
AFAIK @jberezanski wanted last classic version because v8 seems to be different product. Now that last classic version is present (if it is going to receive updates then this has to be streamed), v8 could be added without making a new package for it.

**Comment by majkinetor** [comment]
I tested v8 on personal computer since classic skype couldn't connect any more. It replaces that v7. This should be done as requested.

**Comment by majkinetor** [comment]
Classifying this as a bug as package is not the latest. 

This package was accepted here in speed as Skype was not updated for a longer time, which was apparently not a good decision - on this repo, package is either done correctly or its not here.

**Comment by AdmiringWorm** [comment]
@majkinetor what's the likelihood that the classic edition will be updated (bug fixes), I'm trying to figure out if we should change the update script to use streams or to just handle the latest available.

**Comment by majkinetor** [comment]
We can always add stream later if it happens since we can only guess without official info.

**Comment by AdmiringWorm** [comment]
A new version was just pushed to chocolatey now:
https://chocolatey.org/packages/skype/8.21.0.9
