### ISSUE TITLE
(virtualbox) Installs non-free ExtensionPack despite /NoExtensionPack flag

### ISSUE THREAD

**Issue by gigaturtle** [chocolatey/chocolatey-coreteampackages#1019]
## Expected Behavior
Per the package page, installing with the /NoExtensionPack flag should omit the non-free Extension Pack.

## Current Behavior
Extension pack was installed.

## Possible Solution
Not sure exactly what's going wrong here. My "in a perfect world" solution to this would be to have an alternate/virtual package that only installs the FOSS base package for VirtualBox and completely omits the additional licensed Extension Pack. 

Alternately, maybe make the default install FOSS only and have non-free software opt-in with a /WithExtensionPack flag.

## Steps to Reproduce (for bugs)
cinst virtualbox /NoExtensionPack -y

## Context
This issue is particularly problematic for me since I'm using this in a corporate environment. Having the non-free extension pack unexpectedly installed has licensing implications.

## Your Environment
* Package Version used:  5.2.10
* Operating System and version:  Win7 Enterprise
* Chocolatey version:  0.10.10
* Install/uninstall gist:  https://gist.github.com/gigaturtle/c9b2b741698bcb2fb2513684e0a89025

**Comment by majkinetor** [comment]
The command is not OK:
should be

`cinst virtualbox --params /NoExtensionPack -y`

**Comment by jamy015** [comment]
Could a sentence be added to the description to make it more clear that you also need `--params`?

**Comment by majkinetor** [comment]
No, because people should know how basic chocolatey works.

**Comment by jamy015** [comment]
It's under the 'advanced install concepts' section in the [getting started guide](https://chocolatey.org/docs/getting-started#overriding-default-install-directory-or-other-advanced-install-concepts) (and even there it's behind a link) - I don't think something can be basic and advanced at the same time.

**Comment by majkinetor** [comment]
Its actually among basic cinst examples [here](https://github.com/chocolatey/choco/wiki/CommandsInstall#examples).

**Comment by AdmiringWorm** [comment]
I'ts also shown as an example when you run `cinst --help`.

**Comment by gigaturtle** [comment]
Dang, I was hoping it wasn't something dumb. I do want to point out while you guys are obviously familiar with usage minutiae, I have been using choco at a basic level (cinst/cuninst) for years and never had a need to specify params until I realized you're including a non-free extension in this package by default. 

Looking at the params section on the [package page](https://chocolatey.org/packages/virtualbox), gives no indication that `--params` exists or is necessary. And `choco --help` has a section about passing / Switches, which I misunderstood as being inclusive of /Parameters functionality. 

I still want to encourage you guys to consider **not** including the optional non-free extension by default, but either way thanks for the clarification.
