### ISSUE TITLE
(dropbox) AU updater fails due to the Get-RedirectedUrl bug

### ISSUE THREAD

**Issue by RedBaron2** [chocolatey/chocolatey-coreteampackages#1022]
The [AU status of dropbox package](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f/455aeb6c215ea79d2a03a103649c5a35afaccef3#dropbox) 
## Expected Behavior
If you're describing a bug, tell us what should happen
When using the powershell command
`[uri]::EscapeUriString($url)`
 in `Get-RedirectedUrl` helper
the result is
`https://clientupdates.dropboxstatic.com/dbx-releng/client/Dropbox%252048.4.58%2520Offline%2520Installer.exe`
when it should be
`https://clientupdates.dropboxstatic.com/dbx-releng/client/Dropbox%252048.4.58%20Offline%20Installer.exe`

## Current Behavior
If describing a bug, tell us what happens instead of the expected behavior
The current behavior results in a 403 forbidden error

## Possible Solution

The easiest fix is to PR the `Get-RedirectedUrl` helper to have a switch for EscapeUriString usage
PR is being submitted

## Steps to Reproduce (for bugs)

1. `Get-RedirectedUrl "https://www.dropbox.com/download?build=48.4.58&plat=win&type=full"`
2.
3.
4.

## Your Environment

* Package Version used: Latest
* Operating System and version: 10.0.17661.1001 build 1803
* Chocolatey version: N/A
* Install/uninstall gist: [Chocobot](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f/455aeb6c215ea79d2a03a103649c5a35afaccef3)

**Comment by AdmiringWorm** [comment]
@RedBaron2 when I mentioned to create a issue, I meant on the plugin repo.
I'm using the issues itself to generate a changelog, so a issue is needed for me to accept a PR.
We can leave this one open though, until I've released a bugfix for the plugin.

**Comment by RedBaron2** [comment]
😢 I will open a issue there also ?_?

**Comment by AdmiringWorm** [comment]
yes, please.

**Comment by RedBaron2** [comment]
@AdmiringWorm 
This has been fixed with your update to the script, right?
It doesn't seem to affect the `dropbox` package improperly.

**Comment by AdmiringWorm** [comment]
yeah, it has. Completely forgot to close this issue.
