### ISSUE TITLE
(curl) Header files and linking .lib file

### ISSUE THREAD

**Issue by LuisGP** [chocolatey/chocolatey-coreteampackages#1026]
It would be nice if curl package include headers and lib files to make possible compile and link against it using choco.

Thank you very much.

**Comment by AdmiringWorm** [comment]
I doubt we would include the header and lib files in this package, unless they suddenly include it in the normal archive on the authors download site.

**Comment by AdmiringWorm** [comment]
ah, I see. I must have missed that from the package source.

Guess maybe adding a parameter to keep them could be supported?
I don't think most users would need them, although it probably wouldn't matter to most users anyhow whether they are kept or not.

**Comment by majkinetor** [comment]
It just adds ~1MB to the package so I added them.
