### ISSUE TITLE
(visualstudiocode) Rename to vscode

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#1030]
The name is too long and prone to typos. We should rename package to `vscode` and deprecate original package. The same name is used as MS repo on github.

/cc @AdmiringWorm @pascalberger

**Comment by pascalberger** [comment]
OK, for me. Especially as the name has issues, since the casing was changed at some point

**Comment by majkinetor** [comment]
Package is already owned by someone 
https://chocolatey.org/packages/vscode

@gep13, could you make chocolatey user own it ?

**Comment by gep13** [comment]
@majkinetor sure thing.  Chocolatey user has been added to that package.

**Comment by majkinetor** [comment]
@gep, visualstudiocode is deprecated and pushed. Please make vscode trusted so that we don't have a gap.

**Comment by AdmiringWorm** [comment]
@majkinetor the chocolatey user is a trusted user, so packages will be marked as trusted automatically.
It's only the first version that's subjected to human review when pushing from the chocolatey user.

**Comment by majkinetor** [comment]
OK.

Notice that original package is already deprecated and approved so need to make vscode approved immediately.

**Comment by pascalberger** [comment]
@majkinetor @gep13 Did you have changed maintainers by intention while switching the package names? And who is [jgoesmat](https://chocolatey.org/profiles/jgoemat)?

**Comment by gep13** [comment]
@pascalberger jgoesmat was the original user who pushed the vscode package.  Initially, I rejected this package, because the visualstudiocode package already existed, so it was essentially a duplicate package.  However, recently, it was decided to re-instate that package, since the name is preferrable.

**Comment by majkinetor** [comment]
I would return original maintainers but I don't have the rights.

**Comment by pascalberger** [comment]
@gep13 @majkinetor This lead now to an issue with dependencies. For example any of the Visual Studio Code extensions (e.g. [vscode-powershell](https://chocolatey.org/packages/vscode-powershell)) have a dependency to `VisualStudioCode >= 1.2.0`. How do we proceed here the best? Changing dependencies to `vscode >= 1.24.0` or adding old Visual Studio Code package versions to the `vscode` package or remove the dependency at all?

**Comment by gep13** [comment]
@AdmiringWorm agreed.

**Comment by majkinetor** [comment]
> This lead now to an issue with dependencies

What issue ? :)

**Comment by pascalberger** [comment]
> What issue ? :)

Extensions trying to install old Visual Studio Code package.

I'll look to update the extension packages to the new `vscode` package

**Comment by majkinetor** [comment]
> Extensions trying to install old Visual Studio Code package.

So ? The old VisualStudioCode package will install vscode package in return.

**Comment by AdmiringWorm** [comment]
@majkinetor while I wouldn't say it's a issue, it could cause some confusion to users.
Especially considering that the old package is outputting a message that it is deprecated.

**Comment by majkinetor** [comment]
No issue. Just cosmetics. Whatever is fine by me.
