### ISSUE TITLE
(python2) Ensure pip works from shell

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#1032]
As discussed here:

https://github.com/Microsoft/windows-dev-box-setup-scripts/issues/39#issuecomment-388613732

If it makes sense, the python packages should be extended to ensure that pip works out of the box.  Pip is installed with these packages, however, it doesn't work from the command line, as the `C:\pythonXX\scripts` folder isn't on the path.

Does it make sense to add shims to there executables? Or perhaps to add the above path to the system path variable?

**Comment by majkinetor** [comment]
It looks like python2 installer has this **tools** [option ](https://www.python.org/download/releases/2.4/msi/) that should be used in silent args. That is where pip might be.

**Comment by majkinetor** [comment]
Thanks, I added note to readme.
