### ISSUE TITLE
(typescript) Should this take a dependency on the LTS version?

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#1033]
Rather than the latest Node Version?

//cc @pascalberger @AdmiringWorm 

This came up in this issue:

https://github.com/Microsoft/vsts-image-generation/issues/135#issuecomment-388804222

**Comment by AdmiringWorm** [comment]
Yeah, I guess we probably should do that.
I actually wish there was a better way to handle these kind of dependencies though.

Oh well, maybe in the future.

**Comment by gep13** [comment]
@AdmiringWorm agreed, I think that this is an area that could be improved in the future, once package indexes and true meta packages exist, but for now, I think that changing the dependency makes the most sense.

**Comment by AdmiringWorm** [comment]
> I think that changing the dependency makes the most sense.

Working on it now
