### ISSUE TITLE
(git) Include the "core.longpaths" settings to be configured via parameters

### ISSUE THREAD

**Issue by tempora-mutantur** [chocolatey/chocolatey-coreteampackages#1038]
If you worked with any project that has very long paths structure you've probably already faced this issue: [Filename too long in git for windows
](https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows)

New versions of Git have the `core.longpaths` setting which allows you to checkout files by very long paths. I think it would be nice to have such parameter in the package.

**Comment by majkinetor** [comment]
This is great feature, thx for letting us know.
If anybody can provide what exactly needs to be added [here](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/git.install/tools/helpers.ps1#L15-L46) we can push this ASAP.

**Comment by tempora-mutantur** [comment]
@AdmiringWorm I agree, that this is something that should be specified after the installation.

Thanks.

**Comment by majkinetor** [comment]
Perhaps not useful in this case, but generally I support the concept of configuring app via package parmeters. I have several packages doing so, for example copyq hotkey can be set via parameter becasue its most important setting in which absent it stops the tool from being quickly usefl and you have to manually set it on each machine which takes time
After choco install config 'patch' is not readily available on random place as package parameter. My [rundeck](https://github.com/majkinetor/au-packages/issues/46) packages has few most important 'config params' as another example.
