### ISSUE TITLE
(gpg4win-vanilla/light) Not maintained upstream, possible vulnerability

### ISSUE THREAD

**Issue by wget** [chocolatey/chocolatey-coreteampackages#1043]
## Expected Behavior
`gpg4win-vanilla` and `gpg4win-light` still maintained by upstream.

This is no more the case unfortunately.

## Current Behavior
`gpg4win-vanilla` and `gpg4win-light` have been left on the now outdated and not maintained 2.0 gpg branch. These packages have not been updated for more than a year and are potentially putting users of these at risk. From now on, `gpg4win` will be the only package still maintained by upstream (on the 2.2 gpg branch).

## Possible Solution
Update `gpg4win-vanilla` and `gpg4win-light` to make them a dummy package depending on `gpg4win`. That way, all users of these outdated (lighter) packages will be upgraded to the current branch (2.2) of gpg4win, more secure and maintained.

The current `gpg4win` package is significantly lighter than what it was previously (claws mail has been removed for example).

If I get some sort of quorum/acceptance from some of you, I'll update these two packages in the days to come according to the description of this possible solution. What do you think? Any concerns here?

## Steps to Reproduce (for bugs)
N/A

## Context
N/A

## Your Environment
N/A

**Comment by AdmiringWorm** [comment]
I agree that the `gpg4win-*` packages should be left as the current version, making them dummy packages would not be correct in this regard IMO.
What could be done though, is to update the packages and output a warning to users installing the package (just mentioning that it isn't supported anymore).

BTW, there already exist a gnupg package (well, the modern edition anyhow): https://chocolatey.org/packages/gnupg-modern

**Comment by majkinetor** [comment]
> BTW, there already exist a gnupg package (well, the modern edition anyhow): https://chocolatey.org/packages/gnupg-modern

Yeah, this one is current. IMO it should be migrated here and made embedded. @wget, are you  up for things we decided here, namely:

1. Migrate `gnupg-modern` here, IMO name should be changed to `gnupg`
2. Add warning and/or notes in 2 outdated packages.

**Comment by wget** [comment]
@majkinetor Ok. Understood. What kind of warning should I write? How am I supposed to write it? Simply with `Write-Host` or do you have any other Chocolatey PS helper across that cmdlet formatting the output as error or warning content?

How should I handle the `gnupg-modern` to `gnupg` dependency? Simply make `gnupg-modern` a dummy package depending on the new to be created `gnupg`.?

**Comment by majkinetor** [comment]
`Write-Warning`
Yes

**Comment by majkinetor** [comment]
[Gnupg-modern](https://github.com/jtcmedia/chocolatey-packages/tree/master/gnupg-modern) should be migrated here, PR-ed there (its AU automatic).

**Comment by AdmiringWorm** [comment]
@jtcmedia would you be interested in having the `gnupkg-modern` package migrated to this repository?

**Comment by wget** [comment]
@AdmiringWorm @jtcmedia Done.
I'll now add the long awaited warning to the other outdated GPG4win packages.
