### ISSUE TITLE
/GitAndUnixToolsOnPath doesn't put C:\Program Files\Git\bin on path

### ISSUE THREAD

**Issue by alphaCTzo7G** [chocolatey/chocolatey-coreteampackages#1046]
## Expected Behavior

/GitAndUnixToolsOnPath - Puts gitinstall\bin on path. This setting will override /GitOnlyOnPath.
From the above description, I expect that using `/GitAndUnixToolsOnPath` would put `C:\Program Files\Git\bin` on the path.
 Modify the underlying code to put `C:\Program FIles\Git\bin` on path rather than `C:\Program Files\Git\cmd` if `/GitAndUnixToolsOnPath`  is provided to choco.

## Steps to Reproduce (for bugs)

1. install choco
2. install Git with `choco install git.install /GitAndUnixToolsOnPath -y`
3. check path with `path` in windows command prompt
4. path contains `C:\Program Files\Git\cmd` but not `C:\Program Files\Git\bin`

## Your Environment

* Package Version used: 2.17.2
* Operating System and version: Microsoft Windows [Version 10.0.17134.48]
* Chocolatey version: 0.10.11
* Install/uninstall gist: choco install git.install /GitAndUnixToolsOnPath -y

**Comment by alphaCTzo7G** [comment]
Currently, I am putting `Git\bin` on the path using the additional command: `setx path "%path%;C:\Program Files\Git\bin\"`, which has other sideeffects.

**Comment by AdmiringWorm** [comment]
> choco install git.install /GitAndUnixToolsOnPath -y

That there is the problem, you're not passing the package parameters correctly:
Documentation on how to pass the parameters is available on the chocolatey documentation site:
https://chocolatey.org/docs/how-to-parse-package-parameters-argument#installing-with-package-parameters

basically, install using the following: `choco install git.install -y --params "'/GitAndUnixToolsOnPath'"`
