### ISSUE TITLE
(1Password) auto-update fails to find version 7

### ISSUE THREAD

**Issue by Korni22** [chocolatey/chocolatey-coreteampackages#1048]
Hey everyone!

The 1Password auto updater seems to miss version 7 and stays on version 6.

## Expected Behavior
I'd expect the auto updater to find the recently released version, but it seems to be looking for the "6" in the URL.

## Current Behavior
It seems to look for the "6" in the URL, but with my limited powershell knowledge I can't really tell 😕

## Possible Solution
I can't really tell, to be honest.
It seems that a change to the update-script is needed.

## Steps to Reproduce (for bugs)
1. run `choco install 1password`
2. open 1Password
3. It is outdated :(

## Context
It requires user interaction to update 1Password to version 7, it would be very helpful if this was unnecessary.

## Your Environment
* Package Version used: v6.8.534
* Operating System and version: Windows 10 1803
* Chocolatey version: latest, doesn't matter

**Comment by RedBaron2** [comment]
They have adjusted the download page to not show OPW4 anymore.

I will submit my PR next week to address the OPW7 and OPW7/Y versions.

Enjoy the weekend 😄

**Comment by RedBaron2** [comment]
The PR has been submitted, and is just awaiting the proper checks and balances 😄

**Comment by AdmiringWorm** [comment]
fixed in https://github.com/chocolatey/chocolatey-coreteampackages/commit/2ea2a833b98df83f80d75df7202c99f80308443e and should appear on chocolatey.org soon.
