### ISSUE TITLE
(GnuCash) auto-update fails to find version 3.1-2

### ISSUE THREAD

**Issue by afflux** [chocolatey/chocolatey-coreteampackages#1049]
## Expected Behavior
Distribute version 3.1-2.

## Current Behavior
Version 3.1 is distributed, containing a [major bug](https://bugzilla.gnome.org/show_bug.cgi?id=795653)

## Possible Solution
Fix [auto-update](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/gnucash/update.ps1) script to consider dash versions.

## Context
GnuCash 3.1 on is unusable for many Windows users that have their databases on TrueCrypt-encrypted drives, as the file open dialogs are broken when accessing disks.

## Your Environment

* Package Version used: 3.1
* Operating System and version: Windows 10 1709
* Chocolatey version: v0.10.11

**Comment by AdmiringWorm** [comment]
@afflux when a dash is used in the version, it usually is considered a pre-release, which is incorrect in this case.
I think in this case, a package with a fix version would be more correct and I'm forcing an update right now.
