### ISSUE TITLE
(opera) Doesn't do silent uninstall

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#1054]
## Expected Behavior
Expecting the package to silently uninstall opera, currently we're relying on the auto uninstaller which is unable to detect the correct switches.

## Current Behavior
The uninstall dialog is popping up.

## Possible Solution
Figure out which switches needs to be used for uninstallation.

## Steps to Reproduce (for bugs)

1. Install the opera package
2. Try uninstalling it

## Your Environment

* Package Version used: 53.0.2907.88
* Operating System and version: Windows Server 2008 R2 Standard
* Chocolatey version: 0.10.11
* Install/uninstall gist: Not needed

**Comment by jack1142** [comment]
I'll try to address it today.

**Comment by AdmiringWorm** [comment]
WOuld be great if you could, I haven't yet looked into what switches is available for the uninstaller.
