### ISSUE TITLE
VSCode fails to install 

### ISSUE THREAD

**Issue by kilasuit** [chocolatey/chocolatey-coreteampackages#1058]
In the installer for VSCode seems to fail to instal claiming that the last command on this line `Get-PackageCacheLocation` cannot be found

https://github.com/chocolatey/chocolatey-coreteampackages/blob/0d22cb6331c7bc5b834f073e901769148a6d1c58/automatic/vscode/tools/ChocolateyInstall.ps1#L22

I am likely to just repave this box anyway but thought it best to raise this as an issue in case anyone else gets this

**Comment by kilasuit** [comment]
see below image of this issue
![image](https://user-images.githubusercontent.com/6355225/41366340-b09cc2d6-6f33-11e8-9de6-7953897266e7.png)

**Comment by AdmiringWorm** [comment]
could be a install problem with the `chocolatey-core.extension` package that we use in the package.

try forcing a re-install of that extension (seen this problem pop up for several issuers, across different packages and a re-install usually helped).

just do `choco install chocolatey-core.extension --force`

**Comment by kilasuit** [comment]
That seems to have fixed it

I will be building a new machine to test on as I'm trying to automate a full clean dev build environment from scratch so will see if this crops up again in future.

**Comment by AdmiringWorm** [comment]
As I said, I've heard that failure happening from time to time, but compared to the amount of downloads the extension have had, it's rare.

If it happens again, just try reinstalling it again and it should be fixed (hopefully you don't have to though).

**Comment by brentlintner** [comment]
For posterity, I am still running into this.

```
choco install -f chocolatey-core.extension
choco install -f vscode
```

Works for me too.
