### ISSUE TITLE
Python should NOT be installed into chocolatey lib (nor any package running a native installer)

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#106]
It is an extremely important distinction for packages - if it runs a native installer it should **_NEVER**_ install it to the package lib folder. It could cause issues if you remove the package files.

It should point back to BinRoot or even better - in the case of Python, folks actually want it to go to `c:\python3`. Those are the options available, but installing to the lib folder is not. I am going to remove it as a trusted package until this is fixed.

As a followup, it seems we need to document this - I didn't suspect that was necessary but it seems that it is. 

And as a secondary followup - Get-BinRoot is NOT deprecated yet. The message states we are going to deprecate it in v1.0.0 - which means it will be removed in v2.0.0. I will add a message to the text that clarifies this.

**Comment by ferventcoder** [comment]
FYI - https://github.com/chocolatey/choco/commit/47ef0b5a9a93da42e3427f8967603e2c7e911bf3

**Comment by Tset-Noitamotua** [comment]
Want (actually NEED) to see Python 3 in `C:\Python35` (Python 2 in `C:\Python27` etc). or in their native installation DIRs. 

`choco install python` makes a lot of trubble as it is now. There is an issue with pip ([pypi/pip #1997](https://github.com/pypa/pip/issues/1997#issuecomment-238027142)),  and `choco uninstall python` does not work correctly, though it tells so.

I think most Python user want to have it installed either to C:\PythonXX, to nativ install DIR or to custom DIR which is chosen with care (e.g. contains no spaces or special characters).

**Comment by majkinetor** [comment]
Can you assign me as a python3 maintainer. Currently the package is unusable.

**Comment by gep13** [comment]
@majkinetor is there any reason that you can't update the package in this current repo?  I am in the process of converting all the packages in this repo to add checksums for everything (I have some offline changes that I need to push) but it is still very much a work in progress.  Ideally, I would like to convert all the packages in this repo to AU, but that is also a larger undertaking.  Would you be in a position to do a PR to get the python3 package working as an AU package in this repo?  Thanks!

**Comment by majkinetor** [comment]
@gep13 OK, I will PR.

Do you have an AU runner available ?

**Comment by gep13** [comment]
@majkinetor you mean like AppVeyor? No, not yet, that is something i still have to setup.  But shouldn't take too long, right?

Let me push some of the changes that I made to the folder structure etc...

**Comment by gep13** [comment]
@majkinetor I have pushed the folder structure changes that I was working on, so the AU template layout should now be in there.  Let me know if you need anything from me.

**Comment by majkinetor** [comment]
It takes aproximatelly 5 minutes to setup AV. Let me know in au gitter if you need any hlep

**Comment by majkinetor** [comment]
Lets not discuss it here. AU template is not current, it will not work OK. I will be availalbe on gitter AU chat for you during the day. https://gitter.im/chocolatey_au/Lobby

**Comment by rickity-cricket** [comment]
I think this issue deserves to be reopened. It seems installing python via 
`choco install python`
the install still points to wrong place
