### ISSUE TITLE
No Flash MSI support for China now

### ISSUE THREAD

**Issue by russr123** [chocolatey/chocolatey-coreteampackages#1062]
https://forums.adobe.com/thread/2503969

https://forums.adobe.com/thread/2490901#

just  a FYI....

**Comment by Retia-Adolf** [comment]
Adobe sucks, they won't support it. The most disgusting tailoring I've ever seen.

manually download offline installer at [helpx.adobe.com](https://helpx.adobe.com/flash-player/kb/installation-problems-flash-player-windows.html), maybe proxy through a non-China IP is needed. Then open installer offlinely, or block its connection to internet to make it installable.

And no need to update it until it's too outdated to use in browsers. Fortunately, there aren't so many junkwares of disgusting companies like Adobe's Flash Player.

**Comment by AdmiringWorm** [comment]
I'm not sure what you're asking for in this issue, are you just trying to inform us of this?
Or are you expecting us to allow you to circumvent the restriction?

If the former, I would suggest that you post this the information on the disqus forum for the package, if it's the latter though, I'm afraid that wouldn't be something we will be doing.

I'll be closing this issue, feel free to re-open if you feel that more discussion on the topic is needed.
