### ISSUE TITLE
(maxthon.commandline) Is failing to update

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#1064]
Currently the package maxthon.commandline is failing to update on every run (failure is ignored though).

The error message is the following
```
Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.":https://dl.maxthon.com/mx5/maxthon_portable_5.2.3.4000.7z
```

Not completely sure how to fix this myself though.

**Comment by RedBaron2** [comment]
The problem is really upstream
Simplified:
>This server could not prove that it is dl.maxthon.com; its security certificate is from *.stackpathdns.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

The fix is to reach out to maxthon and ask them to fix the security certificate configuration.

**Comment by AdmiringWorm** [comment]
I thought as much, let me see if I can reach out to them sometime during the weekend.

If it wasn't for the automatic redirection to https feature in chocolatey, this wouldn't be an issue though.

**Comment by AdmiringWorm** [comment]
I've opted to just use the http edition of the maxthon url, couldn't be bothered to anything else right now.
