### ISSUE TITLE
(pdfcreator) Error while running 'C:\ProgramData\chocolatey\lib\PDFCreator\tools\chocolateyInstall.ps1'.

### ISSUE THREAD

**Issue by basictheprogram** [chocolatey/chocolatey-coreteampackages#1065]
## Expected Behavior

choco install pdfcreator would install

## Current Behavior

Installation was not successful. Exit code was '1'

```powershell
PS C:\Users\Administrator> choco install pdfcreator
Chocolatey v0.10.11
Installing the following packages:
pdfcreator
By installing you accept licenses for the packages.
Progress: Downloading PDFCreator 3.2.2... 100%

PDFCreator v3.2.2 [Approved]
pdfcreator package files install completed. Performing other installation steps.
Print Spooler service state:  / Running
Print Spooler service new state: Auto / Running
Installing PDFCreator...
ERROR: Running ["C:\ProgramData\chocolatey\lib\PDFCreator\tools\PDFCreator-3_2_2-Setup.exe" /VERYSILENT /NORESTART /COMPONENTS="program,ghostscript,comsamples,languages,languages\bosnian,languages\catalan,languages\catalan_valencia,languages\chinese_simplified,languages\chinese_traditional,languages\corsican,languages\croatian,languages\czech,languages\danish,languages\dutch,languages\english,languages\estonian,languages\finnish,languages\french,languages\galician,languages\german,languages\greek,languages\hebrew,languages\hungarian,languages\italian,languages\irish,languages\ligurian,languages\latvian,languages\lithuanian,languages\norwegian_bokmal,languages\polish,languages\portuguese_br,languages\romanian,languages\russian,languages\serbian_cyrillic,languages\slovak,languages\slovenian,languages\spanish,languages\swedish,languages\turkish,languages\valencian_avl" ] was not successful. Exit code was '1'. See log for possible error messages.
The install of pdfcreator was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\PDFCreator\tools\chocolateyInstall.ps1'.
 See log for details.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib-bad\PDFCreator]
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib-bad\PDFCreator]
Maximum tries of 3 reached. Throwing error.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 (32) The process cannot access the file because it is being used by another process: [\\?\C:\ProgramData\chocolatey\lib-bad\PDFCreator\tools\PDFCreator-3_2_2-Setup.exe]
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 (32) The process cannot access the file because it is being used by another process: [\\?\C:\ProgramData\chocolatey\lib-bad\PDFCreator\tools\PDFCreator-3_2_2-Setup.exe]

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - pdfcreator (exited 1) - Error while running 'C:\ProgramData\chocolatey\lib\PDFCreator\tools\chocolateyInstall.ps1'.
 See log for details.
```
## Steps to Reproduce (for bugs)

1. choco install pdfcreator

## Context

Trying to install pdfcreator on Windows10

## Your Environment

* Package Version used: pdfcreator 3.2.2
* Operating System and version: Windows 10
* Chocolatey version: 0.10.11
* Install/uninstall gist: 
    * [choco.summary.log](https://gist.github.com/basictheprogram/ac75985bc3127065584c310da3b04075) 
    * [chocolatey.log](https://gist.github.com/basictheprogram/7f8dfffbced56ad221c200dda42fa442)

**Comment by basictheprogram** [comment]
[Setup Command Line Parameters](http://docs.pdfforge.org/pdfcreator/latest/en/pdfcreator/installing-pdfcreator/setup-command-line-parameters/) says /SILENT, /VERYSILENT are supported in 3.2.1 but [What’s new in PDFCreator](http://docs.pdfforge.org/pdfcreator/latest/en/pdfcreator/introduction/whats-new/) says "From now on silent installation is only available for PDFCreator Business, PDFCreator Terminal Server and PDFCreator Custom"

**Comment by basictheprogram** [comment]
```powershell
choco install pdfcreator --install-arguments="/LOG=C:\Users\Administrator\xxxx.txt"
```
PDFCreator doesn't support silent installations in Windows domains anymore! Please use PDFCreator Business
```
2018-07-05 14:33:37.436   ----- Setup - Parameters -----
2018-07-05 14:33:37.436   Compiler version: 05050900
2018-07-05 14:33:37.436   Install PDFCreator: 3.2.2.13517
2018-07-05 14:33:37.436   PDFCreator doesn't support silent installations in Windows domains anymore! Please use PDFCreator Business. Find more information here: https://go.pdfforge.org/pdfcreator-business/upgrade
2018-07-05 14:33:37.436   InitializeSetup returned False; aborting.
2018-07-05 14:33:37.436   Got EAbort exception.
2018-07-05 14:33:37.436   Deinitializing Setup.
2018-07-05 14:33:37.436   Log closed.
```

**Comment by AdmiringWorm** [comment]
Considering this is done by purpose by the developers of the software, I don't believe it wouldn't be correct of us to circumvent this.
This is also why I haven't reviewed the opened PR to use autohotkey instead.

However, I wouldn't mind this being discussed though.

/cc @gep13 @majkinetor @ferventcoder

**Comment by teknowledgist** [comment]
I submitted the PR.  I understand where you are coming from, but I also feel like all the AHK script is doing is removing an annoyance, not circumventing any licensing or even support agreement.  If PDFforge doesn't want to support the free version on domains, they should outright prevent installing it, not just make it a PITA.  No admin is going to leave the domain so they can install PDFCreator and then rejoin the domain.  

It is OSS, so advanced users could compile it in theory, and non-domain users could just install it.  I can't compile it, so if PDFforge prevents domain installs entirely, that's the end of PDFCreator for me and my users.

**Comment by AdmiringWorm** [comment]
> but I also feel like all the AHK script is doing is removing an annoyance, not circumventing any licensing or even support agreement

I disagree, by using AHK script you're actively trying to get around code they implemented that specifically targets domain users in the free version of pdfcreator (when installing silently). If this change had been unintentional by the devs, I would have agreed.

> If PDFforge doesn't want to support the free version on domains, they should outright prevent installing it, not just make it a PITA.

I do agree with this though, I do think of one reason they decided to do this.
They probably don't want to prevent normal users (even when they are in a domain network) to be able to install the software, which usually would install the software in non-silent mode.
Businesses usually use IT Professionals which either uses chocolatey, or custom scripts to install the software in unattended mode.

> so if PDFforge prevents domain installs entirely, that's the end of PDFCreator for me and my users.

you still have the option to upgrade to the business edition of the software, although no chocolatey package exist for this though.

**Comment by AdmiringWorm** [comment]
Anyways, lets continue this discussion in the issue I mentioned earlier
