### ISSUE TITLE
(7zip) 7z.exe shim left behind when package uninstalled

### ISSUE THREAD

**Issue by raikesy** [chocolatey/chocolatey-coreteampackages#1066]
## Expected Behavior

1. `choco install 7zip` installs 7-Zip including writing a shim to  "C:\ProgramData\Chocolatey\bin"
1. `choco uninstall 7zip` successfully uninstalls 7-Zip including removing said shim

## Current Behavior

1. Seems to work as above
1. Shim is not removed, leaving a shim to an executable which no longer exists. This shim is also in the system path so causes anything depending on 7z.exe to fail.

## More info

Console output below shows `Skipping auto uninstaller - '7-Zip 18.05 (x64)' appears to have been uninstalled already by other means.`. Don't know whether this is relevant or not.

```
~ $ choco uninstall 7zip
Chocolatey v0.10.11
Uninstalling the following packages:
7zip
You are uninstalling 7zip, which is likely a metapackage for an
 *.install/*.portable package that it installed
 (7zip represents discoverability).
For the question below, you have 20 seconds to make a selection.
Would you like to uninstall 7zip.install as well?([Y]es/[N]o): y


7zip v18.5
 Skipping auto uninstaller - No registry snapshot.
 7zip has been successfully uninstalled.

7zip.install v18.5
Uninstalling 7zip.install...
0
7zip.install has been uninstalled.
 Running auto uninstaller...
 Skipping auto uninstaller - '7-Zip 18.05 (x64)' appears to have been uninstalled already by other means.
 7zip.install has been successfully uninstalled.

Chocolatey uninstalled 2/2 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

## Steps to Reproduce (for bugs)

1. `choco install 7zip`
2. `choco uninstall 7zip`
3. `7z`

## Context

Happened while switching from a Chocolatey installation of 7-Zip to a Scoop installation. Dangling shim causes Scoop to either hang or silently fail when installing packages.

## Your Environment

* Package Version used: 18.5
* Operating System and version: Windows 10 1803
* Chocolatey version: 0.10.11

**Comment by AdmiringWorm** [comment]
Thank you for reporting this.
Seems like the removal of the shim have been left out of the uninstall script.

Since this is an easy addition I've added this as an up for grabs for now.
