### ISSUE TITLE
(vcredist2015) Installs Visual C++ 2017 runtimes

### ISSUE THREAD

**Issue by jansohn** [chocolatey/chocolatey-coreteampackages#1068]
## Expected Behavior
The meta-package vcredist2015 should install Visual C++ 2015 runtimes.

## Current Behavior
The meta-package vcredist2015 installs Visual C++ 2017 runtimes (latest version of vcredist140 which is currently v14.12.25810).

## Possible Solution
Dependency needs to be specified to exact version match and not minimum version, inclusive (see https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards).

    <dependencies>
      <dependency id="vcredist140" version="[14.0.24215.1]" />
    </dependencies>

## Steps to Reproduce (for bugs)
1. choco install vcredist2015
2. choco list --local-only

```
vcredist140 14.12.25810
vcredist2015 14.0.24215.20170201
```

## Your Environment

* Package Version used: `14.0.24215.20170201`
* Operating System and version: `Windows Server 2012 R2`
* Chocolatey version: `v0.10.11`
* Install/uninstall gist:

**Comment by AdmiringWorm** [comment]
Not an issue, and is being done on purpose.

vcredist2017 is an in place replacement of vcredist2015.

Unlike any previous redistributable, the vcredist2017 is backwards compatible with the older vcredist2015.

**Comment by jansohn** [comment]
Thanks, didn't know that. Here's an article about it:
https://docs.microsoft.com/de-de/cpp/porting/binary-compat-2015-2017
