### ISSUE TITLE
(skype) Fix for skype-autostart after update

### ISSUE THREAD

**Issue by psdavid-muc** [chocolatey/chocolatey-coreteampackages#1069]
## Expected Behaviour
Skype does not start after installation / update.

## Current Behaviour
Right now, if you install or update skype using the official skype package, skype will start automatically after installation/update. This is problematic since skype now runs as admin / with administrative privileges. Also, the user will have to re-enter his login-information (which is not necessary if not run as admin).

## Possible Solution
I've created a custom skype package we're using in our organization:

```
#stop on all errors
$ErrorActionPreference = 'Stop'

#set kill skype variable
$stopSkypeProcess = 'Get-Process -Name "skype" | Stop-Process -Force'

$packageArgs = @{
(omitted)
}

Install-ChocolateyPackage @packageArgs
Start-ChocolateyProcessAsAdmin -Statements $stopSkypeProcess
```
I don't intend to start skype afterwards since the choco process runs as admin and thus skype will run with admin privileges as well. This might be uncomfortable for the user, but is safer 

## Steps to Reproduce (for bugs)

1. Have some version of skype installed on your computer
2. Let choco update skype automatically
3. If you've used skype before, your credentials are saved
4. If skype opens automatically after the update and you have to insert your logon information, that might indicate that skype runs as admin/with administrative privileges. Also, check with procmon/taskmgr

## Context

Usually windows users don't have administrative rights (for obvious reasons). Skype should not run with administrative rights for security reasons.

## Your Environment

* Package Version used: (custom) 8.24.0.2, (official) 8.23.0.10
* Operating System and version: Windows 10 Professional x64, v 1709 (Fall Creators Update)
* Chocolatey version: 0.10.8
* Install/uninstall gist: n/a

**Comment by fraenki** [comment]
https://github.com/chocolatey/chocolatey-coreteampackages/issues/1009

**Comment by AdmiringWorm** [comment]
Closing this in favor of #1009
