### ISSUE TITLE
(gimp) GIMP 2.10.4 libenchant.dll missing from Microsoft Windows installers.

### ISSUE THREAD

**Issue by philipthatcher** [chocolatey/chocolatey-coreteampackages#1070]
GIMP 2.10.4 libenchant.dll missing from Microsoft Windows GIMP 2.10.4 installers.

## Expected Behavior
The newly installed GIMP program should start up without any errors or warnings.

## Current Behavior
Run the installed GIMP program.  Error below displays twice during startup.
"libenchant.dll not found"

## Possible Solution
The GIMP team have corrected their GIMP 2.10.4 Windows installer.
The Choco package now needs to be rebuilt, using the new installer.

Details at : https://gitlab.gnome.org/GNOME/gimp/issues/1789

## Steps to Reproduce (for bugs)
1. Run "choco install gimp" on a Windows 7 64-bit OS that's never had any GIMP installed.
2. Run the installed GIMP program.  Error below displays twice during startup.
"libenchant.dll not found"

## Your Environment
Windows 7 64-bit.  Never had any GIMP installed previously.

**Comment by AdmiringWorm** [comment]
Forcing an update on the appveyor update server now, which should be pushed to chocolatey soon.
