### ISSUE TITLE
(alldup) needs silent install switches changed to include /NORESTART

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/chocolatey-coreteampackages#1077]
RE: https://chocolatey.org/packages/alldup/4.1.5

## Expected Behavior
For a package to not forcibly reboot my computer unexpectedly.

## Current Behavior
If there is a pending reboot flagged, AllDupSetup.EXE will reboot the computer pre-install.

## Possible Solution
Update chocolateyInstall.ps1 to:
silentArgs     = ' /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-'

## Context & Steps to Reproduce (for bugs)
Uninstalled and attempted re-install of alldup package for testing purposes, re-install attempted to reboot the computer.

## Your Environment
Windows 10
Chocolatey v0.10.11
https://chocolatey.org/packages/alldup/4.1.5

**Comment by bcurran3** [comment]
p.s. AllDup runs the program post install. Consider using Start-CheckandStop() in https://chocolatey.org/packages/chocolatey-misc-helpers.extension

**Comment by AdmiringWorm** [comment]
@bcurran3 please let us keep it one request per issue, you can open up a new issue for requesting the ability to deny execution of alldup after installation.

**Comment by bcurran3** [comment]
Sure thing.
https://github.com/chocolatey/chocolatey-coreteampackages/issues/1078

**Comment by AdmiringWorm** [comment]
thanks, I've added both as an `Up for grabs` as I won't be able to look into it until next week.

Well, I hope I can look into it then, at least.
