### ISSUE TITLE
srwareiron: add 64-bit version

### ISSUE THREAD

**Issue by TomOne** [chocolatey/chocolatey-coreteampackages#108]
The 64-bit version for srwareiron is available. We need to include it into the package.

This was reported here: https://chocolatey.org/packages/SRWareIron#comment-2454904156

**Comment by gep13** [comment]
Community member @Vaquero84 is taking ownership of this package, as they have already created portable and install versions of this package, and this package simply needs to be converted to a virtual package.

The new source for this package is hosted here:

https://github.com/Vaquero84/chocolatey-packages/tree/master/automatic

I am going to delete the package source files from this repo, once everything is set up.
