### ISSUE TITLE
(visualstudiocode) Complete the package deprecation procedure

### ISSUE THREAD

**Issue by bazzilic** [chocolatey/chocolatey-coreteampackages#1080]
This package:

- https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/deprecated/packages/visualstudiocode
- https://chocolatey.org/packages/VisualStudioCode

Was deprecated but it did not follow the deprecation guidelines to the full. Namely,

- Icon should be removed,
- Previous versions should be unlisted

Deprecation guidelines: https://chocolatey.org/docs/how-to-deprecate-a-chocolatey-package

**Comment by AdmiringWorm** [comment]
I disagree with unlisting the previous versions, the history of the package could be useful in some cases, and since the `vscode` package won't have the earlier versions, I wouldn't do this.

Removing the icon should definitely be done of course.

**Comment by majkinetor** [comment]
> I disagree with unlisting the previous versions, the history of the package could be useful in some cases, and since the vscode package won't have the earlier versions, I wouldn't do this.

Right, its essential that those versions are not removed in general (since newer packages are mostly embedded and will continue to work indefinitely). I think that documentation should be changed on this 

/cc @gep13

**Comment by gep13** [comment]
@majkinetor could you raise a PR with your suggestion on how it should be changed?
