### ISSUE TITLE
(vagrant) Failing verifier

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#1082]
Is anyone in a position to address the failing installation here:

https://gist.github.com/choco-bot/907157333f45fe3ef1eb9a238338e1ef

Looks like the checksums are now invalid.

**Comment by AdmiringWorm** [comment]
On it.

**Comment by AdmiringWorm** [comment]
Forcing update on appveyor now

**Comment by gep13** [comment]
@AdmiringWorm thank you for fixing this!
