### ISSUE TITLE
(absolute-uninstaller) Checksums do not match

### ISSUE THREAD

**Issue by timko98** [chocolatey/chocolatey-coreteampackages#1083]
When I was trying to install the absolute-uninstaller package, I encountered the error that the checksum hashes do not match.

I used the simple choco install command. 

It looks like the bug has already been detected by the CI, but i wanted to call attention for it.

**Comment by AdmiringWorm** [comment]
@timko98 are you still experiencing the wrong checksum?

I know there may be sometimes a few hours between when our update checks runs were this occurs.

(I'm sorry we haven't responded until now).

**Comment by AdmiringWorm** [comment]
Closing this due to lack of response.
