### ISSUE TITLE
(zotero-standalone) Upstream name changes should be followed

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#1089]
There is no more zotero standalone but only zotero (perhaps desktop) and zotero connector. See

https://www.zotero.org/blog/a-unified-zotero-experience/

I suggest we rename zotero-standalone to just `zotero` (that is deprecate current package and create new one).

/cc @AdmiringWorm

**Comment by AdmiringWorm** [comment]
sounds good to me
