### ISSUE TITLE
mp3tag: Old installers are left behind on package upgrade, spamming the bin directory

### ISSUE THREAD

**Issue by coldacid** [chocolatey/chocolatey-coreteampackages#1090]
## Expected Behavior

Installers for older versions of mp3tag are deleted during the upgrade process.

## Current Behavior

Installers for older versions of mp3tag are left behind in the `tools/` directory without any `.ignore` files, wasting storage space and polluting the `chocolatey/bin/` directory.

## Possible Solution

Delete all installers for older versions of mp3tag in `chocolateyInstall.ps1` after the current version is successfully installed.

## Steps to Reproduce (for bugs)

1. Install mp3tag.
2. Wait for a new version of mp3tag to be released.
3. Upgrade mp3tag.
4. Observe that there are now at least one shim in `chocolatey/bin/` with filename matching the pattern `mp3tagv([0-9]+[a-z]?)setup\.exe`, where the capture matches the previous version(s) of mp3tag installed on the computer via Chocolatey.

## Context

Besides wasting storage space on my computers, this also spams up tab completion for cmd.exe and PowerShell.

## Your Environment

* Package Version used: All versions
* Operating System and version: Windows 10 Pro
* Chocolatey version: 0.10.*

**Comment by AdmiringWorm** [comment]
Thanks for opening this.
I've added it as an `Up for grabs` for now, as I don't have the time to look into adding this myself (although it's quite simple to do that).

**Comment by AdmiringWorm** [comment]
@coldacid this was fixed in the source now thanks to @jack1142 

A fix version have also been pushed to chocolatey, and should be available soon
