### ISSUE TITLE
(chocolatey-core.extension) Get-AppInstallLocation Chrome returns no location

### ISSUE THREAD

**Issue by ishu3101** [chocolatey/chocolatey-coreteampackages#1097]
Running 

```
Get-AppInstallLocation Chrome
Get-AppInstallLocation GoogleChrome
Get-AppInstallLocation Google Chrome
Get-AppInstallLocation "Google Chrome"
```

all returns no location

Running
```
Get-AppInstallLocation Chrome -Verbose
```
returns
```
VERBOSE: Trying local and machine (x32 & x64) Uninstall keys
VERBOSE: Found 0 keys, aborting this method
VERBOSE: Trying Program Files with 2 levels depth: C:\Program Files C:\Program Files\*\*
VERBOSE: Trying native commands on PATH
VERBOSE: Trying Registry: \SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths
VERBOSE: No location found
```

I see that in the `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\` location in the Registry it has a chrome.exe key which has the `Default` and `Path` as string name with
the value set as `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe` and `C:\Program Files (x86)\Google\Chrome\Application` respectively

## Steps to Reproduce (for bugs)
```
cinst GoogleChrome
```

# Your Environment
* Package Version used: chocolatey-core.extension 1.3.3
* Operating System and version: Windows 10 Pro Version 1703
* Chocolatey version: v0.10.11

**Comment by majkinetor** [comment]
Can't reproduce:

```
------------------------------------------------
3  18-08-21 09.23.56  C:\Users\mmilic (admin)
> Get-AppInstallLocation Chrome -Verbose
VERBOSE: Trying local and machine (x32 & x64) Uninstall keys
VERBOSE: Retrieving all uninstall registry keys
VERBOSE: Found 0 keys, aborting this method
VERBOSE: Trying Program Files with 2 levels depth: C:\Program Files C:\Program Files\*\* C:\Program Files (x86) C:\Program Files (x86)\*\*
C:\Program Files (x86)\Google\Chrome
```

**Comment by majkinetor** [comment]
The problem might be that system is  treated by the function as 32bit while it is obviously x64 bit. This is the reason why it wasn't find in Program Files.. That is something you can clearly see as a difference between my output and yours.

I do not know why it wasn't found in Registry tho, but I think this is some local behavior anyway.
