### ISSUE TITLE
NSSM package lighting up AV scanners, false positive or issue with Chocolatey?

### ISSUE THREAD

**Issue by zaggynl** [chocolatey/chocolatey-coreteampackages#1098]
Hi,
The current [Chocolatey NSSM](https://chocolatey.org/packages/NSSM) package lights up most Antivirus Scanners:https://www.virustotal.com/en/file/99f5045fffbffb745d67fe3a065a953c4a3d9c253b868892d9b685b0ee7d07b8/analysis/
The [latest official NSSM](https://nssm.cc/download) zip does not: https://www.virustotal.com/#/file/727d1e42275c605e0f04aba98095c38a8e1e46def453cdffce42869428aa6743/detection
Did NSSM fix their packaging to prevent false positives?
Might be worth it to investigate and repackage the Chocolatey version of NSSM.
I've checked with the Chocolatey package maintainer Gary and he forwarded me to this github page.

**Comment by AdmiringWorm** [comment]
While I can't say for sure, I do believe it to be a false positive.
Just to quote one of the comments on virustotal (for the 32bit edition):
> Allows you to run an arbitrary binary as a service. Certainly not malware in itself - but as always could be used for good and evil purposes

I do agree with his assesment, but as with every package on chocolatey.org:
Do make your own opinion wether or not it's safe, this is one of the reasons why a virustotal report result is provided.

I do admit it's a risk, but I don't believe the software by itself is risky, but rather what is possible to be done with it.

A second opinion on this is always appreciated of course:
/cc @ferventcoder @gep13 @majkinetor

**Comment by majkinetor** [comment]
I left comment on virus total.
Also, notice that several AV's list it as `not-a-virus:RiskTool`

I will close this now, please feel free to open it again if you think there is more to discuss.
