### ISSUE TITLE
(palemoon) v28 is out but not on chocolatey

### ISSUE THREAD

**Issue by b-raj001** [chocolatey/chocolatey-coreteampackages#1100]
Pale moon browser v28 is available for some days now but not via chocolatey, so I contacted the maintainers. I got a reply from Gary Ewan Park suggesting I post an issue here. He says that there is no new package version in the moderation queue, so it could be that there is something not quite right with the automated process.

**Comment by AdmiringWorm** [comment]
Unfortunately It seems like the page we're using to check for updates for this package, no longer exist.

So basically, we'll need to update our update script to grab the new versions.
I'm planning to look into this tomorrow myself, but maybe someone will pick this up before then 🤞

**Comment by AdmiringWorm** [comment]
@b-raj001 our update script have been fixed, and an update is being scheduled right now.
