### ISSUE TITLE
(cURL) Blessed curl builds for windows.

### ISSUE THREAD

**Issue by philipthatcher** [chocolatey/chocolatey-coreteampackages#1105]
Just in case no one's seen this.

Is this where the cURL Windows binaries are being sourced from?  If not, it probably should be.
[https://curl.haxx.se/windows/](https://curl.haxx.se/windows/)

See AUGUST 27, 2018 **Blessed curl builds for windows.**
[https://daniel.haxx.se/blog/2018/08/27/blessed-curl-builds-for-windows/](https://daniel.haxx.se/blog/2018/08/27/blessed-curl-builds-for-windows/)

**Comment by majkinetor** [comment]
Actually, we take `vszakats` binaries from the downloads page from that site which look the same as that on `/windows` page.
