### ISSUE TITLE
(seer) Installation error

### ISSUE THREAD

**Issue by Sytten** [chocolatey/chocolatey-coreteampackages#1111]
## Expected Behavior
It should install the latest version of seer.

## Current Behavior

Error on install, my best bet is that the author removed the releases from github.
```
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/ccseer/Seer/raw/master/Seer-0.7er-0.7.4.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.The install of seer was NOT successful.
```

## Possible Solution

Find where the new releases are stored.

## Your Environment

* Package Version used: latest 
* Operating System and version: Windows 10 1607
* Chocolatey version: 0.10.11

**Comment by AdmiringWorm** [comment]
I think you have the wrong repository, this package isn't located here.
Please use the `Contact Maintainers` on the package page, this repository only contains packages from the chocolatey user.
