### ISSUE TITLE
(openssl.light) Missing dependency on vcredist140

### ISSUE THREAD

**Issue by verglor** [chocolatey/chocolatey-coreteampackages#1120]
OpenSSL depends on VCRuntime140.dll so dependency on vcredist140 package should be declared.

**Comment by majkinetor** [comment]
It indeed does for latest version. Thanks for report.

**Comment by rgl** [comment]
Can you please publish the openssl.light package with this fixed? The current one still does not have the redist as a dependency.

**Comment by gep13** [comment]
@rgl it looks as though the dependency is now in place, for example:

![image](https://user-images.githubusercontent.com/1271146/47283242-64786a00-d5da-11e8-96f0-9bc6a4b9d2d0.png)

Which is one this package version:

https://chocolatey.org/packages/OpenSSL.Light/1.1.1.20181020

Is this not what you expected?

**Comment by majkinetor** [comment]
Yeah, now its OK since I forced update (see commit above your message)

**Comment by rgl** [comment]
It seems the package was published in the mean time, so its fine now :-)
