### ISSUE TITLE
(wixtoolset) old codeplex hosted installers no longer work 

### ISSUE THREAD

**Issue by thisjustin816** [chocolatey/chocolatey-coreteampackages#1127]
## Expected Behavior

Installing old versions of wixtoolset (e.g. `choco install wixtoolset --version 3.9.1208.0`) don't work because they're still using old codeplex links when the project is hosted on github now.

## Current Behavior

See above

## Possible Solution

Switch to github links

## Steps to Reproduce (for bugs)

1. choco install wixtoolset --version 3.9.1208.0

## Context

Need an old version of wix on a build server for a legacy project that needs it to be compatible with other previous installers.

## Your Environment

* Package Version used: 3.9.1208.0
* Operating System and version: Windows 10 Enterprise 1607
* Chocolatey version: v0.10.11
* Install/uninstall gist:

**Comment by gep13** [comment]
@thisjustin816 can you help shortcut the work by including the new links for the older package versions?  Thanks

**Comment by AdmiringWorm** [comment]
@thisjustin816 unless you're able to provide any links to other versions of wixtoolset, I'm afraid I will have to close this issue (I have looked after links, and thus far not found any).
Their github page do not list the versions that was available on codeplex unfortunately.

**Comment by AdmiringWorm** [comment]
As the older versions doesn't exist anywhere (AFAIK), I'm afraid I will have to close this now.
