### ISSUE TITLE
(python3) Use shims instead of PrependPath. Provide python3-shim.

### ISSUE THREAD

**Issue by cmorty** [chocolatey/chocolatey-coreteampackages#1128]
## Expected Behavior
Create a `python3.exe` shim instead of setting `PrependPath=1`.
Optinally a `python.exe` shim could be created, but this probably causes issues with python2.
While one is at it, a pip3.exe shim should be created.

## Current Behavior
Whit `PrependPath=1` the path environment variable is cluttered by the installer.

## Possible Solution
Do not set `PrependPath=1` in the installer, but create a shim.

## Context
Most Linux distros provide python2 and python3 (pip2 / pip3) binaries/symlinks. This avoids issues running the wrong python version.

**Comment by majkinetor** [comment]
> Whit PrependPath=1 the path environment variable is cluttered by the installer.

The path env var SHOULD be cluttered by installer. PATH is normal mechanism.

Regarding python2/python3/symlinks etc that is larger task and not related to this one. But we area not "distro", only package manager. Its certainly possible to do this on choco level but I don't think anybody here is interested in this at this moment, especially since python2 should die already :)

**Comment by cclauss** [comment]
__choco install python__ already creates a __py__ executable that is distinguished from __python.exe__ (legacy Python).  This aligns perfectly with https://docs.python.org/3/faq/windows.html

**Comment by majkinetor** [comment]
Thanks @cclauss for the valuable info.

**Comment by cclauss** [comment]
__python.exe__ is the main executable and the shim is properly put in place for it but there is often a need to have access to both Python 2 and Python 3 so the __python__ vs. __py__ trick mentioned above enabled that.

__pip.exe__ is a _secondary executable that is installed when Python is installed but ___no shim is put in place for pip___.  On other platforms __pip2__ provides access to pip for installing packages into Python 2 and __pip3__ provides access to pip for installing packages into Python 3.  This is not the case with Chocolatey so the __python3 -m pip__ trick is required.

**Comment by cmorty** [comment]
@cclauss See, I got you! You wrote `python3 -m pip` in the first version of your comment. ;) And that would be super-intuitive, as it's in line with most linux-distros. 
BTW: I have no idea who had the great Idea to use "py.exe" as executable, for win, as this is a python command line interpreter in most linux distros (http://manpages.ubuntu.com/manpages/cosmic/man1/py.1.html and https://github.com/Russell91/pythonpy). But that's another topic.
