### ISSUE TITLE
Remove Write-ChocolateyFailure and Write-ChocolateySuccess

### ISSUE THREAD

**Issue by matbech** [chocolatey/chocolatey-coreteampackages#113]
Write-ChocolateyFailure is deprecated.

Remove try/catch handlers from install and uninstall scripts.
Write-ChocolateyFailure $packageName $($_.Exception.Message)

List of affected files:
Write-ChocolateyFailure
https://github.com/chocolatey/chocolatey-coreteampackages/search?utf8=%E2%9C%93&q=Write-ChocolateyFailure+%24packageName+%24%28%24_.Exception.Message%29

Write-ChocolateySuccess
https://github.com/chocolatey/chocolatey-coreteampackages/search?utf8=%E2%9C%93&q=Write-ChocolateySuccess

**Comment by gep13** [comment]
@matbech thanks for the reminder.  This is something that we will have to take care of.
