### ISSUE TITLE
(waterfox) version 56.2.5 released

### ISSUE THREAD

**Issue by mstick99** [chocolatey/chocolatey-coreteampackages#1135]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Package Version used:
* Operating System and version:
* Chocolatey version:
* Install/uninstall gist:

**Comment by AdmiringWorm** [comment]
I'm curious to where you found that version.
I looked at the web page of waterfox, and I can only see 56.2.4 being available.

**Comment by mstick99** [comment]
According to https://blog.waterfoxproject.org/waterfox-56.2.5-release-download it is available. The page does indicate that "Note: Website will update slowly with new version."  Also it shows up as being available under Help, About Waterfox.

**Comment by AdmiringWorm** [comment]
Unfortunately I still can not find any download location for that version on that website. Until there is one, we can not update the package with the new release.

As such, I will be closing this issue until the version is available on the website.
If it suddenly starts appearing there, and no package version have been pushed, then feel free to re-open this issue. (Normally all packages are checked every 6th hour or so).

**Comment by mstick99** [comment]
can be found at https://www.techspot.com/downloads/6249-waterfox.html 
with source code available at https://github.com/MrAlex94/Waterfox

**Comment by AdmiringWorm** [comment]
Unfortunately that download location isn't part of an official download location from the developers (AFAIK).

As such, we can not use it unfortunately.

**Comment by AdmiringWorm** [comment]
I see now that an official download location is available, unfortunately it seems an error occurs when trying to push it to chocolatey.

I'm invistigating the issue, but uncertain if there is a problem with chocolatey or the push of the package itself.
Anyhow, I'm re-opening this issue for now.
