### ISSUE TITLE
(tortoisesvn) Package waiting for moderation

### ISSUE THREAD

**Issue by NicoHaase** [chocolatey/chocolatey-coreteampackages#1136]
According to https://chocolatey.org/packages/tortoisesvn, new versions of the TortoiseSVN package has been pushed to Chocolatey on Oct 10 and Nov 1 and are waiting for moderation since. I contacted the package maintainers using the web interface and they asked me to file an issue here.

## Expected Behavior
Package is checked for getting stuck in moderation, possible bugs are fixed, and users are able to upgrade the local installation

## Current Behavior
Package is stuck in moderation

**Comment by AdmiringWorm** [comment]
I expect to be able to look into this issue sometime this week.

**Comment by AdmiringWorm** [comment]
Not yet.
It's still on my TODO list, but haven't managed to have a look at this yet.

**Comment by AdmiringWorm** [comment]
Seems to be a missing dependency that's preventing the installation of the package.

I need to do some more testing before an updated version can be pushed (but most likely we'll need to request an exemption for this package)

**Comment by AdmiringWorm** [comment]
latest version is available now. I won't fix the previous version though
