### ISSUE TITLE
(peazip.portable) Out of date

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-coreteampackages#1141]
https://chocolatey.org/packages/peazip.portable

**Comment by AdmiringWorm** [comment]
wrong repository, this package is not maintained here.

Please check the package source url (which would point you to dtgm's repository)

**Comment by dimqua** [comment]
Oops, indeed. Something is wrong with website:
![](https://i.imgur.com/9F80tbe.png)

**Comment by AdmiringWorm** [comment]
That's just a caching issue.
The chocolatey was actually previously on that package, which was incorrect. as such I removed it right before I replied to you.
