### ISSUE TITLE
(poi) Push error after updating

### ISSUE THREAD

**Issue by drelatgithub** [chocolatey/chocolatey-coreteampackages#1143]
## Expected Behavior

The package poi is updated from 9.0.3 to 9.0.4 and pushed to chocolatey repository.

## Current Behavior

The push has error with message:

> Push ERROR
> Attempting to push poi.9.0.4.nupkg to https://push.chocolatey.org There was an internal server error, which might mean the package already exists on a Simple OData Server.

## Possible Solution

Push manually... maybe?

## Steps to Reproduce (for bugs)

1. See update logs

## Context

I am one of the maintainers of this package. I think I've seen that problem before and in my impression it is a known problem and happens from time to time. But it seems that it's been many update cycles of the auto updater, but this error persists. Therefore, I suppose that it cannot be resolved on its own automatically. But I do not know the way to actually solve this, maybe there's something that I can do to improve the package itself?

## Your Environment

AU on AppVeyor

**Comment by AdmiringWorm** [comment]
Unfortunately this isn't related to the package itself, nor the AU environment (AFAIK).

The error seems to be on the webserver, as it happens with several packages (from different users, some of them even have tried to push manually).

I believe there are someone associated with chocolatey looking into this issue.

**Comment by drelatgithub** [comment]
Thanks a lot for the reply! As for now, it seems no longer an issue, as the push has just been successful.

**Comment by AdmiringWorm** [comment]
@gep13 yeah, you're right. I haven't changed anything at all.

**Comment by dimqua** [comment]
Hmm, I have the same problem with my embedded packages. At least with biggest ones (~100MB or bigger).

**Comment by gep13** [comment]
@dimqua this is being reported by a few people, but currently, we haven't been able to get a handle on what is causing the problem 😢

**Comment by dimqua** [comment]
@gep13 the problem has been fixed for me few days ago. :-)

**Comment by drelatgithub** [comment]
I'm not requiring a fix or action because I understand that this problem might not be within the scope this repository and the reason is hard to locate, but just fyi the problem re-emerged for recently updated package for poi 10.0.0-beta1.

**Comment by drelatgithub** [comment]
Happy new year fellas!

It seems that the problem still persists for about 3 days for the 10.0.0 version of poi (stable release). The package was rejected by the server with a (seemingly truncated) message (different from the one in the original post)

>Push ERROR
Attempting to push poi.10.0.0.nupkg to https://push.chocolatey.org Failed to process request. 'This package had an issue pushing: Exception of type 'System.OutOfMemoryException' was thrown.'.  The remote server returned an error: (409) Conflict..

**Comment by drelatgithub** [comment]
The push error still exists on upgrading to poi version 10.1.0. Somehow the problem likes to stick with this particular package.

Due to the high reproducing rate (4 out of 5 updates) and each of them persisted for a long time (could not resolve on its own during updating cycles), I think it might be appropriate to reopen the issue.

**Comment by AdmiringWorm** [comment]
As you said previously, this is out of the scope of this repository, and honestly nothing we can do here to fix that.

Please subscribe to the issue opened in the chocolatey.org repo instead: https://github.com/chocolatey/chocolatey.org/issues/613
