### ISSUE TITLE
(PDFCreator) hangs during installation (3.3.0, 3.3.2)

### ISSUE THREAD

**Issue by romanlum** [chocolatey/chocolatey-coreteampackages#1144]
## Expected Behavior
Unattended installation

## Current Behavior
The installer hangs because of a popup showing that a new version is available.

## Possible Solution
use /VERYSILENT as installation argument

## Steps to Reproduce (for bugs)

1. choco install pdfcreator

## Context
Unattended installation of PDFCreator

## Your Environment

* Package Version used: 3.3.0
* Operating System and version: Windows 7 / Windows 10
* Chocolatey version: v0.10.11
* Install/uninstall gist:

**Comment by AdmiringWorm** [comment]
> use /VERYSILENT as installation argument

this is something we actually used in the past, and I suggested to continue to use.
But unfortunately I was overruled here, and an autohotkey script was added instead.

See https://github.com/chocolatey/chocolatey-coreteampackages/issues/1065 and https://github.com/chocolatey/chocolatey-coreteampackages/pull/1079

**Comment by AdmiringWorm** [comment]
Of course they are still available, just not when the windows user is in a domain.

If you see the comment after the one you reference, the log explicitly says:
> PDFCreator doesn't support silent installations in Windows domains anymore! Please use PDFCreator Business. Find more information here: https://go.pdfforge.org/pdfcreator-business/upgrade

**Comment by majkinetor** [comment]
No extra packages please. Dependency on AHK is not a big issue as many packages already have it and its already on the system for majority of users and if not, it is tiny.

I think second option should be used, and AHK script should be fixed to take popup into account.

**Comment by teknowledgist** [comment]
I submitted a PR that should resolve this issue using `2.` above.  I'm not very well versed in GIT, so I'm not sure if the failed checks and conflicts are something I need to do something about or an expected result.  

Hope I'm being helpful.
