### ISSUE TITLE
(datagrip) Latest version failing automated verification

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#1147]
Currently the latest version of datagrip is failing the automated verification step.
It seems like it times out during install, perhaps a missing dependency, or a dialog popping up.

@The-Running-Dev I see you originally provided the package, would you mind having a look at this?

The install log is available here: https://gist.github.com/d2e7c98996d25a7f5723d790bbcd4599

**Comment by The-Running-Dev** [comment]
I looked into it and it seems the latest installer breaks the silent
installation. If run interactively, it throws an error with "Not enough
disk space" in a popup. I will submit a ticket in their tracking system and
see if they get back to me.

**Comment by AdmiringWorm** [comment]
Looks like @mkevenaar have provided a workaround in #1150
