### ISSUE TITLE
(PartitionMasterFree) - EaseUS Partition Master (Free) 13.0 checksums don't match

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/chocolatey-coreteampackages#1148]
From: Kim Nordmo 
Sent: Saturday, December 1, 2018 8:51 AM
To: bcurran3 
Subject: Re: [coreteampackages] [Chocolatey.org] Message for maintainers of the package 'PartitionMasterFree'

Had a quick look at this, it seems they had updated the changelog before releasing the new executable.
Making it so that the package uses the hash for the previous version.
Could you please open a issue over at: https://github.com/chocolatey/chocolatey-coreteampackages/issues (if you haven't already).

Thanks,
Kim N.

**Comment by AdmiringWorm** [comment]
I think I'll be able to look into fixing this at some point tomorrow.

Thanks for opening this issue, it will significant changes to the update script to prevent this from happening again.
