### ISSUE TITLE
(PartitionMasterFree) - EaseUS Partition Master (Free) - quit program when it auto-runs

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/chocolatey-coreteampackages#1149]
RE: This package is not completely silent.
The application will launch after installation.

## Expected Behavior
* The program to not run after install, or at least be stopped when it runs.
* No additional unwanted software

## Current Behavior
* EaseUS Partition Master Free Edition runs and stays open after install of partitionmasterfree package
* The EaseUS Partition Master Free Edition installer also installs EaseUS Todo Backup.

## Possible Solution
* Stop the EaseUS Partition Master Free Edition task if found running at end of install script.
* Don't install EaseUS Todo Backup if there's an EaseUS Partition Master Free Edition installer switch to do so, or uninstall EaseUS Todo Backup after the EaseUS Partition Master Free Edition installer finishes, or if deemed better -  add a package parameter to the package install to give the installer user a choice of having EaseUS Todo Backup uninstalled after the EaseUS Partition Master Free Edition installer finishes.

## Steps to Reproduce (for bugs)
install partitionmasterfree package

## Context
I have a reasonable default expectation that installing a package will NOT result in a GUI program running and staying on my screen after the package has finished installing.

## Your Environment
* Package Version used: PartitionMasterFree v13.0 [Approved]
* Operating System and version: Microsoft Windows [Version 10.0.17763.134]
* Chocolatey version: Chocolatey v0.10.11
* Install/uninstall gist: n/a

**Comment by AdmiringWorm** [comment]
I looked a little into this, and I've been unable to reproduce the result you've mentioned.

1. When install this package, I don't get any additional softwares installed.
2. When install the package, no gui program is launched. However, a website is launched though. Which would be a bad idea to force close (no way in the installer to disable the opening of the website)

**Comment by bcurran3** [comment]
Kim - please take a look again. Maybe you did an upgrade?

Below three screenshots on my mostly virgin Win10 testing VM. 
cinst partitionmasterfree and then screenshots with no further computer interaction.
Looks like maybe the EaseUS Todo Backup was removed from v13 of EPMF.

This behavior has been present going back multiple versions of the package:

![image](https://user-images.githubusercontent.com/14026600/49454061-41c0a000-f799-11e8-81a2-d8e9700a2ff2.png)

![image](https://user-images.githubusercontent.com/14026600/49454075-47b68100-f799-11e8-9ffa-95ab013ca0bf.png)

![image](https://user-images.githubusercontent.com/14026600/49454127-60bf3200-f799-11e8-860b-75117f85aaf2.png)

**Comment by bcurran3** [comment]
CORRECTION: EaseUS Todo Backup still installs:

![image](https://user-images.githubusercontent.com/14026600/49454583-46398880-f79a-11e8-99fb-df5f5d28011c.png)

**Comment by bcurran3** [comment]
Kim,

I just installed on this on a Windows Server 2012 R2 machine.

I noticed some different behavior.

Being on a server, it's not the "free" version but a "trial" version. 

It also did not install EaseUS Todo Backup.

The program did not auto-run.

If you are testing on a server version of Windows, it explains why you and I get different results!

**Comment by AdmiringWorm** [comment]
That would indeed explain the reason why, I did use the server image (the same one recommended to be used for testing package).

Unfortunately I don't have any client VM's available to be used, so I couldn't test that.

> Being on a server, it's not the "free" version but a "trial" version.

Not really surprised on that though.


I did have a look through the installer script used for the installer (extracted using `innounp`), and from what I can see, there is no way to stop the installation of EaseUS Todo Backup (I couldn't actually see any reference to it either, but they could have scripted that).
Same with the auto start of the program, stopping it shouldn't really be much of a problem though.

**Comment by bcurran3** [comment]
Stopping the program on Workstation installs is a paramount request.

Things to consider:
* Changing the package title from "EaseUS Partition Master (Free) " to "EaseUS Partition Master (Free/Trial)"
* adding removing EaseUS ToDo Backup in the uninstall script (if found)

Thanks for continuing to look into this.

**Comment by AdmiringWorm** [comment]
I looked a little more into this (finally got around to find myself a Client based VM).
The startup of the application I can already say won't be shutdown as it currently stands.
The program only reports itself as `Main`, as such it won't be closed due to the risk of suddenly aquiring a different program when trying to stop the process.

*Haven't yet looked into the uninstall part though*

**Comment by AdmiringWorm** [comment]
I'm working on an uninstall script now to allow the uninstallation of the `EaseUS Todo Backup Free` program, however this will be an opt-in when running `choco uninstall`.

The reason I've decided to do an opt-in, is because we can't be sure if it was installed as part of partitionmasterfree, or if the user explicitly installed the program.

This change will be available from the next version of partitionmasterfree (when I'm done with the testing).

**Comment by AdmiringWorm** [comment]
I found a way to what I believe to be a reliable way to close the application.

I've just forced an update run for the package, feel free to test it out when the new version is available.

**Comment by AdmiringWorm** [comment]
If you're interested, the following commits contains the necessary code.

Uninstallation: https://github.com/chocolatey/chocolatey-coreteampackages/commit/1fc4c8cfcc785e3ad82eeac56fe1023057cf6bb5

Stopping the program: https://github.com/chocolatey/chocolatey-coreteampackages/commit/47994431775ad6d555057110d81f3590703559f3

**Comment by bcurran3** [comment]
Sorry for such a delay in my part of the conversation.

Got bombarded with a long emergency job and then bombarded by package validator kickbacks, and my own pet projects.

Hopefully I'll find some time to test this out soon and respond to you appropriately.
