### ISSUE TITLE
GitExtensions 3.0.0 - Installation fails due to Remove=Icons

### ISSUE THREAD

**Issue by laurin1** [chocolatey/chocolatey-coreteampackages#1156]
https://chocolatey.org/packages/gitextensions

C:\windows\system32>cup gitextensions
Chocolatey v0.10.11 Business
Upgrading the following packages:
gitextensions
By upgrading you accept licenses for the packages.

You have gitextensions v2.51.5 installed. Version 3.0.0 is available based on your source(s).
Progress: Downloading gitextensions 3.0.0... 100%

gitextensions v3.0.0 [Approved]
gitextensions package files upgrade completed. Performing other installation steps.
Copying gitextensions
from 'C:\ProgramData\chocolatey\lib\gitextensions\tools\GitExtensions-3.00.00.4433.msi'
Virus check: 0/48 scan engines flagged this assembly.
Due to possible false positives we fail at 4 minimum positives.
Virus scan engines indicate this file is probably safe. For details see
https://www.virustotal.com/...
Installing GitExtensions-3.00.00.4433.msi...
Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding `--install-arguments="'/l*v c:\gitextensions_msi_install.log'"`. Then search the MSI Log for "Return Value 3" and look above that for the error.
ERROR:
Running ['C:\WINDOWS\System32\msiexec.exe' /i "C:\Users\keithdavis\AppData\Local\Temp\chocolatey\gitextensions\3.0.0\GitExtensions-3.00.00.4433.msi" /quiet /norestart ADDDEFAULT=ALL REMOVE=AddToPath,Icons] was not successful.
Exit code was '1603' Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding `--install-arguments="'/l*v c:\gitextensions_msi_install.log'"`. Then search the MSI Log for "Return Value 3" and look above that for the error...
The upgrade of gitextensions was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\gitextensions\tools\chocolateyInstall.ps1'.
See log for details.

Tried running the choco command for this without /quiet:

"C:\WINDOWS\System32\msiexec.exe /i "C:\Users\keithdavis\AppData\Local\Temp\chocolatey\gitextensions\3.0.0GitExtensions-3.00.00.4433.msi" /norestart ADDDEFAULT=ALL REMOVE=AddToPath,Icons"

This is what happened.

![image](https://user-images.githubusercontent.com/75857/49649453-d243ee00-f9ee-11e8-98db-e9f33e210106.png)

If I remove **Icons** from "REMOVE=AddToPath,Icons", I don't get the error.

**Comment by AdmiringWorm** [comment]
Thanks for opening this issue, I'll have a look at this.
Could be that they have renamed the `Icons` variable that we try to remove.

I'll need to test this before a fix version can be pushed.

**Comment by AdmiringWorm** [comment]
It indeed seems like they have completely removed the option to disable installing Icons (can't find any reference to it anymore, not even under other names).

I'll remove it and push out a fix version shortly.
