### ISSUE TITLE
(winrar) v5.6.1 is out but not on chocolatey

### ISSUE THREAD

**Issue by b-raj001** [chocolatey/chocolatey-coreteampackages#1158]
Winrar v5.6.1 is available for some months now but not via chocolatey, so I contacted the maintainers. I have got no response, neither have others.

**Comment by AdmiringWorm** [comment]
winrar isn't maintained in this repository, please contact the correct maintainers to get this package updated.

This can be done through the `Contact Maintainers` link on the package page.
