### ISSUE TITLE
(Ruby) A typo in script causes deletion of *.exe files in working directory

### ISSUE THREAD

**Issue by arkfps** [chocolatey/chocolatey-coreteampackages#1164]
In `Chocolateyinstall.ps1` in the line
```ps
Get-ChildItem $toolsPath\*.exe | ForEach-Object { Remove-Item $_ -ea 0; if (Test-Path $_) { Set-Content "$_.ignore" '' }}
```
the variable `$toolsPath` is undefined (should be `$toolsDir`, probably). As the variable exapnds to nothing this line of code delete `.exe` files in one's working directory.

## Solution
- Change `$toolsPath` to `$toolsDir`.
- Use strict mode (`Set-StrictMode`) to prevent such kind of errors.

**Comment by AdmiringWorm** [comment]
Thanks for letting us know, I'll get out a fix for this ASAP.

Not sure if using the `Set-StrictMode` is a valid approach in a chocolatey package, but definitely something I would consider.

**Comment by AdmiringWorm** [comment]
a fix version have been pushed to chocolatey.org.

Again, thank you for letting us know of the typos.
