### ISSUE TITLE
Add Admin Tag

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#117]
Where necessary, admin tags should be added to all nuspec's where an administrative helper function is being used.  This is inline with the package validator wiki article here:

https://github.com/chocolatey/package-validator/wiki/AdminTagShouldBeUsedWhenUsingAdminHelper

**Comment by dtgm** [comment]
@gep13 did you do this manually or script?

rel: https://github.com/dtgm/chocolatey-packages/issues/213

**Comment by gep13** [comment]
@dtgm fairly sure that this would have been done manually, after doing a search for each of the admin helpers.  I have started doing what you do and adding the script that is used in PR's where a chunk of work was done.
