### ISSUE TITLE
Choco Package Manager (offline installation)

### ISSUE THREAD

**Issue by hs-hub-world** [chocolatey/chocolatey-coreteampackages#1170]
Hello, not sure where to log this request. this is related to the offline package manager installation script located on this site: https://chocolatey.org/docs/installation#completely-offline-install

I have two requests - which I am sure it will help others.
#1- can you please add something in the script that checks for available disk space. Here is a sample
```
$disk = Get-WmiObject Win32_LogicalDisk -Filter "DeviceID='C:'" | Select-Object Size,FreeSpace
write "Disk Size:$([math]::round($disk.Size /1GB, 3).tostring("#,###")) GB"
write "Free Space Available:$([math]::round($disk.FreeSpace/1MB, 3).tostring("#,###")) MB"
$MBFreeSpace = $disk.FreeSpace/1MB
if($MBFreeSpace  -lt 100)
{
    throw "Not enough disk space available."
}
```

#2- For the variable $localChocolateyPackageFilePath can you please check if the path does not exist either create it or throw an error.
SAMPLE:
```
$LocalDirPath = split-path -Path $localChocolateyPackageFilePath 
if(!(test-path $LocalDirPath))
{
    new-item -type directory $LocalDirPath -Force -Confirm:$false |Out-Null
}
```

Thank you!
H

**Comment by AdmiringWorm** [comment]
I'm sorry, but this is the wrong repository for such requests.
This repository is only for issues/requests for the packages maintained in this repository.

I believe the repository you're looking for is: https://github.com/chocolatey/choco-wiki (I could be wrong though).
