### ISSUE TITLE
(git.install) Add options to separately disable Shell Integration option

### ISSUE THREAD

**Issue by SharpSeeEr** [chocolatey/chocolatey-coreteampackages#1173]
## Expected Behavior

Add separate Shell Integration options:

* NoShellHereIntegration - disable the _"Git Bash Here"_ entry in context menus
* NoGuiHereIntegration - disable the _"Git GUI Here"_ entry in context menus

## Current Behavior

The current option only allows enabling or disabling both.

## Possible Solution

I have modified the [automatic/git.install/tools/helpers.ps1](https://github.com/SharpSeeEr/chocolatey-coreteampackages/commit/5ea0483d25c08f0a4bcc1d0bded662123c54c6e9) script on my fork to allow for these two options.  I'll be happy to send a pull request, but I thought it might be good to discuss the idea here first.

## Context

For my team's environment we install Git with only the _"Git Bash Here"_ option, to encourage use of the command line.

## Your Environment

* Package Version used: 2.20.1
* Operating System and version: Windows 10 Home 1803 
* Chocolatey version: 0.10.11

**Comment by AdmiringWorm** [comment]
@StingRayZA I had a look at the code you changed in your repository, and they looks good to me.

So if you're willing, we would love a PR from your to include these changes 😄

**Comment by StingRayZA** [comment]
Um. @AdmiringWorm I think you accidentally tagged me instead of @SharpSeeEr ... :)

**Comment by AdmiringWorm** [comment]
@StingRayZA 😆 ops, must have looked at some other place when I wrote.

Thanks, for referring him for me then, and sorry about the wrong mention.

**Comment by SharpSeeEr** [comment]
Pull request has been sent!  And may I say, very nice CI process you have here.

**Comment by majkinetor** [comment]
Thanks 👍
