### ISSUE TITLE
(mixxx) Entity Too Large Exception

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#1179]
Looks like the mixx package, which is an embedded package has grown too large in order to be pushed to chocolatey.org:

> Attempting to push mixxx.2.2.0.nupkg to https://push.chocolatey.org Failed to process request. 'Request Entity Too Large'.  The remote server returned an error: (413) Request Entity Too Large..

Is there a precedence for what to do in this case?  Should this no longer be an embedded package?

@majkinetor @AdmiringWorm

**Comment by AdmiringWorm** [comment]
Well, since it has grown too large. We really don't have any other option than to change it back to a non-embedded package 🙁

**Comment by majkinetor** [comment]
We can make 2 packages by arch too.


But as far as I can see v2.2.0 combined is 220MB and limit is defined as 300 so you either silently reduced the maximum size or there is a bug. It look like core Chocolatey guys really need to take care of this recent embedding issues (as nobody else can). As it is, its totally demoralizing for this repository, my personal interest is dropping fast.

**Comment by majkinetor** [comment]
Package size has nothing to do with _rate-limiting_. Could you configure Cloudflare to allow previously set 300MB size ?

You must be aware that in the age of electron apps 200MB is way to little.

**Comment by AdmiringWorm** [comment]
Actually it has everything to do with the rate-limiting, because there was a need to change to use Cloudflare (from my understanding).

and since Cloudflare have a maximum value of 200MB (it can't be increased further), it was necessary to decrease the limit.

^^ is from my understanding on the changes that were necessary to implement.

**Comment by gep13** [comment]
>@majkinetor said...
Package size has nothing to do with rate-limiting.

It actually has everything to do with it, and that is why I said it, but let me re-state...

Due to the fact that we implemented rate limiting (which has resulted in a far more stable Chocolatey Community Repository, which previously regularly required maintenance), **all** requests now go through Cloudflare, rather than going directly to the site.  The previous upper limit of 350 MB (as mentioned in the Gitter discussion that you linked to in your commit) was in place due to this being the available upper limit when going directly to the site.

>@majkinetor said...
Could you configure Cloudflare to allow previously set 300MB size ?

The short answer is no.  

The slightly longer answer is that this would mean switching the plan that we have currently with [Cloudflare](https://www.cloudflare.com/plans/).  I will leave it to you to figure out what plan would be required by comparing the [features](https://www.cloudflare.com/plans/#compare-features).  That is not to say that we won't have this available at "some" point, but for now, the upper limit is 200MB.

This change was an unintentional side effect of implementing rate limiting (which has resulted in a better experience for everyone in the community using the Community Repository), and wasn't in any way a malicious act, but I agree that it should have been communicated better.

**Comment by majkinetor** [comment]
OK. We should discontinue mixxx then since it no longer works. 

OR, we keep the package and post updates to Github releases instead until happier future arrives. If we do that, installing mixxxx directly from releases will be no different then using choco iteself.  I use on my own repo [cinst-gh](https://github.com/majkinetor/au-packages/blob/master/cinst-gh.ps1) (it installs from repository, not releases, but I can easily change that) and we can add one here that people can use in a manner:  `cinst-gh mixxx`. I can also add this into AU framework so people that have it could start using it ASAP. Source could be set via environment variable.

**Comment by AdmiringWorm** [comment]
Or just convert the package back to download mixxx from the web during install.

**Comment by majkinetor** [comment]
Meh.

**Comment by Be-ing** [comment]
Hi, Mixxx developer here. @wget asked about this on our [Zulip chat](https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/chocolatey). The reason for the increased package size with 2.2.0 is probably the switch from Qt4 to Qt5. We statically link our builds to keep package size down by excluding unused symbols from libraries, so I'm not sure there's much we can do to reduce our installer size more. If you have ideas how to reduce our download sizes though, let us know. Even better if you make a pull request. :)

> Or just convert the package back to download mixxx from the web during install.

downloads.mixxx.org is up so people can download it, so I'm not opposed to this (I can't speak for other Mixxx developers). Of course if you can offload some traffic onto your servers that would be nice.

**Comment by majkinetor** [comment]
You shouldnt do anything as its not your problem really.

Its not that I have somethimg against ur download place but its antipattern for reasons explained in contributing guide and makes package non cashable on artifact managers.

I own a music production studio and my setup is automated. Projects may not play the same on different sequencer versions and thats why having stable and long living package is a must.

Thx for your great work by the way.

**Comment by wget** [comment]
Btw, I have checked the ability to send data in chunk, this seems really easy to do. We have a nuget chocolatey repo where all our changes are. We just require simultaneous update with the server.

In the mean time. We can close this issue. Pull request fix: #1189
