### ISSUE TITLE
(picard) Requires x64 bit version

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#1180]

**Comment by majkinetor** [comment]
Current problem is that arch versions differ so nothing can be done in this moment.

https://picard.musicbrainz.org/downloads

**Comment by AdmiringWorm** [comment]
From my gathering in their changelog, 2.0+ will only support 64bit.
https://github.com/metabrainz/picard/blob/master/NEWS.txt

**Comment by majkinetor** [comment]
Well, then, it looks like its already good, its just named incorrectly by AU (with _x32 prefix), so its not a big deal. I will close this.
