### ISSUE TITLE
(gpg4win*) Let users provide a custom `gpg4win.ini`

### ISSUE THREAD

**Issue by nagromc** [chocolatey/chocolatey-coreteampackages#1181]
## Expected Behavior

I would need a way to provide a `gpg4win.ini` path, as per described in the [Compendium](https://gpg4win.org/doc/en/gpg4win-compendium_35.html).

## Current Behavior

Currently, `choco install gpg4win` doesn't provide such an option.

## Possible Solution

Maybe use a [`--param` Chocolatey option](https://chocolatey.org/docs/helpers-get-package-parameters) to provide a `gpg4win.ini` path.

## Context

In order to customize my Gpg4win installation, I provide to `gpg4win-x.y.z.exe` a `gpg4win.ini` with the `/C` switch.

## Your Environment

* Package Version used: v3.1.5
* Operating System and version: 10 v1803
* Chocolatey version: v0.10.11

**Comment by AdmiringWorm** [comment]
You can actually do this already, just not through a package parameter.

You can pass arguments directly to the installer when calling choco install.
For instance:
```powershell
choco install gpg4win --install-arguments="/C=C:\My\Path\To\config.ini"
```

I don't disagree with having this as a package parameter though.

**Comment by nagromc** [comment]
Oh I was looking for this option. And all I could find was the `--param` Chocolatey option. I'm quite new to Chocolatey 🙂

Thanks for pointing that out.

**Comment by AdmiringWorm** [comment]
This have now been added to the source.
It won't be available until the next version of gpg4win is released though
