### ISSUE TITLE
Add support for Python 2.7.15 and 3.5.6

### ISSUE THREAD

**Issue by cclauss** [chocolatey/chocolatey-coreteampackages#1183]
https://chocolatey.org/packages/python
* choco install python --version 2.7.15
* choco install python --version 3.5.6

## Expected Behavior

Install of these current versions

## Current Behavior

choco install python --version 2.7.11  # works but is not the latest and greatest
choco install python --version 3.5.4  # works but is not the latest and greatest

## Steps to Reproduce (for bugs)

1. choco install python --version 2.7.15
2. choco install python --version 3.5.6

## Context

Testing Python software packages on Travis CI running Windows

## Your Environment

* Package Version used: 
* Operating System and version: https://docs.travis-ci.com/user/reference/windows/
* Chocolatey version: v0.10.11
* Install/uninstall gist:

**Comment by majkinetor** [comment]
Python packages support streams. Python3 update.ps1 for example looks here:

- https://www.python.org/downloads/windows/

where 3.5.6 isn't listed so its upstream problem.

**Comment by cclauss** [comment]
Understood.  That explains Python 3.5.6 but not 2.7.15...
* That release is here https://www.python.org/downloads/windows/
* But this fails https://travis-ci.com/cclauss/itinerant-tester-windows/jobs/169196524#L27

**Comment by majkinetor** [comment]
The stream versions are kept at:

- https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/python2/python2.json

It shows 2.7.15 is the latest. Here is the adequate [report](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f/557312b7c41cf804dfe5e88e17488a054ac6443d#pushed) where it is shown that it was pushed. 

The package is there and it works:

- https://chocolatey.org/packages/python2/2.7.15

```
PS C:\Users\majkinetor> cinst python2
Chocolatey v0.10.11
Installing the following packages:
python2
By installing you accept licenses for the packages.
Progress: Downloading python2 2.7.15... 100%

python2 v2.7.15 [Approved]
python2 package files install completed. Performing other installation steps.
...
```

**Comment by majkinetor** [comment]
Actually, the MAIN problem with python2 is that it is not embedded into package yet which will render all packages non usable eventually.

I did some work on it and it looks like its working but I never tested it enough nor I have motivation any more. With embedded package you can target *.nupkg directly from Github and it will work in case you have some strange chocolatey problems. 

I can publish the branch if anybody is interested in testing/finishing this.

**Comment by cclauss** [comment]
I will use https://chocolatey.org/packages/python2/2.7.15...  Thanks.
