### ISSUE TITLE
Feature request: compile packages from source

### ISSUE THREAD

**Issue by Foadsf** [chocolatey/chocolatey-coreteampackages#1184]
I think I have asked for this feature before but I'm not able to find it now. Sorry in advance if it is a duplicate. 

**What:**
Following the discussions with @gep13 [here on Twitter](https://twitter.com/fsfarimani/status/1083130861111967746) and @pauby [here](https://github.com/chocolatey/chocolatey-package-requests/issues/376#issue-342304758) I'm proposing to add compile from source feature:

`choco install package --source`

as suggested [here in this Scoop issue](https://github.com/lukesampson/scoop/issues/340). 

**Why:**
- there will be less need for binary hosting
- less maintenance for outdated formulas
- users will have access to the latest bug fixes and features in real time
- for those who want the optimized binaries
- incremental updates instead of downloading the whole binary

**Other:**
 On MacOS HomeBrew can do this and on Linux guix/nix, Spack, EasyBuild, portage, pkgsrc, LinuxBrew ...

**Comment by majkinetor** [comment]
Wrong place to post this. You want https://github.com/chocolatey/choco.

Although this is technically doable during the update, I don't think this is something we will ever see here due to fantastic amount of work involved for random package for next to zero benefit - all the stuff you mentioned are either not worth it or incorrect.

**Comment by Foadsf** [comment]
@majkinetor is there anyway to move this ticket to the right place? Or I have to reopen it there?

**Comment by gep13** [comment]
>@Foadsf said...
is there anyway to move this ticket to the right place? Or I have to reopen it there?

Best to open a new ticket.

**Comment by ferventcoder** [comment]
@majkinetor I agree with you. I elaborated a bit more on this as well - https://github.com/chocolatey/choco/issues/1709#issuecomment-453605012
