### ISSUE TITLE
(everything) Cannot install or upgrade using latest version

### ISSUE THREAD

**Issue by WillPresley** [chocolatey/chocolatey-coreteampackages#1192]
## Expected Behavior
Everything should update or install like normal for a Chocolatey package.

## Current Behavior
The process fails with the following error message:
```
ERROR: Cannot process argument transformation on parameter 'file'. Cannot convert value to type System.String.
The install of everything was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\Everything\tools\chocolateyInstall.ps1'.
 See log for details.
```

## Steps to Reproduce (for bugs)

1. Run `choco install everything` or `choco upgrade everything`
2. Receive error message.

## Context
Noticing while running a weekly `cup all` at work.

## Your Environment

* Package Version used: v1.4.1928 (latest, previous version did not have issue)
* Operating System and version: Windows 10 Insider Preview | 1809 | b17763.253
* Chocolatey version: v0.10.11

## Screenshot of error
![choco-everything-upgrade-error_2019-01-14](https://user-images.githubusercontent.com/5607733/51135336-c1fe0a80-1807-11e9-8510-779cb73947b4.png)

**Comment by majkinetor** [comment]
Could you give the content of your tools folder ?

**Comment by WillPresley** [comment]
I can only assume you meant `dir /s C:\ProgramData\chocolatey\lib\Everything\` as the one you gave isn't a valid command. Here is that output:
```
C:\Windows\system32>dir /s C:\ProgramData\chocolatey\lib\Everything\

 Directory of C:\ProgramData\chocolatey\lib\Everything

01/13/2019  05:35 PM    <DIR>          .
01/13/2019  05:35 PM    <DIR>          ..
12/31/2018  07:45 PM         2,990,136 Everything.nupkg
12/31/2018  07:45 PM             2,766 Everything.nuspec
01/13/2019  05:35 PM    <DIR>          legal
01/13/2019  05:35 PM    <DIR>          tools
               2 File(s)      2,992,902 bytes

 Directory of C:\ProgramData\chocolatey\lib\Everything\legal

01/13/2019  05:35 PM    <DIR>          .
01/13/2019  05:35 PM    <DIR>          ..
12/31/2018  07:45 PM             2,708 License.txt
12/31/2018  07:45 PM             1,051 VERIFICATION.txt
               2 File(s)          3,759 bytes

 Directory of C:\ProgramData\chocolatey\lib\Everything\tools

01/13/2019  05:35 PM    <DIR>          .
01/13/2019  05:35 PM    <DIR>          ..
01/13/2019  07:08 PM             1,212 chocolateyInstall.ps1
12/31/2018  07:45 PM             1,115 chocolateyUninstall.ps1
12/31/2018  07:45 PM           108,136 es.exe
12/31/2018  07:45 PM                 6 Everything-1.4.1.924.x64-Setup.exe.ignore
01/11/2019  04:01 AM         1,603,768 Everything-1.4.1.927.x64-Setup.exe
01/11/2019  04:01 AM                 6 Everything-1.4.1.927.x64-Setup.exe.ignore
01/11/2019  04:01 AM         1,499,400 Everything-1.4.1.927.x86-Setup.exe
               7 File(s)      3,213,643 bytes

     Total Files Listed:
              11 File(s)      6,210,304 bytes
               8 Dir(s)  125,545,226,240 bytes free
```
Seems like the newest installer is not being downloaded.

**Comment by majkinetor** [comment]
As I suspected you have leftovers of previous versions. Delete them and it will work. Its strange how you got this since it should have been deleted after previous install, and if it didn't, the install would fail. 

* https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/everything/tools/chocolateyInstall.ps1#L14

**Comment by WillPresley** [comment]
Thank you for the help. Removing the Setup exe and ignore files and re-running the command takes care of the issue. I'm also not sure how it could have happened, but I will keep an eye on things and find a cause if the issue resurfaces. Thanks again!
