### ISSUE TITLE
Please fix the Python packages/docs

### ISSUE THREAD

**Issue by CollinChaffin** [chocolatey/chocolatey-coreteampackages#1213]
After years it still shows incorrect info for Python as:
```
This package is not intended to use with Chocolatey's -x86 parameter. If you want a 32-bit Python 2.x on 64-bit systems, install the {{PackageName}}-x86_32 package instead. You can also install both packages. In this case you must manually adapt your PATH environment variable so that it picks the Python 2.x version that you want when invoking python.exe.
```

This instruction is incorrect on all counts.  When you visit the x86_32 package, it states in big red letters DEPRECIATED and DO NOT USE and instead, use the very `--x86` the package that just sent me stated NOT to do.  So, you install with `--x86` and the result is horrible. Simply reviewing the package community comments quickly reveals that Python developers have been struggling this exact issue for years.

Proceeding with the `--x86` switch as instructed DOES actually install the 32-bit python2 after the successful 64-bit, however now your system's 64bit package info is essentially lost in that you've forced the 32-bit install as a 2nd run, and with "userememberedforupgrades" option, subsequent upgrades and even an uninstall would only ever be performed on the 32-bit (last installed).

Clearly forcing two installs only to lose all record of the 1st is not the way this should be done.  I'm opening this issue to request these packages finally be updated to provide what was working fine years ago via separate x86 packages.

Note that this is almost ALWAYS today needed on any serious Python DEV system - BOTH the 32 and 64 bit versions and of BOTH python2 and 3.  This requires either again having FOUR total packages, or the much more preferred method which would only require alteration of the two primary (`python` and `python2`) to properly detect the OS bitness and, like other packages commonly do, only if running on 64bit and the `--x86` param given, is the 32-bit installed IN ADDITION to the native 64bit (javaruntime is I believe a working example of this).

Having this finally addressed would be fantastic since today the way these packages are set up essentially makes installing python with Chocolatey and maintaining it MUCH harder than without Chocolatey which kind of defeats the whole purpose of package management. :)

**Comment by majkinetor** [comment]
I already removed that, see https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/python2/README.md

It will get on gallery on next release.
