### ISSUE TITLE
(thunderbird) 64-bit version

### ISSUE THREAD

**Issue by kaffeekanne** [chocolatey/chocolatey-coreteampackages#1218]
## Expected Behavior
Since it is available and chocolatey aims to install only 64-bit software if possible, a 64-bit version of thunderbird would be very nice to have on recent desktops.

## Current Behavior
Currently only the 32-bit version is installed. the 64-bit version is offered but not advertised by mozilla. i use it sind some months and found the direct link through some german thunderbird community.

## Possible Solution
The download link can be obtained by changing "win32" to "win64" and keep everything else. Example:
`https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/60.5.0/win64/de/Thunderbird%20Setup%2060.5.0.exe`

## Steps to Reproduce (for bugs)
None, since it's no bug.

## Context
I like to take full advantage of my machines architecture. If the main install script should stay 32bit as default a switch oder second package offering 64 bit is highly appreciated, until mozilla offers official builds.

## Your Environment
* Package Version used: not yet installed
* Operating System and version: Windows 10 Pro (64 Bit)
* Chocolatey version: 0.10.11

**Comment by kaffeekanne** [comment]
I expected that answer. When the 64 Bit is official a upgradepath would be appreciated. I did uninstall Thinderbird win32 and installed win64 afterwards without noticing problems. Probably Mozilla is taking care of that already.

**Comment by AdmiringWorm** [comment]
I'm currently looking into adding support for 64bit.
I was wrong with my previous comment, we only partially parse the location I mentioned, so there isn't anything stopping us from adding support

**Comment by AdmiringWorm** [comment]
This have now been implemented, and a forced update is being scheduled.

I've taken the same upgrade path as the firefox package, that is.
If the 32bit edition is already installed on the computer, it will continue using 32bit, otherwise it uses 64bit on WIN64
