### ISSUE TITLE
(firefox) Automatic update broken - file URL has changed

### ISSUE THREAD

**Issue by NicoHaase** [chocolatey/chocolatey-coreteampackages#1224]
## Expected Behavior
`cup firefox` updates Firefox to v65.0.1

## Current Behavior
Package update is still in moderation

## Possible Solution
The URL has changed: according to https://download-installer.cdn.mozilla.net/pub/firefox/releases/65.0.1/win64/en-US/, the filename includes the version number now and is no longer held generic

**Comment by NicoHaase** [comment]
I'm not sure how exactly that happened, but https://gist.github.com/choco-bot/837ec070ea1277c58e491d4e4637a163 lists that the download should happen from https://download-installer.cdn.mozilla.net/pub/firefox/releases/65.0.1/win64/en-US/Firefox%20Installer.exe

**Comment by AdmiringWorm** [comment]
I'm guessing that when we initially checked for updates, they hadn't yet uploaded the correctly named installer.

I'm working on an update to the checker to not use the redirected urls, which hopefully will prevent situations like this to occur in the future.

**Comment by AdmiringWorm** [comment]
This is now fixed, and a I'm forcing a resubmit of the latest package version

**Comment by NicoHaase** [comment]
The updated package works, thank you!
