### ISSUE TITLE
(mpc-hc) Project Moved - New Version

### ISSUE THREAD

**Issue by wmDevCodes** [chocolatey/chocolatey-coreteampackages#1226]
## Context
On **Media Player Classic** original page : [https://mpc-hc.org/](https://mpc-hc.org/) , it states in the "latest news" in July 2016 that the mpc project is coming to an end.

clsid2 on Github revived the mpc project and is hosting it here : [https://github.com/clsid2/mpc-hc/releases](https://github.com/clsid2/mpc-hc/releases)

## Possible Solution
- Carry on with mpc-hc updated versions from clsid2's project
- I can take over the mpc-hc choco package as maintainer and carry on with updated versions from clsid2's project :)

**Comment by AdmiringWorm** [comment]
I'm sorry, but the project hasn't moved, but rather a fork of the current source code of mpc-hc. As such, it was considered as a new software, and have been released under a different name [mpc-hc-clsid2](https://chocolatey.org/packages/mpc-hc-clsid2)

**Comment by wmDevCodes** [comment]
@AdmiringWorm Not sure why my issue has been closed, as I was told to open an issue for further discussion. No discussion was even done.

**Media Player Classic 1.7** & **Media Player Classic 1.8** doesn't really define "new software" since it is based of exactly the same base code, as well as versioning continuing, and not starting back to version 0.1.

`choco install mpc-hc` seems like the obvious choice for Media Player Classic in searching as well as installing.

What is happening now, is you find that installing mpc-hc in a logical manner which installs version `1.7.13.20180702` is flawed. An error message upon opening up version `1.7.13.20180702` states immediate upgrade to `1.7.13.32` as per [https://trac.mpc-hc.org/ticket/6239](https://trac.mpc-hc.org/ticket/6239). This leads one to naturally open up an issue after reporting it to the maintainer just to find 1.7 abandoned 3 years ago and wasting 2 days of my life suggestion a simple option of continuing the mpc-hc package as is.

The reason provided for having **mpc-hc-clsid2** does not make sense to me.
