### ISSUE TITLE
(mp3tag) Upgrade isn't silent

### ISSUE THREAD

**Issue by jtcmedia** [chocolatey/chocolatey-coreteampackages#1234]
## Expected Behavior

Upgrade of mp3tag hangs.

## Current Behavior

Have to click through several windows to finish the upgrade.

## Possible Solution

Looks like it might need an autohotkey script

## Steps to Reproduce (for bugs)

just do a choco upgrade

## Your Environment

* Package Version used: 2.94
* Operating System and version: Windows 10 Pro
* Chocolatey version: 0.10.11
* Install/uninstall gist:

**Comment by jack1142** [comment]
I just checked this package, trying to update from 2.93 to 2.94 and I didn't get any window, which would prevent upgrade from being done automatically. I may need more details to help you with this issue: 
1. Do you know from which version was the chocolatey upgrading the package?
2. Do you remember what windows did you have to click through? Was it the part of uninstallation process or installation process?

**Comment by jack1142** [comment]
I want to note, that if the version of package was below Mp3tag 2.91.8-beta, then uninstallation wasn't silent, option to make silent uninstall was added in Mp3tag 2.91h (which is represented by 2.91.8-beta in chocolatey repository), so upgrade from every release before that wasn't silent.

**Comment by jtcmedia** [comment]
I have 2.94 installed and just tried `choco upgrade mp3tag --force`

And get:
`Overriding package arguments with '/DesktopShortcut=false' (replacing '/S')`

And the Setup window pops up:
[![Capture.png](https://i.postimg.cc/6Q35NxCd/Capture.png)](https://postimg.cc/75Fygcs6)

**Comment by AdmiringWorm** [comment]
@jtcmedia actually, from the last information you provided this is unrelated to anything in the package at all.

It seems that chocolatey somehow remembered an argument you may have used previously which completely overrides the package install arguments.
Maybe you've done in the past something similiar to: `choco install mp3tag --ia "/DestkpShortcut=false"`

Also, the argument you're looking for is `/NoDesktopShortcut`
ie `choco install mp3tag --params "/NoDesktopShortcut"`.

Anyways, closing this as it isn't anything related to the code of the package, nor the software itself. Feel free to open it if you think there is any more value to be added.

**Comment by jack1142** [comment]
Yeah, this looks like use of install arguments instead of package parameters.
