### ISSUE TITLE
(dropbox) does not autostart after upgrade

### ISSUE THREAD

**Issue by demoklion** [chocolatey/chocolatey-coreteampackages#1242]
## Expected Behavior
`choco upgrade dropbox`
choco gets an upgrade package (eg. in my case v68.4.102 ➡ v69.3.90), installs it and then starts dropbox again, so it continues watching and syncing files in the background

## Current Behavior
choco gets an upgrade package, installs it and then does not start dropbox

## Possible Solution
if dropbox was running before update, add a command to autostart it again after the upgrade

## Steps to Reproduce (for bugs)
n/a

## Context
I have set `choco upgrade all` to run during system start, to always have fresh versions. I have to take care to start dropbox, after it gets upgraded by choco.

## Your Environment

* Package Version used: irrelevant but v68.4.102 ➡ v69.3.90
* Operating System and version: Windows 10 Pro version 1809 build 17763.379
* Chocolatey version: 0.10.11

Just in case I do something wrong, here's a printout of the update from console:
```cmd
C:\Users\xxxxxx>choco upgrade dropbox
Chocolatey v0.10.11
Upgrading the following packages:
dropbox
By upgrading you accept licenses for the packages.

You have dropbox v68.4.102 installed. Version 69.3.90 is available based on your source(s).
Progress: Downloading dropbox 69.3.90... 100%

dropbox v69.3.90 [Approved]
dropbox package files upgrade completed. Performing other installation steps.
Downloading dropbox
  from 'https://clientupdates.dropboxstatic.com/dbx-releng/client/Dropbox%2069.3.90%20Offline%20Installer.exe'
Progress: 100% - Completed download of C:\Users\jandu\AppData\Local\Temp\chocolatey\dropbox\69.3.90\Dropbox 69.3.90 Offline Installer.exe (97.89 MB).
Download of Dropbox 69.3.90 Offline Installer.exe (97.89 MB) completed.
Hashes match.
Installing dropbox...
dropbox has been installed.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The upgrade of dropbox was successful.
  Software installed as 'exe', install location is likely default.
```

**Comment by RedBaron2** [comment]
@demoklion 
I will look into this I believe a stop-process call was placed in the install inadvertently. Testing this now.

**Comment by jack1142** [comment]
@RedBaron2 I have the branch ready to send a PR too, lol

**Comment by jack1142** [comment]
But it's like 3 line changes, so if you want it, you can take it ¯\_(ツ)_/¯

**Comment by jack1142** [comment]
Oh, and I wouldn't be so sure about stop-process being placed there inadvertently, I'm sure it's there to make the install fully silent, not everybody wants to see a dropbox window during installation of it.

**Comment by RedBaron2** [comment]
@jack1142 
The stop-process was placed originally to replace the need for a AHK script that was outdated for a previous installer. The newer installer for dropbox doesn't appear to need it from my testing.

**Comment by jack1142** [comment]
@RedBaron2 yeah, but I still think that it would be nicer if the login window didn't popup after installation - chocolatey packages are supposed to be silent and that should include what happens after the installation.

**Comment by RedBaron2** [comment]
I had forgot about that, but I am hoping that the installation window pester is due to not being signed in to start

**Comment by demoklion** [comment]
Thanks guys, I believe not killing the process after install, if it was already running before, will solve my problem.

**Comment by jack1142** [comment]
No problem, I'm sure it's annoying, if you have configured upgrades in background (I do the same thing on system start) and you won't see that it killed Dropbox process.
