### ISSUE TITLE
vscode-icons installation failure

### ISSUE THREAD

**Issue by jerome-benoit** [chocolatey/chocolatey-coreteampackages#1243]
## Expected Behavior

Flawless installation. 

## Current Behavior

```
> choco install vscode-icons -y
Chocolatey v0.10.11
Installing the following packages:
vscode-icons
By installing you accept licenses for the packages.
Progress: Downloading vscode-icons 1.0.0.20180620... 100%

vscode-icons v1.0.0.20180620 [Approved]
vscode-icons package files install completed. Performing other installation steps.
Extension 'robertohuertasm.vscode-icons' not found.
Make sure you use the full extension ID, including the publisher, eg: ms-vscode.csharp

Failed Installing Extensions: robertohuertasm.vscode-icons
```

## Steps to Reproduce (for bugs)

1. On a fresh choco bootstrap: choco install vscode-icons -y
2.
3.
4.

## Your Environment

* Package Version used:
* Operating System and version:
* Chocolatey version:
* Install/uninstall gist:

**Comment by gep13** [comment]
Looks like the publisher of this extension has changed. As a result, an update to the package will be required.

**Comment by jerome-benoit** [comment]
On 14/03/2019 11:32, Gary Ewan Park wrote:
>
> Looks like the publisher of this extension has changed. As a result,
> an update to the package will be required.
>
The publisher seems to be now 'VSCode Icons Team' now.

Thanks.

-- 
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by gep13** [comment]
@jerome-benoit exactly.

So this line:

https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/manual/vscode-extensions/vscode-icons/tools/chocolateyInstall.ps1#L2

Will need to be changed, and a new package version pushed.

**Comment by AdmiringWorm** [comment]
Updating that package was on my TODO list (updating to make use of `chocolatey-vscode.extension`). So I'll take care of updating with the correct publishers as well.

**Comment by AdmiringWorm** [comment]
changes have been made, and a new version should be pushed to chocolatey soon.
