### ISSUE TITLE
Notepadplusplus installation failed

### ISSUE THREAD

**Issue by arunjan2019** [chocolatey/chocolatey-coreteampackages#1245]
I used Chocolatey notepadplusplus installation in Ansible play book like below. It worked well for many days but today it throws this error. I haven't changed this code and its reference main.yml file too.

- name: Ensure notepad++ is installed using chocolatey
  win_chocolatey:
    name: notepadplusplus
    state: present

I would like to understand why this package is failed, what is the better solution?

**Comment by arunjan2019** [comment]
It throws the following error...
 fatal: FAILED! => {"changed": false, "module_stderr": "\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 2}
    vsphere-iso:        to retry, use: --limit @/tmp/packer/playbook/build-agents.retry

**Comment by AdmiringWorm** [comment]
Could be due to the new chocolatey version.
See https://github.com/chocolatey/choco/issues/1758

Closing this as I do not believe it to be package related.

**Comment by arunjan2019** [comment]
@AdmiringWorm - Appreciate your quick update. Referring the 1758, it asks to use the following code. but in Ansible playbook how I can use this?
choco feature disable --name="'useEnhancedExitCodes'"

**Comment by AdmiringWorm** [comment]
Unfortunately, I do not have any experience with ansible so I do not know.

This is something you probably have to ask the ansible people.

**Comment by ferventcoder** [comment]
@jborean93 ^^ curiosity here on how to disable a feature

**Comment by jborean93** [comment]
I've posted an example of how to continue to install Chocolatey, disable the enhanced exit code features and then install your package like normal here https://github.com/ansible/ansible/issues/53860#issuecomment-473509704.

**Comment by ferventcoder** [comment]
Note that the default for enhanced exit codes was turned to off for Chocolatey v0.10.14. This is for anyone that finds this issue as most folks commenting here are already aware. https://github.com/chocolatey/choco/issues/1784
