### ISSUE TITLE
(googlechrome) Unable to downgrade to earlier version

### ISSUE THREAD

**Issue by andmos** [chocolatey/chocolatey-coreteampackages#1250]
We ran into an issue with the headless PDF printer in Chrome in later versions that forces us to do a downgrade. We use Ansible and `win_chocolatey` ([doc](https://docs.ansible.com/ansible/devel/modules/win_chocolatey_module.html)) to orchestrate chocolatey packages on multiple servers. When trying a downgrade, let's say to `70.0.3538.11000`, it first fails on the expected checksum. If that is ignored, it installs correctly and Chocolatey returns the correct version, but opening Chrome shows the latest version installed. I guess this is because the package uses the latest MSI.

## Expected Behavior
When downgrading or cherry-picking version, expects this version to be picked.

## Current Behavior
Older versions fails on checksum error, installs latest if ignores while chocolatey returns latest.

Example output (wrapped from Ansible)
```
   "stdout_lines": [
        "Upgrading the following packages:",
        "googlechrome",
        "By upgrading you accept licenses for the packages.",
        "",
        "GoogleChrome v69.0.3497.8100 (forced) [Approved]",
        "googlechrome package files upgrade completed. Performing other installation steps.",
        "Downloading googlechrome 64 bit",
        "  from 'https://dl.google.com/tag/s/dl/chrome/install/googlechromestandaloneenterprise64.msi'",
        "",
        "Download of googlechromestandaloneenterprise64.msi (55.05 MB) completed.",
        "Error - hashes do not match. Actual value was '48CD60CB390475A6AC0DE4EA0DD78E2F2311F082186582DFE3965C3E0509E147'.",
        "ERROR: Checksum for 'C:\\temp\\chocolatey\\GoogleChrome\\69.0.3497.8100\\googlechromestandaloneenterprise64.msi' did not meet '290f0516826165399157b925ed330708dcc0492264bc591d8fe7e44e33b40500' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.",
        "The upgrade of googlechrome was NOT successful.",
```

## Possible Solution
If possible, bundle correct MSI? 

## Steps to Reproduce (for bugs)

1. `choco install googlechrome --version 70.0.3538.11000`
2. `choco install googlechrome --version 70.0.3538.11000 --ignore-checksum`
3. Open Chrome and see version in "about". 

## Context
Going from latest Chrome to earlier version because of breaking change in Chrome.exe headless PDF printing.

## Your Environment

* Package Version used: `70.0.3538.11000`, `69.0.3497.8100`, `73.0.3683.86`
* Operating System and version: Windows Server 2012 R2 and Windows Server 2016
* Chocolatey version: `0.10.11`

**Comment by AdmiringWorm** [comment]
it isn't possible to downgrade to a previous version of googlechrome unfortunately (unless you have a licensed edition of choco), due to google only providing a general url to the latest version of the program.

And since the license for googlechrome don't allow for redistribution of the program we cannot embed the package either.

Because of this, I'll be closing this issue. If the time ever comes when we can embed the binary, we can then reopen this again.

**Comment by andmos** [comment]
Thanks for the clarification!

**Comment by AdmiringWorm** [comment]
no problem

**Comment by andmos** [comment]
@AdmiringWorm how about uninstall? Doesn't seem to be supported either. Should I open separate issue for it?
