### ISSUE TITLE
(vcredist2008) uninstall script is wrong and observation

### ISSUE THREAD

**Issue by ericoporto** [chocolatey/chocolatey-coreteampackages#1253]
Firstly, I would like to also note [this comment here](https://chocolatey.org/packages/vcredist2008#comment-3151132869)

> Be very careful this redist package apparently does not support (nor is this choco package coded with) the "norestart" switch that literally every other vc redist supports. Meaning, this package can (and in my case) does force a sudden full system restart upon installing. This sucks because of course being a prereq, these often come early in a build process, but that also means now to install this package as is, we need to manage and monitor a restart with the build workflow.

Can the norestart flag be added? My env does appear to get an icon on shutdown telling me something needs to update the computer on reinstall, but I need this to run in a build env.

Going on to the main issue

https://chocolatey.org/packages/vcredist2008

## Expected Behavior
uninstall should uninstall vcredist2008 

## Current Behavior
currently, `tools\chocolateyUninstall.ps1` starts like this:

```
$packageName = 'vcredist2005'
$packageSearch = "Microsoft Visual C++ 2008 Redistributable*"
...
```

## Possible Solution
It should instead start like this:

```
$packageName = 'vcredist2008'
$packageSearch = "Microsoft Visual C++ 2008 Redistributable*"
...
```
## Steps to Reproduce (for bugs)
Try to uninstall package

## Context
[I was told I need to depend on this package](https://chocolatey.org/packages/ags).

>Pauby (reviewer) on 27 Mar 2019 09:56:14 +00:00:
>Hi,
>
>Thanks for making those changes. Everything is good to go with one exception.
>
>You mentioned that the package needs VC 2008 but InnoSetup does that. Can I ask you to add it as a dependency? I'll explain why.
>
>If you add the dependency to Chocolatey it will take advantage of 'internalization' of that package which means they may have setup a local Chocolatey source to get their packages from. So if you add it as a dependency it allows them to continue to utilise that and installing it from a local source. If you leave InnoSetup to do it they will pull it from the internet which does allow that to happen.

Also the [vcredist2008 package in this repository](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/manual/vcredist2008) doesn't match the one in [the chocolatey.org listing](https://chocolatey.org/packages/vcredist2008).

## Your Environment
https://az792536.vo.msecnd.net/vms/VMBuild_20150916/VirtualBox/IE8/IE8.Win7.VirtualBox.zip

**Comment by majkinetor** [comment]
Latest choco has a feature to prevent restarts, does that help ?

**Comment by majkinetor** [comment]
> Also the vcredist2008 package in this repository doesn't match the one in the chocolatey.org listing.

Definitelly not pushed to gallery.

> Can the norestart flag be added?

Sure.

**Comment by ericoporto** [comment]
Thank you, yes that helps. Great week for you @majkinetor :D
