### ISSUE TITLE
Python packages (python3, python2) set PATH variable to PATH="C:\PythonX\Scripts;C:\PythonX\;%PATH%"

### ISSUE THREAD

**Issue by day1player** [chocolatey/chocolatey-coreteampackages#1255]
Installing Python packages places C:\Python* at a higher precedence than C:\Windows\System32 and other base windows binaries. 
## Current/Expected Behavior

Currently the install changes the path to `PATH="C:\PythonX\Scripts;C:\PythonX\;%PATH%"` and it should change it to `PATH="%PATH%;C:\PythonX\Scripts;C:\PythonX\"`

## Steps to Reproduce (for bugs)

1. Install chocolatey
2. Install `python`, `python2`, or `python3`
3. In a command prompt window type `echo %PATH%`
```
C:\Users\IEUser>echo %PATH%
C:\Python37\Scripts\;C:\Python37\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Puppet Labs\Puppet\bin;C:\Program Files\OpenSSH\bin;C:\Users\IEUser\AppData\Local\Microsoft\WindowsApps;
```
4. You will see python is at a higher precedence

## Context

This causes problems when installing other python programs, such as Impacket, these scripts are placed inside of the `C:\Python37\Scripts\` directory, so when you type `ping` for example, it resolves to `C:\Python37\Scripts\ping.py` and not `C:\Windows\System32\ping.exe` as one might expect.
## Your Environment

* Package Version used: current version
* Operating System and version: Windows 7 SP1 and Windows 10
* Chocolatey version: current version
* Install/uninstall gist:

**Comment by AdmiringWorm** [comment]
Unfortunately, this isn't exactly package related.

For the python3 package, the additions to PATH is done by the installer (Not the package), and would need to be reported upstream te the developers of python.

For the python2 package, we add the directories to the PATH by using a helper function provided by the choco program. This helper do not provide any option to select where in the PATH the directories gets added.
This would need to be reported upstream to the devs here: https://github.com/chocolatey/choco/issues (not sure if it should be considered a bug or an enhancement request though).

Closing this issue, as what needs to be fixed is located elsewhere.
