### ISSUE TITLE
PDFXChangeViewer upgrade caused reboot

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/chocolatey-coreteampackages#126]
The installer for PDFXChangeViewer needs to include the `/NORESTART` argument.

I just ran an upgrade and the installer caused my box to spontaneously reboot without any user warnings (just glad I didn't lose anything important!)

**Comment by gep13** [comment]
Thanks for letting us know about this.  I have added this flag to the silent arguments for this package.

**Comment by ferventcoder** [comment]
:+1:
