### ISSUE TITLE
(julia) package shows extraction window when installing

### ISSUE THREAD

**Issue by musm** [chocolatey/chocolatey-coreteampackages#1266]
https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/julia

this window should be hidden

**Comment by musm** [comment]
the fix is simple first run `7z x` on the installer then run `julia-installer.exe`

**Comment by musm** [comment]
I think there's also an issue that the uninstaller does not remove it from the control panel

**Comment by AdmiringWorm** [comment]
> this window should be hidden

What window? Do you have a screenshot of it (*I'm currently not in windows, so I can not check it out myself*).

> the fix is simple first run 7z x on the installer then run julia-installer.exe

That would be more appropriate if it was a portable package, if there is a window, we'll most likely need to use autohotkey to close it (after all, we still want the program to be registered as installed).

> I think there's also an issue that the uninstaller does not remove it from the control panel

That would be an issue for the developers of Julia, and nothing to be handled in the package itself.

**Comment by musm** [comment]
![image](https://user-images.githubusercontent.com/4319522/56462773-e7665b80-6396-11e9-92a6-48226e964f24.png)

This is the window that shows up

**Comment by musm** [comment]
Basically the  NSIS installer is actually  archived with 7z before shipped. 

Thus we need to first run a silent 7z extraction before running the installer to suppress the window. 
Or if possible run the installer in  a new process with the window hidden.

**Comment by AdmiringWorm** [comment]
Do the window close eventually and continue the installation, or does it hang there?

If it closes and the installation continues, then there isn't anything wrong.

Packages doesn't necessarily need to be silent, they need to be unattended.

**Comment by musm** [comment]
It closes  and then the installation continues.

> Packages doesn't necessarily need to be silent, they need to be unattended.

Ok, but can we still fix the issue so that it is silent? It's pretty annoying to see this pop up. Plus the fix should be straightforward (outlined above)

**Comment by AdmiringWorm** [comment]
As long as it is unattended, then no, It will not be *fixed* as there is nothing to be fixed from the package perspective.

**Comment by AdmiringWorm** [comment]
Packages are meant to be simple wrappers around existing installers, and not include unnecessary logic (which IMO this change would be).

**Comment by rjt** [comment]
As long as the launch of GUI like window still works when there is no GUI
such as while remoted-in at the command line only using Enter-PSSession or
psexec.exe.

**Comment by musm** [comment]
Ok that makes sense and in this case there is no bug.

At the same time I do wish there was some prioritization to make the installers fully silent. It would make the user experience far more smooth. 

I suppose then PRs to do so would not be accepted?

**Comment by majkinetor** [comment]
> I suppose then PRs to do so would not be accepted?

We can accept anything that is better :)
