### ISSUE TITLE
Add missing owners element in nuspec

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#135]
Lots of packages in this repo are missing the `<owners>` element in the nuspec.  As a minimum, all nuspecs in this repo should have `<owners>chocolatey</owners>` and in some cases others, as some packages are maintained by more than one person.  Add the owners element to all nuspecs with chocolatey as the main entry.

**Comment by gep13** [comment]
This was completed using:

```powershell
Get-ChildItem C:\github\Organisations\chocolatey\chocolatey-coreteampackages -Recurse -Include *.nuspec | 
    ForEach-Object { 
        if(-not(Select-String -InputObject $_ -Pattern "<owners>")){
            Write-Host "Found $_"; 
            $text = Get-Content -raw $_ -Encoding UTF8; 
            $new = $text -replace "([ ]*)(<title>[^`r`n]+)","`$1`$2`r`n`$1<owners>chocolatey</owners>";
            [io.file]::writealltext($_,$new);
        }
    }
```

Big thanks to @dtgm for his help to create script

**Comment by ferventcoder** [comment]
That's money right there. I may have to use something like that for adding the packageSourceUrl to all of my packages.

**Comment by dtgm** [comment]
@gep13 you're welcome, although first I was like, "oh no" when I saw you changed `Get-ChildItem *\*.nuspec` to `Get-ChildItem C:\github\Organisations\chocolatey\chocolatey-coreteampackages -Recurse -Include *.nuspec` ! But then I saw this repo does not upload the pkgs generated by chocopkgup. 

fyi, the powershell script I wrote above I converted from:
```
for i in $(grep -L '<owners>' [a-z0-9]*/*.nuspec); do
  sed -e '/<\/title>/i\
    <owners>chocolatey</owners>' $i
done
```

Do you see why I prefer grep/sed ;)

@ferventcoder I did that in commit for https://github.com/dtgm/chocolatey-packages/issues/18.
```
for i in [a-z0-9]*/*.nuspec; do
  echo $i
  sed -e '/<\/projectUrl>/i\
    <packageSourceUrl>https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/{{PackageName}}/{{PackageVersion}}</packageSourceUrl>' $i
done
```

**Comment by dtgm** [comment]
`sed -e` will only output to console (for review)

`sed -i -e` will make the change inplace

**Comment by dtgm** [comment]
@ferventcoder if some of the nuspecs may already have packageSourceUrl

```
for i in $(grep -L '<packageSourceUrl>' [a-z0-9]*/*.nuspec); do
  echo $i
  sed -e '/<\/projectUrl>/i\
    <packageSourceUrl>https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/{{PackageName}}/{{PackageVersion}}</packageSourceUrl>' $i
done
```

**Comment by gep13** [comment]
>@dtgm said...
But then I saw this repo does not upload the pkgs generated by chocopkgup.

What exactly did you mean by this?  There is a ketarin instance associated with this repo.

**Comment by dtgm** [comment]
@gep13 I mean the output files ketarin produces to build the nupkg...these files https://github.com/ferventcoder/chocolatey-packages/tree/master/automatic/_output

**Comment by gep13** [comment]
@dtgm ah, I see what you mean :+1:
