### ISSUE TITLE
Why is tsremux unlisted

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#142]
https://chocolatey.org/packages/tsremux

@TomOne do you know why this is unlisted?

**Comment by majkinetor** [comment]
Closing this one as there is no answer for a long time.

**Comment by gep13** [comment]
@majkinetor in which case, I will remove the chocolatey user as a maintainer of this package as well then.

**Comment by majkinetor** [comment]
Definitelly.
