### ISSUE TITLE
Fix missing licenseUrls

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#146]
- [x] activepresenter\activepresenter.nuspec
- [x]  absolute-uninstaller\absolute-uninstaller.nuspec
- [x]  chromium\chromium.nuspec
- [ ]  feeddemon\feeddemon.nuspec
- [x]  h264tscutter\h264tscutter.nuspec
- [x]  haali-media-splitter\haali-media-splitter.nuspec
- [ ]  kingsoft-office-free\kingsoft-office-free.nuspec
- [x] lockhunter\lochunter.nuspec
- [x]  nlite\nlite.nuspec
- [ ]  no-ip-duc\no-ip-duc.nuspec
- [x]  python\python.nuspec
- [x]  python-x86_32\python-x86_32.nuspec
- [x]  python2\python2.nuspec
- [x]  python2-x86_32\python2-x86_32.nuspec
- [x]  python3\python3.nuspec
- [x]  python3-x86_32\python3-x86_32.nuspec
- [x]  rukerneltool\rukerneltool.nuspec
- [x]  speccy\speccy.nuspec
- [x] tuniac\tuniac.nuspec
- [x]  universal-extractor\universal-extractor.nuspec
- [x]  rdcman\rdcman.nuspec
- [x]  truecrypt-langfiles\truecrypt-langfiles.nuspec
- [x]  vcredist2015\vcredist2015.nuspec
- [ ] vscode-ember-frost\vscode-ember-frost.nuspec

**Comment by gep13** [comment]
These were found using:

```powershell
Get-ChildItem C:\github\Organisations\chocolatey\chocolatey-coreteampackages -Recurse -Include *.nuspec | 
    ForEach-Object { 
        if(-not(Select-String -InputObject $_ -Pattern "<licenseurl>")){
            Write-Host "Found $_"; 
        }
    }
```

**Comment by majkinetor** [comment]
Since this is almost done, I will close this in a month or two if there is no further work on remaining 2 packages.

**Comment by AdmiringWorm** [comment]
@majkinetor it seems like several of the packages missing licenseUrl was incorrectly checked and a few was missing.
As such I don't believe this should be pending closure just yet, it's good to have a reference of which packages is missing some recommended metadata.

**Comment by majkinetor** [comment]
Some are unlisted and hence no longer apply, restoring those.

**Comment by majkinetor** [comment]
Lockhunter is checked now since it doesn't actually provide any license.
