### ISSUE TITLE
RDCMan 2.2

### ISSUE THREAD

**Issue by jberezanski** [chocolatey/chocolatey-coreteampackages#149]
Microsoft has removed the download for RDCMan version 2.2. Although there is a later version available (2.7), it introduces a few annoying usability regressions (regarding drive mapping and fullscreen mode), which is why we're still using 2.2 at my company.

I'd like to keep the 2.2 package working. Would it be okay to host the installation MSI in this repo? (It is digitally signed by Microsoft, so guaranteed genuine.)
If you agree, I'll prepare a PR.

**Comment by ferventcoder** [comment]
Depends on the distribution rights

**Comment by gep13** [comment]
@jberezanski did you have a chance to look into the distribution rights on this msi?  I have not yet had a chance to look into it.  If you can direct me to somewhere it says that it is "ok" to do it, I will happily accept a PR to keep this version alive.

**Comment by jberezanski** [comment]
Nope, sorry, did not have the time to do that yet. I'll try during the weekend.

**Comment by jberezanski** [comment]
The [license shown by the installer](https://gist.github.com/jberezanski/d50e5bf9ce0e1f25aea4#file-rdcman-2-2-license-txt) specifies the following:

    2. Scope of License. (...) You may not
    (...)
    ·	publish the software for others to copy;

One could perhaps argue that the above refers to the actual RDCMan program binaries, not the installation package, but I guess better safe than sorry and we should not host the MSI ourselves.

However, I found the [original download page](https://web.archive.org/web/20150429104226/http://www.microsoft.com/en-us/download/details.aspx?id=21101) and [MSI](https://web.archive.org/web/20150706210153/http://download.microsoft.com/download/5/2/8/5282718D-87FE-4A4F-9226-789ACF368DB1/RDCMan.msi) cached on Archive.org. Would this be acceptable?

**Comment by gep13** [comment]
I am going to have to defer to @ferventcoder on that on, sorry.

**Comment by ferventcoder** [comment]
Software applies to the installer as well. Unfortunately pulling it from archive.org is also not going to be acceptable. However, one is free to do whatever you want internally and or on your own myget feed. You are not subject to the same distribution issues when you are doing things internally.

**Comment by ferventcoder** [comment]
I updated the above.

**Comment by jberezanski** [comment]
Sure, I'll use an internal server for my needs. Shame about the public package, though.

**Comment by ferventcoder** [comment]
Yes, but our hands are tied for the public site.
