### ISSUE TITLE
Cygwin default mirror change needed?

### ISSUE THREAD

**Issue by paulruiz** [chocolatey/chocolatey-coreteampackages#150]
installing cygwin with the package configured mirror fails at the same spot from multiple hosts and multiple locations (aws & corp net in Seattle). Relevant part of the error:

"mbox note: Unable to get http://mirrors.kernel.org/sourceware/cygwin/x86_64/setup.ini.sig from http://mirrors.kernel.org/sourceware/cygwin/"

The following command, changing the mirror used, works everywhere.

cinst -y cygwin -o -ia ' --quiet-mode -s http://mirrors.xmission.com/cygwin/ --packages default --root C:\ProgramData\chocolatey\lib\Cygwin\tools\cygwin --local-package-dir C:\ProgramData\chocolatey\lib\Cygwin\tools\cygwin\packages'

Does the default mirror used in the package need to be changed?

**Comment by Link-Satonaka** [comment]
I would bet it was just a momentary outage, these happen to any mirror.

Kernel.org is a pretty big deal- it's a widely known and trusted domain, and hosts packages for many distros, not just cygwin. It's a good default mirror for both security and reliability.
