### ISSUE TITLE
(nLite) Failing verifier

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#153]
https://chocolatey.org/packages/nlite

https://gist.github.com/choco-bot/bf2a2738b6e7ced72ef7

**Comment by majkinetor** [comment]
Should be unlisted (see [priorities](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Priorities-for-new-and-existing-packages)).

**Comment by AdmiringWorm** [comment]
package is unlisted.
