### ISSUE TITLE
(TrueCrypt-langiles) Failing verifier

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#154]
https://chocolatey.org/packages/truecrypt-langfiles

https://gist.github.com/choco-bot/c0c9be95acdfb0d22c6f

**Comment by majkinetor** [comment]
I would deprecate this, TrueCrypt does not develop anymore anyway.

**Comment by gep13** [comment]
Sounds like a plan to me.

**Comment by ferventcoder** [comment]
I even received an email recently about this recently:

> Hi Rob, 

> I noticed you've shared TrueCrypt on this page https://chocolatey.org/packages/truecrypt-langfiles/7.1.1, as you may be aware, development of TrueCrypt was discontinued back in 2014 and has subsequently not been maintained. A number of security flaws have been uncovered and as a result we are reaching out to people to highlight a list of alternatives.

> Here's the list (along with further details about TrueCrypt no longer being maintained) - https://www.comparitech.com/blog/information-security/truecrypt-is-discoutinued-try-these-free-alternatives/, when you update your page it could be a useful resource to point your visitors to.

> Please let me know if you have any questions.
