### ISSUE TITLE
Fix rejected UltraDefrag package

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#159]
https://chocolatey.org/packages/ultradefrag/7.0.0

**Comment by schtobia** [comment]
Ultradefrag 7.0.1 has been [released](https://sourceforge.net/p/ultradefrag/news/2016/03/ultradefrag-701-has-been-released/).

**Comment by gep13** [comment]
@majkinetor why did you close this one?

**Comment by majkinetor** [comment]
I confused it with defragller. Reopning.
