### ISSUE TITLE
(patch-my-pc) Fix rejected package

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#164]
https://chocolatey.org/packages/patch-my-pc/3.0.3.2

**Comment by majkinetor** [comment]
Not sure about this one. What do you think @gep13 ?

**Comment by majkinetor** [comment]
I think it should be unlisted too. Scanned the site, 

- most of the stuff is available via chocolatey anyway.
- very low number of choco users.

Simply doesn't deserve attention.
