### ISSUE TITLE
Fix rejected easy.install package

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#166]
https://chocolatey.org/packages/easy.install

**Comment by majkinetor** [comment]
So who keeps the source of this package ? Its not here. 

We should either remove choco user from maintainers or move it here.

The package fails btw as it doesn't have dependency on python.,

@gep13  @ferventcoder

**Comment by gep13** [comment]
@majkinetor the package source is here:

https://github.com/ferventcoder/chocolatey-packages/tree/master/manual/easy.install

**Comment by gep13** [comment]
Likely I added this issue when I saw the issue coming through via email, but didn't check if it was actually in this repo or not.

**Comment by majkinetor** [comment]
I will close this, @ferventcoder should fix it in its own repo.
