### ISSUE TITLE
Use HTTPS for Fiddler4

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#170]
@ericlaw1979 suggested this - https://twitter.com/ericlaw/status/701784805214519296. I also think we should use checksum as well. :)

**Comment by ferventcoder** [comment]
Sorry, @ericlaw1979

**Comment by gep13** [comment]
@ferventcoder am I missing something?  Are the checksum's published somewhere, that I can scrape into the automatic package?

**Comment by gep13** [comment]
@ferventcoder did you create another issue for the checksum?

**Comment by ferventcoder** [comment]
I did not.

**Comment by gep13** [comment]
https://github.com/chocolatey/chocolatey-coreteampackages/issues/174
