### ISSUE TITLE
aptana-studio is failing verifier

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#179]
https://chocolatey.org/packages/aptana-studio/3.6.1

**Comment by majkinetor** [comment]
Should get deprecated

**Comment by AdmiringWorm** [comment]
@majkinetor no it shouldn't there is still work going on in their github repository:
https://github.com/aptana/studio3

**Comment by AdmiringWorm** [comment]
I'm also almost finished converting it to AU, just got some metadata left.
