### ISSUE TITLE
Python is failing verifer

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#182]
https://chocolatey.org/packages/python-x86_32/3.5.1

**Comment by gep13** [comment]
https://chocolatey.org/packages/python3-x86_32/3.5.1

**Comment by dragon788** [comment]
@gep13 This appears to have passed through the verifier at some point since it eventually made it to the site?

**Comment by gep13** [comment]
@dragon788 yes, but there are still some ongoing issues with all the python packages, that I need to try to find some time to look into. :-(

**Comment by dragon788** [comment]
@gep13 Let me know if there is a process outlined (documentation) for testing the applications/verifier locally and I'd be happy to help if I can. I've been doing a lot with Python the last week or so and dove pretty deep on it last year on Windows, so I may be able to help diagnose root causes and fixes.

**Comment by gep13** [comment]
@dragon788 sweet! I think what you are looking for is this:

https://github.com/chocolatey/chocolatey-test-environment

Let me know if you have any questions about getting it set up.
