### ISSUE TITLE
partitionwizard is failing verifier

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#183]
https://chocolatey.org/packages/partitionwizard/9.1.0

**Comment by majkinetor** [comment]
Not from this repository

**Comment by gep13** [comment]
Can you leave this one, and others open, and assign to me, so that I can remove the chocolatey user from the package?  Thanks!

**Comment by gep13** [comment]
Actually, the choco user isn't on that package 😄

**Comment by majkinetor** [comment]
OK, will do that in advance if it happens again
