### ISSUE TITLE
choco list: Error 404 server not found

### ISSUE THREAD

**Issue by sparkvilla** [chocolatey/chocolatey-coreteampackages#188]
Hi,
I have set up a test repository: https://github.com/sparkvilla/c_rep/  with few chocolatey packages that I downloaded and rebuilt with chocolatey. I added my new source by typing:

`choco source add -n=c_rep -s=https://github.com/sparkvilla/c_rep/`

I the disable the chocolatey default repository so that the new one is the only one I pull the packages from. I then tried to list the packages in the new repository so I type:

`choco list -s= https://github.com/sparkvilla/c_rep/`

But I get:

The remote server returned an error: (404) Not found

Somebody knows what am I doing wrong? thank you

**Comment by gep13** [comment]
@sparkvilla have a look at `choco list -h`

and then, given that you have disabled the other source, you should be able to simply do `choco list`

**Comment by gep13** [comment]
@sparkvilla also, the url you are using is **not** a valid nuget feed, it is a GitHub repo.  These two things are not the same.

**Comment by sparkvilla** [comment]
I guess that is the problem. Does it mean I cannot use the Github repo to do the test? what else could I use?

**Comment by gep13** [comment]
@sparkvilla you would need to do one of the suggestions here:

https://github.com/chocolatey/choco/wiki/How-To-Host-Feed

The quickest and easiest one would likely be to set up a MyGet account.

**Comment by sparkvilla** [comment]
Thank you I'll have a look.
