### ISSUE TITLE
Added BCUninstaller

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey-coreteampackages#192]
@gep13 can you add this to the machine?

https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/bulk-crap-uninstaller

**Comment by gep13** [comment]
@Redsandro yip, I will try to do this this weekend.

**Comment by gep13** [comment]
@Redsandro done :smile_cat:

**Comment by Redsandro** [comment]
@gep13 you rule :+1:
