### ISSUE TITLE
Chromium - no new updates

### ISSUE THREAD

**Issue by guillaumecle** [chocolatey/chocolatey-coreteampackages#196]
There are no more new updates available for the Chromium package after March 18, while there were  at least once per day before.

**Comment by guillaumecle** [comment]
Can perhaps come from the release repo: http://chromium.woolyss.com/api/?os=windows&amp;bit=64&amp;out=json is stuck on 51.0.2683.0 since that day.

**Comment by guillaumecle** [comment]
Ho interesting, from http://chromium.woolyss.com/ :

> Important news
The Chromium team has removed few LKGR builders. (sources: 407399 and chromium-dev)
Consequently, since 18 March 2016, the Continuous repository and official site (LKGR) are not updated.

**Comment by gep13** [comment]
@guillaumecle oh, interesting indeed. So looks like the chocolatey package has correctly not updated.  Can this issue be closed?

**Comment by guillaumecle** [comment]
Would chocolatey want to find another source for Chromium releases?

**Comment by gep13** [comment]
If you can suggest another one, I would be happy to look into it.

**Comment by guillaumecle** [comment]
I'm not sure about that, http://chromium.woolyss.com/ has other builds, like the "nik" ones, but I don't know if they are often updated and adapted to chocolatey.

**Comment by woolyss** [comment]
Hello!
I am Jerry, admin of chromium.woolyss.com
I sent an email to Thomas Walter (choco admin) about this issue but he does not give me an answer.

The Chromium developers work currently on LKGR builders and Libfuzzer infrastructure...
https://bugs.chromium.org/p/chromium/issues/detail?id=539572
...but I do not know when they will provide binaries (into the Continuous repo), as before.

@gep13: you can still use the OFFICIAL Snapshot repository... but I do not have an API ready for you :/

@guillaumecle: The following builds are NOT OFFICIAL: The Chromium STABLE version are updated when the Google Chrome STABLE version is released. And about the DEV builds of nik, our devoted developer, he share a Chromium release every 2 or 3 days.

**Comment by gep13** [comment]
@guillaumecle @woolyss I am fairly sure that this has now been taken care of, thanks to the work that @RedBaron2 has done on this package.  If not, then please let me know.
