### ISSUE TITLE
Cygwin - Corrupt Install

### ISSUE THREAD

**Issue by wjk** [chocolatey/chocolatey-coreteampackages#197]
I just finished installing Cygwin using `cyg-get` and Chocolatey, only to find that for some strange reason none of the symlink files in Cygwin's `/bin` folder were properly marked as SYSTEM (which is required to get Cygwin to treat them as symlinks and not as regular files). I had to go into that folder and `attrib +s` each file one by one before they would function correctly.

**Comment by cwiggs** [comment]
I believe this is a duplicate issue of [this issue](https://github.com/chocolatey/chocolatey-coreteampackages/issues/101)
