### ISSUE TITLE
Who is core team packages? And where are the docs? This needs a Wiki.

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey-coreteampackages#20]
I have these packages that I no longer use, e.g. `Ext2Explore`, or partition tools, which have apparently too many users who keep bugging me for updates.

So I thought, nice packages for Core Team packages. But the process is vague. All the repo says is this:

> These packages are managed by the chocolatey core team. To get a package added here, the official Chocolatey Account has to have push access to the package on chocolatey.org.

So I added the `chocolatey` user, but basically the feedback I get is:

> This is not a dumping ground for offloading packages that folks are no longer interested in maintaining.

However, for my package `KeePassX` I was approached by someone advising me to put it on core team packages because I don't update fast enough.

So how does this work? Is the process of packages that get or would get accepted arbitrary? Subjective to the people that are "in" the core team?

This needs a wiki with clear instructions on how to get a package nominated, accepted, added, how to transfer the package, how to transfer the package source code, if and how to request help when your package is not an autopackage, etc.

For now, for some of the most popular packages I have found some random other users who were willing to host the autopackage. But in the light of trustworthiness and the future plan of trusted certificates for package maintainers, the core team would me a safer bet.
 
Also, who are the core team members?

* `TomOne`
* `gep13`
* `ferventcoder`

**Comment by Redsandro** [comment]
I'm not particularly interested in (icons of) old versions, but since the team urges me to go the extra mini-mile, I feel like adding my second two cents:

I'm not sure depending on GitHub's CDN for old icon versions is a sturdy solution. If we lose GitHub or their CDN, or if we want to cater to countries where GitHub is blocked off and on, like Russia, it will be a tedious task to rebuild the history of icons for each package, and it would require manual labor to make these icons available on some other CDN. It's better to have full the icon history available in a file (version) tree in HEAD. This would make the icon base more sturdy and portable.

**Comment by Redsandro** [comment]
I would like to know who has access to the ketarin machine.
What needs to be done from a pullrequest to having the package aumatically updated through chocolatey?

We need someone with that power to take a few moments to look over the pending PR's and merge/fix/add them.

* [Tixati](https://github.com/chocolatey/chocolatey-coreteampackages/pull/90) (15 minutes ago)
* [AEMEI partition wizard](https://github.com/chocolatey/chocolatey-coreteampackages/pull/83) (2 months ago)
* [Resource Hacker](https://github.com/chocolatey/chocolatey-coreteampackages/pull/81) (3 months ago)
* [Absolute Uninstaller](https://github.com/chocolatey/chocolatey-coreteampackages/pull/80) (4 months ago)
* [RenameMaster](https://github.com/chocolatey/chocolatey-coreteampackages/pull/76) (5 months ago)
* [vcredist2015](https://github.com/chocolatey/chocolatey-coreteampackages/pull/75) (5 months ago)
* [UltraDefrag](https://github.com/chocolatey/chocolatey-coreteampackages/pull/58) (7 months ago)
* [patch-my-pc](https://github.com/chocolatey/chocolatey-coreteampackages/pull/47) (8 months ago)

Also see [this discussion](https://github.com/chocolatey/chocolatey-coreteampackages/pull/58#issuecomment-128347050). This is becoming a problem because no one (including new users) is motivated to make fixes anymore if they are never merged.

**Comment by gep13** [comment]
Currently, me, Rob and Tom have access to this machine, but we can certainly have a chat about opening this up to a wider group.

@ferventcoder do you have a script for auto importing xml files into ketatin on each execution, so as to ensure most up to date configuration after the pull?

Sent from my Windows Phone
________________________________

**Comment by Redsandro** [comment]
@gep13 can you tell me the _exact code_ the ketarin machine uses for all the batch jobs?
And where do you put this global code in stead of per-package code?

**Comment by gep13** [comment]
@Redsandro sorry, I am not clear on what you are asking for.  Are you talking about the scheduled task that is running on the ketarin machine to execute ketarin every hour?

**Comment by Redsandro** [comment]
Yes - I think.

I think it was you - but don't be angry if I'm mistaken - who told me that in this repository, ketarin settings for packages need no _execution commands_. There is a one size fits all command. It's probably documented somewhere, but not in this repo.

I want that command so I can tell, if it works in a VM, it will work on the ketarin machine.

**Comment by gep13** [comment]
Ah, I see what you are getting at.  :smile_cat: 

Yes, on the Ketarin instance, there is a global execute command that runs for all packages that are contained within the Ketarin instance.  

This is the command:

```
chocopkgup /p "{appname}" /v "{version}" /u "{preupdate-url}" /u64 "{url64}" /pp "{file}"
```

![image](https://cloud.githubusercontent.com/assets/1271146/10574152/17aeb92c-764c-11e5-99a2-ecb3b3fc3040.png)

**Comment by Redsandro** [comment]
@gep13 Really? It uses the preupdate-url? That's always the one in the _URL_ field in the _download source_, right? So if we need to regex, we need to regex a variable and put that variable in the URL field?

**Comment by gep13** [comment]
And every hour, we run this command:

```
C:\Windows\System32\cmd.exe /c %ChocolateyBinRoot%\ketarinupdate.cmd
```

which contains:

```
@echo off

For /f "tokens=2-4 delims=/ " %%a in ('date /t') do (set mydate=%%c%%a%%b)
For /f "tokens=1-2 delims=/:" %%a in ("%TIME%") do (set mytime=%%a%%b)

echo Updating the github repo first
pushd C:\github\chocolatey-coreteampackages\automatic
call git add .
::call git commit -m "updates prior to automatic run for %mydate%_%mytime%"
call git reset --hard HEAD
call git fetch && git rebase origin/master
::call git push origin master
popd

echo Calling ketarin now the the repo has been updated
call "Ketarin.exe" /silent /log=C:\ProgramData\chocolateypackageupdater\ketarin.%mydate%_%mytime%.log


```

**Comment by gep13** [comment]
>@Redsandro said...
Really? It uses the preupdate-url? That's always the one in the URL field in the download source, right? So if we need to regex, we need to regex a variable and put that variable in the URL field?

Sorry, I am not exactly clear on what you are referring to.  Can you elaborate?  This might not be the optimal way of doing this.  Perhaps @TomOne or @dtgm might be able to help with this.

This is the way that this Ketarin machine has been set up for almost two years.

**Comment by Redsandro** [comment]
@gep13 thank you for pointing the commands out. Now I get what's going on. :smile: 

As for the _"preupdate-url"_, I mean that the _url_ is actually not a value called `url` (like url64 is a value called `url64`, but rather the contents of the download url field in the ketarin package settings. This is a bit misleasing and I never understood this until just now.

**Comment by gep13** [comment]
>@Redsandro said...
This is a bit misleasing and I never understood this until just now.

Ok, cool, sounds like everything is in order then, right?

**Comment by Redsandro** [comment]
Yes, all is clear!

**Comment by Redsandro** [comment]
I know who have access to the ketarin machine now. I think this issue can be closed.

**Comment by ferventcoder** [comment]
I do have a script that auto updates ketarin by importing all ketarin scripts in a particular directory. So I only have to merge.

**Comment by gep13** [comment]
@ferventcoder do you have a link to that script, so that we can put that on the Ketarin machine? Thanks!

**Comment by Redsandro** [comment]
Should implement some sanity checking.

How are (previously working) broken packages detected now?

Does ketarin do something like info>stdout error>stderr? It would be nice to pipe the output log of _only the errors_ to some website where we can see packages that need fixing.

**Comment by ferventcoder** [comment]
> Does ketarin do something like info>stdout error>stderr? It would be nice to pipe the output log of only the errors to some website where we can see packages that need fixing.

Not as far as I'm aware.

**Comment by ferventcoder** [comment]
@gep13 the script is at https://github.com/ferventcoder/chocolatey-packages. I'm starting you there so you can see that all of the ketarin.xml files have been extracted to a singular folder, like @dtgm has done. Then inside of there is a files directory that contains this gem - https://github.com/ferventcoder/chocolatey-packages/blob/master/ketarin/files/ketarinupdate.cmd

The version of ketarin needs to be the latest or it will stay open after import.

**Comment by gep13** [comment]
@ferventcoder perfect thanks, I will take a look, and let you know if I run into any problems. Cheers!

**Comment by ferventcoder** [comment]
@gep13 the really nice thing about this script is that I can set it on a new machine and it will import all of the jobs into ketarin.

**Comment by gep13** [comment]
@ferventcoder agreed.  That has always been my concern about the "portability" of the current ketarin machine we are using.

**Comment by Redsandro** [comment]
@gep13 We don't even have to change the structure. 

iirc you can look one level deep in subfolders using `FOR /D %%F IN`, or recursively through all folders (probably some overhead because of all the tools directories) using `FOR /R`.

**Comment by gep13** [comment]
@Redsandro although we "might" be able to do something, I think there is something to be said for consistency.  If this is what both @ferventcoder and @dtgm have opted for, I think we should follow their lead.

**Comment by Redsandro** [comment]
@gep13 while I agree consistency is an important thing, I also like to point out that things like Javascript, ES, HTML5 and the likes wouldn't exist if we all just went for consistency rather than improvement.

The best approach to any kind of package - for clarity, portability and maintainability's sake - is always to have it as self-contained as possible.

For that reason, the fact that we chose to separate icons from packages in their own `icons` directory is something of a bad decision in that regard.

If we now introduce a third location we need to take into account for package maintenance, we're just going against common sense.

Just my two cents. I will play along either way.

**Comment by ferventcoder** [comment]
More of keeping the ketarin.xml file away from the autopackage so it doesn't get sucked up by the generating tool. But that can be addressed in other ways.

**Comment by ferventcoder** [comment]
And for the sake of argument that the ketarin bit isn't really part of the package - which is a fallacy, it is part of what builds the package.

**Comment by Redsandro** [comment]
`.gitignore`, `Gruntfile.js`, `thumbs.db` GMTA :wink:
