### ISSUE TITLE
Can't install any old versions of Cygwin.

### ISSUE THREAD

**Issue by cwiggs** [chocolatey/chocolatey-coreteampackages#201]
I'm trying to install Cygwin 2.3.1 in Windows 2008 and am having issues.  I'm trying to install an old version since 2.5.0 seems to have problems with Cyg-get.  Attempting to install with debug mode on shows that it is having trouble downloading https://mirrors.kernel.org/sourceware/cygwin/x86_64/setup.xz.sig and maybe a few other files in https://mirrors.kernel.org/sourceware/cygwin/x86_64/ however I'm able to download the file in a browser fine.

It seems like anytime I use the --version flag I get this errror.

Does not work:
`choco install cygwin --version=2.5.0 -y -d`
`choco install cygwin --version=2.4.1 -y -d`
`choco install cygwin --version=2.4.0 -y -d`
`choco install cygwin --version=2.3.1 -y -d`
`choco install cygwin -version 2.3.1 -y -d`

Works:
`choco install cygwin -y -d`

 Attached is a snippet of the chocolatey.log file.

[choco-2.3.1.txt](https://github.com/chocolatey/chocolatey-coreteampackages/files/228275/choco-2.3.1.txt)

**Comment by cwiggs** [comment]
The same thing happens with I try to install cygwin 2.5.0 using --version, if i install without --version it works fine.

Does not work:
`choco install cygwin --version=2.5.0 -y -d`

Works:
`choco install cygwin -y -d`

**Comment by majkinetor** [comment]
Older versions of cygwin arent supported. Its added to the notes on package.
