### ISSUE TITLE
mp3tag

### ISSUE THREAD

**Issue by botmtl** [chocolatey/chocolatey-coreteampackages#202]
mp3tag auto package is messed up.  it's a ketarin package.  ketarin zonked somewhere along the line because you'll find this:
```powershell
[...]
$version = **'2.76'**
$url = 'http://download.mp3tag.de/mp3tag **v239** setup.exe'
```

I checked, and version seems like a ketarin-defined variable.

**Comment by TomOne** [comment]
@botmtl, thanks for this. The Website of mp3tag changed and broke the ketarin job. It’s fixed now: https://chocolatey.org/packages/mp3tag/2.77.0.20160428
