### ISSUE TITLE
(clover) Broken on Windows 7

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#203]
Reporting for @mullerp. See https://gitter.im/chocolatey/chocolatey.org?at=5720f86b0f156f102b415309 for details.

**Comment by mullermp** [comment]
https://dpaste.de/C1D5

relevant log --  install fails on windows 7 64 bit

**Comment by alexchandel** [comment]
The uninstall also fails on Windows 7 64 bit. Is there any fix for this? The uninstall prompt from the control panel is in Chinese, and doesn't appear to do anything.

**Comment by majkinetor** [comment]
I currently do not have Win7 x64 to test it, but install works inside Windows Server 2012 R2:

```
11 [ clear ]  16-11-01 21.35.14  C:\work\_chocolatey\chocolatey-coreteampackages\automatic\Clover
master~> Test-Package -Install

Package info
  Path:         C:\work\_chocolatey\chocolatey-coreteampackages\automatic\Clover\Clover.3.2.0.nupkg
  Name:         Clover
  Version:      3.2.0
  Vagrant:      c:\work\_chocolatey\chocolatey-test-environment

Testing package using vagrant
Removing existing vagrant packages
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ferventcoder/win2012r2-x64-nocm' is up to date...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
    default: Running: shell/TestPackages.ps1 as c:\tmp\vagrant-shell.ps1
==> default: ============================================================
==> default: TESTING FOLLOWING PACKAGES: Clover:3.2.0
==> default: ============================================================
==> default:
==> default: ------------------------------------------------------------
==> default: PACKAGE: Clover:3.2.0
==> default:
==> default: OPTIONS: c:\packages\Clover.3.2.0.xml
==> default:
==> default: Name                           Value
==> default: ----                           -----
==> default: Install                        True
==> default: Uninstall                      False
==> default: Parameters
==> default: ------------------------------------------------------------
==> default:
==> default: TESTING INSTALL FOR Clover:3.2.0
==> default: CMD: choco install -fy Clover --allow-downgrade --version 3.2.0 --source "'c:\packages;http://chocolatey.org/api/v2/'"
==> default: Chocolatey v0.10.3
==> default: Installing the following packages:
==> default:
==> default: Clover
==> default: By installing you accept licenses for the packages.
==> default: Clover v3.2.0 (forced)
==> default: clover package files install completed. Performing other installation steps.
==> default: File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
==> default: Hashes match.
==> default: Hashes match.
==> default: Installing clover...
==> default: clover has been installed.
==> default: Clover installed to 'C:\Program Files (x86)\Clover\3.2'
==> default: Clover registered as Clover
==> default:  The install of clover was successful.
==> default:
==> default:   Software installed as 'EXE', install location is likely default.
==> default:
==> default: Chocolatey installed 1/1 packages. 0 packages failed.
==> default:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
==> default: Exit code for Clover:3.2.0 was 0
```
Uninstall definitelly does nothing and that should be reported to vendor.

**Comment by majkinetor** [comment]
I do think however that it is enough to

# execute `unreg.bat` from clover install dir
# delete files

**Comment by AdmiringWorm** [comment]
@mullermp I know I'm a little late to the party, but I believe I found a bug in the dependency of the clover package (can't really verify since your link to the log has expired).

Could you please try updating the [chocolatey-core.extension](https://chocolatey.org/packages/chocolatey-core.extension/1.0.6) package and try installing the clover package again?

**Comment by AdmiringWorm** [comment]
Closing this as I believe this have been fixed.
Feel free to reopen if the issue still present.

**Comment by adamdev96** [comment]
Not working on my machine 
(Remote file doesn't exist)

**Comment by AdmiringWorm** [comment]
@adamdev96 see
https://github.com/chocolatey/chocolatey-coreteampackages/issues/1006
https://chocolatey.org/packages/clover#comment-3351575070

I've honestly stopped monitoring newer versions of that software, as it seems it will never even try getting rid of the included viruses/malwares detected on virustotal.org

**Comment by majkinetor** [comment]
I was monitoring a tool several versions. Maybe the viruses are false positive, there are few other tools that I know are virus free and still have lots of positives. It turns out its enough to have a single API call and you are flagged. 

Unless someone can provide a proof that specific version is virus free, we won't do anything here. I personally don't care as I don't use Explorer. But there are limits to how long we keep non-working packages and the package is bound to be totally removed from this repo soon.
