### ISSUE TITLE
(PartitionAssistantLite) Failing verifier

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#204]
https://chocolatey.org/packages/PartitionAssistantLite
https://gist.github.com/choco-bot/4f08bd345168a44485b5e6ba47cf760f

**Comment by majkinetor** [comment]
Should be unlisted (see [priorities](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Priorities-for-new-and-existing-packages)).
