### ISSUE TITLE
Palemoon 26.2.2 x64 fails to download

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-coreteampackages#209]
Pale Moon 26.2.2 package is very broken for x64. The Win32 download uses the Pale Moon mirror whereas the x64 version uses the FossHub site which doesn't appear to have the software.

The $url64 variable needs to be amended from 'http://www.fosshub.com/genLink/Pale-Moon/palemoon-26.2.2.win64.installer.exe' to 'http://relmirror.palemoon.org/release/palemoon-26.2.2.win64.installer.exe' (which matches the win32 version).

Will submit a PR if I can.

**Comment by TomOne** [comment]
Thanks for the report. It’s fixed in https://chocolatey.org/packages/palemoon/26.2.2.20160515.
