### ISSUE TITLE
Proposed: Chocolatey uninstall extension

### ISSUE THREAD

**Issue by dtgm** [chocolatey/chocolatey-coreteampackages#214]
https://github.com/chocolatey/chocolatey-coreteampackages/commit/f7fe281d114f1fbb4e7ab80069ae28e8d66cc776

Proposed  | .
--- | ---
package id | `chocolatey-uninstall.extension`
function | `Get-UninstallRegistryKey`

More functions could be included, but initially I am working at resolving issue https://github.com/chocolatey/choco/issues/739, originally logged at https://github.com/dtgm/chocolatey-packages/issues/92

Summarized again here: If a program writes binary data into a registry key, but is not using correct type, Get-ItemProperty fails. I have only encountered a few programs having this issue; the problem exists in >=netbeans-8.0 and other programs by netbeans org. Unfortunately, the presence of these programs will cause this routine used by choco to fail unless the problem registry key is removed.

To keep software from accidentally breaking choco uninstall scripts, the plan is `Get-UninstallRegistryKey` aims to replace a portion of the current chocolateyUninstall.ps1 template https://github.com/chocolatey/choco/blob/7ef16d6003dd3c689156af20d3ce329c85d1cd76/src/chocolatey/infrastructure.app/templates/ChocolateyUninstallTemplate.cs#L57-L63 and would be required to be used in all packages to prevent any package using the old method from breaking.

The solution within the `Get-UninstallRegistryKey` could be incorporated into my uninstall scripts and the template generated by `choco new`. But it seems like it would add too much code so it seems proper to include as an extension instead. Please advise on naming of function or package id since this solution would end up being present in 1,000+ packages.

**Comment by dtgm** [comment]
Related discussion about preferred naming of extensions and functions #128

**Comment by gep13** [comment]
@dtgm I think this would be a good addition, and would happily accept a PR for this :-)

In terms of naming, I think what you have suggested, i.e. `choco-uninstall.extension` makes sense.  To me, this says exactly what it does.  It is an extension, for chocolatey, that deals within uninstallation.  Within this extension, one or more helper methods can be created to help with the process of uninstallation.

**Comment by dtgm** [comment]
It's already up. Take a look. https://github.com/chocolatey/chocolatey-coreteampackages/commit/f7fe281d114f1fbb4e7ab80069ae28e8d66cc776

I named it `chocolatey-uninstall.extension` to follow your lead, but I see you haven't pushed your extension yet so we could change to using `choco-` like `choco-uninstall.extension` (less typing)

**Comment by gep13** [comment]
@dtgm yeah, I need to finish off that extension, got distracted with other stuff.  Can't actually remember where that is at.  Need to look at it again soon.

**Comment by dtgm** [comment]
https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/extensions/chocolatey-fosshub.extension

**Comment by gep13** [comment]
@dtgm Sorry, didn't mean physically where the files are, more, what I still need to do with it :-)

In terms of naming, I think chocolatey-uninstall.extension makes sense.

This would mean that we would have:

`chocolatey.extension`
`chocolatey-fosshub.extension`
`chocolatey-uninstall.extension`

So we would have some consistency.

**Comment by dtgm** [comment]
`chocolatey.extension` ? Are those built-in helpers?

**Comment by gep13** [comment]
That is the official extension that ships as part of the Professional license.  It brings in the features to chocolatey that you get once you buy a license.

**Comment by ferventcoder** [comment]
Left notes on the commit - the file name is too deep. It will work but it's way too redundant.

**Comment by dtgm** [comment]
Total affected packages needing to transition to using this extension is probably at least **728** as of 2016-04-23 (plus new packages added in last month)

At least **102** were using the template provided by `choco new`

**Comment by gep13** [comment]
I think we can go ahead and close this one.
