### ISSUE TITLE
(python311) version 3.11.2 is missing 

### ISSUE THREAD

**Issue by kai2nenobu** [chocolatey/chocolatey-coreteampackages#2141]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

3.11.2

### Download location

https://www.python.org/downloads/release/python-3112/

### Package Page

https://community.chocolatey.org/packages/python311

**Comment by kai2nenobu** [comment]
Curiously, the community repository has been updated to version 3.11.2 in [commit](https://github.com/chocolatey-community/chocolatey-packages/commit/ed38891d16a2619a0a360391a92eae1b837aff06), [tags](https://github.com/chocolatey-community/chocolatey-packages/releases/tag/python311-3.11.2) and [AppVeyor build](https://ci.appveyor.com/project/chocolateycommunity/chocolatey-packages/builds/46178606#L741), but that version does not exist on the package page.

![image](https://user-images.githubusercontent.com/810042/218458772-0727e788-e2ea-494a-8aa0-7202ce7d099f.png)

**Comment by DougTrajano** [comment]
Other Python versions are missing as well.

- 3.11.2
- 3.11.1
- 3.10.10
- 3.10.9

**Comment by DougTrajano** [comment]
> @DougTrajano I'm afraid you are seeing [the python3 package](https://community.chocolatey.org/packages/python3). `python3` package was separated into each minor version package in #1993.
> 
> You can find version 3.10.9 and 3.10.10 in [python310 package](https://community.chocolatey.org/packages/python310). You can also find version 3.11.1 in [python311 package](https://community.chocolatey.org/packages/python311) but not version 3.11.2.

gotcha, but why not add all of them in the same package?

**Comment by pauby** [comment]
If they are all in the same package then it causes issues if people want to just have Python 3.10.x versions (as an example). They woudl then have to pin to version 3.10.9 (as an example) and then when 3.10.10 comes out they would have to unpin, upgrade to that specific version, then pin agian. If they didn't pin they'd end up with the latest Python 3 version, for example 3.11.2. That's not what they want.

So if there are separate packages they can install `python310` and then get all the version of 3.10.x andf not worry about pinning or upgrading to specific versions. With `python310` you'll never get 3.11.x. If you want 3.11.x, you'd install the `python311` package.

This isn't done for every package but is ideal for things like Python.

Does that make sense?

**Comment by DougTrajano** [comment]
> If they are all in the same package then it causes issues if people want to just have Python 3.10.x versions (as an example). They woudl then have to pin to version 3.10.9 (as an example) and then when 3.10.10 comes out they would have to unpin, upgrade to that specific version, then pin agian. If they didn't pin they'd end up with the latest Python 3 version, for example 3.11.2. That's not what they want.
> 
> So if there are separate packages they can install `python310` and then get all the version of 3.10.x andf not worry about pinning or upgrading to specific versions. With `python310` you'll never get 3.11.x. If you want 3.11.x, you'd install the `python311` package.
> 
> This isn't done for every package but is ideal for things like Python.
> 
> Does that make sense?

Hum, I understood, make sense!

I appreciate your answer.

**Comment by isanych** [comment]
Looks like https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/python3-streams/python3-streams.nuspec is for python312 package only, there is no python311 package in that repo, so it is not updated

**Comment by isanych** [comment]
Maybe I don't know how to cook it properly, but I was not able to create working python311 package from master, but after removing all non 3.11 stuff - https://github.com/chocolatey-community/chocolatey-packages/compare/master...isanych:chocolatey-coreteampackages:python311 - I've created working 3.11.2 packages

**Comment by pauby** [comment]
The `python3` packages [supports  3.x versions](https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/python3-streams/update.ps1#L116).

**Comment by pauby** [comment]
@Jackenmen @AdmiringWorm Both of you have updated the [automatic update](https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/python3-streams/update.ps1) script in the past. Any suggestions, what is breaking here?

**Comment by Jackenmen** [comment]
In the related CI run, all packages were built and it seems they were all pushed as GitHub releases but not to Chocolatey:
https://ci.appveyor.com/project/chocolateycommunity/chocolatey-packages/builds/46178606

@pauby Does AU not push all nupkg files generated by a package with multiple streams if multiple streams have updates at the same time?

**Comment by pauby** [comment]
> In the related CI run, all packages were built and it seems they were all pushed as GitHub releases but not to Chocolatey:
https://ci.appveyor.com/project/chocolateycommunity/chocolatey-packages/builds/46178606

It only [pushed `python312` in that run[(https://ci.appveyor.com/project/chocolateycommunity/chocolatey-packages/builds/46178606#L582).

> @pauby Does AU not push all nupkg files generated by a package with multiple streams if multiple streams have updates at the same time? Could it have anything to with different streams using different package names?

@AdmiringWorm would be best to answer that - I'm unsure.  But you got me thinking. Python 3.10.10 and Python 3.11.2 were both released on the same day.

![image](https://user-images.githubusercontent.com/12760779/222922954-7ec6d6c4-a427-4b18-aa73-2f8cc4c16913.png)

And there was an error on the run of that [day](https://ci.appveyor.com/project/chocolateycommunity/chocolatey-packages/builds/46174718#L469).

**Comment by Jackenmen** [comment]
> It only [pushed `python312` in that run](https://ci.appveyor.com/project/chocolateycommunity/chocolatey-packages/builds/46178606#L582).

To chocolatey yes but [it did push *all* nupkg files as GitHub releases](https://ci.appveyor.com/project/chocolateycommunity/chocolatey-packages/builds/46178606#L736). So they were built and they are detected by the CI in a later step but it seems that for some reason AU did not detect or push them to Chocolatey
