### ISSUE TITLE
Push chocolatey-fosshub extension and update packages

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#215]
Any package that uses the Fosshub Utility function should be changed to use the Fosshub extension.

**Comment by dtgm** [comment]
Affected packages:

audacity
avidemux
datacrow
hwinfo.install
hwinfo.portable
IrfanView
irfanviewplugins
kitty.portable
lightalloy
mkvtoolnix
palemoon
smplayer

**Comment by gep13** [comment]
What a guy! :+1: 

I am away to get on a flight, but I will look to taking care of this on the flight :smile:

**Comment by dtgm** [comment]
Well aren't you going to have the most exciting flight ever! (List current as of 2016-04-23)

**Comment by gep13** [comment]
- [x] audacity
- [x] avidemux
- [ ] datacrow
- [ ] hwinfo.install
- [ ] hwinfo.portable
- [ ] IrfanView
- [ ] irfanviewplugins
- [ ] kitty.portable
- [x] lightalloy
- [x] mkvtoolnix
- [ ] palemoon
- [ ] smplayer

**Comment by gep13** [comment]
@dtgm It doesn't look like palemoon uses fosshub anymore, so I think it can come off the list.

**Comment by dtgm** [comment]
@gep13 Good to know, but that isn't a list I was maintaining. I just did a quick grep for packages containing "fosshub" in the install files. It looks like you removed those comments now though.

**Comment by dtgm** [comment]
@gep13 pushed https://chocolatey.org/packages/chocolatey-fosshub.extension

Related question, do you know of a way to add leading space in markdown? I tried 

```
`  `&lt;`dependency id="chocolatey-fosshub.extension" /`&gt;
```
and
`&nbsp;` isn't permissible ... wait, I wonder if `&amp;nbsp;` would work...

**Comment by dtgm** [comment]
^^^ Oh dang, that works.

**Comment by gep13** [comment]
Calling this one done in favour of this one: https://github.com/chocolatey/chocolatey-coreteampackages/issues/265
