### ISSUE TITLE
Classic Shell Package Outdated

### ISSUE THREAD

**Issue by wjk** [chocolatey/chocolatey-coreteampackages#218]
When I try to install the `classic-shell` package on my Windows 10 computer which I just upgraded to build 14342.1001, a popup appears telling me that "Classic Shell is not compatible with this version of Windows." Clicking the popup gives me [a "help" page](http://windows.microsoft.com/en-us/windows-10/incompatible-app-windows-10) that simply restates the error message.

Inspection in the `C:\Program Files\Classic Shell` directory reveals that the `ClassicShell.exe` file does not exist, but the support DLLs and other files in that directory do. Furthermore, no Start-menu shortcuts are created, and the Chocolatey auto uninstaller does not do anything (although there is an entry in Programs and Features, and it works as expected).

Checking the project website reveals that there is [an available update](http://www.classicshell.net/forum/viewtopic.php?f=4&t=6073) that fixes this problem. Could the package please be updated? Thanks!

**Comment by piotr-cz** [comment]
I'm not sure if this issue is related, but when executing `cup classic-shell`, I'm getting an error

```
Installing classic-shell...
 A n o t h e r   v e r s i o n   o f   t h i s   p r o d u c t   i s   a l r e a d y   i n s t a l l e d .     I n s t a l l a t i o n   o f   t h i s   v e r s i o n   c a n n o t   c o n t i n u e .     T o   c o n f i g u r e   o r   r e m o v e   t h e   e x i s t i n g   v e r s i o n   o f   t h i s   p r o d u c t ,   u s e   A d d / R e m o v e   P r o g r a m s   o n   t h e   C o n t r o l   P a n e l .
```

Hopefully the v4.2.7 will fix it

**Comment by bcurran3** [comment]
This looks to be a good download location:
https://fossies.org/windows/misc/ClassicShellSetup430.exe

**Comment by gep13** [comment]
@wjk @piotr-cz @bcurran3 I have just pushed an updated version of this package.  Let me know if this doesn't work.  Closing this issue for not.
