### ISSUE TITLE
(Chocolatey) Community repo API returns incosistent version info

### ISSUE THREAD

**Issue by o-l-a-v** [chocolatey/chocolatey-coreteampackages#2272]
### Chocolatey Version

2.2.0

### Chocolatey License

None

### Package Version

2.2.0 -> 2.2.2

### Current Behaviour

Yesterday, Chocolatey `choco` CLI returned inconsistent version info about the package `Chocolatey`. If searching with `--exact`, `choco` said latest version was 2.2.0. If searching without `--exact`, `choco` said latest version was 2.2.2.

From the logs it seems that the API request with `--exact` does not include `not IsPrerelease` in the filter, while not using `--exact` includes `not IsPrerelease`.

More info and screenshots from the issue I created in the choco cli repo yesterday:

* https://github.com/chocolatey/choco/issues/3297

Yesterday, following commands said latest version of package `Chocolatey` was 2.2.0:

* `choco outdated`
* `choco upgrade chocolatey`
* `choco search chocolatey --exact`

While following command said latest version of package `Chocolatey` was 2.2.2:

* `choco search chocolatey`

### Expected Behaviour

Chocolatey community repo API should return consistent version info, whether you're doing a `choco outdated`, `choco upgrade chocolatey`, `choco search chocolatey` or `choco search chocolatey --exact`.

### Steps To Reproduce

Yesterday, the following returned 2.2.0 as latest version:

```powershell
Invoke-RestMethod -Method 'Get' -Uri "https://community.chocolatey.org/api/v2/Packages()?`$filter=(tolower(Id)%20eq%20'chocolatey')%20and%20IsLatestVersion&semVerLevel=2.0.0"
```

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/6450056/acae510c-bf95-4708-8b2c-e4877e6d8ddb)

While following returned 2.2.2 as latest version:

```powershell
Invoke-RestMethod -Method 'Get' -Uri "https://community.chocolatey.org/api/v2/Packages()?`$filter=(tolower(Id)%20eq%20'chocolatey')%20and%20not%20IsPrerelease%20and%20IsLatestVersion&semVerLevel=2.0.0"
```

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/6450056/158900f5-5763-4c21-b3cc-decf23bfd9a5)

Where the only difference is the inclusion of `not IsPrerelease`.

### Environment

```markdown
See linked issue from `chocolatey/choco`.
```

### Chocolatey Log

```shell
Not relevant.
```

**Comment by cobrabr** [comment]
I added another example of a package running into this very same problem to the linked issue mentioned by the OP.

**Comment by pauby** [comment]
This isn't related to the packages in this repository, so I'm going to go ahead and close this.
