### ISSUE TITLE
ffdshow-x86_32 should be deprecated

### ISSUE THREAD

**Issue by dtgm** [chocolatey/chocolatey-coreteampackages#233]
[ffdshow-x86_32](https://chocolatey.org/packages/ffdshow-x86_32) is managed by chocolatey user, but not in this repo (lost in migration from purity's repo?)

Since the title is 

`ffdshow tryouts (forced 32-bit)` 

this package should probably be deprecated since we should be able to 

`choco install ffdshow --forcex86`

**Comment by dtgm** [comment]
I see it was removed from repo about a month ago https://github.com/chocolatey/chocolatey-coreteampackages/commit/b50df163caed5961b1dde6d8d0b1f1ad5111d694

**Comment by gep13** [comment]
@dtgm happy to take your guidance on this.  What do you need from me?

**Comment by dtgm** [comment]
I should of tagged @TomOne to ask why he removed the pkg without deprecating. Thought maybe he forgot to push it or something.
