### ISSUE TITLE
cygwin install does not start in `await`

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-coreteampackages#234]
when installing Cygwin there is a windows pops up, but the console does not wait until the window finish to finish the install.

I think that is why my `apt-cyg` package fail the install test.

https://gist.github.com/choco-bot/57b7c40f1682227a954e620ce72537af

**Comment by ferventcoder** [comment]
> And I think chocolatey should return the result of moderation in 3 business days...

@chantisnake I'm not sure I understand this statement clearly. Are you saying that ~~chocolatey~~ **chocolatey's community feed aka chocolatey.org** should prompt you within 3 business days if the system is still waiting on you to take corrective action? We have a service that will prompt you if it is still waiting after 20 days of last submission and then will automatically reject the package if you still have not responded/fixed the package given another 15 days.

We are working to make messaging more clear on moderation - **No human sees a moderated package *until* a user responds to the moderation review when failing or they get the automated moderation to pass.** We have wording in the actual messages as to this, but folks keep missing it. You currently get 35 days to get things passing and in front of a human moderator, but it's way too overwhelming for humans to look at packages until they are actually passing the automated checks. HTH.

**Comment by ferventcoder** [comment]
I'm not sure what we are seeing here - it doesn't seem to be installing cygwin first.

**Comment by ferventcoder** [comment]
If anything this is a bug with Chocolatey - I just ran this in the test environment and everything worked out well.  https://github.com/chocolatey/chocolatey-test-environment

**Comment by ferventcoder** [comment]
Closing as not an issue. Let's see how the rerun of the package verifier works out.

**Comment by chantisnake** [comment]
I have reread the latest bug report.
Here is the error:
https://gist.github.com/choco-bot/459fdaefe5279748b99fa767cd5ec65f#file-install-txt-L836
it cannot find Cygwin bash...

and I trace that back, and then found out that there is an error when installing Cygwin:
https://gist.github.com/choco-bot/459fdaefe5279748b99fa767cd5ec65f#file-install-txt-L658

**Comment by ferventcoder** [comment]
I see that now - Not sure why it didn't pick up the updated package for the first rerun, it should have done that after the 30 minute CDN timeout.

**Comment by ferventcoder** [comment]
I'm running it on the test environment and it is passing for me. Could be there was some issue with the cygwin install that is corrected in the updated beta.

**Comment by chantisnake** [comment]
That is a different issue. I am pretty sure when I begin setting up this laptop, I have seen Cygwin not starting on await... But I cannot recreate it now... I am not sure why, I will try again.

**Comment by ferventcoder** [comment]
Alright - I just read over the logs and looked at the package and found it was not installing cygWin first, so I went to investigate that a bit more deeply.

**Comment by chantisnake** [comment]
Thank you for that. I really appreciate your help.
