### ISSUE TITLE
Cygwin Excessive Shimming

### ISSUE THREAD

**Issue by wjk** [chocolatey/chocolatey-coreteampackages#237]
I have installed Cygwin through Chocolatey, and, by default, it installs into a subdirectory of the package folder. Chocolatey then recursively scans that directory for `*.exe` files, and shims every one it finds. The problem is, though, these EXEs do not run properly unless launched from within Cygwin. Therefore, I get some 500-odd shim EXEs in my Chocolatey bin directory (and, therefore, in my PATH) that serve no useful purpose. Hence, I would suggest adding `*.exe.ignore` files to prevent this from happening. I would do this within the install script (I have seen other packages do the same thing). I can prepare a PR for this if you would like.

**Comment by ferventcoder** [comment]
I've asked that CygWin not be installed into the Chocolatey Lib folders as that breaks quite a bit of things, but it appears that my requests have not been implemented. I may need to just do this.

**Comment by majkinetor** [comment]
Cygwin installs to ` Get-BinRoot` at this moment.
