### ISSUE TITLE
PDFCreator problems

### ISSUE THREAD

**Issue by teknowledgist** [chocolatey/chocolatey-coreteampackages#243]
Two issues here:

With Chocolatey 0.9.9.12, PDFCreator installs without error, but also installs PDF Architect.   PDF Architect is a separate uninstall, so a `choco uninstall pdfcreator` removes PDFCreator, but leaves Architect behind.

With Chocolatey 0.9.10.3, PDFCreator does not install ([error log here](https://github.com/chocolatey/chocolatey-coreteampackages/files/343769/ChocolateyLog.txt)), but PDF Architect does install.

I'm not sure why this installer needs the large "components" switch.  `PDFCreator-2_3_1-Setup.exe /verysilent /norestart /COMPONENTS="program"` installs all that is needed.

**Comment by majkinetor** [comment]
https://github.com/chocolatey/chocolatey-coreteampackages/pull/380
