### ISSUE TITLE
Thunderbird package out of date.

### ISSUE THREAD

**Issue by nwra-admin** [chocolatey/chocolatey-coreteampackages#244]
Thunderbird package installs Thunderbird 45.1.1, which is the same version as reported by Chocolatey.

There is now a security update to 45.2.0, which was released June 30th, there is no status shown on the packages page for 45.2.0. The latest version shown on the package page is 45.1.1.

**Comment by gep13** [comment]
@nwra-admin thanks for coming back on this one.  The automatic updater stopped working, hence why the new versions hadn't appeared.

**Comment by nwra-admin** [comment]
Glad to help
