### ISSUE TITLE
Load all ketarin.xml files each time we run the packages

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#247]
This will save issues where out of date ketarin files are loaded into the db, compared to what is in GitHub.

**Comment by dtgm** [comment]
basically missing this 

https://github.com/ferventcoder/chocolatey-packages/blob/master/ketarin/files/ketarinupdate.cmd#L19-L26
```batch
::import all the files
FOR /f "tokens=*" %%F IN ('dir %DIR%..\ /b *.ketarin.xml') DO (
	call ketarin.exe  /import="%DIR%..\%%F"
	TIMEOUT /T 2
)

Echo Wait for all of those to finish importing...
TIMEOUT /T 15
```

But that won't work for this repo since xml files are not in single directory. 
Untested, but I think replacing `$env:ChocolateyBinRoot\ketarinupdate.cmd` with below will work

```batch
@echo off

SET DIR=C:\github\chocolatey-coreteampackages\automatic
SET INCLUDE=*.ketarin.xml
SET EXCLUDE=_output\\

For /f "tokens=2-4 delims=/ " %%a in ('date /t') do (set mydate=%%c%%a%%b)
For /f "tokens=1-2 delims=/:" %%a in ("%TIME%") do (set mytime=%%a%%b)

echo Updating the github repo first
pushd %DIR%
call git add .
::call git commit -m "updates prior to automatic run for %mydate%_%mytime%"
call git reset --hard HEAD
call git fetch && git rebase origin/master
::call git push origin master
popd

::import all the files
FOR /f "tokens=*" %%F IN ('dir /s /b %DIR%\%INCLUDE% ^| findstr /v /i %EXCLUDE%') DO (
	call ketarin.exe  /import="%%F"
	TIMEOUT /T 2
)

Echo Wait for all of those to finish importing...
TIMEOUT /T 15

echo Calling ketarin now the the repo has been updated
call "Ketarin.exe" /silent /log=C:\ProgramData\chocolateypackageupdater\ketarin.%mydate%_%mytime%.log
```

**Comment by dtgm** [comment]
^^^ imports all xml files for every run though. Future improvement would be to only identify updated ketarin XML files in git and just import those.

**Comment by gep13** [comment]
@dtgm thanks for the heads up, I will give this a try.  It has been a LONG time since I set up this ketarin instance... where am I putting that script again?  Also, how to know if things are working as expected?  Thanks!

**Comment by gep13** [comment]
This has been completed based on the new template that is being used which was provided by @ferventcoder
