### ISSUE TITLE
For Python 2/3 packages, please add pip.exe to PATH through shim to <PYTHONPATH>\Scripts

### ISSUE THREAD

**Issue by dragon788** [chocolatey/chocolatey-coreteampackages#250]
Since Python 2.7.9 and Python 3.4 they have included pip with Python. Almost anybody using Python will want to have pip available in their path so they don't have to run ```python -m pip install <somepackage>``` every time instead of just ```pip install <somepackage>```.

**Comment by majkinetor** [comment]
Pip is added to path on Python3 now.

**Comment by gep13** [comment]
>@majkinetor said...
Pip is added to path on Python3 now

Noice!

I don't think that is true of python2 though, right? Would you be able to work your magic on that package as well? Also, I haven't quite got my head around how you handle meta packages with AU yet, like what you did with autohitkey. Would you be able to fix up the python package?

**Comment by majkinetor** [comment]
OK, will look into it in near future.

**Comment by gep13** [comment]
>@majkinetor said...
OK, will look into it in near future.

Thank you, I very much appreciate your help!

**Comment by blackwind** [comment]
When you get around to this, @majkinetor, please update the package to v2.7.12 as well.

**Comment by majkinetor** [comment]
Surw

**Comment by majkinetor** [comment]
Sure.
