### ISSUE TITLE
addging python launcher  (py.exe) to the python package

### ISSUE THREAD

**Issue by jbisson** [chocolatey/chocolatey-coreteampackages#255]
It seems that py.exe (python launcher) is not being package on windows for the python package.

Would be nice to be added as part of the package.

**Comment by gep13** [comment]
@jbisson do you have any thoughts on how to achieve this?  I would welcome any help that you can offer.

**Comment by ferventcoder** [comment]
@jbisson is this a particular option you select during the install of python? The package is a wrapper around the native installer.

**Comment by jbisson** [comment]
Interesting. I didn't see the option to. Do I need to specify a different choco command if I want options?

**Comment by ferventcoder** [comment]
@jbisson I meant from the original native installer, is there an option in the install steps to do what you are asking?

**Comment by ferventcoder** [comment]
You can run `choco install python --not-silent`

**Comment by jbisson** [comment]
ok, if I do --not-silent I'm getting the same installer promp and it works fine, however, without it, it doesn't install it.

In the installer dialog installer, the launcher is checked by default so it's kind of weird that it's not being installed when using choco install python3 ?

For example:
1) choco install python3
2) where py
result -> not found
1) choco install python3 --not-silent
2) where py
Result found.

**Comment by majkinetor** [comment]
I got it installed in the `c:\Windows\py.exe`.

**Comment by majkinetor** [comment]
I rerun the test on my machine and it really doesn't get created.

However, check this out:

![image](https://cloud.githubusercontent.com/assets/85767/20573821/ebf570bc-b1b1-11e6-8e9c-b63ec10d9d9e.png)


Py option is disabled (i did run eleveated) and although it is checked this means it will not be installed.

On the other hand running x32 bit installer:

![image](https://cloud.githubusercontent.com/assets/85767/20574267/f14f4ba8-b1b3-11e6-9129-5e928a6e73f8.png)


So, it looks like python3 doesn't support this.
