### ISSUE TITLE
[chromium] Avoid running the application after installation (annoying new browser window)

### ISSUE THREAD

**Issue by C-Duv** [chocolatey/chocolatey-coreteampackages#264]
When `chromium` package is installed, a new Chromium's browser window opens up. I am guessing this is because the upstream installer runs the application once it is installed.
Is it possible to avoid running the application post-installation (via some switch on the upstream's installer) or, at least, kill it from the package?

I tried handling that on my side with a `Stop-Process` after `choco install chromium` but I can't differentiate when Chocolatey installed/upgraded the application and when it didn't do anything (because it was already installed and up-to-date).

**Comment by gep13** [comment]
@RedBaron2 do you know if there is anything that can be done here? Thanks!

**Comment by RedBaron2** [comment]
@gep13 it is not supposed to do that at all. I will be working on the install to make it read a switch for system install soon.
@C-Duv The PR to fix the current md5 change might fix this issue also.

**Comment by RedBaron2** [comment]
@gep13  This can be closed unless @C-Duv has experienced the issue again. The arguments will fix the issue of the browser spawning after install. There is a brief issue if the package fails to install. The browser will be spawned to open, but this is only on a failed install. It would seem to be a part of the installer launches the browser regardless of any arguments, but this is not a chocolatey issue.

**Comment by C-Duv** [comment]
I can confirm it is fixed: no new browser window after installation :+1:
