### ISSUE TITLE
Export ketarin global config xml

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey-coreteampackages#266]
Can someone export the ketarin global config xml to the root of this repo (and keep it updated if the ketarin config changes)?

It really beats guessing.

//cc @gep13

**Comment by gep13** [comment]
@Redsandro what do you mean by guessing?  

I can certainly do that, but I don't understand the benefit.

**Comment by Redsandro** [comment]
@gep13 The benefit is one source of truth for any coreteam-ketarin related question, and an easy way of importing that configuration for testing purposes has a speed benefit because the people without access to the coreteam-ketarin-machine don't have to guess and manually fill in the config.

Maintainers don't know what global command is executed. I need to google for chocolatey's package documentation and __assume__ the coreteam-ketarin uses the same.

**Comment by Redsandro** [comment]
Also, I'd like the configuration to be imported by ketarin on a [vagrant box](https://github.com/chocolatey/chocolatey-test-environment) from the repo. Makes no sense to do it manually.

**Comment by gep13** [comment]
>@Redsandro said...
Also, I'd like the configuration to be imported by ketarin on a vagrant box from the repo. Makes no sense to do it manually.

If you can get something up and running, I would love to see it, and make use of it.

**Comment by gep13** [comment]
@Redsandro you can find the full export here:

https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/setup/KetarinExport.xml

You will notice that the repo is now setup as suggested by @ferventcoder based on the chocolatey template repository, and it should now be easier to understand, and setup to match what is on the core team server instance.

Also, you will notice that I have started to swap to using AU instead of Ketarin, as it offers far more in terms of configuration, and reporting.

**Comment by Redsandro** [comment]
@gep13 thanks for the update.

Perhaps I'm not looking right and the configuration is in there too, but this xml looks like a joblist, not the global configuration of Ketarin itself.

> I have started to swap to using AU instead of Ketarin

I haven't had the chance to look into that. But if it has benefits, I applaud that.

**Comment by gep13** [comment]
@redsandro there are two ketarin related XML files.  There is this one:

https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/setup/KetarinExport.xml

Which is an export of all the individual ketarin files that are currently loaded into the Ketarin instance on the Azure based Choco Server.

And there is this one:

https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/setup/KetarinSettings.xml

Which is the current global settings that are used on the ketarin machine.

**Comment by Redsandro** [comment]
@gep13 super, thank you.

**Comment by gep13** [comment]
@Redsandro would gratefully accept any help you can offer on converting some of the packages to AU 😺

**Comment by Redsandro** [comment]
@gep13 not any time soon; got a backlog of problems because I was sick for a month. :cry: 
I like this ketarin-independent update method tho. Will inspect it more when time allows me to do so.

**Comment by gep13** [comment]
>@Redsandro said...
