### ISSUE TITLE
[Update] Chromium

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey-coreteampackages#270]
Continued from https://github.com/chocolatey/chocolatey-coreteampackages/issues/265#issuecomment-237745306

---

@RedBaron2 said:
> I'm going to chime in here and state that the Chromium Package has just had the PR #267 #268 #269 done to implement checksum 'md5' because of the whole FOSSHub News. This was able to be done with the help of Woolyss wonderful API.
>
> I would like to see about having the chromium package updated more frequently than seems to be done now. If that would take becoming the package Maintainer I guess I would be up for it.

@RedBaron2 I'm not sure what you mean. `chromium` is automatically updated pretty much [daily](https://chocolatey.org/packages/chromium). Are you suggesting multiple updates per day?

PR look good, but I don't feel comfortable merging without testing such a popular package. @gep13 can you see if Ketarin takes PR #267 #268 #269?

@RedBaron2 please do all your commits in a single commit next time. You can push to your fork after you did the PR and it will automatically be added to that PR.

**Comment by RedBaron2** [comment]
> I'm not sure what you mean. chromium is automatically updated pretty much daily. Are you suggesting multiple updates per day?

Yes! that is exactly what I'm suggesting. The 'Chromium Package' was updated yesterday to a new version twice in one day. There have been times when the 'Chromium Package' has been updated as much as six times in one 24 hour period. I'm just suggesting a morning update and an evening update for the package. This would be nothing too serious, and an easy change that could be done in the schedule of the making the packing.

> please do all your commits in a single commit next time. You can push to your fork after you did the PR and it will automatically be added to that PR.

Thanks for the suggestion.

**Comment by gep13** [comment]
To be clear, the ketarin instance, which runs this chromium package is scheduled to check for new package versions every hour. So if a new version is detected, it will be pushed and approved within about 2-3 hours. So I think we have this covered, right?

**Comment by RedBaron2** [comment]
@gep13 Yeah that sounds fine. I was forgetting the moderation of the package would take extra time.

I have updated the Ketarin file and the install file for uniformity with the choco update packager.
I have also just tested the files.

`$checksum = @{$true = "2aa28074985b0ca6feda7d36a3d3b147"; $false = "034f48de10724f089d4f85945f55bca2"}[$systemIs64bit -eq 64]`

The checksums are placed and ready for install chocolateypackage command

**Comment by Redsandro** [comment]
@gep13 I'm inviting you to merge this, as the new configuration needs to be implemented in ketarin before the new installer makes sense.

**Comment by gep13** [comment]
@RedBaron2 do you use Gitter?  Would love to chat about a few things if you have some time.  Thanks!

**Comment by RedBaron2** [comment]
@gep13 haven't heard of it. Just installed the package a moment ago.
I will shoot you a message when I get it up.

**Comment by gep13** [comment]
@Redsandro with the help of @RedBaron2 I think I have got this sorted out now, so I am going to close this for now.

We can re-open if it doesn't work after the next release.

**Comment by Redsandro** [comment]
@gep13 aaight, that's what it's for. :+1: 

@RedBaron2 package? I didn't know there was an app. Does it add anything valuable that the [gitter.im](https://gitter.im) website doesn't offer?

**Comment by RedBaron2** [comment]
@redsandro The package send to be a stand alone app. The interface is very similar to the website.
