### ISSUE TITLE
Add download checksums to packages

### ISSUE THREAD

**Issue by wjk** [chocolatey/chocolatey-coreteampackages#272]
The title really says it all. While #265 tracks the progress for the five packages in this repo that download binaries from FossHub, many other packages in this repo (`mixxx`, for example) also need download checksums added to their install scripts.

**Comment by gep13** [comment]
@wjk thank you for raising this. This is on my radar, and hoping going to get to this at the weekend.

**Comment by sippi90** [comment]
Could you please add checksums for the package mp3tag? Thanks

**Comment by gep13** [comment]
@sippi90 yes, that is still on my radar. Happy to accept any help that anyone can offer here.  There are quite a lot of packages 😄

**Comment by gep13** [comment]
>@sippi90 said...
Could you please add checksums for the package mp3tag? Thanks

I have just pushed a new version of the mp3tag package, which will hopefully go through verification this time.

**Comment by majkinetor** [comment]
I close this as non specific. About half of the packages are updated already.
