### ISSUE TITLE
Using System.Net.WebClient in some packages

### ISSUE THREAD

**Issue by ebugusey** [chocolatey/chocolatey-coreteampackages#305]
Some packages use `System.Net.WebClient` to download pages for parsing, for example [Firefox](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/Firefox/tools/chocolateyInstall.ps1#L32).
I'm behind corporate proxy with NTLM-auth and this thing doesn't work for me. I got this error:
```
ERROR: Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (407) Proxy Authentication Required."
```
When I configure webclient like this:
```powershell
$wc = New-Object System.Net.WebClient
$wc.Proxy.Credentials = [System.Net.CredentialCache]::DefaultCredentials
```
`DownloadString` does work.

**Comment by ferventcoder** [comment]
Those packages should just use the built-in Chocolatey methods now that they overcome many of the earlier limitations in earlier versions of Chocolatey that set them to use WebClient directly instead of using the built-in methods.

**Comment by ferventcoder** [comment]
@gep13 ^^

**Comment by gep13** [comment]
@ferventcoder  Ah, you might want to take a look at the PR I am just away to mention you in 😄

**Comment by ebugusey** [comment]
Is there pull request already or can I make one?

**Comment by gep13** [comment]
@ebugusey there is a pull request already for some work I was doing with the FossHub extension, which is in this repo as well.  However, this PR doesn't deal with any other packages that are already using WebClient.  Would be happy for you to create a PR to correct them though.

**Comment by gep13** [comment]
@ebugusey this has now been included and I have pushed new package fix version notation's for firefox and thunderbird.

Please let me know if you continue to see issues.

Thanks for your help on this!
