### ISSUE TITLE
Update python3 to v3.5.2

### ISSUE THREAD

**Issue by koppor** [chocolatey/chocolatey-coreteampackages#306]
The current version of python3 is v3.5.2 - see https://www.python.org/downloads/release/python-352/

Can the package be updated?

Refs #146

**Comment by gep13** [comment]
@koppor yes.  There is an open PR for this here:

https://github.com/chocolatey/chocolatey-coreteampackages/pull/303

I just need to review it, and get it merged in.

**Comment by gep13** [comment]
@koppor okay, I think this is ready to go.  Package has been pushed to chocolatey.org.  Let us know if you run into any other problems.
