### ISSUE TITLE
Prerequisites for pulling a package into the core team repo

### ISSUE THREAD

**Issue by TomOne** [chocolatey/chocolatey-coreteampackages#31]
I think it is not specified which prerequisites a package must have to be accepted and pulled into this repo (in addition to the existing [guidelines for contributing](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md) of course). That is a quite important matter, therefore we should specify it and write it into the README.md of this repo.

How about these prerequisites?
1. At least one member of the Chocolatey core team must be interested into the package to get it added to the core team packages repo. Therefore, before making pull requests for adding new packages to this repo, open an issue to ask if it can be added.
2. This repository is not indented as place to host random orphaned packages or package where the original maintainer is no longer interested to keep the package. Prerequisite 1 must be applicable to such packages.

This seems quite obvious, but nevertheless I’d add it (or a grammatically improved version) to the README.md.

Thoughts?

**Comment by gep13** [comment]
This is related to https://github.com/chocolatey/chocolatey-coreteampackages/issues/20 and needs to be added into the wiki/contributing guide, if not already included.

**Comment by majkinetor** [comment]
I agree with resandro here. I will.make a suggestion for core guidance so we can argue.

**Comment by majkinetor** [comment]
New guidelines include almost all here.
