### ISSUE TITLE
Update notepadplusplus to v7.0

### ISSUE THREAD

**Issue by pantosha** [chocolatey/chocolatey-coreteampackages#312]
Notepad++ v.7.0 was released. Major change is Notepad++ support x64.

Link to release notes - https://notepad-plus-plus.org/download/v7.html

Thank you.

**Comment by majkinetor** [comment]
Implemented in this PR: https://github.com/chocolatey/chocolatey-coreteampackages/pull/321

**Comment by gep13** [comment]
@pantosha this has just been pushed to chocolatey.org, and is currently going through moderation.

**Comment by pantosha** [comment]
Ok, thank you!
