### ISSUE TITLE
Issue with Chromium

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#329]
https://gitter.im/chocolatey/chocolatey.org?at=57fd036e4fde7203142a3c2d

@RedBaron2 any chance you can take a look at the above? Thanks!

**Comment by RedBaron2** [comment]
@gep13 The Chromium Package hasn't been updated to the latest version of 56.0.2888.0
This version according to virus total is safe. [https://www.virustotal.com/ro/file/c7aabb983fe2e2c041d99ec8fd596a59e5d6115184167fc5c0718b7772aa9fbd/analysis/1476225750/](url)

Also had virus total scan the current version chocolatey package is also safe
[https://www.virustotal.com/ro/file/336666842deb22b4533e11f0e554c8786c60b929922bfb06b3489da15360e1b6/analysis/1476226420/](url)

I hope this helps.

**Comment by gep13** [comment]
@RedBaron2 it is strange the that package hasn't been updated.

Let me check something...

**Comment by gep13** [comment]
@RedBaron2 okay, latest version should now be pushed.  Let me know if you notice this happening again.

**Comment by RedBaron2** [comment]
@gep13 
This seems to be fixed with the move to AU Update.
