### ISSUE TITLE
When taking a dependency on an extension, specify the minimum version

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#333]
Especially if you need new functionality in the newer module. Otherwise any version satisfies the dependency. That means unless someone upgrades the extension outside of their process, it will not automatically upgrade to the latest version. Just something to keep in mind.

cc @gep13 @majkinetor

**Comment by majkinetor** [comment]
Yeah, I already do that and have a script that updates all older packages with new extension version.

>  That means unless someone upgrades the extension outside of their process, it will not automatically upgrade to the latest version. Just something to keep in mind.

If you install ANY package that has explicitelly set this you will update it for all other packages.
