### ISSUE TITLE
(wincdemu) Installer scripts needs updating

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#335]
Currently the installation script for WinCDemu does no longer work.
Apparrently they have dropped support for the silent argument that was used in previous installers.

To get the installation to work now the following would be required.
Use autohotkey (or some other method) to automate the installation, driver installation and the information messagebox.

A uninstall script would probably also be needed since the chocolatey auto uninstaller isn't able to
completely remove WinCDemu.
The following aren't removed
* The entry in Programs and Features
* A couple of files in the Program Files (x86)\WinCDEmu install directory
  * `mkisofs.exe`
  * `x64\WinCDEmuContextMenu.dll` which is locked by Windows Explorer
  * (Possibly also a x86 directory if installed on 32bit Windows)

**Comment by majkinetor** [comment]
This works for me, please test it

`.\install.ahk $pwd\WinCDEmu-4.1.exe`

```
path = %1%
SplitPath, path, exe_name

Run, %path%
WinWait, WinCDEmu installation ahk_exe %exe_name%
WinActivate
Send, {Enter}
loop {
    sleep 100
    IfWinExist, Windows Security
    {
        WinActivate
        Send, !i
    }
    IfWinExist, Information ahk_exe %exe_name%
    {

        WinActivate
        Send, {Enter}
        break
    }
}
```

It could be just a little more bulletproof with timeouts for windows waiting but lets see how this works.

**Comment by AdmiringWorm** [comment]
@majkinetor I'll try it out, unfortunately I don't have the option to do that now though.
One problem I see though, checking for a window with the title 'Windows Security' would be
a problem, that window is dependent on the user locale.

**Comment by majkinetor** [comment]
Good catch, fixable I think.. I didn't get it long enough, once it passed it never showed up. Other parts of the script should be made bettter (timeout is needed as if something goes wrong and windows never appear, it will just block in the loop).

**Comment by majkinetor** [comment]
Other then that its pretty stable - it cant happen to send to wrong windows for example, typicall problem with AHK.

**Comment by majkinetor** [comment]
Wincdemu still has silent mode.

**Comment by AdmiringWorm** [comment]
It has? I was trying out different install switches, as well as the install switch that was used in
the old packages.
I'll need to check that out then.

**Comment by majkinetor** [comment]
No need, already finished it.

**Comment by AdmiringWorm** [comment]
oh, thanks a lot for doing that.

**Comment by majkinetor** [comment]
https://github.com/chocolatey/chocolatey-coreteampackages/commit/2b803a1392c0485c91c62cdcfc87d10a37eb4f48
