### ISSUE TITLE
(autohotkey) Update package with new installer

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#338]
AHK changed its installer today.

Now it bundles all types of portable AHK into same archive and non-portable installer changed its name.

- Installer changes: https://autohotkey.com/docs/Scripts.htm#Installer_uiAccess
- Releases: https://autohotkey.com/download/1.1

**Comment by majkinetor** [comment]
https://github.com/chocolatey/chocolatey-coreteampackages/commit/e71041db5fd2b50a8fc2243d974ddc07d52e92b4

**Comment by majkinetor** [comment]
@ferventcoder , @gep13 

I fixed AHK, but I see now that somebody pushed bad package ?

$ErrorActionPreference = 'Stop'
 
```
$packageArgs = @{
  packageName    = 'autohotkey.portable'
  url            = 'http://ahkscript.org/download/1.1/AutoHotkey112401.zip'
  url64Bit       = 'http://ahkscript.org/download/1.1/AutoHotkey112401_x64.zip'
  checksum       = '90ECF74C0BDDD243D21B57DB3864EFC3C959CDA7D64296B0A29AD4AC9847E46A'
  checksum64     = '6E61A6CBBADBB37A114C90E885996DE3A392D6E79AF9D9DF37ACF2DCAA8E39E4'
  checksumType   = 'sha256'
  checksumType64 = 'sha256'
  unzipLocation  = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"
}
 
Install-ChocolateyZipPackage @packageArgs
```

It is previous version.

IMO, portable package should be unlisted since it doesn't represent version it says.

**Comment by gep13** [comment]
>@majkinetor said...
I fixed AHK, but I see now that somebody pushed bad package ?

Since happened due to the transition of the packages from @ferventcoder automatic repo to the core team repo.  This is one of the reasons that we need to ensure that maintainers are onboard with moving the packages into core team repo, so that they have time to remove the packages from their automatic systems.  We might be in the same situation with the @dtgm package that you ported.  Has that been removed from his automatic repo?

Are we in a position to force push a package fix notation of these packages?  If so, I can unlist the necessary packages.

**Comment by majkinetor** [comment]
> Has that been removed from his automatic repo?

Don't know, but you could remove him from maintainers for the time being for push to fail.

**Comment by gep13** [comment]
@majkinetor this one is ready to be closed out, right?

**Comment by majkinetor** [comment]
The package works. However the last community package is wrong: https://chocolatey.org/packages/autohotkey.portable

**Comment by gep13** [comment]
Yes, but with the new functionality that you have just added, you can push a new package with the package fix notation, right?

**Comment by majkinetor** [comment]
Right! 
How should I version it, it already uses revision: `1.1.24.02`

**Comment by gep13** [comment]
Ah.  Good question...

Personally, I would be going for `1.1.24.03`.

@ferventcoder what are your thoughts on this?

**Comment by majkinetor** [comment]
Anyway, I just realized that AU doesn't allow for manual version override. It will return version to RemoteVersion even if the NuspeVersion is higher. If it was not using revision part of the version it would autogenerate choco fix notation and push it.

I could change AU so that *if update is forced and NuspecVersion is higher then RemoteVersion* , NuspecVersion should be used. I don't know if that sounds strange or confusing...

**Comment by gep13** [comment]
I think that sounds correct.

**Comment by majkinetor** [comment]
That is, maybe better said, _with force always use NuspecVersion and if it is the same as RemoteVersion use choco fix unless package already uses revision_.

**Comment by gep13** [comment]
:+1:

**Comment by majkinetor** [comment]
I think we should sit this one out. If we push that version the next one will be problematic again if it beomces 03 and it may.  Its very small problem anyway.

**Comment by majkinetor** [comment]
Anyway, I dropped above ideas as they are confusing. Currently only if remote version is higher then nuspec version the package will get updated and if it is the same and forced we will get fix notation.
This is all well and **not confusing**.

So now, I implemented new global variable that can be used along with Force, for example:
 
       $au_Force = $true; $au_Version = '0.1'; ./update.ps1
 
This will force update and use explicit version.
I think this is way more telling then what is going on with other idea.
The only downside is that if you force multiple packages you will have to remember to null out au_Version or it may apply to wrong package.

Anyway, with this published I can change AU message to AV to support explicit version: 

`[AU pkg1 pkg2 ... pkgN:verN ... ]`

So in this case we would `[AU autohotkey.portable:1.1.24.03]`. I wont to this for AHK as told before, this is thinking about the future. 

If you think this is OK I will implement it. Is semicollon notation OK ? I think there are no packages with it in name. Alternativelly we could use `|`. 

@gep13, @ferventcoder , what do you think about this ?

**Comment by gep13** [comment]
>@majkinetor said...
The only downside is that if you force multiple packages you will have to remember to null out au_Version or it may apply to wrong package.

This part concerns me a little bit.  Can AU not null out the global variables at the end of the execution?

>@majkinetor said...
Is semicollon notation OK ?

In this instance, I think the `|` delimiter might be easier to read.

**Comment by majkinetor** [comment]
> This part concerns me a little bit. Can AU not null out the global variables at the end of the execution?

First of all this can not happen when updateall runs as each thread has separate global vars. This can only happens when you do this in your local shell, and force several packages. I can null it out between calls which might not be expected by the user.

**Comment by gep13** [comment]
>@majkinetor said...
I can null it out between calls which might not be expected by the user.

It might also not be expected for the version number to be persisted between calls either though.

**Comment by majkinetor** [comment]
Actually, all other env vars are kept. Thats why its unintuitive. But since its dangerious I will null it on each call.

**Comment by ferventcoder** [comment]
03 sounds good to me.

**Comment by majkinetor** [comment]
No its not good. Next version willl with some certainly be 03. Since we will take it, we will have to use 04 for 03 which makes us enter loop (02 is 01, 03 is 02, 04 is 03 ...). So we will just do nothing. When tools have revision in the version its virtually impossible to use fix notation (unless we allow pre versions, such as in this case `1.1.24.02-20161024` but choco has to support this).

**Comment by ferventcoder** [comment]
> When tools have revision in the version its virtually impossible to use fix notation

Incorrect - we've documented how it is possible in https://chocolatey.org/docs/create-packages#package-fix-version-notation. It's ugly and requires manual intervention, but it is possible.

>When the fourth segment is already used, it is recommended to add two zeroes (`00`) to the end of the version. Then when you need to fix, you just increment that number. So if the package was ruby and the version was `2.0.0-p353`, the package is `2.0.0.35300` (adding the two zeroes at the end). Then a fix would be `2.0.0.35301` and so on. **WARNING:** If you decide to add a secondary set of numbers to the fourth segment, you MUST ALWAYS include that secondary set of numbers while the other three version segments are the same. The reason - if you fix `.1` to `.100`, then release `.2`, `.100` is greater than `.2` because versioning doesn't look at the ".", only the number in the element. So `100` is greater than `2`.

**Comment by majkinetor** [comment]
> Incorrect - we've documented how it is possible in https://chocolatey.org/docs/create-packages#package-fix-version-notation. It's ugly and requires manual intervention, but it is possible.

Can you 'fix' this case for me then? You said 03 and I say it will probably collide (given previous 2 versions ere 01 and 02, 03 is something to be expected).

The fix you proposed is a bit unrealistic. It requres you to create special  version IN ADVANCE. This special version would be required for ALL packages that use revision just in case they may need fixing in the future. Given that version is different from remote in all cases it could lead to confusion.

**Comment by majkinetor** [comment]
Its also not idempotent .
