### ISSUE TITLE
(firefox) 49.0.2.20161023 install fails on PowerShell < 3

### ISSUE THREAD

**Issue by lafrech** [chocolatey/chocolatey-coreteampackages#352]
I get this error when upgrading firefox:

```
ERROR: A parameter cannot be found that matches parameter name 'Raw'.
The upgrade of firefox was NOT successful.
```

From a quick search, it could be powershell version related. See [this SO post](http://stackoverflow.com/questions/39580203/get-content-raw-parameter-error):

> The parameter -Raw was introduced with PowerShell v3.

My PS version is 2:

```
PS C:\Users\jlafrechoux> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      -1     -1
```

**Comment by gep13** [comment]
@ebugusey seems like there is an issue with the chocolatey-core.extension with respect to PowerShell version.  Ideally, the extension should support back to PowerShell 2.  Would you be in a position to provide an update for this?  Thanks!

**Comment by ebugusey** [comment]
@gep13 I can fix it, but I don't have testing environment ready.

**Comment by majkinetor** [comment]
@ebugusey You don't need test environment. You can use AU `Test-Package` also to test it locally.

**Comment by ebugusey** [comment]
@majkinetor I need to test it on PowerShell v2, and I don't have a VM with that setup. And also _firefox_ is a _ketarin_ package.

**Comment by ebugusey** [comment]
Oh, wait. Can I use `-Version` to run v2?

**Comment by majkinetor** [comment]
You should be able to do that.... let us know. U dont need ketatin for this

**Comment by gep13** [comment]
@lafrech I am just away to push new package fix notation version of both firefox and thunderbird.  If you could verify that these work for you, I would really appreciate it, thanks!

**Comment by lafrech** [comment]
The upgrade of Firefox was successful.

Thanks.

**Comment by gep13** [comment]
>@lafrech said...
The upgrade of Firefox was successful.

That is great news! Thanks for letting us know.
