### ISSUE TITLE
Audacity v2.1.2.20161006 installer exits with code 4, fails installation

### ISSUE THREAD

**Issue by bazzilic** [chocolatey/chocolatey-coreteampackages#353]
The installer installs Audacity successfully, i.e., it appears in Program and Files, etc. However, `chocolateyInstall.ps1` (I assume) exits with code 4 (if the return code comes from the installer, then it is fatal error, according to [InnoSetup docs](http://www.jrsoftware.org/ishelp/index.php?topic=setupexitcodes)), and therefore Chocolatey considers this as failed install.

Running into this with Chocolatey v0.10.3 on Windows 10 Pro v1511 (b10586.633) x64.

There are reports of same behavior and interesting observations regarding the topic in the [comments to Audacity package](https://chocolatey.org/packages/audacity#comment-2946609592).

The installer itself seems to work fine:

```
C:\Users\bazzilic\Downloads>start /wait audacity-win-2.1.2.exe

C:\Users\bazzilic\Downloads>echo %errorlevel%
0

C:\Users\bazzilic\Downloads>start /wait audacity-win-2.1.2.exe /verysilent

C:\Users\bazzilic\Downloads>echo %errorlevel%
0
```

**Comment by gep13** [comment]
@bazzilic thanks for reporting this. I haven't personally tested this package on a Windows 10 machine, only Windows Server 2012 and Windows 8.1.  Really not sure where the 4 would be coming from.  We could certainly add that as a valid exit code to the chocolateyInstall.ps1 file, but that seems like a very crude workaround.  Would be nice to know "why" it is returning that.

**Comment by majkinetor** [comment]
```
PS C:\Users\majkinetor> cinst audacity --ignore-checksums
Installing the following packages:
audacity
By installing you accept licenses for the packages.

audacity v2.1.2.20161006 [Approved]
Using system proxy server '10.35.9.55:8080'.
Downloading audacity
  from 'https://www.fosshub.com/Audacity.html/audacity-win-2.1.2.exe'
Using system proxy server '10.35.9.55:8080'.
WARNING: C:\Users\mmilic\AppData\Local\Temp\chocolatey\audacity\2.1.2.20161006\audacity-win-2.1.2.exe is of content type text/html; charset=utf-8

Download of audacity-win-2.1.2.exe (-1 B) completed.
WARNING: Ignoring checksums due to feature checksumFiles = false or config ignoreChecksums = true.
Installing audacity...
ERROR: The file was a text file but is attempting to be run as an executable - 'C:\Users\mmilic\AppData\Local\Temp\chocolatey\audacity\2.1.2.20161006\audacity-win-2.1.2.exe'
The install of audacity was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\audacity\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - audacity (exited 4) - Error while running 'C:\ProgramData\chocolatey\lib\audacity\tools\chocolateyInstall.ps1'.
 See log for details.
```

The extension failed - it downloads HTML file.

**Comment by AdmiringWorm** [comment]
This seems to be fixed when the chocolatey-fosshub extension was updated.
Closing for now
