### ISSUE TITLE
Java SE Runtime Environment Package Issue

### ISSUE THREAD

**Issue by Rgum00** [chocolatey/chocolatey-coreteampackages#356]
Having an issue I discovered recently where when running Chocolatey as system to install to the latest version of JRE8 it doesn't actually install the program. But Chocolatey reports the latest version is indeed installed. 

![2016-10-21_10-46-05](https://cloud.githubusercontent.com/assets/23055250/19687932/84300628-9a95-11e6-9386-e0fd1125ec77.jpg)

**Comment by gep13** [comment]
@Rgum00 I can see might you might think that the source for this package is in this repo, but it isn't.  It is actually over here: https://github.com/proudcanadianeh/ChocoPackages This package is maintained by @proudcanadianeh.  Can I ask that you open the issue there?  Thanks!

**Comment by jberezanski** [comment]
Ah, sorry, I pointed @Rgum00 here based on the "Possible package source" link on the package page. My mistake.

**Comment by gep13** [comment]
@Rgum00 not a problem. I figured that the possible package source link might have been the source of the issue 😄
