### ISSUE TITLE
flashplayerplugin: missing security update for a week

### ISSUE THREAD

**Issue by NicoHaase** [chocolatey/chocolatey-coreteampackages#367]
A week ago, an update for the flash player has been released containing fixes for severe bugs, see https://helpx.adobe.com/security/products/flash-player/apsb16-36.html. It would be good to release the update through Chocolatey too

**Comment by gep13** [comment]
@NicoHaase thanks for reaching out.

Please check here:

https://chocolatey.org/packages/flashplayerplugin/23.0.0.205

Just pushed new package version.
