### ISSUE TITLE
AU updaters block when it uses Invoke-WebRequest and Vector smash appears in the output

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#382]
`Invoke-WebRequest`  (`iwr`) is very handy so we all use it. Sometimes `Vector smash` appears in the output of the update which means IE settings aren't set to allow all cookies (this doesn't happen with `WebClient` and other tools such as `curl.exe` or `wget.exe`). When 'Vector smash' appears, `./update.ps1` that uses `iwr` in the `au_GetLatest`  displays that message but updater finishes normally. However, when `updateall` iterates over packages, those that have Vector smash block or simply fail without returning normal result, `AUPackage` object that holds details of the update execution.

**Example**

```
PS> $releases = 'http://www.videosoftdev.com/free-video-editor/download'
PS> $download_page = Invoke-WebRequest -Uri $releases
PS> $download_page.Content -split "`n" | sls 'Current version' -Context 2

  <div style="float: left;">
  <div style="float: left; width: 110px;">
> <p>Current version:</p>
  <p>File size:</p>
  </div>
  <p><strong>How to install the program</strong></p>
  <p>To install the program, click the "<a href="/services/download.aspx?ProductID=1">Download Video Editor</a>" button, then start the downloaded installation file and  follow on-screen instructions.</p>
> <p>Please, note, that the current version doesnât run on Windows versions prior to Windows XP SP3. If you use older Windows versions, please, make use of <a href="/ services/download.aspx?ProductID=xp_1">VSDC Video Editor version 3.3.5</a></p>
  <hr size="1" style="height: 1px; color: #c0c0c0;" />
  <p><a href="/support/faq">How to uninstall the program</a></p>
```

Vector smash protection kicks in here:

```
PS> $download_page = Invoke-WebRequest -Uri $releases
PS> $download_page.Links
Vector smash protection is enabled.
```

![image](https://cloud.githubusercontent.com/assets/85767/20096002/3244fdc8-a5a8-11e6-9d3a-565f6c427371.png)

`To allow this website to provide information personalized for you. will you allow it to put a small file (called a cookie) on your computer`

Does anybody has any ideas.

**It looks like THIS cookie popup is the reason why AU's `updateall` blocks when `Vector smash` shows in the output.**

**Comment by majkinetor** [comment]
This should change the popup appearing:

```
sp 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' 1A10 1
```

**Comment by majkinetor** [comment]
I tested it in vagrant and it doesn't report `Vector smash`, however, it still doesn't show any version, so it doesn't seem to be related to that. Good thing is that we now can probably solve vector smash for `updateall` using above registry setting.

**Comment by majkinetor** [comment]
Funny thing:

```
$download_page.AllElements | ? tagname -eq 'strong'

innerHTML      : 5.5.0
innerText      : 5.5.0
outerHTML      : <STRONG slick-uniqueid="252">5.5.0</STRONG>
outerText      : 5.5.0
tagName        : STRONG
slick-uniqueid : 252
```


On vagrant it works but now popup appears.

So this seems to be complete solution:

```
'HKLM', 'HKCU' | % { sp "$_:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3" A10 0 }
($download_page.AllElements | ? tagname -eq 'strong').innerText | ? { [version]::TryParse($_, [ref]($__))}
```

@gep13 , @AdmiringWorm

**Comment by majkinetor** [comment]
I will add this registry setting line to the AV setup.

**Comment by gep13** [comment]
@majkinetor what does that setting actually do?  Is it going to have an impact on the other update scripts?

**Comment by majkinetor** [comment]
Its enbles all cookies as safe in IE:
![](http://i.stack.imgur.com/T3dnr.jpg)

> HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3 1A10 (Dword) to 0, where values indicate the same as on the slider from Windows 8.1: Block All Cookies: 00000003 High: 00000001 Medium High: 00000001 Medium: 00000001 Low: 00000001 Accept all Cookies: 00000000

**Comment by majkinetor** [comment]
Its a little different in WIn 10:

![image](https://cloud.githubusercontent.com/assets/85767/20099707/450a4f6e-a5ba-11e6-8de4-6e4759f91e28.png)

**Comment by majkinetor** [comment]
Reopening as it still happens

**Comment by majkinetor** [comment]
I couldn't make the IE setting off with powershell.

**Comment by RedBaron2** [comment]
I found a solution to this problem, and it requires two lines of code to add/remove a registry key. I will update this with the lines of code tomorrow

**Comment by majkinetor** [comment]
How that differs from what I done [above](https://github.com/chocolatey/chocolatey-coreteampackages/issues/382#issuecomment-259115847).

Plus, I am not sure what you do there - you add the key then delete that key .. how that helps.

I am not sure I understand next part too.

Plus, I prefer this to be done on systemic level, not for each package.

It would be good to full working package example, perhaps on your AppVeyor instance or we can merge something here for test.

**Comment by majkinetor** [comment]
You mean you do this:

```powershell
reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3" /t REG_DWORD /v 1A10 /f /d 0
Invoke-WebRequest $releases
reg delete "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3" /v 1A10 /f
```
What do you mean _it is just better to close the iwr call_ ?

**Comment by RedBaron2** [comment]
@majkinetor This is my example (and my reason for finding it myself)
`reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3" /t REG_DWORD /v 1A10 /f /d 0 | out-null;
$URI = “https://www.360totalsecurity.com/en/features/360-total-security/“;
$HTML = Invoke-WebRequest -Uri $URI;
$try = ($HTML.ParsedHtml.getElementsByTagName(‘span’) | Where{ $_.className -eq ‘version’ } ).innerText;
$try = $try -replace( ' : ',' = ');
$techy =  ConvertFrom-StringData -StringData $try;
$CurrentVersion = ( $techy.Version );
reg delete "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3" /v 1A10 /f | out-null;
$HTML.close;`
This is for a per call issue at least in my case. I close the iwr call's because in testing I found several IE hidden windows open. Besides it did help your 'AU' issue did it not?

**Comment by majkinetor** [comment]
> Besides it did help your 'AU' issue did it not?

I don't know I didn't test it. 

_Your_ issue is irrelvant and what it solves. The only relevant stuff is referent environment, in this case AppVeyor or at least chocolatey test environment. 

So, provide an example with `free-video-editor` which suffers from this when you remove `UseBasicParsing`:

```
function global:au_GetLatest {
    $download_page = Invoke-WebRequest -Uri $releases -UseBasicParsing
...
```

UseBasicParsing is currently there becuase of this issue. Make this package work on AppVeyor and the issue is solved. I made it work on my own machine but it still didn't on AV.

**Comment by majkinetor** [comment]
I have never seen anybody clsoing IWR the way you did, but the problem with multiple IEs is not related to this one. The problem in free-video-editor appears for example with this code:

```
function global:au_GetLatest {
    $download_page = Invoke-WebRequest -Uri $releases
    $download_page.links # <--- BLOCKS HERE
```

**Comment by RedBaron2** [comment]
@majkinetor 
I bring up the past 
>  >    Besides it did help your 'AU' issue did it not? 

to show you --> refer to  _AU closed PR#35_
_**> It looks like this is fixed with your code so I will close it. If it reapears again I'll reopen.**_

Now for your AppVeyor issue.  How about this @majkinetor 
> Posted by Ilya Finkelshte... on Dec 02, 2016 @ 09:48 AM AppVeyor Support Staff 

> Please try to run one of the following in PowerShell before running your script:

> ```$IE=new-object -com internetexplorer.application```
> ```$IE.navigate2("https://cvs.khronos.org")```

> ```$HTTP_Request = [System.Net.WebRequest]::Create('https://cvs.khronos.org')```
> ```$HTTP_Response = $HTTP_Request.GetResponse()```

> Theory is that some intermediate certificate is not provided by the server and client should dynamically download it. This feature called AIA is not very good documented, I googled this simple explanation. So some SSL clients support it, some not. One of those calls (Internet Explorer based has better chance than .NET based one) should call this AIA thing and download that intermediate certificate. After this your script should feel itself the same way as on your local machine (where you opened that site number of times already).

> Please let us know if this helps.

> --ilya.

Your basic problem lies in what **ilya** says is a _**certificate**_ is missing. That is why it works for most sites and not for _**free-video-editor**_ or the OP _**cvs.khronos.org**_.

**Comment by majkinetor** [comment]
> to show you --> refer to AU closed PR#35

Irrelevant to this subject. Webclient is used there, not iwr.

> Your basic problem lies in what ilya says is a certificate is missing.

I highly doubt that.

But this is not a chatty issue. You help by providing actionable code, nothing else matters, no interpretations, no snippets no chat.  Code - working code on reference machine - is **the only thing** that proves or disproves any points you made here. Make the package work without `UseBasicParsing` and you fixed the problem.

**Comment by RedBaron2** [comment]
@majkinetor 
Might I suggest next time you ask for help you don't take everything as a criticism.
Now for the point of this so you don't get all huffy. 
I have a solution of making

> the package work without `UseBasicParsing` and you fixed the problem.

@gep13 @majkinetor 
--AppVeyor Output-
`Build started`
`git clone -q --branch=master https://github.com/RedBaron2/development.git C:\projects\development`
`git checkout -qf f6789c41b4e8b829c42a0c35e14a9bea03fafddb`
`Running Install scripts`
`Install-Product node $env:nodejs_version`
`Uninstalling node 4.6.2 (x86)...`
`Installing node 0.10.47 (x86)...`
`.\invoker.ps1`
`A version is -<STRONG slick-uniqueid="254">5.7.1</STRONG>-`
`B1 version is -5.7.1</STRONG>-`
`C version is -5.7.1-`
`Build success`
-Script invoker.ps1-
`function Test( $releases ) {`
`reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3" /t REG_DWORD /v 1A10 /f /d 0 | out-null`
`    #$releases = 'http://www.videosoftdev.com/free-video-editor/download'`
`    $download_page = Invoke-WebRequest -Uri $releases`
`$cpt=1  ` 
`$resu=@{}`
`$download_page.ParsedHtml.getElementsByTagname("p") |%{`
`    if ($_.id -eq $null){ $_.id="p$cpt";$cpt++}`
`    $resu[$($_.id)]=$_.innerHTML`
`}                                 `                                                      
`#$resu   `
`    $version = $resu.p4`
`    write-host A version is -$version-`
`    $version = $version -replace '<STRONG slick-uniqueid="\d\d\d">',''`
`    write-host B1 version is -$version-`
`    $version = $version -replace '</STRONG>',''`
`    write-host C version is -$version-`
`reg delete "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3" /v 1A10 /f | out-null`
`    $download_page.close`
`}`
`Test -releases 'http://www.videosoftdev.com/free-video-editor/download'`

Enjoy the Solution.

**Comment by majkinetor** [comment]
@RedBaron2 

> Might I suggest next time you ask for help you don't take everything as a criticism.
> Now for the point of this so you don't get all huffy.

Sorry, that was definitelly harsh from me (stressfull week on a job). 

Thx for the code, I will check it out soon.

**Comment by majkinetor** [comment]
Closed due to expiration. Unresolved.
