### ISSUE TITLE
Use /VERYSILENT with audacity

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#39]
https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/audacity/tools/chocolateyInstall.ps1#L5

**Comment by gep13** [comment]
:+1: nice one, thanks for getting that done!

**Comment by gep13** [comment]
Have you seen our huboard by the way?

https://huboard.com/chocolatey/chocolatey-coreteampackages

(Yes, I know it is not documented :smile:)

When you are picking up an issue from the backlog, can you move it through the various stages, and assign it to yourself, so that we know you are working it?  You will see I have done that with the PR's that I am working:

![image](https://cloud.githubusercontent.com/assets/1271146/5696850/c7c9d448-99d6-11e4-853e-c61b398a8626.png)

Thanks!

**Comment by Redsandro** [comment]
Didn't know! Looks like an old version of Trello but better Github integration.

This PR was closed while committing. As you might know, if you _fix #number_ in your commit message, the issue will automatically close. So in this specific case, doesn't the issue automatically move out of huboard?

-edit-

You can only have one assignee? I already like Trello with Zapbook better. :angel:

**Comment by gep13** [comment]
> You can only have one assignee? I already like Trello with Zapbook better

That is a limitation of GitHub issues, not of HuBoard.

> This PR was closed while committing. As you might know, if you fix #number in your commit message, the issue will automatically close. So in this specific case, doesn't the issue automatically move out of huboard?

Unfortunately not.  The way HuBoard works is that it uses labels assigned to an issue to track it's state.  In this case, this ticket still had ```Backlog``` assigned to it.

For another project I help out with we are using Zenboard, which is similar, but doesn't use the same labelling technique.  I am actually tempted to switch to Zenhub for this repo.  What are your thoughts:

https://www.zenhub.io/

**Comment by Redsandro** [comment]
Looks nicer.

My thoughts are: I'd prefer something that is integrated so well that a developer doesn't _have_ to use it. E.g. automatically moves closed issues to `done`.

I personally prefer not to have the overhead of closing issues twice especially when they are minor like this one, but it's nice to be able to sit down and have the overview such a board provides if one chooses to.

**Comment by Jeroen52** [comment]
And you can respond via email with github.

2015-01-12 21:28 GMT+01:00 Sander AKA Redsandro <notifications@github.com>:

**Comment by gep13** [comment]
> My thoughts are: I'd prefer something that is integrated so well that a developer doesn't have to use it. E.g. automatically moves closed issues to done.

I believe that this is what Zenhub does, let me enable it on this repo, and we can see what happens.

**Comment by gep13** [comment]
Ok, you can see the board here:

https://github.com/chocolatey/chocolatey-coreteampackages#boards

You will need to install the Chrome plugin for Zenhub, that is the one slight drawback with it, but an acceptable one, IMO.

**Comment by Jeroen52** [comment]
Once a board has been officially picked I might stuff some ideas and issues in them.

**Comment by gep13** [comment]
> Once a board has been officially picked I might stuff some ideas and issues in them.

No need to wait for that :smile_cat: Both Zenhub and HuBoard are driven by the issues list on GitHub, so feel free to add any issues that you think are required.

**Comment by gep13** [comment]
Issues list is here:

https://github.com/chocolatey/chocolatey-coreteampackages/issues

**Comment by ferventcoder** [comment]
There is also https://waffle.io/

**Comment by gep13** [comment]
> There is also https://waffle.io/

Yeah, I looked at that one, I didn't like it very much :-)  The thing I like about Zenhub is that it adds functionality to GitHub, seamlessly.  So you don't have to move to a different site to look at the board, it is right there, on the GitHub page.

**Comment by ferventcoder** [comment]
To github? Interesting.

**Comment by ferventcoder** [comment]
Those permissions though. Yikes!

**Comment by gep13** [comment]
> To github? Interesting.

Yes, with the plugin installed, it adds functionality to the page directly:

![image](https://cloud.githubusercontent.com/assets/1271146/5710642/c426fad0-9a9b-11e4-8f17-888671ba71ec.png)

Yeah, I thought about that, but I thought it was acceptable :-)
