### ISSUE TITLE
(nomacs) How should software get updated

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#395]
Perhaps switch to using Fosshub, as suggested in disqus comment:

https://chocolatey.org/packages/nomacs#comment-2997181741

**Comment by majkinetor** [comment]
I already did create it but at the end I found that versions are problematic:

- [Foshub](https://www.fosshub.com/nomacs.html) keep fixed file name for installer and versioned for portable
- [SourceForge](https://github.com/nomacs/nomacs/releases) doesn't have newer versions. 
- [Their history](http://download.nomacs.org/versions/) lists only portables
- [Github](https://github.com/nomacs/nomacs/releases) doesn't have binaries

Switch to portable package ? Keep only latest version ?

**Comment by majkinetor** [comment]
It looks that I can [get the repository](http://nomacs.org/unattended-installation/) and run silent from there. This makes Github page most appropriate I think.

**Comment by majkinetor** [comment]
Except that gihtub code is not the same as provided repository zip on above page.

**Comment by majkinetor** [comment]
So their 3.x installer is generic, it is proxy that always downloads latest version.

Portable version is completelly offline but only x64 bit. 

So versionless installer should be used I guess for this package and portable variant may be done as alternative.

**Comment by majkinetor** [comment]
Current package doesn't work correctly with proxy. Asked about unattended setup here:

https://www.nomacs.org/redmine/issues/765
