### ISSUE TITLE
vcredist2017: Visual C++ Redistributable for Visual Studio 2017

### ISSUE THREAD

**Issue by matbech** [chocolatey/chocolatey-coreteampackages#405]
It would be nice if somebody could add the vcredist2017 package (Visual C++ Redistributable for Visual Studio 2017) based on the Visual Studio 2015 package:
https://chocolatey.org/packages/vcredist2015

**Comment by AdmiringWorm** [comment]
vcredist2017 already exists: https://chocolatey.org/packages/vcredist2017

**Comment by matbech** [comment]
Yes, right. But the idea was to move it to chocolatey-coreteampackages repo so that it can be updated without depending on a single maintainer.

**Comment by AdmiringWorm** [comment]
@matbech to do that, you need to contact the maintainer @jberezanski

**Comment by gep13** [comment]
@matbech Yes, I have suggested to @jberezanski that he move those packages here.  I think he was up for doing that, but just needed to find some time to do it.

**Comment by jberezanski** [comment]
@gep13 I believe we talked about vcredist2015; as for 2017, I did not intend to move it here until RTM. Now that VS 2017 RC has a go-live license, however, I'll probably move vcredist2017 here as soon as I actually update the package to RC (i.e. in a couple of days).

**Comment by gep13** [comment]
@jberezanski sounds good to me! :+1:
