### ISSUE TITLE
The big ketarin machine is not updating anymore.

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey-coreteampackages#41]
I wanted to download the new [blender](https://chocolatey.org/packages/blender) by updating to 2.73, and noticed it only updates to 2.72.2.

I noticed the `chocolatey` user but the update is not available. 

1. Why doesn't *blender* update?
1. Does the big ketarin machine a name for referencing or should we give one?
1. Can we make packages show which user uploaded a certain version? (For example, I could see if the chocolatey user in fact did all the latest releases)

**Comment by TomOne** [comment]
The Ketarin machine isn’t updating anymore due to a bug in chocopkgup, which had to be updated due to the expiration date. On every update it overwrites the custom settings with the default ones.

I’ll fix the paths to make it work again later this day.

@ferventcoder are you aware of this bug?

**Comment by Redsandro** [comment]
I noticed this too. You have to re-add the API key. Not sure if that is (also) what you mean though.

**Comment by gep13** [comment]
@TomOne can you note exactly what is required to be done, in case I can get to this before you?  Thanks!

**Comment by TomOne** [comment]
@gep13, sorry, forgot to answer sooner.

I fixed it in the meantime. chocopkgup.exe.config had to be edited again to include the actual path:

```XML
<?xml version="1.0"?>
<configuration>
  <appSettings>
    <add key="PackagesFolder" value="c:\github\chocolatey-coreteampackages\automatic" />
    <add key="TokenReplaceFileSearchPattern" value="*.txt|*.nuspec|*.ps1|*.config" />
    <add key="PS1FileToExecute" value="ChocoPkgUp.ps1" />
  </appSettings>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0" />
  </startup>
</configuration>
```

This was missing in ketarinupdate.cmd because it was overwritten with the default ketarinupdate.cmd:
``` Batch
cd "C:\github\chocolatey-coreteampackages"
git pull

"Ketarin.exe" /database=C:\github\chocolatey-coreteampackages\jobs.db /silent /log=C:\ProgramData\chocolateypackageupdater\ketarin.%mydate%_%mytime%.log
```

**Comment by gep13** [comment]
@TomOne ah, yes, now I remember, I set that up :smile_cat: 

Thanks for getting this sorted out.
