### ISSUE TITLE
Move over PHP package

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#411]
There are quite a few enhancements and issues folks would like to see done with the PHP package. Can we move this into the core team repository so that it gets the love and attention that it deserves?

**Comment by majkinetor** [comment]
https://github.com/chocolatey/chocolatey-coreteampackages/pull/418

Please take a look and let us know when you remove it from your repository.

**Comment by ferventcoder** [comment]
Please look at enhancement issues and open PRs over at the orignal repo.

**Comment by ferventcoder** [comment]
I posted the issues to the PR instead.
