### ISSUE TITLE
Chocolatey FossHub Extension 0.4.0 seems to break compatibility with 0.2.0

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/chocolatey-coreteampackages#413]
Seems to break compatibility with 0.2.0, I haven't investigated fully. IrfanView package won't download now. (No, IrfanView didn't release a new ver.)
Does this still support two URLs for 32 and 64 bit?
I'm passing: $urlArray = $urlArray = @('https://www.fosshub.com/IrfanView.html/iview442_setup.exe','https://www.fosshub.com/IrfanView.html/iview442_x64_setup.exe') to it.

This is the result:
IrfanView v4.42.0.20161101 (forced) [Approved]
irfanview package files install completed. Performing other installation steps.
Could not find a part of the path 'C:\Users\bcurran\AppData\Local\Temp\chocolatey\IrfanView\4.42.0.20161101\cbtmqeco.ii5.istext'.

Download of cbtmqeco.ii5 (-1 B) completed.

Download of 0t4oqpx2.m4c (-1 B) completed.
Attempt to use original download file name failed for 'IrfanView.html'.
Copying irfanview
  from 'IrfanView.html'
Cannot find path 'C:\WINDOWS\system32\IrfanView.html' because it does not exist.
ERROR: Chocolatey expected a file to be downloaded to 'C:\Users\bcurran\AppData\Local\Temp\chocolatey\IrfanView\4.42.0.20161101\irfanviewInstall.exe' but nothing exists at that location.
The install of irfanview was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\IrfanView\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - irfanview (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\IrfanView\tools\chocolateyInstall.ps1'.
 See log for details.

C:\WINDOWS\system32>

**Comment by gep13** [comment]
@bcurran3 can you help me out here...

I don't think any of the versions of the fosshub extension included support for a URL Array.  Perhaps this "might" have worked, but I don't think that this was ever the intention 😢 

All the examples within the documentation for the method show a single url being passed in, and returned.

**Comment by bcurran3** [comment]
I swear .2 worked (for IrfanView and I think something else)!

 

But we definitely need a way to pass two URLs for x86/x64.

 

 

____  _ _ _ 

| __ )(_) | |

|  _ \| | | |

| |_) | | | |

|____/|_|_|_|

**Comment by gep13** [comment]
>@bcurran3 said...
I swear .2 worked (for IrfanView and I think something else)!

And it may very well have, but I don't think it was meant to :smile:

>@bcurran3 said...
But we definitely need a way to pass two URLs for x86/x64.

The workaround, for now, would be to call the function twice, once for each URL.

**Comment by bcurran3** [comment]
Hmmmmmmmmmmmmm, why didn’t I think of that? 

 

That I will do. (later)

 

 

____  _ _ _ 

| __ )(_) | |

|  _ \| | | |

| |_) | | | |

|____/|_|_|_|

**Comment by majkinetor** [comment]
Yes, that is the way function is used.

**Comment by gep13** [comment]
@bcurran3 said...
Hmmmmmmmmmmmmm, why didn’t I think of that?
That I will do. (later)

Perfect! 👍
