### ISSUE TITLE
reshack checksum mismatch

### ISSUE THREAD

**Issue by wjk** [chocolatey/chocolatey-coreteampackages#416]
I just tried updating reshack on my computer (from v4.2.5 to v4.5.28), and got the below error. Apparently the hashes don't match. I'm presuming that this is a bug, and not overriding the check for this reason. Can a fix be pushed? Thanks!

![choco screenshot](https://cloud.githubusercontent.com/assets/1915951/20644649/bd12ab70-b409-11e6-94e9-bee174c2f9b2.PNG)

**Comment by majkinetor** [comment]
That isn't a bug. Developer silently updated. Otherwise, it couldn't pass verifier.

**Comment by majkinetor** [comment]
New version is out - [report](https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e/238f88abc3243848bc7c1f14c4849de5c2623086#pushed)
