### ISSUE TITLE
(virtualbox) - Unfixed ferventcoder repository issues

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#423]
* [x] https://github.com/ferventcoder/chocolatey-packages/issues/132
* [x] https://github.com/ferventcoder/chocolatey-packages/issues/153

@ferventcoder

**Comment by majkinetor** [comment]
Added parameters.

I added [BeforeModify](https://github.com/chocolatey/chocolatey-coreteampackages/blob/fd01fd63e37322b0c6a20e9f212bd72e1c28318c/automatic/virtualbox/tools/chocolateyBeforeModify.ps1) but I can not test it as `vboxmanage` returns nothing on my system with parameter `runningvms` even tho I have running machines (vbox 5.1.10).

Adding extension remains to be done.

**Comment by majkinetor** [comment]
BTW, `oracle.cer` is expired.

**Comment by majkinetor** [comment]
After unpacking extension mentioned in ferventcoder/chocolatey-packages#132 doesn't exist. So I guess it has to be downloaded from the internet just as with package ferventcoder mentioned. 

We could deprecate that package and I can add downloader in the vbox package directkly, makes more sense.

This is the code I tried:

```powershell
Write-Host "Installing latest extension pack"
$installer_path = "$(Get-PackageCacheLocation)/VirtualBox*.exe"
& $installer_path --path (Split-Path $installer_path) --extract --silent
$ep = gi "$installer_path\*.vbox-extpack$"
if (!$ep) { Write-Warning "Can't find latest extension pack, it will not be installed"; return }

Set-Alias vboxmanage $installLocation\VBoxManage.exe
vboxmanage extpack install --replace $ep
```

**Comment by majkinetor** [comment]
@ferventcoder @gep13 @AdmiringWorm 

Will do this tonight, if you have any input until then let me know. If anybody can test  BeforeModify that would be awesome although it will not harm to stay even if it doesn't work.

**Comment by AdmiringWorm** [comment]
personally I think that since a package for the extension pack already exists, and it looks like it needs to downloaded it should stay as it is.
Not be included in the virtualbox package, be just be kept separate.

regarding the BeforeModify script, I can't seem to get it to run at all.
Not even after editing the nuspec file so it is actually added to the package.

**Comment by majkinetor** [comment]
> personally I think that since a package for the extension pack already exists, and it looks like it needs to downloaded it should stay as it is.

I don't like the fact that they may become unsynchronized and bring different versions.

**Comment by majkinetor** [comment]
> Regarding the BeforeModify script, I can't seem to get it to run at all. Not even after editing the nuspec file so it is actually added to the package.

@ferventcoder  ?

**Comment by AdmiringWorm** [comment]
> I don't like the fact that they may become unsynchronized and bring different versions.
true that is a problem of course, we could of course ask one of the maintainers if (s)he would be willing to add it to this repo, then both the core and the extension would be updated at the same time.
/cc @Iristyle @michaelray

**Comment by AdmiringWorm** [comment]
I managed to get the beforemodify script to run, but is getting hit by the following errors:

```
ERROR: At D:\ChocoInstall\lib\virtualbox\tools\chocolateybeforemodify.ps1:4 char:59
+ if (!($installLocation -and (Test-Path $installLocation)) { return }
+                                                           ~
Unexpected token '{' in expression or statement.

At D:\ChocoInstall\lib\virtualbox\tools\chocolateybeforemodify.ps1:4 char:59
+ if (!($installLocation -and (Test-Path $installLocation)) { return }
+                                                           ~
Missing closing ')' after expression in 'if' statement.
```

**Comment by majkinetor** [comment]
> true that is a problem of course, we could of course ask one of the maintainers if (s)he would be willing to add it to this repo, then both the core and the extension would be updated at the same time.

It can still get desync. It alraedy happened - Autohotkey virtual was pushed but at the same run ahk.install failed due to network problems....

**Comment by majkinetor** [comment]
> I managed to get the beforemodify script to run, but is getting hit by the following errors:

Another typo, fixed

**Comment by ferventcoder** [comment]
beforemodify is from OLD version. Only runs with `choco upgrade` and `choco uninstall`, but it is not run from the package you are updating ***to***, only the package you are updating ***from***

**Comment by ferventcoder** [comment]
> I don't like the fact that they may become unsynchronized and bring different versions.

Agreed!

**Comment by majkinetor** [comment]
> beforemodify is from OLD version. 

Great, didn't know that, documented anywhere the complete list of scripts ?

**Comment by ferventcoder** [comment]
Documented in choco new and https://chocolatey.org/docs/create-packages#during-which-scenarios-will-my-custom-scripts-be-triggered

**Comment by majkinetor** [comment]
I think I fixed all of the issues. Please take a look as this is very important package.

**Comment by ferventcoder** [comment]
Looks like you went backwards with the changes?

**Comment by majkinetor** [comment]
what do you mean ?
