### ISSUE TITLE
(php) Unfixed ferventcoder repository issues 

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#425]
- [x] https://github.com/ferventcoder/chocolatey-packages/issues/115
- [x] https://github.com/ferventcoder/chocolatey-packages/issues/90
- [x] https://github.com/ferventcoder/chocolatey-packages/issues/38

**Comment by ferventcoder** [comment]
Unfixed - what does that mean?

**Comment by majkinetor** [comment]
It means not fixed :)

**Comment by majkinetor** [comment]
You are tripping me about my english :) The word defintelly exists:

**unfixed**
**ʌnˈfɪkst/Submit**
adjective
not fixed, in particular:
not fixed in a definite place or position; unfastened; loose.
"the green cloth cover had become unfixed in a dozen places"
uncertain or variable.
"a being of unfixed gender"

**Comment by ferventcoder** [comment]
I get it now. Didn't catch the context at first. 

"php - open issues to address" is more normally used.

**Comment by AdmiringWorm** [comment]
I believe all of these are fixed now.
