### ISSUE TITLE
Force Test Build on AppVeyor

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#429]
@majkinetor you mentioned that this wasn't working, but I am not clear on exactly what you mean.

Looking at the history, I can see that it has been running, there are however, have been failures.

Can you confirm exactly what you mean?

**Comment by majkinetor** [comment]
Can you share the link of the AV project ?

**Comment by gep13** [comment]
@majkinetor sure thing...

https://ci.appveyor.com/project/chocolatey/chocolatey-coreteampackages-xnxcr

**Comment by majkinetor** [comment]
Looks like that commit https://github.com/chocolatey/chocolatey-coreteampackages/commit/11cb6ec8c49c735d5f96033afab74e270916a9e1 fixed it.

I also switched to use single group, it looks like its way faster then 1 hour limit to update all packages.
