### ISSUE TITLE
(firefox) Mozilla Maintenance Service

### ISSUE THREAD

**Issue by ebugusey** [chocolatey/chocolatey-coreteampackages#434]
This is a feature request.

As a user I want to disable installation of Mozilla Maintenance Service, because it's used only for updates and chocolatey handles that.

Possibly make it as a switch and disable installation of service by default.
https://wiki.mozilla.org/Installer:Command_Line_Arguments

**Comment by ferventcoder** [comment]
Typically we won't disable by default, because we want you to be as secure as possible by default - which means let the upgrades occur from the vendor - typically the vendor is closest to when that update will occur and an updated community package could trail by hours if not days or weeks.

But we would provide a package parameter to disable the updating if it's doable - that way it is opt in instead of opt out. HTH

**Comment by ebugusey** [comment]
Then at least this switch should be remembered for further updates.

**Comment by ebugusey** [comment]
And this policy sounds a little strange for me. Because in Linux there is no such thing as Mozilla Maintenance Service. Because you don't need it, you have repositories.

And on Windows it only needed to install updates without UAC approval.

**Comment by ferventcoder** [comment]
> Then at least this switch should be remembered for further updates.

Working on it - https://github.com/chocolatey/choco/issues/797

**Comment by ferventcoder** [comment]
> And this policy sounds a little strange for me. Because in Linux there is no such thing as Mozilla Maintenance Service. Because you don't need it, you have repositories.

Repositories/packages are the primary way of getting software on Linux. It's not the primary means of getting software on Windows. 

The policy is strange if you try to compare it to Linux. Looking at the Windows ecosystem, note that we've come a long way over the past five years with Chocolatey, and there are software vendors that do maintain Chocolatey packages now on the community repository, but the vast amount of maintainers currently are volunteers. The open source community in Windows has also come a long way, but it will be awhile before it is at a level like Linux (if ever - not a good or bad statement, just an awareness).

**Comment by majkinetor** [comment]
@AdmiringWorm, I assigned you because you are fresh with this. I would support all the available options.

**Comment by AdmiringWorm** [comment]
@majkinetor, that's fine although I'm not entirely sure about this one, since to support the parameters
it would require creating the ini file on the fly.
I'll look into it sometime in the coming days, but I'll add the up to grabs label until I do.

**Comment by majkinetor** [comment]
Anything wrong in creating ini on the fly?

**Comment by AdmiringWorm** [comment]
not really, I personally just don't like it.

**Comment by majkinetor** [comment]
WHat is the difference between Up for grabs and 1- Ready for work  ? @ferventcoder @gep13

**Comment by gep13** [comment]
All the labels with a number on them are to do with the agile tracking boards that are used on this repo.  I am not sure if they are actually still required or not.  @ferventcoder ?

Up for grabs is really used as an indication that this issue would be literally, up for grabs by a community member to work on.

**Comment by majkinetor** [comment]
I think those 2 mean the same thing. I would remove 'Up for grabs'.

1- Ready to work means nobody took it, but its aknowledge it needs to be done.

**Comment by gep13** [comment]
No, they are not the same thing at all.  One is used by the agile tracking boards (or at least used to me and it would automatically label the issue with it's progress through the board), and the other would be manually assigned by a user.

**Comment by majkinetor** [comment]
OK.

**Comment by majkinetor** [comment]
Closing as there is no interest in this for 6 mo.
