### ISSUE TITLE
(mkvtoolnix) Shims for executables

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#435]
> please make some shims for mkvmerge and mkvextract, so that they work from the command line
```

C:\ProgramData\chocolatey\tools\shimgen.exe -o="C:\ProgramData\chocolatey\bin\mkvextract.exe" -p="C:\Program Files\MKVToolNix\mkvextract.exe"
C:\ProgramData\chocolatey\tools\shimgen.exe -o="C:\ProgramData\chocolatey\bin\mkvinfo.exe" -p="C:\Program Files\MKVToolNix\mkvinfo.exe"
C:\ProgramData\chocolatey\tools\shimgen.exe -o="C:\ProgramData\chocolatey\bin\mkvmerge.exe" -p="C:\Program Files\MKVToolNix\mkvmerge.exe"
```

**Comment by majkinetor** [comment]
I created this because it is a general problem with many packages. They don't provide easy access that is typical in Linux world.

That is one of the reasons I created `Register-Application`  so that GUI apps are available both in WIN + R, windows start menu search and console (with adequate profile script).

We should standardize this behavior and provide guidelines - what do to PATH or shim. I generally use PATH if there are more then few apps (sysinternals, nirlauncher etc.) and shim for 1 or 2 apps in a package. This one falls somewhere in between.

What do you think @gep13 @AdmiringWorm

**Comment by AdmiringWorm** [comment]
personally I would prefer to shim them and not mess around with the path environment unless necessary (as in cases where a lot of cli programs is located in the same directory).

And for windows oriented people, there isn't that likely that they expect gui apps to available from the console (depending on the use case of the program).

**Comment by majkinetor** [comment]
I now realize that this **can completelly repalce shims**.

Currently with above mentioned profile script registered apps work in Posh. To have the same effect in cmd.exe (which is finally [not default shell anymore](http://www.theregister.co.uk/2016/11/18/windows_cmdexe_deposed_by_powershell/)) one can use `doskey`, a la:

    doskey srptool="c:\Program Files\Git\mingw64\bin\srptool.exe"

If chocolatey profile contains the said script and chocolatey installer adds [cmd.exe startup script](http://stackoverflow.com/a/17405182/82660) in registry that does the doskey stuff, we will cover all 3 worlds - powershell, cmd and Explorer.

Management of this stuff is also easier - even ccleaner and friends would remove invalid enteries while leftover shims will be deleted by no tool. You also can't know if shim actually shims correct application until you check it out personally in detail.

> And for windows oriented people, there isn't that likely that they expect gui apps to available from the console (depending on the use case of the program).

I don't use desktop, I start all the apps using either shell or WIN+R. Althought I might not be representative, that is irrelevant - good system should have this especially since it covers all grounds with the same code, plus it is an official way offered by MS instead of PATH. On linux the sistuation is the same - all apps register in console. Unified experience on multiple platforms is great feature.


cc @ferventcoder

**Comment by majkinetor** [comment]
Furthermore, both mechanisms can exist at the same time so package maintainer can choose. I think this is valuable. Implementing such a change is trivial.

**Comment by majkinetor** [comment]
I added to path since there are 5 apps in the package.

**Comment by AdmiringWorm** [comment]
I agree that this is valuable.

> On linux the sistuation is the same - all apps register in console

That's not entirely true, on linux there is also a path environment which quite often is set to `/usr/bin;/usr/local/bin` as a default (possibly more paths as well).
And since executables usually placed in the bin directory (or at least a script pointing to the executable), this works out of the box in such an environment.

**Comment by majkinetor** [comment]
> That's not entirely true

That is entirelly true, because underlying mechanism is not important. They don't have to put stuff in bin, no ? They chose to so to be available.

**Comment by majkinetor** [comment]
Moved discussion to https://github.com/chocolatey/choco/issues/1072

**Comment by ferventcoder** [comment]
Install-BinFile https://chocolatey.org/docs/helpers-install-bin-file
