### ISSUE TITLE
(everything) Migrate from user

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#443]
This is best tool in the world for searching and it belongs here. It requires modernization and checksum ATM. License allows redistribution so it should be embeded, especially given the very low size. 

I contacted maintainer to give ownership to chocolatey user. 

https://chocolatey.org/packages/Everything

**Comment by majkinetor** [comment]
@gep13 , user responded but doesn't know how, could you do it ? 

> Hi,
> 
> For some reason, I am not seeing this discussion in the Everything comments so I am emailing you directly.  I would be glad to add "Chocolatey" as a user to the repo for this package but I am not seeing "Chocolatey" as a Github username.  Can you please verify the Github ID.
>

**Comment by gep13** [comment]
@majkinetor sounds like they are trying to add a "chocolatey" user as an owner to the GitHub Repo where the source files for the Chocolatey Package resides.  I am assuming that you are talking about adding the chocolatey user as a co-maintainer on chocolatey.org, and then your intention is to move the Everything package over to the Core Team Repo, right?

**Comment by majkinetor** [comment]
Yeah.

BTW, this conversation took place several days back.

**Comment by gep13** [comment]
As long as you email him back to confirm exactly what is being done, I will go ahead and add the user as a co-maintainer.  A PR to his repo to remove the source files would also make sense, assuming you can find his repo, as it is not immediately obvious where that is.

**Comment by majkinetor** [comment]
> Date: Wed, 7 Dec 2016 12:27:59 +0100
> Message-ID: <CAB6nfs4GNWGNhin-sp2sPFcbjZCSDqV-oK-zGnJ92TmFx-mU=A@mail.gmail.com>
> Subject: Re: [Chocolatey.org] Message for maintainers of the package 'Everything'
> From: Miodrag Milic <***************>
> To: Mark Michaelis <*****************>
> Content-Type: multipart/alternative; boundary=047d7bfcfb9226d16b05430fd0a6
> 
> 
> Choco moderators added chocolatey user as maintainer.
> Please remove the package from your automatic routines.
