### ISSUE TITLE
(smartftp)  A stable release of a package should not have on a prerelease dependency

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#445]
Updater currently doesn't work ([report](https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e/9b1e876407d096898f1e2dc52d28c3df7909980c#errors)).

This is complete output

```
smartftp - checking updates using au version 2016.12.5.60754
URL check
  https://www.smartftp.com/get/SmartFTP64.msi
  https://www.smartftp.com/get/SmartFTP86.msi
nuspec version: 8.0.2271.0
remote version: 8.0.2272.0
New version is available
Automatic checksum started
Downloading smartftp 32 bit
  from 'https://www.smartftp.com/get/SmartFTP86.msi'

Download of SmartFTP.msi (16.81 MB) completed.
Package downloaded and hash calculated for 32 bit version
Downloading smartftp 64 bit
  from 'https://www.smartftp.com/get/SmartFTP64.msi'

Download of SmartFTP.msi (18.45 MB) completed.
Package downloaded and hash calculated for 64 bit version
Updating files
  $Latest data:
    Checksum32      (String)    fbdce2c27defff5c1145fde6eea721cac9b71b6696482f4ef0525836b1512f5b
    Checksum64      (String)    876fac48777818bce1e169a311ff1a5eb18b126588446032e26c4552ebef9897
    ChecksumType32  (String)    sha256
    ChecksumType64  (String)    sha256
    FileType        (String)    msi
    NuspecVersion   (String)    8.0.2271.0
    PackageName     (String)    smartftp
    URL32           (String)    https://www.smartftp.com/get/SmartFTP86.msi
    URL64           (String)    https://www.smartftp.com/get/SmartFTP64.msi
    Version         (String)    8.0.2272.0

  smartftp.nuspec
    setting id:  smartftp
updating version: 8.0.2271.0 -> 8.0.2272.0
  .\tools\chocolateyInstall.ps1
    (?i)(^\s*url\s*=\s*)('.*') = $1'https://www.smartftp.com/get/SmartFTP86.msi' 
    (?i)(^\s*fileType\s*=\s*)('.*') = $1'msi' 
    (?i)(^\s*packageName\s*=\s*)('.*') = $1'smartftp' 
    (?i)(^\s*checksum64\s*=\s*)('.*') = $1'876fac48777818bce1e169a311ff1a5eb18b126588446032e26c4552ebef9897' 
    (?i)(^\s*url64bit\s*=\s*)('.*') = $1'https://www.smartftp.com/get/SmartFTP64.msi' 
    (?i)(^\s*checksum\s*=\s*)('.*') = $1'fbdce2c27defff5c1145fde6eea721cac9b71b6696482f4ef0525836b1512f5b' 
Attempting to build package from 'smartftp.nuspec'.
A stable release of a package should not have on a prerelease dependency. Either modify the version spec of dependency "vcredist2017 (≥ 14.10.24629.0-rc1)" or update the version field.

```

**Comment by matbech** [comment]
@majkinetor What do you propose? We can make vcredist2017-rc1 a stable release or SmartFTP a pre-release. I believe we should do the former since vcredist2017 is considered production ready (go live license).

**Comment by jberezanski** [comment]
"considered production ready" != stable.
Where does that error come from?

**Comment by majkinetor** [comment]
`choco pack` fails.

**Comment by jberezanski** [comment]
OK, I've been thinking about this a bit. If vcredist2017 were a completely new library, I'd probably agree to remove the prerelease suffix. This is not the case, however: vcredist2017 is an incremental, in-place upgrade of the same DLL that had been released as vcredist2015 (msvcp140.dll). That DLL is dependent upon by a lot of software. I would not want folks to get upgraded to vcredist2017 RC without them being fully aware that this is not a final, official release, there may be bugs in it and some applications may break.

That is why I believe the best course of action would be either to make SmartFTP a pre-release, if it really needs to depend on msvcp140 14.10.*, or make it depend on vcredist2015, if it is able to work with that.

**Comment by majkinetor** [comment]
Can we return it to vcredist2015 then ?

**Comment by matbech** [comment]
@majkinetor I'm against it. SmartFTP is compiled with Visual Studio 2017 RC and linked against the 2017 libraries.

**Comment by majkinetor** [comment]
I will disable AU for smartftp (prepending _ to update.ps1). We don't want it to spam errors indefinitelly. 
When you find a solution for this just PR file rename to enable it again.

**Comment by majkinetor** [comment]
Didn't rename it but make ./update.ps1 return special keyword 'ignore'.

**Comment by majkinetor** [comment]
https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e#smartftp

**Comment by AdmiringWorm** [comment]
@matbech any thoughts on changing the dependency for smartftp to use the [vcredist140](https://chocolatey.org/packages/vcredist140/14.0.24215.1) package?
This would mean by default it would install vcredist2015 until a stable version of vcredist2017 is released (unless a user installs it using `--pre` argument)

**Comment by matbech** [comment]
@AdmiringWorm The release of VS 2017 is imminent (6th March), in a week we do have the final release of vcredist2017.

**Comment by AdmiringWorm** [comment]
@matbech Yeah, I know.
I was asking purely because the package isn't updating now because of the pre-release dependency, but would work if adding a dependency on vcredist140, then we could just updated the dependency version when the stable release of vcredist2017 have been submitted on chocolatey.
