### ISSUE TITLE
Overlapping functions in chocolatey-core.extension and mm-choco.extension need more thought

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#454]
https://chocolatey.org/packages/virtualbox#comment-3040800131

If there are, you need to ensure that chocolatey-core.extension wins.

**Comment by ferventcoder** [comment]
@majkinetor @AdmiringWorm FYI

**Comment by majkinetor** [comment]
mm-choco.extension is now completelly contained in chocolatey-core.extension and I will deprecate it ASAP.

**Comment by ferventcoder** [comment]
Cool, so the answer is yes, you do need to account for the fact that folks may have that extension installed.

**Comment by ferventcoder** [comment]
mm-choco is currently after chocolatey-core in the alphabet, so all functions in the other package win and override the same ones in chocolatey-core. 

Typically you would set an alias for the ones you want to win.

**Comment by ferventcoder** [comment]
> Typically you would set an alias for the ones you want to win.

This is not meant to always be used, as it is a heavy handed approach. It should only be used in cases where this could occur.

**Comment by majkinetor** [comment]
https://chocolatey.org/packages/mm-choco.extension/0.0.4.1

I am not sure if people will have to explicitelly uninstall it now

**Comment by ferventcoder** [comment]
The problem was the versionless or minimum version installed dependencies from other packages. Anyone coming along now or upgrading all will be put in a good place.

This is one of the reasons I drug my feet in ever documenting extensions, because they do require a lot of upfront thought sometimes in planning whether a function should be loaded or not.

**Comment by ferventcoder** [comment]
Like checking to see if a command is already available and only loading the function is not already loaded by other means (an automatic deprecation to functions that are later built into newer Chocolatey versions).

**Comment by majkinetor** [comment]
core extension actually does this. It wont load if its already available.

**Comment by ferventcoder** [comment]
It's trickier when you move functions from one extension into another. You have to consider all scenarios and try to provide the best experience to lower a user's issues. I tend to prefer having no hard to determine issues. Like this one. It may not be obvious at first (it certainly wasn't to me until I thought about it).

**Comment by ferventcoder** [comment]
I just looked through the code in core extension and I don't see this at all. Can you point me to the code that does something like this:

https://github.com/ferventcoder/chocolatey-packages/blob/f22175b28804dfa9bddbf07edadf08a77c6d7b78/manual/pik/tools/chocolateyInstall.ps1#L7-L10

**Comment by ferventcoder** [comment]
What I'm specifically looking for is this:

https://github.com/chocolatey/chocolatey-coreteampackages/pull/456/files

**Comment by ferventcoder** [comment]
HTH

**Comment by majkinetor** [comment]
I beleive that is not needed due to the:

https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/extensions/chocolatey-core.extension/extensions/chocolatey-core.psm1#L5-L9

**Comment by majkinetor** [comment]
I will  test that code again.

**Comment by majkinetor** [comment]
I tested this up and it behaves correctly:

test.psm1

```
function Register-Application() {
    Write-Host 'DUMMY REGISTER-APPLICATION'
}
Export-ModuleMember -Function *
```


```
> import-module .\test.psm1
> Register-Application
DUMMY REGISTER-APPLICATION
> import-module C:\ProgramData\chocolatey\extensions\chocolatey-core\chocolatey-core.psm1
> Register-Application
DUMMY REGISTER-APPLICATION
```

The code in psm1 is WAY better then putting that smelly code infront of every function. 

The problem with OP was not of this nature anyway - mm-choco.extension didn't have this mechanism as it was following how other extensions are implemented and it was loaded after core. I made psm1 of Core extension differently for a reason.

I will close this and and PR if there is nothing more to add.

**Comment by ferventcoder** [comment]
I agree it is much better to do it in a single place rather than carry it in every function. From rereading the code, I finally understand what it is doing. I'd almost prefer it was explained better so folks not as well versed in PowerShell can reason about it. 

From my stance, I've never preferred what I call write one read never code (like perl). I'm not saying you are doing that here, it's just hard to reason about what the code is doing until you understand `Compare-Object` and it's output.

**Comment by majkinetor** [comment]
True. I myself didnt asap understand it after a year or so. Will add decription in comment. Thx.
