### ISSUE TITLE
(cygwin) --no-admin option

### ISSUE THREAD

**Issue by furlongm** [chocolatey/chocolatey-coreteampackages#457]
Would it be possible to add the --no-admin switch for installing cygwin without admin privileges?

**Comment by majkinetor** [comment]
Chocolatey requires admin access in general however - it needs write access to its `C:\ProgramData\Chocolatey\lib`. It would require non admin install.

Also, currently every future update would revert this behavior as chocolatey ATM doesn't remember parameters.

**Comment by majkinetor** [comment]
But adding:

```

-B --no-admin                     Do not check for and enforce running as
                                   Administrator
```

is a one line of code anyway. I can do that any time but you need to have non admin chocolatey installation.

**Comment by furlongm** [comment]
I have a non admin chocolately installation that seems to work, somehow I have write access to C:\ProgramData.

**Comment by majkinetor** [comment]
Could you test it up, I didn't push it yet. 
You will have to download it from repository and cpack it then install it from the dir. I don't have admin install and wont push it without single test.

**Comment by furlongm** [comment]
The parameters don't seem to get passed in for me. Any of them, not just the /NoAdmin one.

Is this the correct way to pass package parameters?

> choco install -v -y -f Cygwin.2.6.0.20161207.nupkg --source %cd% --params='"/NoAdmin"'

**Comment by majkinetor** [comment]
I use this one:

`choco install -y  cygwin --source . --params='"/NoAdmin"`

**Comment by majkinetor** [comment]
You have extra "

**Comment by ferventcoder** [comment]
@furlongm @majkinetor `"'/NoAdmin'"`

**Comment by majkinetor** [comment]
Both seem to work with my helper func:

```
master~>     Get-PackageParameters "/NoAdmin" ; Get-PackageParameters "'/NoAdmin'"

Name                           Value
----                           -----
NoAdmin                        True
NoAdmin                        True
```
