### ISSUE TITLE
(LibreOffice) The package names do not respect the guidelines from upstream

### ISSUE THREAD

**Issue by wget** [chocolatey/chocolatey-coreteampackages#458]
Hello all,

Wrt. the issue I raised to you via the website chocolatey.org, @gep13 asked me to follow the discussion here.

My issue was that the Chocolatey package name (`libreoffice` and `libreoffice-oldstable`) were not respecting the upstream naming convention which are respectively (`libreoffice-fresh` and `libreoffice-still`).

Even if I was against the names -fresh and -still when this has been discussed at the Document Foundation, I think me need to respect their decisions.

I'm maintaining some packages for some GNU/Linux distributions. As a package maintainer (this also apply to Chocolatey packagers, since we are basically all package maintainers), we need to respect the upstream names as much as we can.

In order to keep the upstream official names, would it be possible for you to respect the package names libreoffice-fresh and libreoffice-still for the current and respectively old stable releases?

Since this package is now used by a bunch of people (+181k users), maybe aliasing would be better instead of renaming.

Let me know your intentions. ;-)

**Comment by gep13** [comment]
@wget as chocolatey currently stands, the concept of aliases isn't fully there.  Instead, I think what is needed in this case would be to deprecate the existing packages, in favour of a package with the new names.

As per this:

https://chocolatey.org/docs/how-to-deprecate-a-chocolatey-package

Would you be interested in helping with a PR for this?  I can help with actually unlisting of the package versions when required.

**Comment by wget** [comment]
Ok will do.

**Comment by AdmiringWorm** [comment]
@wget any update on this?

**Comment by wget** [comment]
@AdmiringWorm I [proposed a PR here](https://github.com/chocolatey/chocolatey-coreteampackages/pull/528).

**Comment by wget** [comment]
It has been discussed the packages need to migrate to AU and provide 64 bits (as they are available) in order to be pushed. /me Taking care of it.

**Comment by majkinetor** [comment]
@wget any news on this ?

**Comment by majkinetor** [comment]
Closing due to no feedback

**Comment by AdmiringWorm** [comment]
I have just pushed out the packages:
[libreoffice-fresh](https://chocolatey.org/packages/libreoffice-fresh) and [libreoffice-still](https://chocolatey.org/packages/libreoffice-still).
And will be deprecating the original packages when those are approved.
