### ISSUE TITLE
(virtualbox) Add a 5.0 branch

### ISSUE THREAD

**Issue by shirokatze** [chocolatey/chocolatey-coreteampackages#462]
Heya.
I've chatted with Gary via email, and they requested me to raise a suggestion here.

So currently VirtualBox has two actively maintained versions, 5.0 and 5.1, which can be seen here at https://www.virtualbox.org/wiki/Download_Old_Builds .  Revently I've encountered some issues in 5.1 that forced me to use the 5.0 branch.

I suggest something like virtualbox-5.0 so that people can get the latest 5.0 branch without manually specifying --version.

I believe it's achievable with something called virtual package, just like python?

**Comment by majkinetor** [comment]
https://github.com/majkinetor/au/issues/56

**Comment by majkinetor** [comment]
See AU topic for details.

[Virtualbox](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/virtualbox) example:

1. `cp automatic/virtualbox automatic/virtualbox5`
1. `mv automatic/virtualbox5/virtualbox.nuspec automatic/virtualbox5/virtualbox5.nuspec`

In ./update.ps1 in `au_GetLatest`:

```powershell
function global:au_GetLatest {
    ....
    @{
        .....
        PackageName = 'virtualbox'
    }
}
```

This ofcourse keeps the package name the same but updates different version.

**Comment by ferventcoder** [comment]
Sweet - the only thing I might add is the current maintained versions are 5.0.x and 5.1.x. virtualbox5 might be a tad confusing. Does virtualbox_5.0.x make more sense? Also looking for a tiny difference that immediately identifies this as maintaining multiple versions of the same package (the "_" bit).

**Comment by ferventcoder** [comment]
Is the nuspec required to be copied over or does it just need a folder with the update.ps1  file?

**Comment by ferventcoder** [comment]
Oh wait, I see - to see version?

It's not completely clear to me which nuspec would actually be used to build the package - I'm guessing the one in this folder should be used?

Or would it be best to just copy it all over here and it builds and ships what is in this folder? This will reduce complexity for folks and allow making things different in the install scripts when necessary. It is a bit of duplication, but in the sense that we are maintaining two or more versions of the same package in tandem I think that is acceptable. It's duplication to reduce complexity and contextual overhead to understand what is going on.

**Comment by ferventcoder** [comment]
Just read the au issue - looks like we are in agreement!

Was confused by your instructions here about moving the nuspec, but I didn't read it right I see. I am almost of the mindset that the folder names are the only real difference. The nuspec file could still be slthe same. Reporting could be interesting for AU. Have you seen how that plays out yet?

**Comment by majkinetor** [comment]
> virtualbox5 might be a tad confusing. Does virtualbox_5.0.x make more sense?

The above setup is to use **the same package name**. So it would push as virtualbox and must be installed using `cinst -version`. 

If you want completelly new package then you don't need to consider instruction about `au_getLatest` and just treat it as any other package.

**Comment by majkinetor** [comment]
My personal position about it is that it should use the same package name. 

However, the problem with that is that it would update with `cup all` unless pinned and updated manually to explicit version each time.

**Comment by majkinetor** [comment]
Maybe this situation deserves some attention on the client side. Perhaps a choco could allow for individual package settings for update. In this case we could set that updates are allowed only within specific range etc. This could also contain for example default parameters for update etc.

**Comment by ferventcoder** [comment]
>> virtualbox5 might be a tad confusing. Does virtualbox_5.0.x make more sense?

>The above setup is to use the same package name. So it would push as virtualbox and must be installed using cinst -version.

I meant the name of the folder. Not `virtualbox5`, but `virtualbox_5.0.x`. If you have a folder structure with

* virtualbox
* virtualbox5

as a consumer, committer and/or contributor, which one of those has 5.1.x and which has 5.0.x?

That's why a suggestion of 

* virtualbox
* virtualbox_5.0.x

as the folder structure so it's obvious immediately which one is which. The underscore is also a dead giveaway for someone who knows that this equates to multiple versions of the same package being maintained in tandem.

**Comment by ferventcoder** [comment]
> My personal position about it is that it should use the same package name.

I agree here completely.

> However, the problem with that is that it would update with cup all unless pinned and updated manually to explicit version each time.

> Maybe this situation deserves some attention on the client side. Perhaps a choco could allow for individual package settings for update. In this case we could set that updates are allowed only within specific range etc. This could also contain for example default parameters for update etc.

This is a good idea - similar to locking down client side in a packages.config that you can do in straight NuGet. Do you want to write up the ticket?

**Comment by majkinetor** [comment]
> Do you want to write up the ticket?

sure, I'll just think a bit more on it and then ticket it.

Regarding this branch, we accept PR's (I am personally not interested).

**Comment by AdmiringWorm** [comment]
I'm look ing into this now
