### ISSUE TITLE
(virtualbox & vlc) Substring error on package upgrades

### ISSUE THREAD

**Issue by michaelray** [chocolatey/chocolatey-coreteampackages#465]
With the recent changes, I'm now getting this error when trying to upgrade the virtualbox package and the vlc package:

ERROR: Exception calling "Substring" with "1" argument(s): "startIndex cannot be larger than length of string.
Parameter name: startIndex"

Here are the gists from my upgrade attempts:

virtualbox (from v5.1.10 to v5.1.10.20161207):
https://gist.github.com/michaelray/41332926fd5b16494f0264c080e6b2a1

vlc (from v2.2.4 to v2.2.4.20161210):
https://gist.github.com/michaelray/0077afc22a3dfcb6ae4638d7f7602a63

**Comment by majkinetor** [comment]
This must be the error in chocolatey-core.extension then and specifically with `Get-PackageParameters` which was the last changed and used within both packages:

```
function Get-PackageParameters([string] $Parameters = $Env:ChocolateyPackageParameters) {
    $res = @{}
    $re = "\/([a-zA-Z]+)(:([`"'])?([a-zA-Z0-9- _\\:\.]+)([`"'])?)?"
    $results = $Parameters | Select-String $re -AllMatches | select -Expand Matches
    foreach ($m in $results) {
        $a = $m.Value -split ':'
        $opt = $a[0].Substring(1); $val = $a[1..100] -join ':'
        if ($val -match '^(".+")|(''.+'')$') {$val = $val -replace '^.|.$'}
        $res[ $opt ] = if ($val) { $val } else { $true }
    }
    $res
}
```

I am can not reproduce this however. As far as I can see you installed it without parameters. 

My tests are passing:


Without parameters:

PS C:\work\_chocolatey\chocolatey-coreteampackages\automatic\vlc> Test-Package
Package info
  Path:         C:\work\_chocolatey\chocolatey-coreteampackages\automatic\vlc\vlc.2.2.4.20161210.nupkg
  Name:         vlc
  Version:      2.2.4.20161210
  Vagrant:      c:\work\_chocolatey\chocolatey-test-environment

```
==> default:
==> default: Running provisioner: shell...
    default: Running: shell/TestPackages.ps1 as c:\tmp\vagrant-shell.ps1
==> default: ============================================================
==> default: TESTING FOLLOWING PACKAGES: vlc:2.2.4.20161210
==> default: ============================================================
==> default:
==> default: ------------------------------------------------------------
==> default: PACKAGE: vlc:2.2.4.20161210
==> default: OPTIONS: c:\packages\vlc.2.2.4.20161210.xml
==> default:
==> default: Name                           Value
==> default: ----                           -----
==> default: Install                        True
==> default: Uninstall                      False
==> default: Parameters
==> default: ------------------------------------------------------------
==> default: TESTING INSTALL FOR vlc:2.2.4.20161210
==> default:
==> default: CMD: choco install -fy vlc --allow-downgrade --version 2.2.4.20161210 --source "'c:\packages;http://chocolatey.org/api/v2/'"
==> default: Chocolatey v0.10.3
==> default: Installing the following packages:
==> default:
==> default: vlc
==> default: By installing you accept licenses for the packages.
==> default: vlc v2.2.4.20161210 (forced)
==> default: vlc package files install completed. Performing other installation steps.
==> default: Installing x64 bit version
==> default:
==> default: Installing vlc...
==> default: vlc has been installed.
==> default: vlc installed to 'C:\Program Files\VideoLAN\VLC'
==> default:
==> default: vlc registered as vlc
==> default:  The install of vlc was successful.
==> default:
==> default:   Software installed to 'C:\Program Files\VideoLAN\VLC'
==> default:
==> default: Chocolatey installed 1/1 packages. 0 packages failed.
==> default:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
==> default: Exit code for vlc:2.2.4.20161210 was 0
```

**Comment by majkinetor** [comment]
This was not update tho, but install...

**Comment by majkinetor** [comment]
Tried upgrade now, the same results.

**Comment by ferventcoder** [comment]
Do it from PowerShell v2. See what you get.

**Comment by ferventcoder** [comment]
My guess is that because it doesn't provide a line where the issue occurred, it might be something in what it was loading.

**Comment by majkinetor** [comment]
Yup, its 2.0 phenomena:

```
PS> powershell -Version 2
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.

PS> function Get-PackageParameters([string] $Parameters = $Env:ChocolateyPackageParameters) {
>>     $res = @{}
>>     $re = "\/([a-zA-Z]+)(:([`"'])?([a-zA-Z0-9- _\\:\.]+)([`"'])?)?"
>>     $results = $Parameters | Select-String $re -AllMatches | select -Expand Matches
>>     foreach ($m in $results) {
>>         $a = $m.Value -split ':'
>>         $opt = $a[0].Substring(1); $val = $a[1..100] -join ':'
>>         if ($val -match '^(".+")|(''.+'')$') {$val = $val -replace '^.|.$'}
>>         $res[ $opt ] = if ($val) { $val } else { $true }
>>     }
>>     $res
>> }
>>
PS > Get-PackageParameters
Substring : Exception calling "Substring" with "1" argument(s): "startIndex cannot be larger than length of string.
Parameter name: startIndex"
At line:7 char:31
+         $opt = $a[0].Substring <<<< (1); $val = $a[1..100] -join ':'
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

[ : Index operation failed; the array index evaluated to null.
At line:9 char:14
+         $res[ <<<<  $opt ] = if ($val) { $val } else { $true }
    + CategoryInfo          : InvalidOperation: (System.Collections.Hashtable:Hashtable) [], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex

```

**Comment by majkinetor** [comment]
I am in the process of creating Win7 vagrant environment with Posh2 for testing so those kind of errors should be more visible then.

Anyway, this must be Posh 2.0 bug because this works (comment  `<--- ADDED THIS LINE` )

```powershell
function Get-PackageParameters([string] $Parameters = $Env:ChocolateyPackageParameters) {
    $res = @{}
    $re = "\/([a-zA-Z]+)(:([`"'])?([a-zA-Z0-9- _\\:\.]+)([`"'])?)?"
    $results = $Parameters | Select-String $re -AllMatches | select -Expand Matches
    foreach ($m in $results) {
        if (!$m) {continue}    # <--- ADDED THIS LINE
        $a = $m.Value -split ':'
        $opt = $a[0].Substring(1)
	$val = $a[1..100] -join ':'
        if ($val -match '^(".+")|(''.+'')$') {$val = $val -replace '^.|.$'}
        $res[ $opt ] = if ($val) { $val } else { $true }
    }
    $res
}
```

Get-PackageParameters

**Comment by ferventcoder** [comment]
I can hook you up with a Windows 2008 R2 vagrant image.

**Comment by majkinetor** [comment]
@michaelray , could you please test it on your system ? 

Open by hand the file `Get-PackageParameters.ps1` on your system and add above line then try again.

**Comment by majkinetor** [comment]
> I can hook you up with a Windows 2008 R2 vagrant image.

What will that achieve ?

I am making single vagrant environment for all windows systems. It should be runnable via 

      Test-Package -OSVersion <win7/win10/....>

or directlly using env vars.   When I finish that I can hook up that box into it.

**Comment by ferventcoder** [comment]
> I am in the process of creating Win7 vagrant environment with Posh2 for testing so those kind of errors should be more visible then.

I assumed this mean you were also setting up a Win7 box. Win 7 == Win 2008 except for Server vs Client.

**Comment by majkinetor** [comment]
> Win 7 == Win 2008

You are right. Send it over.

**Comment by ferventcoder** [comment]
I am uploading the boxes now to https://atlas.hashicorp.com/ferventcoder/boxes/win2008r2-x64-nocm/ - the released version will be v1.0.1

**Comment by majkinetor** [comment]
Thx @ferventcoder

**Comment by majkinetor** [comment]
I updated extension and source code of tools that use it but didn't push all of the affected tools, those will resolve on next update. Currently you can manually update `chocolatey-core.extension` and it should work.

**Comment by michaelray** [comment]
Adding the continue line to Get-PackageParameters did the trick.  I was able to upgrade with that line added.

**Comment by majkinetor** [comment]
thx for the feedback @michaelray .
