### ISSUE TITLE
(qtox) Should be manually bump the nuspec version

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#467]
https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e

Not sure why this is raising it's head now.  But looks like 1.5.1 is already pushed to chocolatey.org, but the nuspec version is still at 1.4.1.1.

Thoughts? @AdmiringWorm

**Comment by majkinetor** [comment]
I saw it and can't understand how that happened. With existing version qtox should return that there is no update unless if it is forced which it was not. 

So it was like `NoCheckChocoUrl` was present.

**Comment by AdmiringWorm** [comment]
I wonder if perhaps an exception occurred when au tried to check the hosted version,
if so au would probably just think it doesn't exist.
We could just bump the version, but I would like to see if it happens again during the next build run.

**Comment by majkinetor** [comment]
> I wonder if perhaps an exception occurred when au tried to check the hosted version,
if so au would probably just think it doesn't exist.

Highly unlikely as exception would be thrown. I will retest this part anyway.

> We could just bump the version, but I would like to see if it happens again during the next build run.

That isn't needed:

```
qtox - checking updates using au version 2016.12.12.120845
URL check
  https://github.com/qTox/qTox/releases/download/v1.5.1/setup-qtox-64.exe
  https://github.com/qTox/qTox/releases/download/v1.5.1/setup-qtox.exe
nuspec version: 1.4.1.1
remote version: 1.5.1
New version is available but it already exists in the Chocolatey community feed (disable using $NoCheckChocoVersion):
  https://chocolatey.org/packages/qtox/1.5.1
```

**Comment by AdmiringWorm** [comment]
> Highly unlikely as exception would be thrown. I will retest this part anyway.

not if it happened here:
https://github.com/majkinetor/au/blob/master/AU/Public/Update-Package.ps1#L331

Since you're catching any thrown exception and ignoring it while checking if the package+version exists on chocolatey.

**Comment by majkinetor** [comment]
You are right. That is definitelly what happened. I guess we could ignore this or I could add connection timeout special handling and catch 404.

**Comment by majkinetor** [comment]
Will close it here, reported it on AU.

It doesn't matter much anyway, it will report timeout error or push error.

**Comment by AdmiringWorm** [comment]
I don't really see this happening too often, so personally I don't see the value of adding anything to catch 404 errors specifically (or timeout).

**Comment by gep13** [comment]
@majkinetor @AdmiringWorm do we still need to bump the nuspec version to match what is actually pushed to chocolatey.org, or has that already been done?

**Comment by majkinetor** [comment]
No it has not been done. There are several packages that do not mach, so its not a big deal I guess. It will resolve on the next update probably.

This could be synced by some script periodically or something or we can just ignore it for now.
