### ISSUE TITLE
(visualstudiocode) 'Get-PackageParameters' is not recognized

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-coreteampackages#472]
The Visual Studio Code package currently throws the following error:

```
The term 'Get-PackageParameters' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by pascalberger** [comment]
@majkinetor Any idea what's causing this? Running `update.ps1` works for me locally

**Comment by majkinetor** [comment]
Lets get redistribution rights for this ...

**Comment by pascalberger** [comment]
@majkinetor I asked for permission at the VsCode repo: https://github.com/Microsoft/vscode/issues/17283. But wouldn't have helped with this issue :)

**Comment by majkinetor** [comment]
It would because then automatic checksum can be disabled.

**Comment by AndrewSav** [comment]
Why am I still getting this error, if it's fixed? Do I need to update something (what?) somewhere (where?)?

**Comment by john1726** [comment]
If you want to have powershell load the choco APIs by default so you can test calling chocolateyInstall.ps1 directly then execute this command:

`choco install chocolateypowershell -y`

Next double-click the ChocolateyPowerShell shortcut on your desktop to open a powershell with choco APIs enabled. See https://community.chocolatey.org/packages/chocolateypowershell

**Comment by john1726** [comment]
If you want to have powershell load the choco APIs by default so you can test calling chocolateyInstall.ps1 directly then execute this command:

`choco install chocolateypowershell -y`

Next double-click the ChocolateyPowerShell shortcut on your desktop to open a powershell with choco APIs enabled. See https://community.chocolatey.org/packages/chocolateypowershell
