### ISSUE TITLE
(mkdocs-material) Only create package if release is pushed to PyPi

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-coreteampackages#481]
The mkdocs-material package currently checks GitHub releases for update. They are not necessarily pushed to Python Package Index. This happened with 1.0.0-beta (https://github.com/chocolatey/chocolatey-coreteampackages/commit/94604dadc1e6a387304ec13453eb61a8dbaf54b5)

**Comment by majkinetor** [comment]
This will be marked as prerelease on chocolatey so I think this is probably good thing.

**Comment by pascalberger** [comment]
The problem is that it was not pushed to Python Package Index (see https://pypi.python.org/pypi/mkdocs-material/) from where the package tries to install.

**Comment by pascalberger** [comment]
I unlisted https://chocolatey.org/packages/mkdocs-material/1.0.0-beta on Chocolatey and will create a PR for an improved AU script.
