### ISSUE TITLE
(notepadplusplus) IconUrl is wrong

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#498]
https://github.com/chocolatey/chocolatey-coreteampackages/blob/edcff7ffc5e59d7ad2ff170987d5b7b4d0fb4195/automatic/notepadplusplus/notepadplusplus.nuspec#L36

It should point to the result of https://raw.githubusercontent.com/chocolatey/chocolatey-coreteampackages/master/icons/notepadplusplus.png

**Comment by majkinetor** [comment]
This should get automatically fixed by the `Update-IconUrl.ps1` script. I will leave this to @AdmiringWorm to take a look at.

**Comment by ferventcoder** [comment]
Cool

**Comment by AdmiringWorm** [comment]
I'll add some changes later to handle `.commandline` suffix, after I've added that it should be enough to move the icon to the icons directory and rename it to `notepadplusplus.png` and it should automatically be updated when the package is updated.

**Comment by AdmiringWorm** [comment]
I've added a change to the update icon url script in https://github.com/chocolatey/chocolatey-coreteampackages/commit/14cbbb83a8d3c95c04be9434bc400ed5aa87a9d2

this will then update the icon urls the next time the notepad++ packages is updated.
I'll leave this open until then though.
