### ISSUE TITLE
cyg-get [package_name] doesn't work on cyg-get v1.1.1

### ISSUE THREAD

**Issue by pandarun** [chocolatey/chocolatey-coreteampackages#5]
Hi, I've installed cyg-get via $cinst cyg-get 
but whenever I try to install package, for ex: cyg-get.bat openssh, it writes to console : 
"Attempting to install 'openssh' to C:\Cygwin\packages' " and exits immediately.
As a result folder C:\Cygwin\packages' stays empty.

**Comment by gep13** [comment]
@ferventcoder is there still work to do here then?  Is this something you can take care of?

**Comment by ferventcoder** [comment]
Hmmm - I can look at it but it may not be until next week.

**Comment by gep13** [comment]
> Hmmm - I can look at it but it may not be until next week.

Not a problem, I was just going through and triaging all open issues in this repo.

**Comment by ferventcoder** [comment]
This is fixed with cyg-get 1.2.0. It's in moderation at the moment
