### ISSUE TITLE
[request][cyg-get] http mirror by default instead of ftp mirror

### ISSUE THREAD

**Issue by haraldreingruber** [chocolatey/chocolatey-coreteampackages#50]
Many corporate firewalls block FTP connections. Would it be possible to set the HTTP mirror as a default, or make it configurable?

I've also found this comment:
https://chocolatey.org/packages/cyg-get#comment-1800404245

Apparently the FTP mirror is already announced deprecated in the cygwin package: https://chocolatey.org/packages/cygwin

**Comment by ferventcoder** [comment]
This was completed some time ago.
