### ISSUE TITLE
(LibreOffice) Download location could use a different more "stable" url (Or Embed)

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#502]
LibreOffice could be downloaded from https://downloadarchive.documentfoundation.org/libreoffice/old/ instead of https://download.documentfoundation.org/libreoffice/stable/.

Judging from the most recent - 5.2.4.2, it went up to both locations at the same time.

This is from https://chocolatey.org/packages/libreoffice#comment-3072278348

Or if this is embeddable, we can go that route.

**Comment by AdmiringWorm** [comment]
I don't think embedding it would be possible, unless they where to split into separate 64bit and 32bit packages (size limit).

I'm not sure about have it downloaded from the archive location as a default either (potentially slower mirror).
But having a fallback if it isn't found at the default download location should definitely be done.

**Comment by wget** [comment]
Hi there. I just asked upstream; Please do not use the downloadarchive source. The latter is used only for devs. CGN and mirrors etc. need to use the download version.

**Comment by majkinetor** [comment]
Closing this.
If you feel there is anything else to add, please reopen.
