### ISSUE TITLE
(notepadplusplus) Uninstaller isn't silent for notepadplusplus.install

### ISSUE THREAD

**Issue by scowalt** [chocolatey/chocolatey-coreteampackages#503]
After the uninstall script has finished executing, the uninstaller pops up and needs to be manually clicked through.

**Comment by AdmiringWorm** [comment]
could you please provide some more details as I'm unable to reproduce this on my end.

what OS and architecture do you run?
was it 64bit or 32bit version of notepad++ you had installed?
Do the script any output, or warnings?
