### ISSUE TITLE
(tor-browser) Change to embedded package

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-coreteampackages#509]
[Tor Browser License](https://www.torproject.org/docs/faq.html.en#DistributingTor) would allow to redistribute which would help in situations where the original download was removed (like [recently with the 6.0.5 release](http://disq.us/p/1eck6mu)).

On the other hand the [chocolateyInstall.ps1](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/tor-browser/tools/chocolateyInstall.ps1#L68) downloads and installs the browser in the target culture.

Is there a way to create an embedded package in this case?

**Comment by AdmiringWorm** [comment]
I'm not sure of how big the installers are, but if in total(all locales combined) they are under 150MB then there shouldn't be any problem, just download each of the file and store them in the tools directory.

**Comment by pascalberger** [comment]
Unfortunately I don't think embedding all packages is an option, since each contains the full version with about 50MB

**Comment by AdmiringWorm** [comment]
I'm closing this as it isn't possible to do without changing the functionality of the package to only include a single language file.
