### ISSUE TITLE
(git) Verification issues

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#519]
Looks like au pushed up git/git.portable packages just now. The portables are missing the LICENSE and VALIDATION files, plus it failed verification. https://chocolatey.org/packages/git.portable/2.11.0.2

Git was just missing git.install.

**Comment by ferventcoder** [comment]
@AdmiringWorm @gep13 @pascalberger @majkinetor

**Comment by ferventcoder** [comment]
It's looking for an invalid file to unzip? C:\ProgramData\chocolatey\lib\git.portable\tools\PortableGit-2.11.0-64-bit.7z.exe (note the missing `.2`) as compared to the actual file PortableGit-2.11.0.2-64-bit.7z.exe

**Comment by AdmiringWorm** [comment]
odd, was sure it should grab the actual url when it was updating.
also noticed that git was pushed, but not git.install.

I don't have time to look at it today, but I'll try to have a look tomorrow.

**Comment by pascalberger** [comment]
There seems to be also encoding issues with git.portable: https://github.com/chocolatey/chocolatey-coreteampackages/commit/54b404392f4d8644bf11aec8323747259cc1c820#diff-bf5c1a5a81da8e7952b6748dfdc11c22R49

**Comment by pascalberger** [comment]
I'll have a look and create a PR

**Comment by pascalberger** [comment]
Pull request available here for most of the issues: #520
