### ISSUE TITLE
(git.install) Registry key error on install

### ISSUE THREAD

**Issue by michaelray** [chocolatey/chocolatey-coreteampackages#524]
I'm getting an error "The registry key at the specified path does not exist." when attempting to install the git package (which installs git.install).

Here's the gist:
https://gist.github.com/michaelray/0796d6c6f7efadf31d51315cfd733713

**Comment by michaelray** [comment]
Also, even though git.install did not successfully install, it still shows that git succeeded.  That doesn't seem like the correct logical behavior.  If git.install fails to install successfully, then I would think that git should be marked as failed, too (since git installs git.install).

**Comment by pascalberger** [comment]
@ferventcoder Any idea about the second issue (`git` suceeding even if `git.install` fails). Sounds like an issue in `choco` or underlying NuGet to me?

**Comment by ferventcoder** [comment]
The meta package was successful, even though it didn't do anything. Technically it is correct, but you can see how the .install package failing to install makes things look wrong. So in other words, I might call it a bug even though the behavior is correct.
