### ISSUE TITLE
Add embedded tag to obligatory tags

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-coreteampackages#531]
How about introducing another tag `embedded` in the guidelines at [§1.2.2](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Contributing-guidelines#122-obligatory-tags) for embedded packages (or packages which don't require internet access)

**Comment by AdmiringWorm** [comment]
Personally I don't really think it's necessary.

**Comment by ferventcoder** [comment]
I don't really see it as necessary either - there will be a progress bar for downloading packages themselves in 0.10.4, so you will likely know that the package being downloaded contains something when it has a bigger size than 8K.

**Comment by ferventcoder** [comment]
@chocolatey/chocolateycommunitypackages

**Comment by gep13** [comment]
Yeah, I think I agree with @AdmiringWorm and @ferventcoder.  I don't think that this is required.  Going to go ahead and close this one out.

Feel free to open if you think further discussion is required.
