### ISSUE TITLE
flashplayeractivex v24.0.0.194 outdated url

### ISSUE THREAD

**Issue by pyhedgehog** [chocolatey/chocolatey-coreteampackages#544]
```
C:\>cup -y flashplayeractivex
flashplayeractivex v24.0.0.194 [Approved]
flashplayeractivex package files upgrade completed. Performing other installation steps.
Attempt to get headers for https://download.macromedia.com/get/flashplayer/current/licensing/win/install_flash_player_24_active_x.msi failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download.macromedia.com/get/flashplayer/current/licensing/win/install_flash_player_24_active_x.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading flashplayeractivex
  from 'https://download.macromedia.com/get/flashplayer/current/licensing/win/install_flash_player_24_active_x.msi'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download.macromedia.com/get/flashplayer/current/licensing/win/install_flash_player_24_active_x.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The upgrade of flashplayeractivex was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\flashplayeractivex\tools\chocolateyInstall.ps1'.
 See log for details.
```
`https://download.macromedia.com/get/flashplayer/current/licensing/win/install_flash_player_24_active_x.msi` redirects to `http://fpdownload.macromedia.com/get/flashplayer/current/licensing/win/install_flash_player_24_active_x.msi`.

Correct URL is `https://download.macromedia.com/pub/flashplayer/pdc/24.0.0.194/install_flash_player_24_active_x.msi` redirecting to **`http://fpdownload.macromedia.com/pub/flashplayer/pdc/24.0.0.194/install_flash_player_24_active_x.msi`**.

**Comment by AdmiringWorm** [comment]
thank you for opening this issue, we are aware of the issue.
The url have been fixed in the repository, but have yet to be pushed out.

I'm waiting for the go ahead from the rest of the core team packages maintainers on  https://github.com/chocolatey/chocolatey-coreteampackages/pull/543

When that one is merged we would then be able to send out an update for this package.

**Comment by AdmiringWorm** [comment]
@pyhedgehog a updated version of all the flashplayer packages have been pushed to chocolatey.org
