### ISSUE TITLE
(7zip) 7z shim creation

### ISSUE THREAD

**Issue by rgl** [chocolatey/chocolatey-coreteampackages#549]
Can the 7zip.install package also install a shim for the `7z.exe` executable? That is, I would like to have `7z.exe` on the system `PATH` has `choco.exe`.

**Comment by AdmiringWorm** [comment]
@rgl good idea.
Would have to check if another shim exists for `7z.exe` first though.
Should probably add shims to `7zFM.exe` and `7zG.exe` as well.
