### ISSUE TITLE
(inkscape) Due to the bug in vendor installer, package should uninstall prior to update

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#550]
Upgrading the inkscape package is currently impossible due to a bug in the installer making it return error code 1638 if a previous version of the software is already installed.

See:
http://disq.us/p/1f03dr0
https://bugs.launchpad.net/inkscape/+bug/1653574

**Comment by AdmiringWorm** [comment]
Current workaround for this is to uninstall the software before upgrading

**Comment by opello** [comment]
When I `choco install inkscape` after not rolling back and then uninstalling manually from the Control Panel I saw the MSI installer dialog with a progress bar during the installation.  Based on the log it's using `/passive` and not `/quiet`.

**Comment by Spongman** [comment]
chocolatey should check to see if the previous version is installed and uninstall it before installing the new version.

**Comment by HolisticDeveloper** [comment]
Agreed with @Spongman, as long as the package doesn't use the Win32_Product WMI class to check if it is installed -- I know this can cause some perf issues that I've seen with the Skype package, for example. See https://chocolatey.org/packages/skype#comment-2630543885.

**Comment by Spongman** [comment]
Was this fixed? I believe it's still a bug. Do you want me to re-submit?

**Comment by AdmiringWorm** [comment]
No, it haven't been fixed. It was closed because there haven't been activity on this issue for a long time.
We can re-open it though, when/if there is anyone that is interested in fixing this issue.

**Comment by Spongman** [comment]
Seems like a strange reason to close a bug. Surely if it's still a bug it should stay open...

**Comment by AdmiringWorm** [comment]
not really, when an issue have been open without any activity for so long as this one have, there is unlikely that this issue will be fixed even if it is kept open.
As such, for what reason is there to keep it open?

With that said, we won't deny a PR that fixes this issue even when it have been closed.
There is just no reason to have a issue that have gone stale around anymore.

**Comment by AdmiringWorm** [comment]
Oh, and just to have it said.
This isn't really a bug in the package, but rather a bug in the installer.

**Comment by majkinetor** [comment]
We opted for closing stale issue to reduce information overload. We maintain over 200 packages here and there needs to be some triage. PR is ofc. welcome any time.

**Comment by jtcmedia** [comment]
I'm working on a solution for this and have it working except due to the length of time of doing the uninstall, it looks like choco times out or perhaps the uninstall is causing these access is denied errors:
`You have InkScape v0.92.1 installed. Version 0.92.2 is available based on your source(s).
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib-bkp\InkScape]
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib-bkp\InkScape]
Maximum tries of 3 reached. Throwing error.`

It does end up upgrading ok. But is there a way to give it extra time?

**Comment by AdmiringWorm** [comment]
I'm thinking it is the upgrade that isn't completely done, when the package is complete.

Other than detecting if the process is running, or using `sleep`, I don't believe there is any way to give it extra time.

Since you're looking into this, I'll re-open the issue.

**Comment by majkinetor** [comment]
You can execute it in a background job and give it timeout.

**Comment by majkinetor** [comment]
Closing this again as there is no feedbacak.

**Comment by AdmiringWorm** [comment]
Re-Opening this issue, as it was reported again on the disqus channel

**Comment by ferventcoder** [comment]
@jtcmedia in the chocolateyInstall.ps1 script, check for the software being installed and uninstall it, not the Chocolatey package. I think that's where you are seeing those errors.

Also, our first friendly exit code in the wild showed up in that disqus comment (http://disq.us/p/1r9378g):

ERROR: Running ["C:\WINDOWS\System32\msiexec.exe" /i "C:\Users\...\AppData\Local\Temp\chocolatey\InkScape\0.92.3\inkscape-0.92.3-x64.msi" /passive /norestart ] was not successful. Exit code was '1638'. **Exit code indicates the following: This MSI requires uninstall prior to installing a different version. Please ask the package maintainer(s) to add a check in the chocolateyInstall.ps1 script and uninstall if the software is installed. This is most likely an issue with the 'InkScape' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly.**

**Comment by jtcmedia** [comment]
Thanks @ferventcoder. I've submitted PR [#996](https://github.com/chocolatey/chocolatey-coreteampackages/pull/996) that should fix it.

**Comment by AdmiringWorm** [comment]
This issue have now been fixed in the repository, and will be available when the next version of InkScape is available.

**Comment by AdmiringWorm** [comment]
@nielsvdp what Windows version are you running? I'm thinking it may be an older version of windows which is causing your issue (can't say for sure yet though)

**Comment by AdmiringWorm** [comment]
Just verified that the removal of the old program doesn't work on older versions of windows.

Re-Opening this issue, and am working on a fix now.

**Comment by AdmiringWorm** [comment]
or rather, I submitted it as a new issue #1207

**Comment by nielsvdp** [comment]
@AdmiringWorm I use Windows 10 1803. Sorry if I missed anything, it's my first time posting an issue.

I originally used ChocolateyGui to upgrade. Now I tried using regular choco from PowerShell and it uninstalled and installed InkScape fine. The uninstallation just took a while.

**Comment by AdmiringWorm** [comment]
hmm, that's odd. Well, I found it didn't work on older versions of windows, so it could be the same issue as when running through ChocolateyGUI

**Comment by AdmiringWorm** [comment]
@nielsvdp hmm, after my changes the issue is still happening in ChocolateyGUI. This leads me to think that there may be a bug in their program, instead of the package (although there was a compatibility issue with it).

As such, I recommend that you open up an issue over at their repository: https://github.com/chocolatey/ChocolateyGUI/issues
