### ISSUE TITLE
(nodejs) LTS package

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#557]
Many folks, including @digitaldrummerj have requested that there be an actual LTS package for NodeJs - I think it's a good idea. Thoughts?

**Comment by digitaldrummerj** [comment]
@ferventcoder  After I requested this one of the maintainers for the nodejs package responded that there already was a package at https://chocolatey.org/packages/nodejs-lts

**Comment by ferventcoder** [comment]
Yeah, there is. I forgot about that one.

**Comment by AdmiringWorm** [comment]
@ferventcoder fyi
I've added a note about the LTS package, it will be included in future versions of the nodejs package.

https://github.com/chocolatey/chocolatey-coreteampackages/commit/6e56dc3e0e193eab9230ffb28bf8be79f43749ef
