### ISSUE TITLE
javaruntime should install jre8

### ISSUE THREAD

**Issue by TomOne** [chocolatey/chocolatey-coreteampackages#56]
The javaruntime* package should really install the latest version of JRE. Many packages on Chocolatey.org take dependency on that package and it isn’t nice that it installs JRE 7, even if all these programs would work with JRE 8 too.

We need to figure out a proper way how the javaruntime* packages should work.

**Comment by ferventcoder** [comment]
Is this still an issue?

**Comment by TomOne** [comment]
There’s still a [javaruntime-platformspecific](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/javaruntime-platformspecific) package in the repository and also on https://chocolatey.org/packages/javaruntime-platformspecific. Should we deprecate it? I think it’s no longer needed.

**Comment by cfoellmann** [comment]
The javaruntime works correctly now.

Since the jre8 package has the correct flags for platform-specific installs `javaruntime-platformspecific` can be deprecated

**Comment by TomOne** [comment]
Thanks. This issue can be closed. Deprecating `javaruntime-platformspecific` is tracked in #195.
