### ISSUE TITLE
Pyhoca-GUI Uninstall Script Errors

### ISSUE THREAD

**Issue by wjk** [chocolatey/chocolatey-coreteampackages#562]
I was wandering through the list of newly modified packages on the community feed, when I stumbled upon a strange syntax error in the PyHoca-GUI uninstall script. To wit:

[Lines 24-25](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/pyhoca-gui/tools/chocolateyUninstall.ps1#L25-L26) of the uninstall script for this package are missing the `Write-Warning` part of the cmdlet, as well as the opening quote for the message. I suspect it should look [more like this](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/vlc/tools/chocolateyUninstall.ps1#L26-L27). [The djvu package](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/djv/tools/chocolateyUninstall.ps1#L25-L26) also suffers from this same problem. Other instances may well exist, but those two are the two I noticed.

I suspect that this issue slipped past the verifier because this code only occurs as part of an error-handling branch that should never be executed on a properly functioning system. It certainly does not occur on the verifier VM.

**Comment by AdmiringWorm** [comment]
yeah, that is very strange that such an error got through (and it being my fault as well 😢)
I'm about to sign off, but I'll fix them first thing tomorrow.

Thanks for opening the issue and letting us/me know.

**Comment by AdmiringWorm** [comment]
Two other packages also needs fixing.
- picard
- ietester
