### ISSUE TITLE
(git.install) NoShellIntegration 

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-coreteampackages#571]
As reported [here](https://chocolatey.org/packages/git#comment-3140452082), the `NoShellIntegration` parameter no longer seems to work on the `git.install` package.

**Comment by AdmiringWorm** [comment]
I found out why this doesn't work, the component string that is generated is never returned from the function.

**Comment by eberkund** [comment]
It is broken again for me with the last few versions
