### ISSUE TITLE
(git.install) Cannot process argument transformation on parameter 'silentArgs'

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-coreteampackages#574]
As reported [here](https://chocolatey.org/packages/git#comment-3142764863):

Getting the following error message when attempting to upgrade (cup all). After the failed upgrade attempt the package had been removed so I tried installing it again (choco install git.install) with the same result.

```
ERROR: Cannot process argument transformation on parameter 'silentArgs'. Cannot convert value to type System.String.
The upgrade of git.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\git.install\tools\chocolateyInstall.ps1'.
See log for details.
```

The only thing that might be relevant that I can find in the log is:

```
2017-02-07 10:51:27,816 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\git.install\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '''] exited with '-1'.
```

Win 10 Anniversary update, ran from both elevated cmd and ps. Any ideas?

**Comment by pascalberger** [comment]
@AdmiringWorm Any idea why convertion fails for the `silentArgs` parameter?

**Comment by AdmiringWorm** [comment]
@pascalberger 
Unfortunately I have no idea right now.

**Comment by yhrn** [comment]
Any more information I can provide?

**Comment by pascalberger** [comment]
@yhrn You just run `choco install git` without any additional parameters? Whats your PowerShell version?

**Comment by AdmiringWorm** [comment]
@yhrn if you could install it with debug and verbose output enable i.e: `choco install git.install -dv` and share that output (make sure it doesn't contain anything sensitive), then that would be great.

@pascalberger Considering he said he is running Windows 10 Anniversary the PowerShell version would either be `5.0` or `5.1`

**Comment by yhrn** [comment]
PS version: 5.1.14393.693
[Log gist](https://gist.github.com/yhrn/3a311902b89e7f6a1284b036f0c92781)

**Comment by AdmiringWorm** [comment]
I think I've found the problem.
The string array of silent args just aren't automatically expanded to a string on some systems (oddly enough it's on mine, and in the test environment).

**Comment by ferventcoder** [comment]
Upgrade choco - you are running into a known issue that was handled in 0.10.x. Silent args are an array here but the version of choco you have can't work with arrays.

**Comment by ferventcoder** [comment]
0.9.10.3 - https://github.com/chocolatey/choco/issues/808

**Comment by AdmiringWorm** [comment]
ah, that explains it. never noticed he ran v0.9.10.2.

**Comment by yhrn** [comment]
Yup that solved it. I was under the impression that Chocolatey would upgrade itself when running `cup all`, but maybe that something that got introduced in a later version than the one I was on?
