### ISSUE TITLE
Update the firefox package to use package parameters for locale selection

### ISSUE THREAD

**Issue by TomOne** [chocolatey/chocolatey-coreteampackages#59]
Currently it misuses the install arguments override to achieve that.

Same story with thunderbird.

**Comment by TomOne** [comment]
Fixed with https://github.com/chocolatey/chocolatey-coreteampackages/commit/2e3a83b31ac3324177b542ac6fb1fabab7c63b7d

**Comment by ferventcoder** [comment]
:+1:
