### ISSUE TITLE
Google Chrome binaries have changed for 56.0.2924.87

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#604]
The version is the same, however the binaries have changed.

https://chocolatey.org/packages/GoogleChrome#comment-3171878283

When the package was created for version 56.0.2924.87, the checksums were:

~~~powershell
 url                    = 'https://dl.google.com/tag/s/dl/chrome/install/googlechromestandaloneenterprise.msi'
  url64bit               = 'https://dl.google.com/tag/s/dl/chrome/install/googlechromestandaloneenterprise64.msi'
  checksum               = '9a5e2810a164654d9a4a42f0597d8668110134ee7d1aca0faf8cc48d203fc019'
  checksum64             = 'c47ff551ff8b251268905cd87fb299959e6bcb3640a3e60085a3a7dbf176845f'
~~~

However without a new version the checksums are now:

~~~powershell
checksum    = '8B83B51566E02A349BF4F94B753D198883994C713D8DE001B0ABF7E650BDC9FB'
checksum64  = '1450DE87F0289CE725DF1C138BBA2666304FB94BF4476B03C06D058C999D4805'
~~~

**Comment by ferventcoder** [comment]
FYI - It looks like they pulled a bad version - https://gist.github.com/choco-bot/6bd4eeb385ac2b753aa6e66b2ede9fe2#file-1-registrysnapshot-xml-L5 (note that display version showed up as the actual version - Google Chrome does some very weird things with respect to version). The number you see here is what is in the MSI, but the actual DisplayVersion is typically overridden.

**Comment by AdmiringWorm** [comment]
Ah. Now it makes sense why the old installer was replaced.
I'll look into adding an updated package using the [Get-Padded-Version](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/scripts/Get-Padded-Version.ps1) helper

**Comment by ferventcoder** [comment]
![Here](https://snag.gy/15FbeV.jpg)
