### ISSUE TITLE
Create vcredist 2005-2015 packages

### ISSUE THREAD

**Issue by matbech** [chocolatey/chocolatey-coreteampackages#61]
Common packages on which a lot of packages (should) depend on should be part of the core packages. Namely Visual C++ redistributables:
- [x] vcredist2005 - https://chocolatey.org/packages/vcredist2005
- [x] vcredist2008 - https://chocolatey.org/packages/vcredist2008
- [x] vcredist2010 - https://chocolatey.org/packages/vcredist2010
- [x] vcredist2012 - https://chocolatey.org/packages/vcredist2012
- [x] vcredist2013 - https://chocolatey.org/packages/vcredist2013
- [x] vcredist2015 - https://chocolatey.org/packages/vcredist2015

Right now it seems that almost all packages which depend on the Visual C++ runtime, individually install it either in the bootstrapper or as a merge module in the MSI file.

Making the redistributables available as maintained packages would make it easier for these packages to split up the dependencies.

**Comment by ferventcoder** [comment]
Makes sense.

**Comment by gep13** [comment]
@matbech just looking back at some older issues, and stumbled into this one.

Were you in a position to look at this?  I know you have done a lot of work in maintaining the vcredist2015 package.  Have you looked into who is currently maintaining the other packages?  Could you help out in this regard?

**Comment by matbech** [comment]
The vcredist2015 package is currently maintained by https://github.com/pocki
Maybe he can share some details on why he has decided not to use the chocolatey-coreteampackages repo.

**Comment by jberezanski** [comment]
Actually, @pocki has asked me to take over maintaining vcredist2015 a short while ago (hasn't made me co-maintainer yet, though). He had been actively updating that package, but now he said he was stepping away from maintaining packages in the community repo.

I do not know his reasons for continuing to update the package in his repo after his PR was accepted here. However, it might have been for convenience reasons - it is much easier and quicker to update the package in one's own repo than to wait until a PR is accepted.

**Comment by gep13** [comment]
@jberezanski ah, I see.  Would you be interested in maintaining the source code for the package in this repo then, rather than your own?  You have write access into the repo 😄 

>@jberezanski said...
it is much easier and quicker to update the package in one's own repo than to wait until a PR is accepted.

To an extent I agree with this, and can understand the thought process.  However, as has just been evidenced, they are no longer in a position to maintain the package.  Had they been using the version in this repo, it would have been easier to switch to another maintainer, rather than moving source code to another repo.

**Comment by jberezanski** [comment]
> Would you be interested in maintaining the source code for the package in this repo

With pleasure.

> You have write access into the repo 

I keep forgetting that 😉 

> Had they been using the version in this repo, it would have been easier to switch to another maintainer, rather than moving source code to another repo.

Agreed. In case of important packages that many other depend upon, it is vital to be able to continue updating the package if the current maintainer goes AWOL. Hosting the package in this repo provides that capability.

**Comment by gep13** [comment]
@jberezanski nice one, thank you very much! 😄

**Comment by gep13** [comment]
Looks like each of these packages have been created.  While the could, and perhaps should, be moved to the core team packages repo is another question.  For now, I think we can close this out.

**Comment by majkinetor** [comment]
SGTM. We can tackle that problem later and create different ticket for it.
