### ISSUE TITLE
[RFC] add a phpmyadmin

### ISSUE THREAD

**Issue by photodude** [chocolatey/chocolatey-coreteampackages#624]
We already have the `pg admin` install option for managing PostgreSQL, it would be very helpful to also have the `phpMyAdmin` install option for managing MySQL.

downloads
https://www.phpmyadmin.net/downloads/

`PHPMyAdmin` should be installed with PHP, MySQL and a webserver like Apache, IIS, or nginx

- check if MySQL is installed, install if it's not
- check if a webserver is installed, install one if not (default to Apache???)
- Check if PHP is installed, install it if it's not

**Comment by majkinetor** [comment]
Should be on https://github.com/chocolatey/chocolatey-package-requests

**Comment by photodude** [comment]
Thanks @majkinetor new issue opened https://github.com/chocolatey/chocolatey-package-requests/issues/118
