### ISSUE TITLE
(git.install) Add option to Enable Symlinks and Default on Windows 10

### ISSUE THREAD

**Issue by dragonwolf83** [chocolatey/chocolatey-coreteampackages#631]
Git Installer added the option to enable symbolic links. Add an install parameter to configure the setting. 

To stay consistent with existing parameters, the registry item is: `Inno Setup CodeFile: Enable Symlinks`. The values are Disabled or Enabled.

The option should be set to enabled by default on upcoming Windows 10 Creators Update if Developer Mode is turned on, otherwise default to disabled. 

It was disabled on Windows because creating Symbolic Links required Elevated Admin rights making it less user friendly. Creators Update changes this in Developer Mode to allow any user on the machine to set Symbolic Links. See the [Windows Blog](https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/#6kzwrB0oERyeUMHW.97) for more details on the change in Windows.

Since Symbolic Links is the intended behavior by Git and a top issue, it makes sense to enable this by default with the new support for it. On older versions of Windows, it should remain disabled but optional so that developers that turn off UAC or don't mind the hassle can have it turned on.

**Comment by AdmiringWorm** [comment]
That would probably be a nice additions.
I'm not sure how to check if the developer mode is enabled though (and if the Creators Update is installed).

A PR to add this would be most welcome.

**Comment by rlabrecque** [comment]
I'm not doing this but:
- Check if [System.Environment]::OSVersion.Version == 10
- Check if [System.Environment]::OSVersion.Build >= 15063

**Comment by p3lim** [comment]
As of Git 2.14.2 (or .1, not sure), the installer detects and enables symlinks by itself, by checking the validity of creating a symlink: https://github.com/git-for-windows/build-extra/commit/62823afd9794e4f292cddc09fe50f92ee45ea8de.

This issue can be closed.

**Comment by JackZylkin** [comment]
This issue should not have been closed. If I understand the git for windows installer correctly, Git can only detect and enable symlinks if it is not running as Admin. As far as I know, Chocolatey must always run as Admin.
