### ISSUE TITLE
(core.extension) Path gets cut into half when parsing

### ISSUE THREAD

**Issue by Schroedingers-Cat** [chocolatey/chocolatey-coreteampackages#636]
I'm creating a chocolatey package with an optional parameter to change the installation path. Because the installer itself has no support for that, I'm parsing the path as a PackageParameter and put it into the registry, where the installer gets it's default path from. However, when parsing the path, I run into an issue where the path seems to correctly get into my script, but nevertheless is stored wrong into the PackageParameter-Hastable. 

Here is the [log of my package.](https://gist.github.com/Schroedingers-Cat/a32268c7bc00a35d7cf1f86e1ffd28ac)
At [line 1](https://gist.github.com/Schroedingers-Cat/a32268c7bc00a35d7cf1f86e1ffd28ac#file-powersh-L1), you can see I'm using the correct quoting pattern of parsing paths with spaces.
At [line 5](https://gist.github.com/Schroedingers-Cat/a32268c7bc00a35d7cf1f86e1ffd28ac#file-powersh-L5) you can see that the path survived with full quotes. The same thing with [line 24.](https://gist.github.com/Schroedingers-Cat/a32268c7bc00a35d7cf1f86e1ffd28ac#file-powersh-L24)

However, when accessing the resulting PackageParameter variable, the [path got cut into half.](https://gist.github.com/Schroedingers-Cat/a32268c7bc00a35d7cf1f86e1ffd28ac#file-powersh-L186-L187)

I have [discussed this at the chocolatey google groups](https://groups.google.com/d/msgid/chocolatey/9d8fec95-f404-438c-a244-dc2e875ca6c9%40googlegroups.com) with Rob and he told me it's likely a bug and asked me to report hit here.

**Comment by AdmiringWorm** [comment]
@Schroedingers-Cat Could you please try something for me.
try calling the `--packageParameters with '""/Vst2x86Path:C:\Program Files (x86)\Common Files\VST2\Voxengo""'`

I doubt this changes anything, but just want to make sure.
It's possible that the regex used in the parsing the package parameters don't account for spaces.
Trying the mentioned call would make sure if that is the case.

**Comment by Schroedingers-Cat** [comment]
Yes, that didn't change anything.

**Comment by AdmiringWorm** [comment]
@Schroedingers-Cat Yeah, I figured. Just wanted to make sure.
I'll assign it as a bug, a PR to fix this would be appreciated though.

**Comment by AdmiringWorm** [comment]
@majkinetor any thoughts on this?

**Comment by majkinetor** [comment]
Its a bug:

```
23  17-03-17 22.38.23  C:\Users\majkinetor\go\bin
> import-module C:\ProgramData\chocolatey\extensions\chocolatey-core\chocolatey-core.psm1
> Get-PackageParameters -Parameters '/Vst2x86Path:"C:\Program Files (x86)\Common Files\VST2\Voxengo"'

Name                           Value
----                           -----
Vst2x86Path                    "C:\Program Files
```

Braces do this and now I see that many other funky chars in paths will do this such as `$`

This re is problematic: https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/extensions/chocolatey-core.extension/extensions/Get-PackageParameters.ps1#L24

Adding braces fixes this problem but not other funky chars:

```
$re = "\/([a-zA-Z0-9]+)(:([`"'])?([a-zA-Z0-9- _\\:\.()]+)([`"'])?)?"
```

We need to find some good `$re` for this. This is however problematic as additional params may follow that are not part of the path.

I think braces should be added to RE nevertheless because `(86)` is every day folder.

**Comment by majkinetor** [comment]
This function would require test cases tho, due to its usage in bunch of packages.

**Comment by majkinetor** [comment]
I came up with this RE:

```
$re = "\/([a-zA-Z0-9]+)(:[`"'].+?[`"']|[^ ]+)?"
```

In other words, if there is value for parameter, after `:` its either one of the quotes and whatever until the other quote OR whatever but no spaces allowed

Complete function:

```powershell

function Get-PackageParameters {
    [CmdletBinding()]
    param(
       [string] $Parameters = $Env:ChocolateyPackageParameters,
       # Allows splatting with arguments that do not apply and future expansion. Do not use directly.
       [parameter(ValueFromRemainingArguments = $true)]
       [Object[]] $IgnoredArguments
    )

    $res = @{}

    $re = "\/([a-zA-Z0-9]+)(:[`"'].+?[`"']|[^ ]+)?"
    $results = $Parameters | Select-String $re -AllMatches | select -Expand Matches
    foreach ($m in $results) {
        if (!$m) { continue } # must because of posh 2.0 bug: https://github.com/chocolatey/chocolatey-coreteampackages/issues/465

        $a = $m.Value -split ':'
        $opt = $a[0].Substring(1); $val = $a[1..100] -join ':'
        if ($val -match '^(".+")|(''.+'')$') {$val = $val -replace '^.|.$'}
        $res[ $opt ] = if ($val) { $val } else { $true }
    }
    $res
}
```

It looks better then before

```
> Get-PackageParameters -Parameters "/c: meh /Vst2x86Path:'C:\@Program Files (x861 $)\Common Files\VST2\Voxengo' /v2 /use:no /2 /2:'123 123' \invalid"

Name                           Value
----                           -----
2                              123 123
v2                             True
use                            no
Vst2x86Path                    C:\@Program Files (x861 $)\Common Files\VST2\Voxengo
c                              True
```

**Comment by majkinetor** [comment]
Oh, and looking forward to this package @Schroedingers-Cat :)

**Comment by majkinetor** [comment]
I commited this, so lets hope for the best :) I don't think it will make any problems for existing packages but  lets keep any eye on this. 

I didn't PUSH the new version, if others agree to this somebody should `[PUSH chocolatey-core.extension]`.

**Comment by majkinetor** [comment]
Some third party testing might not be bad idea before pushing.

**Comment by Schroedingers-Cat** [comment]
Awesome! When can I work with this? :)

**Comment by majkinetor** [comment]
I will push this in Wednesday (in 2 days) if nobody provides any feedback.

**Comment by Schroedingers-Cat** [comment]
That sounds great!

If you want, I could test it before. Just tell me what I have to do so it's on my chocolatey installation.

**Comment by AdmiringWorm** [comment]
@majkinetor I had a quick look at it, and think it looks good. feel free to push it whenever you want.

**Comment by majkinetor** [comment]
Quick look is not enough, this should be tested as it is core functionality. 

Pushing it anyway

**Comment by Schroedingers-Cat** [comment]
Thank you. That makes parsing the the path via `-packageParameters '/Vst2x86Path:""C:\Program Files (x86)\Common Files\Target""'` work flawlessly!

Now how to parse that path but using an environment variable instead? When I do one of these:
```
-packageParameters '/Vst2x86Path:""${env:CommonProgramFiles(x86)}\Target""'
-packageParameters '/Vst2x86Path:"${env:CommonProgramFiles(x86)}\Target"'
-packageParameters '/Vst2x86Path:${env:CommonProgramFiles(x86)}\Target'
```
The result is always `PackageParameters='/Vst2x86Path:${env:CommonProgramFiles(x86)}\Target'|`. How can I get the variables path instead?

**Comment by majkinetor** [comment]
`-packageParameters "/Vst2x86Path:'${env:CommonProgramFiles(x86)}\Target'"`

**Comment by Schroedingers-Cat** [comment]
Ok, that makes chocolatey work at the start of the script:
```
PackageParameters='/Vst2x86Path:'C:\Program Files (x86)\Common Files\Target''|
```
However using that variable [fails.](https://gist.github.com/Schroedingers-Cat/fc2d0ba3cc8656c9d1020d8f37ec72ce) Esp. this sounds like the [same bug again.](https://gist.github.com/Schroedingers-Cat/fc2d0ba3cc8656c9d1020d8f37ec72ce#file-powershell-L5)

**Comment by majkinetor** [comment]
You can't use single quote ' but double quote ". WIth double quotes, Powershell will then replace environment variable and that has nothing to do with choco as it will get expanded version (and contrary, with single quotes it doesn't get replaced). Inside dobule quote string use single quote for path.

**Comment by Schroedingers-Cat** [comment]
I think, there is a misunderstanding.

I used the quotes exactly as you were explaining:
```
-packageParameters "/Vst2x86Path:'${env:CommonProgramFiles(x86)}\Target'"
```
This is the [debug output.](https://gist.github.com/Schroedingers-Cat/989787f5a59d98c0e7f33da73a7752b6)

At what step did I use the wrong quotes? 

I think the problem happens when the variable gets replaced with text containing spaces. `env:CommonProgramFiles(x86)` becomes `C:\Program Files (x86)\` in most cases. But paths with spaces have to be quoted with two ". You see the problem here?

**Comment by gep13** [comment]
@Schroedingers-Cat  Have you read through this?

https://chocolatey.org/docs/commands-reference#how-to-pass-options-switches

I suspect that you are going to need to introduce the backtick `

**Comment by majkinetor** [comment]
Works for me:

```
PS C:\> import-module C:\ProgramData\chocolatey\extensions\chocolatey-core\chocolatey-core.psm1
PS C:\> Get-PackageParameters  "/Vst2x86Path:'${env:CommonProgramFiles(x86)}\Target'"

Name                           Value
----                           -----
Vst2x86Path                    C:\Program Files (x86)\Common Files\Target



```

**Comment by Schroedingers-Cat** [comment]
@majkinetor 
Your example works for me too. Do you have an idea why it fails nevertheless when accessing the package parameter during install?

@gep13 
Yes, I've read that document. As it states `"value`" is the same as 'value', I just stick to 'value' and try to make it work with that. Or do you think `"value`" may work better in this scenario?

**Comment by Schroedingers-Cat** [comment]
I tried some variations with 
```
`"value`"
```
This pattern works (added spaces to improve readability):
```
-packageParameters "/InstallPath: ""`"${env:CommonProgramFiles(x86)}\Target`""" "
```
After that, I wanted to test if it really is the same as:
```
-packageParameters "/InstallPath: ""'${env:CommonProgramFiles(x86)}\Target'"" "
```
But that fails like before.

I think both points should get a bit more attention at the docs. It would be nice to give an example for how to pass environment variables containing spaces. With no example at the wiki it will be a lot of trial and error until you got the right combination. 
Also, it will be more trial and error when the docs tell you that one quoting pattern is essentially the same as another only to find out it isn't.

**Comment by majkinetor** [comment]
> Your example works for me too. Do you have an idea why it fails nevertheless when accessing the package parameter during install?

No, I have no idea. It is exactly the same as not using environment variable as Powershell itself does the translation of env. var before calling choco.
