### ISSUE TITLE
(transmission-qt) Package unmaintained and outdated

### ISSUE THREAD

**Issue by pyhedgehog** [chocolatey/chocolatey-coreteampackages#638]
Package [transmission-qt](https://chocolatey.org/packages/transmission-qt) states that it's maintainer's github name is @TomOne. His choco packages [repository](https://github.com/TomOne/chocolatey-packages) states that all packages moved here. But transmission-qt is somehow lost in transition.
Package version is `2.84.9`.
Current version is `2.92`.

Also links should be changes:
Software Site: https://transmissionbt.com/
Software Source: https://github.com/transmission/transmission
Download Page: https://transmissionbt.com/download/
Releases page: https://github.com/transmission/transmission/releases
Current version download links:
https://github.com/transmission/transmission/releases/download/2.92/transmission-2.92-x86.msi
https://github.com/transmission/transmission/releases/download/2.92/transmission-2.92-x64.msi
Hashes according to official site and virustotal:
```
transmission-2.92-x86.msi: f8bfaba603036d35f74bbd5d27ea5bc51fe58d991af48228c290323e406bef00
transmission-2.92-x64.msi: 8cee6436e79d48409d76a85bbb1bb506c8c76c8f686551b9e7e13b9a2ca2299d
```

**Comment by AdmiringWorm** [comment]
I see there is new maintainer for that package, could perhaps be he recently took over the package and just haven't yet been able to update it.
As such I believe he should be contacted first, before anything is done with this package (especially since it isn't located here, and never have as far as I know)

**Comment by majkinetor** [comment]
This is not core team package, no matter what external source claims. You could either contact maintainer or submit PR here.
