### ISSUE TITLE
Palemoon errors on Get-Fosshub

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey-coreteampackages#64]
Got this comment in an email (however I don't see it on disqus):

---

_Dear all,_

_I used to use Pale Moon 25.2.1 and wanted to update to 25.3.0 by cup. It failed though. Well it actually is installed and it works. But clist -lo doesn't show up palemoon. And cinst -force palemoon always fails. I put the log as enclosure._

_Thank you for any help and work._

_Gunner_

```
2015-03-22 10:59:30,891 [INFO ] - ============================================================
2015-03-22 10:59:30,912 [INFO ] - Chocolatey v0.9.9.2
2015-03-22 10:59:30,967 [INFO ] - Installing the following packages:
2015-03-22 10:59:30,973 [INFO ] - palemoon
2015-03-22 10:59:30,974 [INFO ] - By installing you accept licenses for the packages.
2015-03-22 10:59:32,511 [INFO ] - 
palemoon v25.3.0 (forced)
2015-03-22 10:59:32,580 [INFO ] - Found 'chocolateyInstall.ps1':
2015-03-22 10:59:32,582 [INFO ] - 
$packageName = 'palemoon'
$installerType = 'exe'
$url = 'http://relmirror.palemoon.org/release/palemoon-25.3.0.win32.installer.exe'
$url64 = 'http://www.fosshub.com/genLink/Pale-Moon/palemoon-25.3.0.win64.installer.exe'
$silentArgs = '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-'
$validExitCodes = @(0)
$pwd = "$(split-path -parent $MyInvocation.MyCommand.Definition)"

Combatibility - This function has not been merged

if (!(Get-Command Get-UrlFromFosshub -errorAction SilentlyContinue)) {{{{
Import-Module "$($pwd)\Get-UrlFromFosshub.ps1"
}}}}

$url = Get-UrlFromFosshub $url
$url64 = Get-UrlFromFosshub $url64

Install-ChocolateyPackage "$packageName" "$installerType" "$silentArgs" "$url" "$url64" -validExitCodes $validExitCodes

2015-03-22 10:59:32,596 [INFO ] - 
Do you want to run the script? 
NOTE: If you choose not to run the script, the installation will 
fail.
Skip is an advanced option and most likely will never be wanted.

2015-03-22 10:59:32,597 [INFO ] - 1) yes
2015-03-22 10:59:32,599 [INFO ] - 2) no [Default - Press Enter]
2015-03-22 10:59:32,599 [INFO ] - 3) skip
2015-03-22 10:59:36,318 [ERROR] - Cannot index into a null array.
2015-03-22 10:59:36,320 [ERROR] - At C:\ProgramData\chocolatey\lib\palemoon\tools\Get-UrlFromFosshub.ps1:13 char:
2015-03-22 10:59:36,321 [ERROR] - 3
2015-03-22 10:59:36,322 [ERROR] - + $fosshubAppName = $Matches[1]
2015-03-22 10:59:36,323 [ERROR] - + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2015-03-22 10:59:36,323 [ERROR] - + CategoryInfo : InvalidOperation: (:) [], RuntimeException
2015-03-22 10:59:36,324 [ERROR] - + FullyQualifiedErrorId : NullArray
2015-03-22 11:00:04,832 [INFO ] - Installing palemoon...
2015-03-22 11:00:26,404 [INFO ] - palemoon has been installed.
2015-03-22 11:00:26,454 [ERROR] - palemoon install not successful.
2015-03-22 11:00:26,457 [ERROR] - Error while running 'C:\ProgramData\chocolatey\lib\palemoon\tools\chocolateyInstall.ps1'.
See log for details.
2015-03-22 11:00:28,471 [WARN ] - 
Chocolatey installed 0/1 package(s). 1 package(s) failed.
See the log for details.
2015-03-22 11:00:28,473 [ERROR] - Failures:
2015-03-22 11:00:28,475 [ERROR] - - palemoon
```

_This comment has been added to the disqus forum thread for palemoon._

_Package Url: http://chocolatey.org/packages/palemoon_
_Comment Url: http://chocolatey.org/packages/palemoon#comment-1921466149_

---

I'm not sure what is going on here. I believe fosshub has changed. This could be fixed globally if fosshub was a global helper.

https://github.com/chocolatey/chocolatey/issues/377

**Comment by gep13** [comment]
>@Redsandro said...
Got this comment in an email (however I don't see it on disqus):

It could be that the comment was deleted, or that the comment is sitting in the moderation queue.  There should be a note to that effect in the email that you received.

**Comment by Redsandro** [comment]
New version of PaleMoon browser, **Gunnersson** reported in again with the same problem.

```
Cannot index into a null array.
palemoon\tools\Get-UrlFromFosshub.ps1 line 13 char 3
```

**Comment by Redsandro** [comment]
![image](https://cloud.githubusercontent.com/assets/1702193/6887529/7c2b9102-d662-11e4-8bdc-0746e9bb65c6.png)

This scrolls like the matrix when trying to learn something from `-debug`. @TomOne do you have any suggestions?

**Comment by TomOne** [comment]
The error was caused by accessing a non-array here: https://github.com/chocolatey/chocolatey-coreteampackages/blob/86b9fa09890ef0a40cbb288f4d3be6fd874537ac/automatic/palemoon/tools/Get-UrlFromFosshub.ps1#L12-L13

The 32-bit URL of the package (http://relmirror.palemoon.org/release/palemoon-25.3.2.win32.installer.exe) is not a FossHub-URL, so there were no matches.

I made the function more robust when used with non-FossHub URLs: https://github.com/chocolatey/chocolatey-coreteampackages/commit/ff484e02c6bd7de115c987f61427b49765b02ff5

The fixed package is released: https://chocolatey.org/packages/palemoon/25.3.2.20150501

@Redsandro, that matrix-style scrolling is the UTF-8 representation of the binary exe file downloaded from http://relmirror.palemoon.org/release/palemoon-25.3.2.win32.installer.exe, which the function downloaded in https://github.com/chocolatey/chocolatey-coreteampackages/blob/86b9fa09890ef0a40cbb288f4d3be6fd874537ac/automatic/palemoon/tools/Get-UrlFromFosshub.ps1#L20. This won’t happen again with my fix. :smile:

**Comment by Redsandro** [comment]
Ah thank you!

**Comment by i-give-up** [comment]
I'm not sure that the function is working - I'm getting 403 Forbidden Error for the FossHub link

I've [posted on Pastebin](http://pastebin.com/DiDnYRdN) a relevant snippet of the log file (I tried to attach it here but I got "we can't process that file" error). 

I'm thinking that it might be easier to simply use the direct `relmirror.palemoon.org` links. Unless there's some catch that I'm not aware of.

**Comment by Redsandro** [comment]
Hi @i-give-up,

I can't work on this right now and the latency in getting PRs checked and merged in this core team packages repository is larger than my attention-span. Maintenance of my packages is in abeyance.

Do you want to take over as maintainer?

**Comment by i-give-up** [comment]
Unfortunately I know too little about Chocolatey to be a package maintainer. I only started using it for about a week or so.

**Comment by Redsandro** [comment]
Fair enough. Since you said 32 bit installs correctly, and 64 bit is hosted on relmirror too, I've [updated ketarin](https://github.com/chocolatey/chocolatey-coreteampackages/commit/d0343f915eb83ffc8c8fa848d6f7d25c948957ec) to reflect your changes.

@gep13 are changes to ketarin .xml in Master automatically picked up by the ketarin machine? Or does someone need to import it?

**Comment by gep13** [comment]
@Redsandro when I last looked at it, it was a manual process, but I seem to remember that @ferventcoder had a script that could be used to import the xml files from the repo on each ketarin run.  Not sure if that ever got implemented or not though.

**Comment by Redsandro** [comment]
@gep13 Can you do this for this palemoon package? Or who do I need to @mention?

**Comment by i-give-up** [comment]
How long does this change take to propagate?

I just tried `choco install palemoon` again and it is still trying and failing to get the 64-bit installer from fosshub. And I'm still seeing the old chocolateyInstall.ps1 on [palemoon's Chocolatey page](https://chocolatey.org/packages/palemoon).

**Comment by Redsandro** [comment]
I have no power over this. I think @gep13 @TomOne and @ferventcoder can do this. Otherwise it will happen automatically when a new version of `palemoon` comes out.
