### ISSUE TITLE
(autohotkey.portable) Fails with 403: Forbidden during update

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#642]
As the title says, whenever we try to update the `autohotkey.portable` package it fails with `Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden.":https://autohotkey.com/download/1.1/AutoHotkey_1.1.25.01.zip`
https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e/56a2ebcd3ed17a913dae9bb2dbff855272e4711c#autohotkeyportable

However, the `autohotkey.install` package works as expected.

@majkinetor since you have the most experience with autohotkey (as far as I know), could you perhaps look into this?

**Comment by majkinetor** [comment]
> @majkinetor since you have the most experience with autohotkey (as far as I know), could you perhaps look into this?

Hah, nice try :)

But OK, I'll pretend  I am a  squirrel and this is an Autohotkey issue ;)

**Comment by AdmiringWorm** [comment]
You can't blame we for trying :P

Anyways, I tried the download link in a browser which works.
It's only when trying to update it through AU that fails.

**Comment by majkinetor** [comment]
I already looked at it before few days and I left it to see what will happen on the next update, it already got updated correctly. I am not sure what can be done because the install version uses exactly the same updater.

**Comment by majkinetor** [comment]
Looks like WebClient issue, iwr doesn't fail here.

**Comment by AdmiringWorm** [comment]
ah I see. I never actually checked if it had updated, just noticed the error and figured it hadn't.
I'm thinking we probably should just wait and see what happens when it tries to update the next time.

> Looks like WebClient issue, iwr doesn't fail here.

I see, still odd that the portable package fails though, while the install package works.

**Comment by AdmiringWorm** [comment]
I've updated the autohotkey.portable script to use iwr instead of webclient, also had to add `-NoCheckUrl`

https://github.com/chocolatey/chocolatey-coreteampackages/commit/f2a82361b9d41616bf43f7221c63039dfc7edd98
