### ISSUE TITLE
Fix thunderbird package

### ISSUE THREAD

**Issue by TomOne** [chocolatey/chocolatey-coreteampackages#65]
The thunderbird package needs the same fixes as Firefox in https://github.com/chocolatey/chocolatey-coreteampackages/commit/2e3a83b31ac3324177b542ac6fb1fabab7c63b7d.

**Comment by ferventcoder** [comment]
Great that you are fixing - I enhanced Chocolatey in 0.9.9.4 to handle these

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/issues/207

**Comment by TomOne** [comment]
Fixed with https://github.com/chocolatey/chocolatey-coreteampackages/commit/198f4b070012b9e6c1fb6f1781be786d062eaeb1.
