### ISSUE TITLE
(7zip) installing wrong architecture

### ISSUE THREAD

**Issue by wilddev65** [chocolatey/chocolatey-coreteampackages#663]
The recent update a day ago changed how 7zip is installed via chocolatey and it now installs the 32-bit version on a 64-bit OS. I believe the relevant lines in chocolateyinstall.ps1 are;
$filePath = if ((Get-ProcessorBits 64) -and $env:chocolateyForceX86 -ne $true) {
       Write-Host "Installing 64 bit version" ; gi $toolsDir\*_x32.exe }
else { Write-Host "Installing 32 bit version" ; gi $toolsDir\*_x64.exe }

The Get-Item is swapped for the package it's using.

**Comment by AdmiringWorm** [comment]
thanks for opening this. I'll have it fixed soon.

**Comment by AdmiringWorm** [comment]
fixed in https://github.com/chocolatey/chocolatey-coreteampackages/commit/5e68553c682787eaf014efdaac2688f02c6d83b9

should be available on chocolatey.org in a couple of hours.
