### ISSUE TITLE
(googlechrome) Switching from 32-bit to 64-bit

### ISSUE THREAD

**Issue by mattheyan** [chocolatey/chocolatey-coreteampackages#667]
Hi,

I recently ran into an issue with the `GoogleChrome` package. I noticed that the package was switching Chrome from 32-bit to 64-bit on 64-bit systems, but didn't think it would be a problem. Since it ended up causing problems for me I had to look into it further.

I tested the registry key check that the package is using and it does not return a value to indicate that Chrome is 32-bit on example systems where Chrome is in fact 32-bit.

I found [this group post](https://productforums.google.com/forum/#!topic/chrome/w93eUkzgkEo) where the poster mentions that he noticed a file that was only present for 32-bit installs. This is part of the script I ended up using to check for 32-bit vs. 64-bit and it seems to be working so far FWIW. Horrible, I know, but its what I had to do to solve our problem.

```
$os = Get-WmiObject -Class 'Win32_OperatingSystem'

if ($os.OSArchitecture -eq '64-bit') {
	$appDir = "$(${env:ProgramFiles(x86)})\Google\Chrome\Application\$($chromeVersion)"

	if (-not(Test-Path $appDir)) {
		Write-Error "Path '$($appDir)' doesn't exist."
		return
	}

	if ((Test-Path "$($appDir)\nacl64.exe") -and (Test-Path "$($appDir)\nacl_irt_x86_32.nexe")) {
		return $chromeVersion
	}

	return "$($chromeVersion) (64-bit)"
}

return $chromeVersion

```

Anyway, I thought you might want to know that this could potentially be causing issues for others. Feel free to adapt the code above if you want, or look for a better solution. Or, if not maybe put a disclaimer in the package description?

Thanks,
Bryan

**Comment by AdmiringWorm** [comment]
The package should actually already check if a 32bit version of chrome is already installed.
It does the check based on a registry value as can be seen here: https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/GoogleChrome/tools/helpers.ps1#L1

Can you verify that the used registry key and value is no longer created, or is perhaps being set to another value?

**Comment by mattheyan** [comment]
@AdmiringWorm The registry key did not exist when I checked last week.

**Comment by AdmiringWorm** [comment]
@mattheyan I see, we'll definitely need to look into this then.
I'm a little busy with some other stuff right now, but I'll look into this whenever I'm done with everything else I'm planning.

**Comment by mattheyan** [comment]
@AdmiringWorm I understand. FWIW, I tested this is on Windows Server (both 2012 R2 and 2008 R2), I have not tested on workstations.

**Comment by AdmiringWorm** [comment]
@mattheyan good to know.
Those two are what I usually test the packages on as well (sometimes on a Win 7 environment as well)

**Comment by majkinetor** [comment]
We can add this as a fallback when registry key doesn't exist.

**Comment by mattheyan** [comment]
@majkinetor That makes sense. This seems like one of those cases where you have to try multiple things until something works. ;)

**Comment by majkinetor** [comment]
I can confirm that on my x64 bit install `nacl_irt_x86_64.nexe` exists

**Comment by majkinetor** [comment]
That is, its named `C:\Program Files (x86)\Google\Chrome\Application\57.0.2987.133\nacl_irt_x86_64.nexe`

**Comment by mattheyan** [comment]
@majkinetor Yes, I think that file should be present in all Chrome installs. The files `nacl64.exe` and `nacl_irt_x86_32.nexe` should be present in 32-bit installs based on what I've seen.

**Comment by AdmiringWorm** [comment]
I can confirm that the `nacl_irt_x86_32.nexe` is present in 32-bit installs and not in 64-bit installs.

Can also confirm that the registry key we already checks is also present, but have changed to `x64-stable` for 64-bit installs and `stable-arch_x86` for 32-bit installs.

So changing the check for the registry key first, and then falling back to the file based check would be the best option IMO.
