### ISSUE TITLE
(Set-DescriptionFromReadme) Allow option combine line endings

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#685]
Considering the markdown used in the Readme files here on github uses soft line breaks, and chocolatey.org uses hard line breaks (all line breaks is replaced with `<br />`) I think it would be useful to extend the script to allow the descriptions line breaks (unless ending with two spaces, or a blank line) to be combined.

I can of course look into this, but wanted your thoughts on it first @majkinetor .

**Comment by majkinetor** [comment]
I solved it for my case by not using breaks in `README.md`, seems like an easier solutions. Show up nice on both places and you can always ward wrap when editing it.

**Comment by AdmiringWorm** [comment]
true, that's an easier solution. I would still like to have the option of converting the line breaks though, if that's a change you would be okay with.

**Comment by majkinetor** [comment]
Sure.

**Comment by AdmiringWorm** [comment]
I'm putting this on hold for the moment, even-though I would find it useful it isn't a priority right now.
I need to get around to compile a list of exceptions where we shouldn't combine the line breaks (in a list, a header, empty line, code block, etc.)

**Comment by majkinetor** [comment]
Too much work for almost zero benefit.

**Comment by AdmiringWorm** [comment]
> Too much work for almost zero benefit

true, it's. I still want to do it though, I get annoyed all the time with chocolatey and its hard line breaks.
Although editors usually have the option to wrap lines, I still find it annoying and don't really like it.

**Comment by AdmiringWorm** [comment]
I'm closing this, I don't think I'll start working on this any time soon. I'll reopen it if I ever start working on it though.
