### ISSUE TITLE
Script for URL redirects

### ISSUE THREAD

**Issue by RedBaron2** [chocolatey/chocolatey-coreteampackages#687]
@majkinetor @ferventcoder @AdmiringWorm @gep13 @pascalberger
I have been seeing a lot of the websites that have software for download using a redirect. Although they don't need to be as complex as the now [Deprecated]  'Chocolatey FossHub Extension' package. This seems to be a needed item. The  @The-Running-Dev whipped up a useful [script](https://github.com/The-Running-Dev/chocolatey-coreteampackages/blob/6780c247c4e1c5b2b7f4d92a48aa9ed10c7f28e9/automatic/dropbox/update.ps1#L42-L55) that is part of PR #664 that handles this redirect nicely. It can also be used in another or other package(s) that have redirects.

When this was mentioned on gitter @AdmiringWorm wanted to have it discussed. 

This is the opened issue for that discussion.

**Comment by majkinetor** [comment]
The script is way simplistic. To get included into core it would have to support multuple redirections and proxy and headers.

**Comment by The-Running-Dev** [comment]
@majkinetor Feel free to make it more complicated :-)

**Comment by majkinetor** [comment]
No I wont, but I have a great quote:

> Everything Should Be Made as Simple as Possible, But Not Simpler

**Comment by majkinetor** [comment]
Closing due to no feedback.

**Comment by AdmiringWorm** [comment]
I've added a few days ago a simple redirect script, it uses another way to read the redirected url than the function created by @The-Running-Dev.
Instead of disabling `AllowAutoRedirect` and reading the response status code, it allows it and  read the `ResponseUri` instead.

https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/scripts/Get-RedirectedUrl.ps1

It's pretty simplistic right now, but for now it works. When it's needed it can be extended of course.

**Comment by majkinetor** [comment]
Wont do without proxy.

**Comment by AdmiringWorm** [comment]
@majkinetor if it was part of the install script I would agree, but considering it's just a script for using with updating the package itself it doesn't really matter.
In which case, all of the calls (for every package) to iwr need to be changed as well to add support for proxies.

**Comment by AdmiringWorm** [comment]
Same would be with the `Get-RemoteFiles` which uses the `WebClient` .NET class as well.

**Comment by majkinetor** [comment]
I thought it would be used within installer.  

BTW, iwr handles proxy automatically from the system.

**Comment by AdmiringWorm** [comment]
> I thought it would be used within installer.

yeah no, only for the update script.

> BTW, iwr handles proxy automatically from the system.

I see, didn't know that. I thought it didn't
