### ISSUE TITLE
(python-*_32) Deprecate packages

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#696]
Packages
 * http://chocolatey.org/packages/python-x86_32
 * http://chocolatey.org/packages/python2-x86_32
 * http://chocolatey.org/packages/python3-x86_32

should be unlisted now that install parameters can be remembered since you can just `ForceX86` for the same effect without fear that it will later revert to x64 version.

**Comment by AdmiringWorm** [comment]
I've already seen this issue, still contemplating on the whole unlisting though.
Even though it won't get updated anymore, it still have some kind of historical value.
I think it perhaps would be more appropriate to *semi-deprecate*  it instead, adding a install script that just throws out an exception mentioning to install the non x86_32 package with the `ForceX86` parameter.
(Of course also add it in the description)

**Comment by majkinetor** [comment]
I pushed all packages. They show a message and throw, so they can't really be installed. Because of throwing they can't pass automated test and they should be white listed.

**Comment by AdmiringWorm** [comment]
packages have been approved
