### ISSUE TITLE
Find alternative locations or embedd CodePlex software

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#698]
Since codeplex is shutting down this year we should start moving packages that download software from codeplex to embedded software or find alternative download locations.
If we can't find alternative locations, we should definitely move the software to the manual directory.
But this would require a change in how we use the `[PUSH packageName]` in the git title as we need to support downloading the software somehow before packing it.
Or we could take the easy route and just drop everything related to the affected packages.

as far as I know there is only two packages that download from codeplex
[ontopreplica](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/ontopreplica) *This package have not yet been migrated to AU*
and
[svg-explorer-extension](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/manual/svg-explorer-extension) *Have not looked at the package, but I'm guessing this could be embedded*

/CC @majkinetor @pascalberger @gep13

**Comment by majkinetor** [comment]
There is no need for that. Both should be embedded and moved to manual packages. 3 years without any update.

**Comment by AdmiringWorm** [comment]
@majkinetor the svg-explorer-extension is already moved to manual directory.

quoting myself
> But this would require a change in how we use the [PUSH packageName] in the git title as we need to support downloading the software somehow before packing it.

^^ or alternatively, allow binaries to included inside the manual directory (which would probably be a better option).

**Comment by majkinetor** [comment]
You can always force specific files in the repo no matter what is ignored. Just force git add.

However, I added in `[PUSH pkg]` section to call update.ps1 in manual package if it exists. It can be as simple as:

```
iwr "http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=ontopreplica&DownloadId=780725&FileTime=130345325848130000&Build=21050" -OutFile tools\setup.exe -UseBasicParsing
```

**Comment by pascalberger** [comment]
> ^^ or alternatively, allow binaries to included inside the manual directory (which would probably be a better option).

If going this way make sure to use [git-lfs](https://git-lfs.github.com/) to avoid bloating the repository.
