### ISSUE TITLE
(Opera) AU - no new version

### ISSUE THREAD

**Issue by shutovilya** [chocolatey/chocolatey-coreteampackages#703]
No new version of Opera in repo. As I understood, choco-bot must autoupdate it, but it wasn't

**Comment by AdmiringWorm** [comment]
thanks for opening this issue, I've looked at the problem regarding this and seems like we are incorrectly sorting the versions when we try grabbing the latest version.
I'll see if I can't get it updated asap (working on also adding 64bit to the package, so may take some time)

**Comment by AdmiringWorm** [comment]
this is now in the process of getting pushed to chocolatey.org.
Once again, thank you for opening this issue.
