### ISSUE TITLE
(OpenSSL.Light) 1.1.0.40000000 installs directly to C:\

### ISSUE THREAD

**Issue by trondhindenes** [chocolatey/chocolatey-coreteampackages#712]
previous versions installed to %ProgramFiles%, so this is is probably a bug

**Comment by AdmiringWorm** [comment]
Definitely an oversight when I migrated the openssl.light package to AU.
I don't know when it will get fixed though, but a temporary workaround you can use is
to call choco install/upgrade with the following arguments
`--params '"/DIR=C:\path\you\want\to\install\into"'`
