### ISSUE TITLE
Package changelogs

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#715]
Opening this for discussion for whether we should provide changelogs for when bugs/feautres have been fixed/added to the package, and if we should start adding changelogs then which format should we use.

Personally I think it would be helpful to add changelogs, and use a dates when these changes was implemented.
I.E.
```markdown
# Package Changelog

## 2015-05-01
### Bugs
- Fixed a problem that the wrong install directory was used (Issue \#457)

### Features
- Implemented ability to enable symlinks (Issue \#578)
```

Probably shouldn't require it though, not at first. But just recommend to add one.

Thoughts @gep13 @pascalberger @majkinetor

**Comment by AdmiringWorm** [comment]
Another option could perhaps be to just use a generic `## Upcoming` subheader and have it replaced with the version when it have been pushed from appveyor (using a script).

**Comment by majkinetor** [comment]
Changelog.md in package root might be good to have. Should probably be included in the package as it can be viewed from the gallery.

**Comment by AdmiringWorm** [comment]
Yeah, it was in the package root I was thinking as well.
Not sure about including it in the package though, think it would be better to link to the changelog in the release notes element IMO.
Even though the changelog would be viewable on chocolatey.org, if using markdown it would just be displayed as ordinary text.

**Comment by AdmiringWorm** [comment]
@majkinetor I've added a PR as an example to one way I think the changelogs could be implemented.
see PR #716

**Comment by majkinetor** [comment]
I think its hard to read with all that subheaders. Peraps just use Bugfix prefex ?

**Comment by majkinetor** [comment]
> Not sure about including it in the package though, think it would be better to link to the changelog in the release notes element IMO.

Not sure either. One rationale to include it was that you don't have to depend on external sources in order to see it which may be important for some people, especially those that cache it.

**Comment by AdmiringWorm** [comment]
> Peraps just use Bugfix prefex and just version header ?

You mean something similiar to the [changelog used in chocolatey-core.extension](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/extensions/chocolatey-core.extension/CHANGELOG.md)?

Personally I like to separate bugfixes and features/improvements to their own section (under the version), as well as having the date it was added, and I don't really find the [7zip.install changelog](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/7zip.install/Changelog.md) I added hard to read.
With that said though, formatting could definitely be improved.

**Comment by majkinetor** [comment]
> You mean something similiar to the changelog used in chocolatey-core.extension?

Yeah, thats way more readable IMO

> Personally I like to separate bugfixes and features/improvements

They can be separated without a header. The header formatting makes more sense where there are expected many changes across versions, packages will usually only have 1 thing per version, usually no more then 2 in any case, which makes headers just spam. So no, formatting can not be improved, its about ratio of header lines / changes which will here be most of the time > 1.

**Comment by majkinetor** [comment]
To resume, we are for changelog.

Closing this.
