### ISSUE TITLE
(ghostscript.app) Fix urls for older version

### ISSUE THREAD

**Issue by teknowledgist** [chocolatey/chocolatey-coreteampackages#719]
Hi guys,

I am the maintainer of GSView (GhostScript PreViewer) which is depended on
GhostScript. I recently discovered that my v5 release needed a max version
(9.16) on the GhostScript dependency. My package is failing because the url
on the old GhostScript package version is no longer valid. Would you be
willing to update that old 9.16 package?

You'll need some new information in the `chocolateyInclude.ps1` file:
``` 
$url = 'http://downloads.ghostscript.com/public/old-gs-releases/gs916w32.exe'
$url64 = 'http://downloads.ghostscript.com/public/old-gs-releases/gs916w64.exe'
$checksum = '53E30B22F7DC9E26685EF18AD969650C9573F42D281257DBBFF02D9403F89502'
$checksum64 = '3E19A2316BEE2CC655395C16CAD0970D058B29E00EC4DB1290A92180FAC28FB6'
$checksumType = 'sha256'
```
(and the checksums passed to `Install-ChocolateyPackage`)

There is a v6 of GSView that works with the newest GhostScript, but it is
actually a different product with different owners, license, code base and
everything. I'd like to have both the v5 and v6 versions working and
available in case the differences are meaningful to some users.

Thanks.

**Comment by AdmiringWorm** [comment]
Thanks for creating this issue, updating older packages isn't really a priority right now but I'll see if I can't update that specific version some time this week.
Do note though, it will be updated to be similar to how we are handling the latest releases of Ghostscript (embedding the installer), and the version won't be the same (once a version is approved it is immutable)

**Comment by teknowledgist** [comment]
I understand fully.  Whenever you get a chance is just fine.

Thanks.

**Comment by AdmiringWorm** [comment]
Thank you for understanding, I'll see if I can't get around to updating tomorrow or the coming weekend.
(I make no promises though, not yet)

**Comment by AdmiringWorm** [comment]
Of course if you would be able to help out, it would be most appreciated.
It's actually quite simple to update (kinda) older versions, what is needed is to update the following [update.ps1](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/Ghostscript/update.ps1) file to grab the url from the version you need, as well as set the version in the nuspec files for [Ghostscript](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/Ghostscript/Ghostscript.nuspec) and [Ghostscript.app](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/Ghostscript.app/Ghostscript.app.nuspec) to  `9.16`.
Then only open a PR and mention in the description it is a temporary change to update an older version, and should be reverted when it have been updated and that the PR should be merged with `[AU ghostscript ghostscript.app]` (this may not be required, depending on who reviews the opened PR though)

**Comment by AdmiringWorm** [comment]
@teknowledgist in the process now for pushing an update for version 9.16, keep a lookout for the new version on chocolatey.org
