### ISSUE TITLE
(vcredist2008) Garbage in the root drive

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#724]
This is what I have on all my computers after vcredist is installed which is highly annoying. The `install.exe` starts vcredist 2008 setup.

I believe the package is this one: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/vcredist2008/9.0.30729.6161

@jberezanski, would it be possible for you to move it here and fix this ?

```
PS: ls c:\

-a----       2007-11-07     07:00          17734 eula.1028.txt
-a----       2007-11-07     07:00          17734 eula.1031.txt
-a----       2007-11-07     07:00          10134 eula.1033.txt
-a----       2007-11-07     07:00          17734 eula.1036.txt
-a----       2007-11-07     07:00          17734 eula.1040.txt
-a----       2007-11-07     07:00            118 eula.1041.txt
-a----       2007-11-07     07:00          17734 eula.1042.txt
-a----       2007-11-07     07:00          17734 eula.2052.txt
-a----       2007-11-07     07:00          17734 eula.3082.txt
-a----       2007-11-07     07:00           1110 globdata.ini
-a----       2007-11-07     07:44         855040 install.exe
-a----       2007-11-07     07:00            843 install.ini
-a----       2007-11-07     07:44          75280 install.res.1028.dll
-a----       2007-11-07     07:44          95248 install.res.1031.dll
-a----       2007-11-07     07:44          90128 install.res.1033.dll
-a----       2007-11-07     07:44          96272 install.res.1036.dll
-a----       2007-11-07     07:44          94224 install.res.1040.dll
-a----       2007-11-07     07:44          80400 install.res.1041.dll
-a----       2007-11-07     07:44          78864 install.res.1042.dll
-a----       2007-11-07     07:44          74768 install.res.2052.dll
-a----       2007-11-07     07:44          95248 install.res.3082.dll
-a----       2007-11-07     07:00           5686 vcredist.bmp
-a----       2007-11-07     07:50        1927956 VC_RED.cab
-a----       2007-11-07     07:53         242176 VC_RED.MSI
```

**Comment by jberezanski** [comment]
Yeah, I could give it a shot. At first glance, however, the package does not do anything out of the ordinary, so it will probably mean debugging the native installer to determine the way to convince it to put its temp files elsewhere.

**Comment by AdmiringWorm** [comment]
Looks like this was a known bug for the vcredist 2008 installer, seems like the recommended aproach is to install vcredist 2008 SP1 which have fixed that bug.
https://support.microsoft.com/help/950683/vcredist-from-vc-2008-installs-temporary-files-in-root-directory

**Comment by jberezanski** [comment]
OK, so according to [this](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) the package should be updated to install https://www.microsoft.com/en-us/download/details.aspx?id=26368.

**Comment by majkinetor** [comment]
URLs I got when downloading this from MS site are:

- https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe
- https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x64.exe

Is this safe to use, i.e. not something that will expire ?

**Comment by jberezanski** [comment]
Yes, download.microsoft.com urls are generally stable (apart from very rare cases when MS decides to remove a download).

**Comment by majkinetor** [comment]
Looks like dtgm package is already of that version. I will migrate it here just for the sake of all vcredists to be on the same place.

**Comment by majkinetor** [comment]
I don't know how then, I still get the garbage in the root. Perhaps some other package depends on particular version ? If that is the case it might be good idea to unlist other versions, then those packages will fail and can be fixed to use the latest one.

**Comment by AdmiringWorm** [comment]
If they depend on an exact version, they wouldn't fail as the package version is still there just not shown on the website.

**Comment by majkinetor** [comment]
Then we would know that package failed and can fix it to use new version instead of adding garbage to the root. It might not be good idea tho on 2nd thought.

**Comment by majkinetor** [comment]
Will reopen it until its pushed.

**Comment by majkinetor** [comment]
Should I  push this with `9.0.30729.6162`? (added +1) or something else ?

**Comment by AdmiringWorm** [comment]
Personally I would probably add `01` to the existing version (using zero a separator between version and fix), but considering the redistributable will unlikely ever be updated again I'm fine with either way.

**Comment by jberezanski** [comment]
A minor issue - tags contain "2017" instead of "2008".
Just checked installing interactively on a Win7-32 VM, no garbage. According to logs (%TEMP%\dd_vcredist*.txt) the files got extracted to C:\<a_directory_name_which_looks_like_a_guid> and that directory was removed at the end of install.
Will check via choco now.

**Comment by majkinetor** [comment]
Thx, fixed tag.

**Comment by jberezanski** [comment]
choco 0.10.3 on Win7-32 - no garbage
choco 0.10.3 and 0.10.5 on Win10.1607-64 - no garbage (also when installed as dependency of `vcredist-all`)
@majkinetor perhaps it's something specific to your setup that causes this - custom permissions on C:\? antivirus?

**Comment by majkinetor** [comment]
nah, several different machines.

**Comment by majkinetor** [comment]
OK, will close this and leave package unpushed for now. Will try to determine more precise how this happen and eventually reopen this.

**Comment by mmikeww** [comment]
I just got this too. WTF

**Comment by majkinetor** [comment]
I am using winmerge too.
