### ISSUE TITLE
(OpenSSL.Light) 1.1.0.40000001 installation fails with Not Found 404

### ISSUE THREAD

**Issue by dimitarivanov** [chocolatey/chocolatey-coreteampackages#726]
The download address of the installation package does not exist.
The new URL has a letter 'k' appended after the version number: https://slproweb.com/download/Win64OpenSSL_Light-1_0_2k.exe

> Attempt to get headers for https://slproweb.com/download/Win64OpenSSL_Light-1_0_2.exe failed.
>   The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://slproweb.com/download/Win64Ope
> nSSL_Light-1_0_2.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404)
>  Not Found."
> Downloading OpenSSL.Light 64 bit
>   from 'https://slproweb.com/download/Win64OpenSSL_Light-1_0_2.exe'
> WARNING: Write-ChocolateyFailure is deprecated and will be removed in v2. If you are the package maintainer, please use
> 'throw $_.Exception' instead.
> ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://slproweb.com/download/Win
> 64OpenSSL_Light-1_0_2.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error:
> (404) Not Found."
> The install of openssl.light was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\OpenSSL.Light\tools\chocolateyInstall.ps1'.
>  See log for details.

**Comment by AdmiringWorm** [comment]
You're not trying to install version 1.1.0.40000001 (We embedd the installer in the package, rather than downloading it during install), it seems you're trying to install an older version of OpenSSL.Light (this is not yet supported).

I'm going to close this with the wontfix tag, although support for older versions may be added in the future there is no plans for that right now.

**Comment by dimitarivanov** [comment]
I used the standard command to install openssl and I didn't specify a version.
> choco install openssl.light

**Comment by AdmiringWorm** [comment]
then it could be a caching issue (happens from time to time).
try installing with and explicit version.
`choco install openssl.light --version 1.1.0.40000001`

or perhaps you have another feed that is used which only contain a earlier version of openssl.light.

**Comment by dimitarivanov** [comment]
Specifing the version did it.
Thanks!
