### ISSUE TITLE
(apache-httpd) migrate repo to core team

### ISSUE THREAD

**Issue by photodude** [chocolatey/chocolatey-coreteampackages#728]
As [per suggestion](https://github.com/rgra/choco-packages/pull/13#issuecomment-301631450), we should migrate apache-httpd to the core team repo so it can be automatically updated.

**Comment by AdmiringWorm** [comment]
Feel free to open a PR to migrate the package here, just make sure to follow our [guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md) and to get the permission of the original maintainer to move it here (if you can't get permission, you'll need to follow the official chocolatey [triage process](https://chocolatey.org/docs/package-triage-process) before we can accept it).

If you have any questions, then feel free to jump into our [gitter channel](https://gitter.im/chocolatey/chocolatey-coreteampackages?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) (I'll be gone most of the day, but there are several other people in that room that may be able to answer your questions)

**Comment by photodude** [comment]
I've thought about making a PR, but I feel I've very much out of my skill zone and capabilities (I have a lot on my plate at the moment and for the next few months).

I did attempt to rewrite the package once following what you did for PHP. see https://github.com/rgra/choco-packages/pull/17
I'm not at a point where I am confident it works (I haven't been able to attempt testing locally, it's a bit beyond my skills at the moment) but it might help someone in the process of the migration.

There are also a number of issues/requests that should be looked at, and if possible included in any migration. 
- https://github.com/rgra/choco-packages/issues/6
- https://github.com/rgra/choco-packages/issues/7
- https://github.com/rgra/choco-packages/issues/14
- https://github.com/rgra/choco-packages/issues/15
- https://github.com/rgra/choco-packages/issues/16

**Comment by photodude** [comment]
I made an attempt at #745 it currently is failing as I did something wrong.

**Comment by photodude** [comment]
closing via https://github.com/chocolatey/chocolatey-coreteampackages/pull/747
