### ISSUE TITLE
(poweriso) Package needs update

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/chocolatey-coreteampackages#729]
In Feb 2017 v6.8 was released.
Yes, I realize the download link is now "protected."
License says "By installing, **copying**, or otherwise using the SOFTWARE PRODUCT, you agree" which seems to imply that copying is allowed and the Chocolatey package could include the binary. Even better to e-mail them and ask for specific allowance of redistribution. Seems logical that they'd want to get the program into as many computers as possible to then beg for a license purchase.

Additionally:
bugtrackerurl should be updated to: http://www.poweriso.com/tutorials/history.htm
licenseurl should be updated to: http://www.poweriso.com/tutorials/eula.htm

**Comment by AdmiringWorm** [comment]
They also have the sentence:
> The licensee shall not use, copy, rent, lease, sell, modify, decompile, disassemble, reverse engineer, or transfer the 
licensed SOFTWARE PRODUCT except as provided in this agreement. Any such unauthorized use shall result in immediate termination of this license.

which makes me think we can not embedd the software, as well as the license don't explicitly state that we can distribute the software (which a license need to state if we are to embedd the installer on chocolatey.org).

Of Course, contacting them and asking for redistribution rights should be done.
I'll update the bugtrackerUrl and licenseUrl you mentioned, but unfortunately I won't be looking into fixing the updating of poweriso any time soon.

**Comment by AdmiringWorm** [comment]
btw, 6.8 was actually pushed in the past, but was rejected as the automated testing didn't pass and no-one looked into why.

**Comment by AdmiringWorm** [comment]
wait, the link you provided isn't to a bug tracker, but rather to the release notes

**Comment by AdmiringWorm** [comment]
I've tried to re-push the 6.8 version, we'll see if it passes automated testing this time though.

**Comment by AdmiringWorm** [comment]
Looks like the re-push of the 6.8 version passed validation, so closing this issue now.
