### ISSUE TITLE
Cywgin install does not pass chocolately detected proxy settings

### ISSUE THREAD

**Issue by RogerThiede** [chocolatey/chocolatey-coreteampackages#73]
Unable to install [Cygwin](https://chocolatey.org/packages/Cygwin) package when a proxy is necessary.

Cywgin is installed via an external installer that is referred to as the installerFile.  [chocolateyInstall.ps1](https://github.com/chocolatey/chocolatey-coreteampackages/blob/e30b1a1fd4874928038e3fc6837f63c7fc626c98/automatic/Cygwin/tools/chocolateyInstall.ps1) does not forward any detected proxy settings onto the installerFile which is needed when Chocolately is using a proxy.  The cygwinInstall.exe command line arguments needed is [--proxy](https://cygwin.com/faq/faq.html#faq.setup.cli)

**Comment by ferventcoder** [comment]
This sounds like the package will need to do some detection to be able to pass that. Or we can set up package parameters so this can be passed in.

**Comment by pyhedgehog** [comment]
Had same problem - found work-around:
cinst -y cygwin --ia --proxy=proxy:8080

**Comment by ferventcoder** [comment]
Let's keep an eye on this that needs to be fixed first - https://github.com/chocolatey/choco/issues/243

**Comment by ferventcoder** [comment]
In the latest - cyg-get v 1.2.0 (in moderation at the moment) you can pass `cyg-get -proxy value`

See `cyg-get -help` once you've updated.
