### ISSUE TITLE
(sysinternals) Add portable tag

### ISSUE THREAD

**Issue by SamuelEnglard** [chocolatey/chocolatey-coreteampackages#730]
To make it easier to find that this package is portable I'd like to propose adding the tag "portable"

**Comment by AdmiringWorm** [comment]
for which packages?
We currently have around 180 packages in this repository, and not all of them is portable.

I'm sorry to say, I'm not going through all those packages just to determine which package need the `portable` tag.

**Comment by SamuelEnglard** [comment]
Woops, sorry. That's what I get for multi-tasking. For `sysinternals`

**Comment by AdmiringWorm** [comment]
I'll see, hopefully I can get that tag in before the update version is approved
