### ISSUE TITLE
(vlc) Updating resets VLC configuration settings

### ISSUE THREAD

**Issue by 07416** [chocolatey/chocolatey-coreteampackages#738]
https://chocolatey.org/packages/vlc

Updates 2.2.5.1 and 2.2.6 wiped VLC config settings - this has also happened before, but I can't personally verify with which releases. Can user data be preserved? 
VLC settings are stored in `~AppData\Roaming\vlc`.

**Comment by AdmiringWorm** [comment]
Considering the `AppData` is user specific, I'm against doing anything inside the script to backup and restore the settings, especially considering the script is running as administrator (some circumstances it may run under the system account, in which case the found `AppData` folder wouldn't be the correct one).

So unless the installer actually supports an argument to passed to keep the configuration, this likely won't be fixed.

**Comment by 07416** [comment]
@AdmiringWorm What I don't understand is why the settings are cleared when installed with Chocolatey, but not when installing with [the official installer](https://www.videolan.org/vlc/download-windows.html)?

**Comment by AdmiringWorm** [comment]
It shouldn't, we basically just call the installer using the necessary arguments for silent installs.
We don't even touch the `AppData` directory at all in the script, so unless the developers of VLC automatically removes the configuration when running a silent install then this sounds like a bug in the installer.

**Comment by majkinetor** [comment]
We use the same installer. It might be the upstream bug.

**Comment by AdmiringWorm** [comment]
@07416 I'm pretty much of the opinion that this is an upstream bug (as @majkinetor said), possibly because silent arguments are used (I've seen this happen a few times for other softwares, which used bad defaults), and should be fixed there and not in the package.
As such I'm closing this Issue, feel free to re-opening it if you disagree though.
