### ISSUE TITLE
(hedgewars) Failing the verifier

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#739]
https://gist.github.com/choco-bot/93480f1f949af4f1b315f29a047b93bf

I've taken the necessary steps locally to embedd the package and updated using the correct url, unfortunately the download link on their website is currently down, so an updated package can't be pushed yet though, but should be monitored so when the download link is up again then we should push the package.

**Comment by AdmiringWorm** [comment]
Damn, looks like the installer may be a few megs too large to embed. Will know for sure when the download url starts working again.

**Comment by majkinetor** [comment]
Compress it with something stronger perhaps ?

**Comment by AdmiringWorm** [comment]
Possibly, but I'm not entirely sure of the size since the download links listed on the page doesn't work right now.
Need to see the actual size when it starts working again.

**Comment by AdmiringWorm** [comment]
Hmm, seems like chocolatey.org reports that hedgewars is too large, oddly enough though is that when I checked the package locally it's 144MB. So unless chocolatey.org only counts 1000 bytes per KB, then there is something wrong I believe.

I've fixed it locally, but I'm waiting with the push until I've heard back from Rob.

**Comment by majkinetor** [comment]
The same thing happend with [Calibre too](https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e/f4bfc31d9f1163069aa206f536b07fe4b628e4a4) althouth the combined size is way way lower then 150MB

/cc @ferventcoder

**Comment by AdmiringWorm** [comment]
The size limit have been fixed, and hedgewars have been pushed.
