### ISSUE TITLE
cyg-get.ps1 local_key

### ISSUE THREAD

**Issue by Voskrese** [chocolatey/chocolatey-coreteampackages#741]
Приветствую, столкнулся с такой проблемой, установлен давно cygwin
Но установить cyg-get никак не мог

```
> E:\tools\source>cyg-get mc -arch x86_64
> Attempting to install cygwin packages: mc
> C:\ProgramData\chocolatey\lib\cyg-get\tools\cyg-get.ps1 : Please ensure you have Cygwin installed.
> To install please call 'choco install cygwin' (optionally add -y to autoconfirm).
> ERROR: Не удается выполнить команду из-за следующей ошибки: Не удается найти указанный файл.
> строка:1 знак:1
> + & 'C:\ProgramData\chocolatey\lib\cyg-get\tools\cyg-get.ps1'  mc -arch ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,cyg-get.ps1
```

прописывание переменных так же не помогло

~cyg-get mc --root E:\tools\cygwin~
~set cygwin=E:\tools\cygwin\cygwinsetup.exe~
~set PATH=%PATH%;E:\tools\cygwin;E:\tools\cygwin\bin~
~set cygRoot=E:\tools\cygwin~

и прописать свой путь к ПО
$cygRoot = 'c:\tools\cygwin'

на , в моем случае E:\tools\cygwin
$cygRoot = 'E:\tools\cygwin'

**Comment by AdmiringWorm** [comment]
Aaandd I understand nothing, please repeat everything in English (I'll be closing this until an english translation is available).

**Comment by Voskrese** [comment]
получается вы игнорируете ошибки только из за того что я не разговариваю на англ.?
это ж прямая дискриминация по языковому признаку) даже смешно
