### ISSUE TITLE
(ruby) Ruby 2.4.1.1 is not unattended

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#742]
This window comes up (but it does not block the install from finishing):
![image](https://cloud.githubusercontent.com/assets/63502/26527879/bc7f36f4-4362-11e7-9242-2ffc9201aee3.png)

https://github.com/oneclick/rubyinstaller2/issues/43

**Comment by pauby** [comment]
I got this yesterday and didn't have time to do anything about it. Menu
pops up giving you three options to install.

I only have Ruby installed as Vagrant needs it.

Paul

**Comment by AdmiringWorm** [comment]
@pauby vagrant doesn't really need it though, they have included the binaries for ruby in the installer.

**Comment by pauby** [comment]
@AdmiringWorm I checked the vagrant package and the previous version and neither have a dependency on Ruby. I have no idea what is going on with Ruby then!

Apologies guys. False alarm. But I did see the Ruby pop just the other day as I said, while installing a chocolatey package (that I'm sure was vagrant).

**Comment by AdmiringWorm** [comment]
> I checked the vagrant package and the previous version and neither have a dependency on Ruby. I have no idea what is going on with Ruby then!

Exactly, a dependency for it have never been needed (as far as I know), the necessary ruby binary have always (again, as far as I know) been installed with the vagrant installer.

![image](https://cloud.githubusercontent.com/assets/1474648/26532274/a399864a-43fc-11e7-86b0-b31601dc101a.png)


ANYWAYS, with that said. The problem with the ruby installer not being silent would definitely need to be fixed. Although, I've checkout the issue @ferventcoder linked to and it looks like this will be fixed automatically when the next ruby version is released (should we just wait it out, or actually do something before it's released?)

**Comment by pauby** [comment]
My view is if it's going to be fixed in the next release, assumiong that is weeks anot months away, then I wouldn't waste the time on fixing it. Tag the package as 'notsilent' and move on.

**Comment by AdmiringWorm** [comment]
considering adding the tag `notsilent` would require a new push anyhow, it should probably be looked into making it silent (for this version) anyhow.
Unfortunately, I'm not going to do that though (well not anytime soon anyhow)

**Comment by majkinetor** [comment]
I dont think any action is required here from us.

**Comment by ferventcoder** [comment]
Note that we can add the `noridkinstall` - https://github.com/oneclick/rubyinstaller2/wiki/FAQ#user-content-silent-install (the note there is only for anything past 2.4.1-1.

So it looks like this - `/verysilent /dir="c:\ruby24" /tasks="assocfiles, modpath, noridkinstall"`

And then we wait for the next release unless we want to start using the double zeros at the end until x is greater than 1 in 2.4.x. My vote is for waiting but adding that additional item.

**Comment by ferventcoder** [comment]
Created https://github.com/chocolatey/chocolatey-coreteampackages/pull/744.

**Comment by majkinetor** [comment]
I think its better to just leave it as it is as it affects only the single version that way (in non detrimental way). If we push this we will probably pollute several versions with added suffixes.

**Comment by pauby** [comment]
I am inclined to agree with @majkinetor on the basis that the new version of Ruby that will address this is imminent. As I said previously if it's week or months away then, now that we know what the change is and it's fairly straightforward, should be done.

**Comment by larskanis** [comment]
RubyInstaller-2.4 is usable without MSYS2, but compilation of source gems requires MSYS2 (for nokogiri, rails, etc.). RubyInstaller2's default is to install a separate MSYS2 instance (typically into `c:/msys64`). However since chocolatey already ships MSYS2 as well, I think it's obviously to make use of that package.

Therefore I would recommend to set `noridkinstall` explicit and recommend the [MSYS2 package](https://chocolatey.org/packages/msys2) somehow. However I'm not really familiar with chocolatey and it's possibilities.

**Comment by larskanis** [comment]
Previous versions of RubyInstaller didn't know the `ridkinstall` or `noridkinstall` parameters, but simply ignore them if given. Similarly RubyInstaller-2.4 ignores parameters other than these in the [FAQ](https://github.com/oneclick/rubyinstaller2/wiki/FAQ#user-content-silent-install).

**Comment by majkinetor** [comment]
> RubyInstaller-2.4 is usable without MSYS2, but compilation of source gems requires MSYS2

This practically means its unusable IMO. Source gems are more rule then exception.

**Comment by ferventcoder** [comment]
That is not specifically as true anymore - for very highly used gems, there are platform-specific gems that don't require compilation. Take a look at [FFI](https://rubygems.org/gems/ffi/versions) and [nokogiri](https://rubygems.org/gems/nokogiri/versions) (the bane of my existence as a Ruby Windows developer).

That said, Jekyll I believe still requires DevKit, and Jekyll-based blogs / sites are heavily used.

**Comment by ferventcoder** [comment]
I prefer that we use the MSYS2 bundled with Ruby - just to cut down on any incompatibility issues. It would be nice to say that never happens, but Ruby on Windows is already quite finnicky, I'd rather not introduce anymore elements into the equation.

**Comment by ferventcoder** [comment]
I don't want an exact version dependency on the MSYS2 package either, as that could introduce weird incompatibilities outside of Ruby where someone is using the machine MSYS2 package for other things and needs updated versions. I actually preferred the vendored MSYS2 approach here as it will continue to allow me to have multiple versions of Ruby (and architectures MinGW vs MinGWx64) without fear of being setup incorrectly.
