### ISSUE TITLE
Adding powershell and guidelines validation

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#743]
Was just browsing around github a little now, and found the [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer).

I'm thinking this software could perhaps be used when validation Pull Requests (and none master branches perhaps), and since it looks like it can accept custom rules it probably can be extended to validate the guidelines for this repository (custom logic for the metadata would probably still be needed though, but it's a start).
I've not tested it out just yet though.

Thoughts?

/cc @gep13 @majkinetor @ferventcoder @pascalberger

**Comment by majkinetor** [comment]
I am OK with that as long as it is informative only. I wouldn't like, at least for the time being, to have have it blocking something (such as alias usage or non-verb named functions).  There are number of things that I disagree with with all analysers and if they are too intrusive I totally disable them.

>  And since it looks like it can accept custom rules it probably can be extended to validate the guidelines for this repository

I very much doubt that. There are only 2 Powershell code guides. All others would require dedicated system . For example [1.1.4](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md#114-embed-a-package-if-allowed) would require to have a list of licenses that allow redistribution, check if one of those licenses is set in nuspec, check if remote file sizes are lower then 150MB and only then complain about broken rule.

I am not sure that value of having guidelines check now justifies it development, at least not while we have only 2 active maintainers.

**Comment by pascalberger** [comment]
Integrating PSScriptAnalyzer would be nice (I already use it locally in Visual Studio Code through [PowerShell Language Support for Visual Studio Code](https://github.com/PowerShell/vscode-powershell)).

The tricky part might be how to provide the analyzing results back to the pull request. Having them posted back as comments would be nice, but AppVeyor doesn't support secret variables in pull request builds. Using a public token with a very limited scope (only permission to write comments) might be a solution.

For the part of posting the comments I have written a [Cake Addin](https://cake-contrib.github.io/Cake.Prca.Website/), which could be enhanced to support PSScriptAnalyzer and GitHub, but it would require to use Cake for the build.

**Comment by pauby** [comment]
Pester tests would seem like a better fit for some of the logic and testing of pull requests and this was something I was going to look at doing a little while ago and didn't get around to, for testing packages locally. PSScriptAnalyzer would be a good fit for testing rules on the scripts themselves such as testing for using deprecated functions etc.

As I was all set to also do a blog posts in the coming weeks on rolling your own PSScriptAnalzer rules I'm happy to pick this up but have not done any integration with Appveyor / Pull Requests so would need guidance there.

**Comment by majkinetor** [comment]
I agree that Pester seems like way better solution for guideliness check then PSScriptAnalyzer. Pester script with adequate arguments could be easily hooked into AU update process.

**Comment by majkinetor** [comment]
I will close this as there seem to be no more activity. If you feel there is more to be said, please reopen.
