### ISSUE TITLE
(sourcetree) Uninstalling the sourcetree package does not uninstall the software

### ISSUE THREAD

**Issue by ma499** [chocolatey/chocolatey-coreteampackages#746]
`choco uninstall sourcetree` on the current version (2.0.20.1) doesn't actually uninstall the sotware on Windows 10. Chocolately uninstalls the package but it then has to be removed manually using Windows Add/Remove Programs.

@ferventcoder [commented ](https://chocolatey.org/packages/SourceTree#comment-3332174780)that "This is likely due to an issue somewhere in seeing the registry changes on upgrade. "

**Comment by AdmiringWorm** [comment]
Considering it was previously was removed during uninstall, and nothing have changed in that department I'm thinking this may be a issue with choco itself perhaps.

@ferventcoder could correct me on that though.

**Comment by AdmiringWorm** [comment]
Of course, would probably be easy enough to provide a uninstall script though
