### ISSUE TITLE
(notepadplusplus.install) Make shim to executable

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#751]
Otherwise its not usable in shell easily.

**Comment by AdmiringWorm** [comment]
Sounds good, was genuinely surprised it didn't already do this.

**Comment by majkinetor** [comment]
Install packages usually do not do that - most of the users do not live in shell. I think we should make it standard ( i.e. look at it during review) for tools that have bigger potential to be usable from within shell.

**Comment by AdmiringWorm** [comment]
I'm not sure about making it a standard, but to take it under consideration and maybe suggest it if it's a tool that makes sense to use from a shell.
