### ISSUE TITLE
(apache-httpd) htdocs folder is removed on uninstall

### ISSUE THREAD

**Issue by photodude** [chocolatey/chocolatey-coreteampackages#754]
When Apache-httpd is uninstalled the htdocs folder is removed in the uninstall. 

As a default, if there is content in the htdocs folder; the folder should not be removed during the uninstall process.

### Expected
The htdocs folder should not have been removed on uninstall as there was content in the folder beyond the default index.html file and the apache icon file.

### Actual
The htdocs folder was completely removed on uninstall

**Comment by photodude** [comment]
Please reopen, this is an important issue. The htdocs folder should not be removed.

**Comment by majkinetor** [comment]
The issues hanged 6 mo and it reached the end of life.  We can't have issues pilling up here without any activity on them. 

Anybody can provide PR any time.

**Comment by majkinetor** [comment]
See [3.3](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md#33-open-issue-expires-after-6-months) about issue expiration.

**Comment by photodude** [comment]
Does anyone ever really work on an issue that is an "enhancement" or "up for grabs" and has been closed? 
Should we just pollute the issues by posting a new issue for this to ensure it's open and has a chance someone might work on it. That does not make a lot of sense to me.
I understand the policy, but the application of it clearly leaves a lot of things just hanging out in the wind to wither away.

I don't have the PowerShell knowledge or skills to deal with this issue, but it is a necessary one to be dealt with.
