### ISSUE TITLE
(apache-httpd) add option to select download source

### ISSUE THREAD

**Issue by photodude** [chocolatey/chocolatey-coreteampackages#758]
It would be helpful to have an option to select the download source for the package. Currently, the only option is to download package from apachehaus

## Expected behavior

a string/array parameter that allows selecting one of the two download sources for apache-httpd
this will then download the appropriate current version of apache-httpd package from that source. (note: semi-related other requests #752 #753)

## Options
- apachehaus
- apachelounge
## Example
```ps1
choco install apache-httpd --params "'/source:apachelounge'"
```
## Note
files are available on the downloads pages for the respective sources

- http://www.apachehaus.com/cgi-bin/download.plx
- https://www.apachelounge.com/download/

**Comment by majkinetor** [comment]
Why is this needed ?

This is not possible as package is embedded. 
The one must create a new package, i.e. `apachelounge` that will embed the package from another source.

**Comment by photodude** [comment]
two providers for the same package with slight differences in how they are compiled

for example 
- apachelounge offers VC11, VC14, VC15 versions and their own set of available modules for those VC versions
- apachehaus (current package source) offers VC9, VC11, VC14 versions and their own set of available modules for those VC versions

I'm guessing based on what I see for PHP that it is split into 3 packages but it's all installed via one php command. Is that what we need to do here?

**Comment by majkinetor** [comment]
> I'm guessing based on what I see for PHP that it is split into 3 packages but it's all installed via one php command. Is that what we need to do here?

No, there is a meta package php that serves only for discoverability and points to the 'main' version, usually the latest (you can see in it dependencies what).

> oh and for naming, both sources are the apache-httpd package.

That is not particularly relevant. For example, we have vim, vim-tux, kickassvim, all installing plain old vim from different place. You can connect packages using Notes in description so it will aid in discovery. Also, you can keep prefix the same so `choco list apahce-httpd` will list all packages. (i.e. apache-httpd-lounge, apache-http-xyz).

**Comment by AdmiringWorm** [comment]
To support differently compiled versions of apache-httpd would most likely provide multiple packages, the default apache-httpd package should (IMO) provide the most common/officially created binaries.

As such, I do not believe this issue will ever be fixed and am closing it (feel free to reopen if you disagree).
