### ISSUE TITLE
(dropbox) Beta builds still being picked up

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#763]
Seems like the beta builds for dropbox is still being picked up.
I'm thinking the update script should be changed to parse https://www.dropboxforum.com/t5/Desktop-client-builds/bd-p/101003016
instead of parsing the version from executable returned by https://www.dropbox.com/download?full=1&plat=win

Until this issue have been resolved, I'm stopping the update of the dropbox package.

**Comment by RedBaron2** [comment]
I might have something that will help. I just need to finish up a few things.

**Comment by AdmiringWorm** [comment]
@RedBaron2 I've added the `Up for grabs` label, so if you have the time I/we would very much appreciate a PR.

**Comment by RedBaron2** [comment]
I've been testing the version of the update that does use the requested html page. The only **con** to it is that it takes about **_3 minutes_** for the function to complete via _Appveyor_. The time via any other windows is only a **_0.04 seconds_** at most.
If the time is not a major _**constraint**_?
I will put in a PR .

**Comment by AdmiringWorm** [comment]
Well, it would be preferred to keep to a lowest as possible, but if that is what it takes to keep the update script to pick up beta packages, the so be it.
Feel free to open a PR, I won't have a look at it tonight, but I'll take a look at it tomorrow.

**Comment by leesei** [comment]
I think this issue has to be reopened:
https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/dropbox/dropbox.json 

I'm surprised that the Beta build of Dropbox will be treated as stable. Luckily I recently learnt to identify beta build from the version number when I was hit by the following issue.
[Re: Dropbox icon stuck on starting - Dropbox Community - 331778](https://www.dropboxforum.com/t5/Files-folders/Dropbox-icon-stuck-on-starting/m-p/331937/highlight/true#M49822)
Beta: xx.3.xx
Stable: xx.4.xx
