### ISSUE TITLE
(everything) Is hanging on automated tests

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#764]
It seems the automated tests is hanging on the chocolatey package, and takes several weeks to actually complete.
When it complets it fails with a message that the chocolatey-core.extension could not be found.
I've tried looking into it back in april/may but had no luck.

Is there anything we can do, or is there a problem with the automated verification process?

/cc @majkinetor @gep13 @ferventcoder

**Comment by majkinetor** [comment]
The package should be allowed to pass anyway. Its not 'everything problem' or bug IMO - the package works.

**Comment by majkinetor** [comment]
> and takes several weeks to actually complete.

What do you mean several weeks ... If so, then big LOL x 💯

**Comment by AdmiringWorm** [comment]
Well, I may have exaggerated a little when I said several weeks.
But it takes 1-2 weeks for the automated testing to finish for the everything package.

Currently there are two versions of the everything package awaiting automated testing, which was submitted on the 6th and 7th.

The version before that (the currently [rejected one](https://chocolatey.org/packages/Everything/1.4.1867.20170417)) was last submitted on April 29th, and failed automated testing on May 6th.

**Comment by AdmiringWorm** [comment]
I've exempted the everything package from automated tests, we should still try monitoring somehow though.

Anyways, closing this one for now.
