### ISSUE TITLE
(php) Chocolatey only adds php to administrator's PATH, not all users' PATH

### ISSUE THREAD

**Issue by lne1030** [chocolatey/chocolatey-coreteampackages#767]
I'm using Windows 10 as a standard user.
After my Administrator user installed PHP by 
> choco install php

I found out that the path C:\tools\php71 was only added to Administrator user's PATH, so all standard users can't use PHP in Command Prompt until my Administrator add C:\tools\php71 to System Variables.

Here is a screenshot
![path_php](https://user-images.githubusercontent.com/1152164/27405294-da5558a8-5685-11e7-80b4-ad63a29fa2cd.png)

**Comment by majkinetor** [comment]
Fixed but will remain unpublished until next official release.

**Comment by AdmiringWorm** [comment]
@majkinetor the same changes should perhaps also be added to the manual legacy versions of the package as well (and a new push).

**Comment by majkinetor** [comment]
Perhaps, but not by me. I don't see why would we support tools not supported by vendor.

**Comment by fredericpetit02** [comment]
Hi, this issue is again with php 8.0.3.

**Comment by waghcwb** [comment]
Problem still happening in PHP82

**Comment by pauby** [comment]
@waghcwb Please see the previous comment as this issue is closed.
