### ISSUE TITLE
(php) PHP extensions not found (faulty "ext" setting?)

### ISSUE THREAD

**Issue by bojanz** [chocolatey/chocolatey-coreteampackages#769]
I installed PHP, enabled a few extensions in the php.ini, confirmed that they were present in "php -m",
Running apache didn't show them though, logs showed that Apache couldn't find any on the specified extensions. Replacing the "ext" path from php.ini with the absolute path (C:\tools\php71\ext) resolved the issue. So, there's either a PATH bug (related to #767? I was restarting Apache from an admin powershell though), or a php.ini defaults bug.

**Comment by bojanz** [comment]
After resolving this I went back and enabled some more extensions. Realized that even with this fix, the curl extension only gets loaded in the CLI but not in Apache. I've heard people say that curl depends on other dlls that need to be in the PATH, so it's probably the same issue.

**Comment by photodude** [comment]
@bojanz you need the php_curl.dll enabled for curl to work in Apache. Check out [this blog post](https://brian.teeman.net/joomla/install-amp-on-windows-with-chocolatey) I guest wrote on setting up AMP on Windows with Chocolatey. Note: some of the apache instructions have changed now that the apache-httpd package is in the core repo; I'll be updating that sometime in July.

**Comment by bojanz** [comment]
@photodude Of course I do. What I'm saying is that after uncommenting php_curl.dll in php.ini the extension becomes available on the CLI, but not on Apache.

**Comment by photodude** [comment]
Have you configured apache to use your php install? (Covered in the. Blog post)

**Comment by bojanz** [comment]
Yes, I have. All other extensions work fine. Please reread my original post.

**Comment by photodude** [comment]
so I'm not sure why but the relative path for the ext folder path doesn't work you have to specify the absolute path. It has never worked. Maybe there is a different solution, but as far as I know, you have to specify the absolute path.

**Comment by majkinetor** [comment]
@bojanz  does it change anything to add php path to machine PATH and restart apache?
