### ISSUE TITLE
Contributing link in the PR template is broken

### ISSUE THREAD

**Issue by chrisevett** [chocolatey/chocolatey-coreteampackages#775]
In the PR template, the section that links to CONTRIBUTING.md doesnt work

**Comment by chrisevett** [comment]
This is the current link https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/.github/CONTRIBUTING.md . I'll address this tomorrow.

**Comment by chrisevett** [comment]
[http://i.imgur.com/8ThjFYX.png](url)

**Comment by majkinetor** [comment]
https://github.com/chocolatey/chocolatey-coreteampackages/commit/1eb616af8b0dc2edfde6746e208ea0e1cd0c02ab
