### ISSUE TITLE
(sourcetree) Add auto-update disabling to main package

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-coreteampackages#776]
## Expected Behavior
The sourcetree package should provide a parameter for disabling auto update.

## Current Behavior
There's currently the `sourcetree-disableautoupdate` package which no longer works with SourceTree 2.x since the installer has changed. 

## Possible Solution
With the new installer auto update can be disabled by setting the following value in the `SourceTree.exe.config`:

```
<setting name="AutoUpdater" serializeAs="String">
  <value>false</value>
</setting>
```

Since 2.x SourceTree is installed to the local use profile (eg. `c:\Users\bep\AppData\Local\SourceTree\app-2.1.2.5\`). Therefore this file will be different for each version and therefore needs to be done in the main package as parameter instead of the separate `sourcetree-disableautoupdate` package.

The dependency of the `sourcetree-disableautoupdate` to the `sourcetree` package should be limited to versions < 2.

**Comment by AdmiringWorm** [comment]
> Since 2.x SourceTree is installed to the local use profile (eg. c:\Users\bep\AppData\Local\SourceTree\app-2.1.2.5\). 

In that case, we should probably start looking at how to install to a different folder by default.

**Comment by pascalberger** [comment]
> In that case, we should probably start looking at how to install to a different folder by default.
Not sure if that is easily possible since they now use Squirrel for updating

**Comment by pascalberger** [comment]
Theres are already issues open for SourceTree to switch back to another installer and allowing to install to program files directory: https://jira.atlassian.com/browse/SRCTREEWIN-7082

**Comment by majkinetor** [comment]
Closing due to lack of interest.
