### ISSUE TITLE
cyg-get doesn't process multiple packages correctly

### ISSUE THREAD

**Issue by pyhedgehog** [chocolatey/chocolatey-coreteampackages#78]
Command `cyg-get pkg1,pkg2,pkg3` doesn't do what it should.
It runs 
```shell
"C:\tools\cygwin\cygwinsetup.exe" -q -N -R C:\tools\cygwin -l C:\tools\cygwin\packages -s ftp://mirrors.kernel.org/sourceware/cygwin -P "pkg1 pkg2 pkg3"
```
instead of
```shell
"C:\tools\cygwin\cygwinsetup.exe" -q -N -R C:\tools\cygwin -l C:\tools\cygwin\packages -s ftp://mirrors.kernel.org/sourceware/cygwin -P "pkg1,pkg2,pkg3"
```
I had to run `cyg-get 'pkg1,pkg2,pkg3'` to get correct result.
At least it should be documented as temporary work-around.

**Comment by ferventcoder** [comment]
This is now fixed for 1.2.0 (may be in moderation at the moment) - you just pass `cyg-get pkg1 pkg2 pkgN` - see `cyg-get -help` once you've updated. Tons of other switches have been added as well.
