### ISSUE TITLE
(patch-my-pc) updater fails with 403 Forbidden

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#780]
patch-my-pc [fails now](https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e/2cd84d8c782106c13607a53fe4adda52bf101dc8#errors) , and `iwr` has a problem to download a page where version is located:

```
iwr -Uri "https://patchmypc.net/download"

iwr : The remote server returned an error: (403) Forbidden.
At line:1 char:1
+ iwr -Uri "https://patchmypc.net/download"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

`curl.exe` and `wget.exe` work fine, although curl reports certificate error and `-k` is needed to ignore it (equivalent in posh,  `[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }` didn't help

**Comment by AdmiringWorm** [comment]
I changed the update script to parse the version from the release notes page instead, which worked as expected when I tested locally.
