### ISSUE TITLE
(ruby) 2.4 not comaptible with DevKit2

### ISSUE THREAD

**Issue by darkn3rd** [chocolatey/chocolatey-coreteampackages#786]
In general, with Ruby 2.4, DevKit is no longer supported, and MSYS2 is used at the backbone for native extensions.  This caused a lot of confusion that advance users may be able to piece together with a few well placed google searches.   Perhaps we could have some optional parameters or some docs on this.

## Expected Behavior

Before after sleuthing through how to get native extensions to work, required for rails and other gems, I thought I would have to do the following:

```powershell
choco install ruby
choco install ruby2.devkit
# Refresh PATH
$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
cd C:\tools\DevKit2
ruby dk.rb init
'- C:\tools\ruby24' | Out-File -Append -Encoding "UTF8" config.yml
ruby dk.rb install
gem install rails
```

## Current Behavior

This crashes and burns with make chunks naturally because DevKit is no longer supported with Ruby 2.4.

## Possible Solution

First install MSYS2: `choco install msys2`

Then in MSYS2, you need to install MinGW toolchain:

```bash
  pacman -Sy pacman
  pacman -S base-devel mingw-w64-i686-toolchain # for 32 bit RubyInstaller
  pacman -S base-devel mingw-w64-x86_64-toolchain # for 64 bit RubyInstaller
```

Reference: https://github.com/oneclick/rubyinstaller2

After this things magically work, and `gem install rails` works fine.

## Steps to Reproduce (for bugs)

Install Chocolately and then:

```powershell
choco install ruby
choco install ruby2.devkit
# Refresh PATH
$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
cd C:\tools\DevKit2
ruby dk.rb init
'- C:\tools\ruby24' | Out-File -Append -Encoding "UTF8" config.yml
ruby dk.rb install
gem install rails
```

## Context

I was trying install rails.  This affects everyone that installs Ruby 2.4 and wants to install gems that require compilation (native extensions).  This shouldn't affect Ruby 2.3 or earlier deprecated Ruby 2.x versions.

## Your Environment
* Package Version used: `ruby` and `ruby2.devkit`
* Operating System and version: Windows 10.0.15063 Pro
* Chocolatey version: 0.10.7

**Comment by darkn3rd** [comment]
In a nutshell:
* ruby_version < 2.4 && ruby_version >= 2.0  `ruby2.devkit` is fine.  
* ruby_version > 2.4, DevKit = MSYS2 + MSYS2 packages:
   * `base-devel` 
   * `mingw-w64-$(uname -i)-toolchain`

This should NOT BE INSTALLED for Ruby 2.4 (like block it or have loud warnings).

**Comment by majkinetor** [comment]
I am ceating new msys2 pkg that should fix this. Please take a look #891.

Not sure about your last sentence. You say msys2 wont work in older ruby?
