### ISSUE TITLE
hashes do not match (malwarebytes)

### ISSUE THREAD

**Issue by Bazalia** [chocolatey/chocolatey-coreteampackages#788]
## Expected Behavior

I ran choco install malwarebytes expecting it to be installed without an issue.

## Current Behavior

Instead I received an error suggesting that the checksum does not match.

## Possible Solution

Perhaps the checksum needs to be updated?

## Your Environment

* Package Version used: 3.1.2.1733102092 (MalwareBytes)
* Chocolatey version: v0.10.7

**Comment by AdmiringWorm** [comment]
Sorry, but I do not understand why you opened this issue in this repository.
The malwarebytes package is not maintained here. Please contact the maintainer of the package.
