### ISSUE TITLE
(opera) Upgrading 64-bit Opera actually forces 32-bit

### ISSUE THREAD

**Issue by douglaswth** [chocolatey/chocolatey-coreteampackages#789]
## Expected Behavior
Upgrading 64-bit Opera upgrades to the new version of 64-bit Opera and other packages are not forced to 32-bit.

## Current Behavior
When upgrading 64-bit Opera, the [`Is32BitInstalled`](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/opera/tools/helpers.ps1#L6) check is triggering so the 32-bit Opera is downloaded and installed instead and also the [`ChocolateyForceX86`](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/opera/tools/chocolateyInstall.ps1#L5) environment variable is set so subsequent unrelated package upgrades in a `choco upgrade all` are forced to 32-bit as well. I'm guessing that at some point the 64-bit Opera installer changed to no longer explicitly put its uninstall key into the 64-bit registry and is now putting it into the 32-bit registry instead.

## Steps to Reproduce (for bugs)
1. On a 64-bit version of Windows: `choco install opera -y --version=46.0.2597.39` will download and install the previous 64-bit version of Opera.
2. Then running `choco upgrade all -y` will download and install the latest 32-bit version. If another package needs to be upgraded after Opera, it will also be forced to 32-bit.

## Context
Just trying to upgrade packages.

## Your Environment
* Package Version used: 46.0.2597.46
* Operating System and version: Windows 10 Version 1703 (OS Build 15063.413)
* Chocolatey version: 0.10.7

**Comment by majkinetor** [comment]
I confirm this behavior:
```
master~> choco install opera -y --version=46.0.2597.39
Chocolatey v0.10.8
Installing the following packages:
opera
By installing you accept licenses for the packages.

Opera v46.0.2597.39 [Approved]
opera package files install completed. Performing other installation steps.
Downloading Opera 64 bit
  from 'https://get.geo.opera.com/pub/opera/desktop/46.0.2597.39/win/Opera_46.0.2597.39_Setup_x64.exe'
Progress: 100% - Completed download of C:\Users\majkinetor\AppData\Local\Temp\chocolatey\Opera\46.0.2597.39\Opera_46.0.2597.39_Setup_x64.exe (41.99 MB).
Download of Opera_46.0.2597.39_Setup_x64.exe (41.99 MB) completed.
Hashes match.
Installing Opera...
Opera has been installed.
  opera may be able to be automatically uninstalled.
 The install of opera was successful.
  Software installed to 'C:\Program Files\Opera'

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------3 [ M:0 D:0 A:0 ?:1 ]  17-09-21 20:42:45  C:\Work\_\chocolatey-coreteampackages\automatic (admin)
master~> cup opera
Chocolatey v0.10.8
Upgrading the following packages:
opera
By upgrading you accept licenses for the packages.

You have Opera v46.0.2597.39 installed. Version 47.0.2631.80 is available based on your source(s).
Progress: Downloading Opera 47.0.2631.80... 100%

Opera v47.0.2631.80 [Approved]
opera package files upgrade completed. Performing other installation steps.
Downloading Opera 32 bit
  from 'https://get.geo.opera.com/pub/opera/desktop/47.0.2631.80/win/Opera_47.0.2631.80_Setup.exe'
...
```
