### ISSUE TITLE
(visualstudiocode) Support 64-Bit installations

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-coreteampackages#790]
## Expected Behavior
The Visual Studio Code package should install the 64-bit version on 64-bit operating systems which will be [available starting from 1.15](https://code.visualstudio.com/updates/v1_14#_windows-64-bit-insiders)

## Current Behavior
Currently only 32-bit version is installed

**Comment by AdmiringWorm** [comment]
nice, we would probably need to wait and see how they are planning on the executable naming though.
Guess we could temporary logic to throw when version 1.15 is available perhaps.
Thoughts?

**Comment by pascalberger** [comment]
Name of the insider build is `VSCodeSetup-x64-1.15.0-insider.exe`.

The AU script checks the same JSON as the internal auto updater: https://vscode-update.azurewebsites.net/api/update/win32/stable/VERSION. I assume there should be a similar JSON for the 64-bit version, which can be used in the AU script, from where we can get the file name.

**Comment by AdmiringWorm** [comment]
yeah, I would expect the same.
But until we actually **KNOW**, we can't implement such a change though.

**Comment by AdmiringWorm** [comment]
or, we could chance it and change out `win32` with `win64` and hope for the best (adding a check to see if it's redirected to x86 json
