### ISSUE TITLE
Icons in widnwos 10 are in subfoldre, and can't find it typing the program name

### ISSUE THREAD

**Issue by tikky** [chocolatey/chocolatey-coreteampackages#791]
## Current Behavior
When I am installing packages via Choclatety command line, the icons in start menu are created but in subfolders. I am using Windows 10.

![zrzut007](https://user-images.githubusercontent.com/546755/28158074-d4422722-67b8-11e7-87fd-d6588383a7e0.jpg)

Only single level folder structure is allowed under Start Menu\Programs in Windows 10.
So I have for example installed Skype, but can't find it when I am clicking on start menu and trying to type Skype.
This is hard for me. Is it a way to change this behavior?

## Expected Behavior

I would like to have all icons in start menu exacly the same like in regular install.

**Comment by AdmiringWorm** [comment]
The skype package is not being maintained here in this repository (yet). Please contact the maintainer. Also, from the looks of it, it is the skype installer that creates the folder, not the package itself

**Comment by tikky** [comment]
Skype it was only an example. Other software installed by Chocolatey have similar behavior:
![obraz](https://user-images.githubusercontent.com/546755/28164351-64c7638c-67cf-11e7-96db-8a8d1298853e.png)

![obraz](https://user-images.githubusercontent.com/546755/28164355-6c9a2090-67cf-11e7-9706-bdc3480d7126.png)

![obraz](https://user-images.githubusercontent.com/546755/28164373-7a8d6a04-67cf-11e7-97cc-0f1422bceaf1.png)

**Comment by pauby** [comment]
@tikky This is not a Chocolatey issue. This is an issue with your Windows 10 indexing. All of the packages I installed with Windows 10, under folders (like you show in your last message) are discovered fine and not in the way you describe.

> Only single level folder structure is allowed under Start Menu\Programs in Windows 10.

This is not the case I'm afraid. Windows 10 supports folders just like previous versions of Windows.

My suggestion is to investigate the indexing on your setup.
