### ISSUE TITLE
(brackets) version 1.10 has wrong download hash in the repository

### ISSUE THREAD

**Issue by hayalci** [chocolatey/chocolatey-coreteampackages#797]
The hash of the setup file has been changed with  commit 108b6c44b3ec1e16bb42e5bfce6132568d5d0cc2.

The version has been updated to 1.10, and hash changed to:
> d691bbb24cca2e0b8aa3f37f85b9d16884d950ba75ac7f82bfbd17771a48e906

But if you install the file manually from
https://github.com/adobe/brackets/releases/download/release-1.10/Brackets.Release.1.10.msi
The sha256 hash is 
> 0AC206DDB6E780E484B30704F44DFB7ED0BE7965E62108924D2CE60D641C4CDF

Can you investigate how the bot miscalculated the hash?

## Expected Behavior
Hashes should match the official release file.

## Current Behavior
The hash in brackets/tools/chocolateyInstall.ps1 doesn't match 

## Possible Solution
Symptomatic solution: update the hash in the file manually.
Systemic solution: investigate why the  choco-bot commited the wrong hash. 

## Steps to Reproduce (for bugs)
1. choco install brackets
2. Get error message: 
ERROR: Checksum for 'C:\Users\user\AppData\Local\Temp\chocolatey\Brackets\1.
10\Brackets.Release.1.10.msi' did not meet 'd691bbb24cca2e0b8aa3f37f85b9d16884d9
50ba75ac7f82bfbd17771a48e906' for checksum type 'sha256'. Consider passing the a
ctual checksums through with --checksum --checksum64 once you validate the check
sums are appropriate. A less secure option is to pass --ignore-checksums if nece
ssary.
3. Download file from https://github.com/adobe/brackets/releases/download/release-1.10/Brackets.Release.1.10.msi
4. Calculate hash and see it's different from the error message

## Your Environment

* Package Version used: v1.10
* Operating System and version: Windows 7
* Chocolatey version: Chocolatey v0.10.7
* Install/uninstall gist:

**Comment by AdmiringWorm** [comment]
> Can you investigate how the bot miscalculated the hash?

The bot didn't miscalculate the hash, that was the correct hash when aquired 15 days ago (otherwise it wouldn't have completed the automated checks on chocolatey).
This means that the official binary have been silently replaced upstream at some point after that.

Anyways, I've verified that the hash have changed and will push out a new update shortly.

**Comment by AdmiringWorm** [comment]
Updated version is available on chocolatey.org.
