### ISSUE TITLE
(ffmpeg) Use a static install location

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/chocolatey-coreteampackages#799]
REQUEST: Can this package be changed to always install the latest version of ffmpeg to the same directory please? As it's currently packaged it always installs to programdata\chocolatey\lib\ffmpeg\tools\ffmpeg-VERSION-winBITS-static. Every time a new release comes out it makes a new directory under the package's toolsdir and extracts the files there. This causes hell with other programs (pyTiVo and streambaby are prime examples) that rely on ffmpeg via hard coded paths that keep failing after an upgrade. Of course, there's the issue that old versions never get deleted and just keep accumulating and taking up unnecessary disk space. If ffmpeg just got extracted to the toolsdir without creating a subdirectory, new versions would overwrite old versions and all of this would be solved. ALTERNATIVE#1 the location could be added to the path and updated with each version. Alternative#2 there's always the bin/tools directory (with no version specific subfolder please!). Would you please consider installing to a consistent generic folder?
 

Moving the files from the extracted dir to the toolsdir in the installation script would be perfectly acceptable. Or making a ffmpeg dir inside of toolsdir and then moving them from the extracted path into the generic ffmpeg directory would work as well. 
Any reliably consistent path will do.

**Comment by majkinetor** [comment]
FFMpeg is a zip package, as such shim gets created at consistent location. Older dir accumulation is a problem and will get solved.
