### ISSUE TITLE
(winff) Download location have changed

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#801]
Seems like the download location (as well as the home page) have changed.
This was brought up through an email message.

**Currently the winff package is a manual package**

## Original Message
WinFF has been re-homed to http://www.biggmatt.com/winff/ and the latest version is 1.5.5. 1.5.4 as setup for chocolatey does not install. It returns a file corrupted error, no matter how many times I retry the install AFTER removing the corrupted installer from temp.

**Comment by majkinetor** [comment]
Should be embedded, particularly because:

> This maybe the final version of WinFF except for preset updates.
