### ISSUE TITLE
(git) Can't find git/unix tools on Windows 10 environment path.

### ISSUE THREAD

**Issue by mit2nil** [chocolatey/chocolatey-coreteampackages#805]
So I learned about chocolatey just yesterday after I ended up on this blog -> http://www.jamessturtevant.com/posts/5-Ways-to-install-git-on-Windows/#using-chocolatey.

Like many out there, I wanted git on Windows 10. I was happy to give it a try and to my delight it worked far better than what I was expecting. I installed choco on windows 10 64 bit using command 
`@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
`

Then I installed git using command `choco install git -params '"/GitAndUnixToolsOnPath"'`. It worked perfectly fine yesterday. Today when I log back in to my system and try git, I am running into issue 
`'git' is not recognized as an internal or external command,
operable program or batch file.`.

C:\ProgramData\chocolatey\bin is already in my environmental path. I am not sure what I am missing here or what changed. Can someone help me in manually setting correct path if it already not there.

I also tried force reinstall of git thinking may be something was wrong using command `choco install git -params '"/GitAndUnixToolsOnPath"` but that also didnt help.

I am on Chocolatey v0.10.7 on Windows 10 64 bit system. All packages and chocolatey is installed using administrative cmd.

**Comment by AdmiringWorm** [comment]
Did you try calling `refreshenv` after installing git?
Or closing and re-opening your shell?
The PATH for the current shell isn't automatically updated when the PATH environment variable have changed

**Comment by mit2nil** [comment]
Yes I did fired refreshenv.cmd multiple times. It executed without error but didn't enable correct paths. I also closed and opened shell.

In fact, C:\ProgramData\chocolatey\bin is in my PATH. I will try git.portable but this might be a genuine bug may be not on choco side but git side. It was working fine yesterday and I don't recall changing anything since then.

**Comment by AdmiringWorm** [comment]
Yeah, I believe it have to be on the git part, as we don't manipulate the PATH environment variable at all in the package (just relying on the installer),

You said you tried calling `refreshenv` which didn't work, did you try closing and opening a new shell?

**Comment by AdmiringWorm** [comment]
Another thing, when you installed git, did choco mention that the `PATH` variable had been changed?

**Comment by mit2nil** [comment]
yes to both your queries. It worked from different shell yesterday just fine.

**Comment by majkinetor** [comment]
Can you make sure that git install dir is in your PATH ?

It might be that path env var is too long.

**Comment by mit2nil** [comment]
@majkinetor I tried that and that didn't work. I also tried git portable and it didn't work either. 
I did choco uninstall of git and git portable and re-did choco install git and refreshenv and now it is again working. Not sure what's the issue and what's the solution. But I can close the issue unless someone wants to further investigate.

**Comment by majkinetor** [comment]
You didn't provide enough feedback for us to continue. Provide path length, path content etc...

**Comment by mit2nil** [comment]
@majkinetor git install dir was not in my path. Only path that was added by choco was to its bin directory. There are no path env variable that are too long. 
Right now, I have two path variables. one local to my account which contains "C:\tools\git"
and my global path variable has four new entries (which were missing when the issue occurred)

1. C:\ProgramData\chocolatey\bin (only this existed earlier)
2. C:\Program Files\Git\cmd
3. C:\Program Files\Git\mingw64\bin
4. C:\Program Files\Git\usr\bin

**Comment by mit2nil** [comment]
let me know if you need any more information.

**Comment by majkinetor** [comment]
If they were missing how did they appear now?

**Comment by mit2nil** [comment]
I uninstalled all git packages from choco and reinstalled and it worked. Earlier I had reinstalled wiyh force option on top of already existing installation.

**Comment by majkinetor** [comment]
I will close this for now as you resoved your issue. We cant be sure what happened given the limitted input. Feel free to continue discussion if needed.

**Comment by medianick** [comment]
I experienced this myself today with a new Azure VM running Windows Server 2016. I had installed Chocolatey (0.10.11) prior to sysprepping it, then created a new VM and installed Git on it using the following:

```
choco install git -y --no-progress
```

After doing this, I attempted some `git config` commands but they errored out with the `'git' is not recognized...' error. I tried running `refreshenv` as well as uninstalling and then reinstalling by adding the `/GitAndUnixToolsOnPath` parameter, but the git commands are still failing.

It appears that the initial install of Git didn't add itself to the PATH, for reasons unclear to me, but I've got a sysprepped image I should be able to retest with if anyone has ideas on what to try.

**Comment by J-Swift** [comment]
Also just ran into this, I installed git as part of an initial provisioning but I couldn't find the binaries anywhere, then force installed again which worked (I now see a folder at `C:\Program Files\Git`). Here is the output of the force install in case it helps:

```
> choco install git --force
Chocolatey v0.10.11
Installing the following packages:
git
By installing you accept licenses for the packages.
git v2.20.1 already installed. Forcing reinstall of version '2.20.1'.
 Please use upgrade if you meant to upgrade to a new version.
Progress: Downloading git 2.20.1... 100%

git.install v2.20.1 (forced) [Approved]
git.install package files install completed. Performing other installation steps.
The package git.install wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): y

Using Git LFS
Installing 64-bit git.install...
git.install has been installed.
git.install installed to 'C:\Program Files\Git'
  git.install can be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of git.install was successful.
  Software installed to 'C:\Program Files\Git\'

git v2.20.1 (forced) [Approved]
git package files install completed. Performing other installation steps.
 The install of git was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.
```

**Comment by majkinetor** [comment]
We still do not get sufficient forensic elements. I installed this package on literally thousands on computers without any problems of this kind.

**Comment by hborders** [comment]
I just ran into the same problem. I'm running Windows 10 home, and `git` is the only package I've ever installed with `choco`. I don't see any git binaries or mlinks in my choco directory, and I don't see the git directory on my path.

```
C:\ProgramData\chocolatey\bin> $Env:Path
C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Users\Heath\AppData\Local\Microsoft\WindowsApps;
C:\ProgramData\chocolatey\bin> ls


    Directory: C:\ProgramData\chocolatey\bin


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         6/3/2019   4:08 PM         143496 choco.exe
-a----         6/3/2019   4:08 PM         143496 chocolatey.exe
-a----         6/3/2019   4:08 PM         143496 cinst.exe
-a----         6/3/2019   4:08 PM         143496 clist.exe
-a----         6/3/2019   4:08 PM         143496 cpack.exe
-a----         6/3/2019   4:08 PM         143496 cpush.exe
-a----         6/3/2019   4:08 PM         143496 cuninst.exe
-a----         6/3/2019   4:08 PM         143496 cup.exe
-a----         6/3/2019   4:08 PM         143496 cver.exe
-a----         6/3/2019   4:08 PM           2340 RefreshEnv.cmd
-a----        3/29/2020   9:29 AM             21 _processed.txt
```

However, git is present on my system path:
![windows-system-path](https://user-images.githubusercontent.com/166391/77852732-d973aa00-71a5-11ea-9e08-375171a2b357.png)

I'm going to try restarting to see if that improves things.

**Comment by hborders** [comment]
Restarting fixed things.

**Comment by AlanMaxxx** [comment]
> So I learned about chocolatey just yesterday after I ended up on this blog -> http://www.jamessturtevant.com/posts/5-Ways-to-install-git-on-Windows/#using-chocolatey.
> 
> Like many out there, I wanted git on Windows 10. I was happy to give it a try and to my delight it worked far better than what I was expecting. I installed choco on windows 10 64 bit using command
> `@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin" `
> 
> Then I installed git using command `choco install git -params '"/GitAndUnixToolsOnPath"'`. It worked perfectly fine yesterday. Today when I log back in to my system and try git, I am running into issue
> `'git' is not recognized as an internal or external command, operable program or batch file.`.
> 
> C:\ProgramData\chocolatey\bin is already in my environmental path. I am not sure what I am missing here or what changed. Can someone help me in manually setting correct path if it already not there.
> 
> I also tried force reinstall of git thinking may be something was wrong using command `choco install git -params '"/GitAndUnixToolsOnPath"` but that also didnt help.
> 
> I am on Chocolatey v0.10.7 on Windows 10 64 bit system. All packages and chocolatey is installed using administrative cmd.

Today I met the same question .
At the beginning, I used `choco install git` command to install Git , and it installed successfully and the version is **2.29.2**.
But, when I tried to use `git clone xxxx` command to do something, it didn't work , and I saw `'git' is not recognized as an internal or external command, operable program or batch file.`
Finally, I serached how to fix and I tried `choco install git.install` and `choco uninstall git` and reinstall, but these all didn't work. **Until I used `refreshenv` command under administrator permission** , after that , when I reuse `git clone xxxx` , it **worked** and the question was gone .
I hope it can help you !
**OS version : Windows 10**
