### ISSUE TITLE
(elasticsearch/server-jre8) Installation behind proxy

### ISSUE THREAD

**Issue by tobias-kuendig** [chocolatey/chocolatey-coreteampackages#809]
## Expected Behaviour

I am trying to install `elasticsearch` on a system that sits behind a proxy. This fails to install it's dependecy `server-jre8`. So I tried to install that first manually via

    choco install server-jre8 -y  --proxy="'<REMOVED>:8080'"

This is the output:

```
Chocolatey v0.10.7
Installing the following packages:
server-jre8
By installing you accept licenses for the packages.
Progress: Downloading server-jre8 8.0.131.20170420... 100%

server-jre8 v8.0.131.20170420 [Approved]
server-jre8 package files install completed. Performing other installation steps.
ERROR: Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (407) Proxy Authentication Required."
The install of server-jre8 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\server-jre8\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - server-jre8 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\server-jre8\tools\chocolateyInstall.ps1'
.
 See log for details.
```

You can find the log file here: https://pastebin.com/xtdSgwH1

It looks like the download of the package is sucessfull (proxy settings are corectly loaded) but the `chocolateyInstall.ps1` script that downloads the actual software completely ignores the proxy settings.

## Expected Behaviour

Since I provide a `--proxy` flag to the command I expect the `chocolateyInstall.ps1` script to use these proxy settings as well. If I omit the `--proxy` flag chocolatey correctly uses my global system settings but the install script fails nonetheless.

**Comment by AdmiringWorm** [comment]
Please contact the maintainer of the server-jre package, this package is not being provided in this repository (same is true for the elasticsearch package).

**Comment by tobias-kuendig** [comment]
Thank you for the feedback. I have moved the issue here:
https://github.com/rgra/choco-packages/issues/20
