### ISSUE TITLE
(git) CVE found - 2.14.1 released less than an hour ago

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#814]
I'm not sure when the next scheduled run of AppVeyor goes (it's every 6 hours), but let's try to speed up this process on this one. The sooner we can push it, the sooner it can get approved.

https://github.com/git-for-windows/git/releases/tag/v2.14.1.windows.1

**Comment by ferventcoder** [comment]
@gep13  kicked off a manual AppVeyor run two minutes ago.

**Comment by ferventcoder** [comment]
https://ci.appveyor.com/project/chocolatey/chocolatey-coreteampackages/build/2258

**Comment by gep13** [comment]
`git.portable` worked, and was updated.

**Comment by ferventcoder** [comment]
The packages are all three up to the community repository - in the next hour they will be approved and available. If you need them now, `choco upgrade git --version 2.14.1 -y`
