### ISSUE TITLE
(classic-shell) Update failing

### ISSUE THREAD

**Issue by zero77** [chocolatey/chocolatey-coreteampackages#818]
There’s a new update for Classic Shell out.
Thanks

**Comment by pascalberger** [comment]
Update script currently seems to throw an error: https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e#classic-shell

**Comment by pascalberger** [comment]
New version pushed: https://chocolatey.org/packages/classic-shell/4.3.1
