### ISSUE TITLE
We should have a "Ready for ketarin" label.

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey-coreteampackages#82]
Or anything else that signifies we need action from the people with access to the batch (for now ketarin) machine.

**Comment by pyhedgehog** [comment]
Please please tell me what ["mamebapma"](https://www.google.ru/search?q=mamebapma) means?

**Comment by Redsandro** [comment]
Sorry, I was being silly. It's the ketarin machine that checks the files for updates.

> master mega batch processing machine

https://github.com/chocolatey/chocolatey-coreteampackages/pull/80#issuecomment-121890182

**Comment by gep13** [comment]
@Redsandro this should no longer be required, as the ketarin xml files are now being loaded each time the ketarin instance is scheduled to run.
