### ISSUE TITLE
(visualstudiocode) killswitch for visualstudiocode package

### ISSUE THREAD

**Issue by marcinbojko** [chocolatey/chocolatey-coreteampackages#826]
Hi guys. Can we add killswitch when installing/upgrading this package?
When machine has VSCode open, upgrade fails with MSI code '1'.
It can be a burden to do automated deploy.
Kill switch should be optional.

## Expected Behavior

When upgrading package, with VSCode open by current user or any other user (RDP/Terminal) if killswitch is set to on, we can kill all instances of vscode.

## Current Behavior

When upgrading package, with VSCode open by current user or any other user (RDP/Terminal) MSI exits with code '1'

## Steps to Reproduce (for bugs)

1. choco install visualstudiocode (older version)
2. open vsc
3. add any file to it
4. choco upgrade visualstudiocode

## Your Environment

* Package Version used:
* Operating System and version: W2k12, W2k6
* Chocolatey version: 0.10.7
* Install/uninstall gist:

**Comment by AdmiringWorm** [comment]
@pascalberger since visual studio code uses inno setup, maybe see if all we need is to add the following to the silent arguments `/CLOSEAPPLICATIONS /RESTARTAPPLICATIONS`?

**Comment by pascalberger** [comment]
@AdmiringWorm Unfortunately doesn't work. Calling setup with `/silent /forcecloseapplications` leads to this:

![grafik](https://user-images.githubusercontent.com/2190718/29428448-862ff60e-838d-11e7-9e9a-6ffa6142c38c.png)

Together with the `/suppressmsgboxes` slot it will return with exit code 5.

**Comment by marcinbojko** [comment]
What about something brutal?

$killexec           = 1
$killexecprocess    = "doublecmd*"
# Should we kill some exec ?
if ($killexec) {
  Stop-Process -processname $killexecprocess -force
  }
  Start-Sleep -s 10
  Install-ChocolateyPackage @packageArgs

I used it in doublecmd package.

**Comment by majkinetor** [comment]
how about something non brutal: `ps code | % { $_.CloseMainWindow() }` ?

**Comment by marcinbojko** [comment]
ForEach-Object : Cannot bind parameter 'RemainingScripts'. Cannot convert the "?" value of type "System.String" to
type "System.Management.Automation.ScriptBlock".
At line:1 char:38
+ ps code | % { $_.CloseMainWindow() } ?
+                                      ~
    + CategoryInfo          : InvalidArgument: (:) [ForEach-Object], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.ForEachObjectComman

**Comment by AdmiringWorm** [comment]
@marcinbojko remove the question mark (`?`) and try again.

**Comment by marcinbojko** [comment]
Thanks. Works with saved and unsaved files in project.

**Comment by marcinbojko** [comment]
Guys, tested with 16.x and 17.1 - this behaviour still stays.

```
ERROR: Running ["C:\Windows\TEMP\chocolatey\VisualStudioCode\1.17.2\VSCodeSetup-x64-1.17.2.exe" /verysilent /suppressmsgboxes /mergetasks="!runCode, desktopicon, quicklaunchicon, addcontextmenufiles, addcontextmenufolders, addtopath" /log="C:\Windows\TEMP\chocolatey\vscode.log" ] was not successful. Exit code was '5'. See log for possible error messages.
The upgrade of visualstudiocode was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\VisualStudioCode\tools\ChocolateyInstall.ps1'.
See log for details.
```
