### ISSUE TITLE
(visualstudiocode) upgrades 1.14.x to  1.15.x fail

### ISSUE THREAD

**Issue by basictheprogram** [chocolatey/chocolatey-coreteampackages#827]
## Expected Behavior

cup all should upgrade visualstudiocode to the latest version

## Current Behavior

cup all fails when attempting to upgrade 1.14.x to 1.15 series

## Possible Solution

choco uninstall visualstudiocode
choco install visualstudiocode

## Steps to Reproduce (for bugs)

 1. Have or install visualstudiocode from 1.14 release
 1. cup all

## Context

Upgrading all installed chocolatey packages to their latest version

## Your Environment

* Package Version used: visualstudiocode 1.14.1
* Operating System and version: Windows 7
* Chocolatey version: Chocolatey v0.10.7
* Install/uninstall gist: https://gist.github.com/basictheprogram/bdc2fbc0e5ddc08470865330ba231871

**Comment by basictheprogram** [comment]
Odd, I do not have 32-bit installed, in fact the package is not installed at all.

```
2017-08-18 15:21:55.045   Log opened. (Time zone: UTC-05:00)
2017-08-18 15:21:55.045   Setup version: Inno Setup version 5.5.6 (u)
2017-08-18 15:21:55.045   Original Setup EXE: C:\Users\Admin\AppData\Local\Temp\chocolatey\VisualStudioCode\1.15.1\VSCodeSetup-x64-1.15.1.exe
2017-08-18 15:21:55.045   Setup command line: /SL5="$B002E,41844951,144384,C:\Users\Admin\AppData\Local\Temp\chocolatey\VisualStudioCode\1.15.1\VSCodeSetup-x64-1.15.1.exe" /verysilent /suppressmsgboxes /mergetasks=!runCode,desktopicon,quicklaunchicon,addcontextmenufiles,addcontextmenufolders,addtopath /log="C:\Users\Admin\AppData\Local\Temp\chocolatey\vscode.log" 
2017-08-18 15:21:55.045   Windows version: 6.1.7601 SP1  (NT platform: Yes)
2017-08-18 15:21:55.045   64-bit Windows: Yes
2017-08-18 15:21:55.045   Processor architecture: x64
2017-08-18 15:21:55.045   User privileges: Administrative
2017-08-18 15:21:55.076   64-bit install mode: Yes
2017-08-18 15:21:55.076   Created temporary directory: C:\Users\Admin\AppData\Local\Temp\chocolatey\is-A4384.tmp
2017-08-18 15:21:55.107   Message box (OK):
                          Please uninstall Code 32bits before installing this 64bits version.
```

**Comment by pascalberger** [comment]
Since 1.15 Visual Studio Code is available in a 64-bit version and the Chocolatey package will install the 64-bit version on a 64-bit system. This requires any 32-bit version to be manually uninstalled first. 

It was decided that failing installation and having the user to manually uninstall Visual Studio Code first if he wants to switch to the 64-bit version. To stay on the 32-bit version install you can use the `--x86` option. See #813

**Comment by pascalberger** [comment]
> Odd, I do not have 32-bit installed, in fact the package is not installed at all.

@basictheprogram Now I'm confused. The tilte of the issue is `upgrades 1.14.x to 1.15.x fail` which indicates that you have Visual Studio Code 1.14 installed

**Comment by basictheprogram** [comment]
Sorry, I can open another ticket. 

Let me clarify. I thought the problem was 32 bit vs 64 bit so I uninstalled Visual Studio Code and tried to re-install it and it failed with "... Please uninstall Code 32bits before installing this 64bits version. ..."

Tried a reboot and install, still failed.

If this different issue I'll open another ticket, but for me
 * Upgrading to 1.15 from 1.14.x fails
 * Installation of 1.15.x fails (pristine Windows 7)
 * installing --version 1.14.2 fails  (pristine Windows 7)

Let me know about a new ticket or maybe a title check of this ticket?

**Comment by pascalberger** [comment]
Having to uninstall Visual Studio Code first if upgrading from 1.14 32-bit to 1.15 64-bit is expected as explained [above](https://github.com/chocolatey/chocolatey-coreteampackages/issues/827#issuecomment-323467784).

The error message you mention [here](https://github.com/chocolatey/chocolatey-coreteampackages/issues/827#issuecomment-323467519) indicates that Visual Studio Code is still installed. If the Chocolatey package is not installed please check in control panel if you have an entry for `Microsoft Visual Studio Code` and uninsstall it from there.

**Comment by basictheprogram** [comment]
I do not see it when view via control panel.

**Comment by pascalberger** [comment]
> I do not see it when view via control panel.

Can you please download the Visual Studio Code installer, start installation manually and check if the error also appears there. 

If you think this is an error in the Visual Studio Code installer please open an issue at https://github.com/Microsoft/vscode, there's nothing we can do here, since the Chocolatey package is just a simple wrapper around the installer.

**Comment by basictheprogram** [comment]
Download from https://github.com/Microsoft/vscode and manual installation worked.

via the below command line works as well
```
> .\VSCodeSetup-x64-1.15.1.exe /verysilent /suppressmsgboxes /mergetasks=!runCode,des
ktopicon,quicklaunchicon,addcontextmenufiles,addcontextmenufolders,addtopath
```

**Comment by pascalberger** [comment]
On the same machine with the same user?

Sorry, I'm out of ideas. I don't see any difference than in the call we do from the Chocolatey package in this case, and the error is thrown in the installer. I also never experienced a similar behavior.

**Comment by basictheprogram** [comment]
Same user, local Administrator, 13 different Windows7 machines.

**Comment by pascalberger** [comment]
> 13 different Windows7 machines.

Can we stick to one machine please, otherwise I don't have any chance to follow what you are doing. 

So on the same machine the installer run manually worked but the Chocolatey package didn't?

> Downloaded from https://github.com/Microsoft/vscode

What exactly did you download from there? The binaries aren't available from GitHub. Please download from https://code.visualstudio.com/

**Comment by basictheprogram** [comment]
Ok. 

Using one machine, call it G1457, installation package downloaded form https://go.microsoft.com/fwlink/?Linkid=852157 installs with no problems.

https://go.microsoft.com/fwlink/?Linkid=852157 gave me the below file:
 * MD5 (VSCodeSetup-x64-1.15.1.exe) = cc35b2a1a0f68fc0ef08b8807310f9f1

Installing via chocolatey fails

**Comment by pascalberger** [comment]
Can you please post the log of the failing output

**Comment by basictheprogram** [comment]
Showing Visual Studio Code is not installed  via chocolatey.
```
PS C:\ProgramData\chocolatey\logs> choco list -lo
Chocolatey v0.10.7
ccleaner 5.33.6162
chocolatey 0.10.7
chocolatey-core.extension 1.3.1
DotNet4.5.2 4.5.2.20140902
git 2.14.1
git.install 2.14.1
GoogleChrome 60.0.3112.101
PowerShell 5.1.14409.20170510
8 packages installed.
```
Visual Studio Code not listed in Control Panel

<img width="734" alt="gsis1457" src="https://user-images.githubusercontent.com/6723257/29484202-3b6d0a38-847f-11e7-9872-09b2050d5c56.png">

```
PS C:\ProgramData\chocolatey\logs> choco install visualstudiocode
Chocolatey v0.10.7
Installing the following packages:
visualstudiocode
By installing you accept licenses for the packages.
Progress: Downloading VisualStudioCode 1.15.1... 100%

VisualStudioCode v1.15.1 [Approved]
visualstudiocode package files install completed. Performing other installation steps.
Merge Tasks:
!runCode,desktopicon,quicklaunchicon,addcontextmenufiles,addcontextmenufolders,addtopath
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Hashes match.
Hashes match.
Installing visualstudiocode...
```
This dialog is displayed.

<img  alt="gsis1457" src="https://user-images.githubusercontent.com/6723257/29484144-2a3c1a3e-847e-11e7-85b1-468f6d400482.png">

I click **Ok**. 

```
ERROR: Running ["C:\Users\Admin\AppData\Local\Temp\chocolatey\VisualStudioCode\1.15.1\VSCodeSetup-x64-1.15.1.exe
" /verysilent /suppressmsgboxes /mergetasks=!runCode,desktopicon,quicklaunchicon,addcontextmenufiles,addcontextmenufolde
rs,addtopath /log="C:\Users\Admin\AppData\Local\Temp\chocolatey\vscode.log" ] was not successful. Exit code was
'1'. See log for possible error messages.
The install of visualstudiocode was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\VisualStudioCode\tools\ChocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - visualstudiocode (exited 1) - Error while running 'C:\ProgramData\chocolatey\lib\VisualStudioCode\tools\ChocolateyIns
tall.ps1'.
 See log for details.
```
[choco.summary-log.txt](https://github.com/chocolatey/chocolatey-coreteampackages/files/1236109/choco.summary-log.txt)

[chocolatey-log.txt](https://github.com/chocolatey/chocolatey-coreteampackages/files/1236112/chocolatey-log.txt)

**Comment by pascalberger** [comment]
@ferventcoder Any idea what might be different between calling installer directly and from Chocolatey package which might cause the installer to behave differently?

**Comment by basictheprogram** [comment]
No. 

Running the Microsoft download package by hand (like I stated [above](https://github.com/chocolatey/chocolatey-coreteampackages/issues/827#issuecomment-323474977)) with the chocolatey install options works fine.

That will be my Plan B (manual install).

Other then that I don't have clue. 

I'm really a Unix guy and get Windows stuff dumped on my because DevOps platform agnostic (so I'm told) :-(

**Comment by majkinetor** [comment]
How about this - just record the install with `--no-script` option, install manually and updates will work afterwards ?

**Comment by basictheprogram** [comment]
I did not know about the --no-script but I got a work around. 

I got 2 new computers imaged with a new(er) version of things and the choco install works. 

Sent 2 of the "broken" computer back for a re-image and choco install works.

The problem looks to be specific to something on my side and specific to the older OS images.

You can close this ticket.

Thanks.

**Comment by ferventcoder** [comment]
@pascalberger 👍
