### ISSUE TITLE
(sonarlint-vs2015) URL no longer working

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-coreteampackages#836]
Reported through contact maintainer link:

> The url used in the powershell script isn't working anymore... please could you update this url and repack the nupkg?
>
> For your information, i use this url:
> https://visualstudiogallery.msdn.microsoft.com/47d1049d-bb27-454e-aab8-24566c85e548/file/169863/36/SonarLint.VSIX-3.5.0.1803-2015.vsix

**Comment by pascalberger** [comment]
Looking at [Update Status](https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e), it seems like the [AU script for the package](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/vs-extensions/sonarlint-vs2015/update.ps1) currently isn't run and the package therefore not updated.

**Comment by majkinetor** [comment]
AU doesn't see subfolders, it [doesn't search recursively](https://github.com/majkinetor/au/blob/master/AU/Public/Get-AUPackages.ps1#L31).   Folder needs to be moved one level up.
