### ISSUE TITLE
(everything) Run as a service by default

### ISSUE THREAD

**Issue by AndrewSav** [chocolatey/chocolatey-coreteampackages#839]
As per discussion here http://disq.us/p/1m4unnc

## Expected Behavior
The big majority of packages just install software, they do not run it. Package managers are traditionally for getting the bits on the PC and configuring them, and it's up to the end user to run them if they wish to. 

## Current Behavior
Currently the package starts the application after installation. 

## Possible Solution
Remove line 30 [here](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/everything/tools/chocolateyInstall.ps1#L30) and test that it has the desired effect.

## Steps to Reproduce (for bugs)
`cinst everything -y`

## Context
In many automation scenarios, it is preferable that the application is NOT run after install.

Another example is that if you are installing Everything via WinRM, the WinRM session does not finish, while there are child processes alive. And if you, say are using [Packer](https://github.com/hashicorp/packer) that leverages WinRm to configure a VM template it's creating it make packer hang waiting for WinRM session waiting for Everything. Forever.

## Your Environment
* Package Version used: latest as of today
* Operating System and version: Windows Server 2012
* Chocolatey version: latest as of today
* Install/uninstall gist: `cinst everything -y`

**Comment by AdmiringWorm** [comment]
Thank you for opening this issue.

Before any changes are made though, I would like to hear from @majkinetor on his thoughts and the reason why the package starts Everything after installation.

**Comment by amivit** [comment]
Is it possible to look into this too: 

"When installing "Everything" from the official website, the shortcuts to the program don't require UAC Admin permissions. The chocolatey installed version does for some reason. I tried fixing it by going to the properties of the binary, but nothing is checked. A fix could be very helpful in my situation. Thanks!"

**Comment by AdmiringWorm** [comment]
@amivit Unfortunately I believe that is caused by chocolatey being run as an admin (I could be wrong though). As such, I don't think it's easily fixable.

But as I mentioned on disqus, I've not worked on this package (nor have I ever used Everything), so I could be completely wrong in this regard.

**Comment by majkinetor** [comment]
@amivit , see `choco info everything` => Package Parameters. Something like this might help: `cinst everyghing --params /service`. 

@AdmiringWorm, _everything_ should run all the time, otherwise you pretty much loose the benefit of the tool - realtime search (if it doesn't run, it needs to scan everyghing on disk). Situation with the WinRM is easily solvable using `ps everything | kill` (even within Packer) . So I really think there isnt anything to fix here. Parameter could be added tho, but requires some refactoring of existing code. 

Repositories in general do start services, not just configure them.

**Comment by AndrewSav** [comment]
>@AdmiringWorm, everything should run all the time, otherwise you pretty much loose the benefit of the tool - realtime search (if it doesn't run, it needs to scan everyghing on disk). 

I'd argue that. If you have an old HDD and ten millions of files, then sure. If you are running a compact minimal VM on an SSD the full scan takes a few seconds.

**Comment by majkinetor** [comment]
No, it doesn't popup @AndrewSav (that would be unacceptable) becasuse of startup argument. Try it yourself:

```
start "C:\Program Files\Everything\Everything.exe" -ArgumentList "-startup"
```

It might be becase I install it with `--params /service`.

**Comment by AndrewSav** [comment]
@majkinetor Well I'm sure that the command line does not but the package installer does, and that's what we should be testing. It's very easy with vagrant. Install [virtualbox](https://www.virtualbox.org/) and [vagrant](https://www.vagrantup.com/), make sure that you have all the bios and os settings that allows a hypervisor to run. Then:

```
vagrant init habsgoalie/windows2012r2-wmf5
vagrant up --provider virtualbox
vagrant snapshot push
vagrant rdp
```

Login to the rdp session with vagrant/vagrant credentials, open powershell as admin and run:

```
cinst everything -y
```
observe the pop-up.

**Comment by AndrewSav** [comment]
I can confirm that with "--params /service" it does not pop up. It should not pop up without them either.

**Comment by majkinetor** [comment]
That is the desired program behavior then (i.e. upstream problem). Perhaps service should be there by default as without it UAC also happens on startup.

**Comment by AndrewSav** [comment]
>Perhaps service should be there by default as without it UAC also happens on startup.
Well event that is better than now ;)

>That is the desired program behavior then (i.e. upstream problem).
How so? It's the package that issues the `Start-Process` and this is what causes the pop-up with the _package default settings_ How possibly is this an upstream problem?

**Comment by AndrewSav** [comment]
@majkinetor there is a commit [here](https://github.com/chocolatey/chocolatey-coreteampackages/commit/179e8d3baa1f6534c6807c2d4bbf741cdd95cb57#diff-6ae7c0ac9d3f7cd0dc9b47ec31c6adb4) by you that claims to fix the UAC issue, but this never made it's way to the official repo. It also may fix the pop-up problem because it's not the `start-process` that causes the pop-up but calling `everything` without arguments [like this](https://github.com/chocolatey/chocolatey-coreteampackages/blob/51337826e024dc33106ec7e033f1030c8d0c1725/automatic/everything/tools/chocolateyInstall.ps1#L25). Now when we have `'--disable-run-as-admin` it may no longer be a problem. (Of course testing is required).

**Comment by majkinetor** [comment]
> How so? 

Because program behaves differently depending on how it is installed.

> Could you please tell me, what's the story about that? In particular, 1) was the UAC issue fixed by that commit and 2) why is it not in the official chocolatey package repository?

1. It is fixed as far as I can tell. Everything is my mandatory tool and I have it installed on dozen of systems. 
2. Sometimes we do not make fixed package but wait for the next official release. There was no release of everything after that commit so thats why its not there. I will force AU update.

**Comment by AndrewSav** [comment]
@majkinetor thank you for this. @amivit when this comes through, can you test if the issue you brought up is resolved?

**Comment by amivit** [comment]
Hey!!! Just got around to reading through this thread. Awesome "Everything!" is being shown some love - it is truly a nice tool. Can even disable the default Windows indexer. 

I totally agree on changing the default parameter to install as a service - it only makes sense. And will test it out ASAP.

**Comment by AndrewSav** [comment]
That's the spirit! Just what we need to dilute this austere conversation between two dour Slavic men. ;) Thank you for checking in!

**Comment by AdmiringWorm** [comment]
@amivit @AndrewSav seems like the new version of everything is available on chocolatey.org now, mind giving it a try to see if it fixes everything.

**Comment by amivit** [comment]
@AdmiringWorm @AndrewSav My reported UAC problem is completely fixed! Chocolatey _does_ need UAC elevation once to install Everything! and its service, but that is perfectly expectable, and similar to many other choco packages. From there on out, the app itself, works without UAC elevation perfectly fine, by communicating with the service 👍

**Comment by majkinetor** [comment]
Great. I am going to make `service` default, i.e. add parameter `/NoService`.

**Comment by AndrewSav** [comment]
The pop-up is also disappeared. Thanks!
