### ISSUE TITLE
(cameyo) Failing to update to new version due to website changes

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#848]
Because the developers of cameyo have completely changed their website, the cameyo package is no longer being updated.

I've no interest in trying to fix the update script, hence I only opted to ignore failing updates for the package and opening this issue.

**Comment by RedBaron2** [comment]
Last I checked the website for this package. The update file was working correctly. They are pushing more towards their on-line services now. Development of the install version seems to be maybe stalled at the current version.

**Comment by majkinetor** [comment]
@AdmiringWorm 

I vote that we remove this package from the repository.

**Comment by AdmiringWorm** [comment]
yeah, unless someone is interested in fixing this issue, I think removing the package from the repo (and create a new RFM) would be the best choice now.

**Comment by majkinetor** [comment]
OK, could you please remove chocolatey user from maintainers, I will remove the package itself.

**Comment by AdmiringWorm** [comment]
@majkinetor done

**Comment by AdmiringWorm** [comment]
also just added a RFM for the package
