### ISSUE TITLE
cyg-get: Add support for cygwinports

### ISSUE THREAD

**Issue by pyhedgehog** [chocolatey/chocolatey-coreteampackages#85]
It would be very useful to be able to install [cygwinports](http://cygwinports.org/) packages via `cyg-get`.
At least there should be way to pass additional options (i.e. `-K http://cygwinports.org/ports.gpg`) to `cygwinsetup.exe`.

**Comment by ferventcoder** [comment]
There is when you install the cygwin package, you would just use `-ia '"-K http://cygwinports.org/ports.gpg"'`

**Comment by ferventcoder** [comment]
Adding additional Pubkeys would be nice.

**Comment by pyhedgehog** [comment]
It's great idea but can be used only with `cup cygwin --force -ia '"-K key-url -P packages"'`.
You need packages from cygwin to use packages from cygports.
