### ISSUE TITLE
(sourcetree) Don't create shims for installer

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-coreteampackages#851]
## Expected Behavior
Installing the SourceTree package shouldn't create shims for the setup package

## Current Behavior
Currently it can happen that the SourceTree package create shims for the setup package:

```
Installing SourceTreeSetup-2.3.1.0.exe...
SourceTreeSetup-2.3.1.0.exe has been installed.
 ShimGen has successfully created a shim for SourceTreeSetup-2.1.10.0.exe
 ShimGen has successfully created a shim for SourceTreeSetup-2.1.11.0.exe
 ShimGen has successfully created a shim for SourceTreeSetup-2.1.2.5.exe
```

## Possible Solution
Exclude setup files for shim creation

## Steps to Reproduce (for bugs)
1. Install SourceTree 2.1.2.5
2. Upgrade to SourceTree 2.3.1.0

## Your Environment
* Package Version used: 2.3.1.0
* Operating System and version: Microsoft Windows [Version 10.0.15063]
* Chocolatey version: Chocolatey v0.10.8 Business

**Comment by majkinetor** [comment]
I ma not sure how this happens since it is not embedded package. Are you sure this is package related but not some other side effect ? Why would the package be downloaded in tools instead of regular TEMP location ?

**Comment by pascalberger** [comment]
@majkinetor Valid point. In my case I used the package after running it throug Chocolatey Interalizer. Most propably it was caused by this together with SourceTrees Squirel installer (it installs to users local AppData directory) from previous installations

**Comment by majkinetor** [comment]
Yeah, internalizer is probably buggy or something.

The same thing happened with AU embedded packages and the solution was to add this after installation:

```
ls $toolsPath\*.exe | % { rm $_ -ea 0; if (Test-Path $_) { touch "$_.ignore" } }
```

Other then that, I suggest write them for distribution rights so we can do it proper here.

I will close this issue now as it isn't related to the package, but feel free to continue any discussion.
