### ISSUE TITLE
(sourcetree) Setup is locked on upgrade

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-coreteampackages#852]
## Expected Behavior
Chocolatey package should not throw an error on upgrading

## Current Behavior
After installation SourceTree setup seems to run some stuff, while already giving back control to Chocoaltey resulting in locking issues:

```
Installing SourceTreeSetup-2.3.1.0.exe...
SourceTreeSetup-2.3.1.0.exe has been installed.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 Access to the path 'C:\Users\bep\AppData\Local\Temp\chocolatey\SourceTree\2.3.1.0\SourceTreeSetup-2.3.1.0.exe' is denied.
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 Access to the path 'C:\Users\bep\AppData\Local\Temp\chocolatey\SourceTree\2.3.1.0\SourceTreeSetup-2.3.1.0.exe' is denied.
Maximum tries of 3 reached. Throwing error.
```

## Steps to Reproduce (for bugs)
1. Install SourceTree 2.1.2.5
2. Upgrade to SourceTree 2.3.1.0

## Your Environment
* Package Version used: 2.3.1.0
* Operating System and version: Microsoft Windows [Version 10.0.15063]
* Chocolatey version: Chocolatey v0.10.8 Business

**Comment by majkinetor** [comment]
This is probably also related to your internalizing thingie.
