### ISSUE TITLE
Sourceforge packages AU errors

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#854]
Yesterday AU reported 18 errors, all from sourceforge:

* [ 00 errors - 2017-09-26 12:08 UTC](https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e/cf0697487d050ca84074d2bb3d4bc0aa95c1bb5d)
* [18 errors - 2017-09-26 18:08 UTC](https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e/bd3428e860269dfc5626b1c644b413bbd061a52d)

## Errors

Errors are mostly _Bad content type 'text/html'_ from AU URL Mime check but there are 2 that are unrelated to this (and still strange how they appeared first time now).

|Icon|Name|RemoteVersion|NuspecVersion|Error|
|---|---|---|---|---|
|<img src="https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/edba4a5849ff756e767cba86641bea97ff5721fe/icons/cdrtfe.png" width="32" height="32"/>|[cdrtfe](https://chocolatey.org/packages/cdrtfe/1.5.6)|[1.5.7](http://cdrtfe.sourceforge.net/)|[1.5.6](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/cdrtfe)|[Bad content type 'text/html':http://sourceforge.net/projects/cdrtfe/files/cdrtfe/cdrtfe%201.5.7/cdrtfe-1.5.7.exe](#cdrtfe)|
|<img src="https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/efc9e0914779661ad7aa88e9dbde0333cfb81f12/icons/djv.png" width="32" height="32"/>|[djv](https://chocolatey.org/packages/djv/1.1.0.20170207)|[1.1.0](http://djv.sourceforge.net/)|[1.1.0.20170207](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/djv)|[Bad content type 'text/html':http://sourceforge.net/projects/djv/files/djv-stable/1.1.0/djv-1.1.0-Windows-64.exe/download](#djv)|
|<img src="https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/8a5d2740db65d1750e4312294f4163e348cd5a45/icons/ext2fsd.jpg" width="32" height="32"/>|[ext2fsd](https://chocolatey.org/packages/ext2fsd/0.68.0.20161111)|[](http://www.ext2fsd.com/)|[0.68.0.20161111](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/ext2fsd)|[Invalid version:](#ext2fsd)|
|<img src="https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/a8fa14d8c3ca49fd8bd8f856d9091b1a9103ada1/icons/jubler.png" width="32" height="32"/>|[jubler](https://chocolatey.org/packages/jubler/5.1.0.20170608)|[5.1](http://www.jubler.org/index.html)|[5.1.0.20170608](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/jubler)|[Bad content type 'text/html':https://sourceforge.net/projects/jubler/files/Jubler%20Binary%20Releases/5.1/Jubler-5.1_32.exe/download](#jubler)|
|<img src="https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/edba4a5849ff756e767cba86641bea97ff5721fe/icons/keepass.svg" width="32" height="32"/>|[keepass-classic](https://chocolatey.org/packages/keepass-classic/1.33)|[1.33](http://keepass.info/index.html)|[1.33](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/keepass-classic)|[Bad content type 'text/html':https://sourceforge.net/projects/keepass/files/KeePass%201.x/1.33/KeePass-1.33-Setup.exe/download](#keepass-classic)|
|<img src="https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/edba4a5849ff756e767cba86641bea97ff5721fe/icons/maxima.png" width="32" height="32"/>|[maxima](https://chocolatey.org/packages/maxima/5.40.0.20170607)|[5.40.0](http://maxima.sourceforge.net/)|[5.40.0.20170607](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/maxima)|[Bad content type 'text/html':https://sourceforge.net/projects/maxima/files/Maxima-Windows/5.40.0-Windows/maxima-clisp-sbcl-5.40.0-win32.exe](#maxima)|
|<img src="" width="32" height="32"/>|[optipng](https://chocolatey.org/packages/optipng/0.7.6)|[0.7.6](http://optipng.sourceforge.net/)|[0.7.6](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/optipng)|[Can't validate URL; Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden.":http://prdownloads.s ...](#optipng)|
|<img src="https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/588d16b30aa063f71d41ce18849cb42a23367d05/icons/pspp.png" width="32" height="32"/>|[pspp](https://chocolatey.org/packages/pspp/1.0.1)|[](https://www.gnu.org/software/pspp/)|[1.0.1](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/pspp)|[Invalid version: 09](#pspp)|
|<img src="https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/edba4a5849ff756e767cba86641bea97ff5721fe/icons/qbittorrent.png" width="32" height="32"/>|[qbittorrent](https://chocolatey.org/packages/qbittorrent/3.3.16)|[3.3.16](http://www.qbittorrent.org/index.php)|[3.3.16](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/qbittorrent)|[Bad content type 'text/html':https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-3.3.16/qbittorrent_3.3.16_setup.exe/down ...](#qbittorrent)|
|<img src="https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/1c7defed5af3d4f87905acc3d19cfa1903e78bc4/icons/screencloud.svg" width="32" height="32"/>|[screencloud](https://chocolatey.org/packages/screencloud/1.3.0)|[](https://screencloud.net/)|[1.3.0](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/screencloud)|[au_GetLatest failed; Cannot index into a null array.](#screencloud)|
|<img src="https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/c60e11994d4e9da90e4e5a974f54e284b8d92823/icons/scribus.svg" width="32" height="32"/>|[scribus](https://chocolatey.org/packages/scribus/1.4.6.20170429)|[1.4.6](https://www.scribus.net/)|[1.4.6.20170429](https://github.com/Chocolatey/chocolatey-coreteampackages/tree/master/automatic/scribus)|[Bad content type 'text/html':https://sourceforge.net/projects/scribus/files/scribus/1.4.6/scribus-1.4.6-windows-x64.exe/download](#scribus)|
|<img src="https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/edba4a5849ff756e767cba86641bea97ff5721fe/icons/supertuxkart.png" width="32" height="32"/>|[supertuxkart](https://chocolatey.org/packages/supertuxkart/0.9.2)|[0.9.2](http://supertuxkart.sourceforge.net/)|[0.9.2](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/supertuxkart)|[Bad content type 'text/html':https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.2/supertuxkart-0.9.2.exe/download](#supertuxkart)|
|<img src="https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/736a00f718c84566b58be6146579ed1a6ce7648e/icons/sweet-home-3d.png" width="32" height="32"/>|[sweet-home-3d](https://chocolatey.org/packages/sweet-home-3d/5.5.2)|[5.5.2](http://www.sweethome3d.com/)|[5.5.2](https://github.com/Chocolatey/chocolatey-coreteampackages/tree/master/automatic/sweet-home-3d)|[Bad content type 'text/html':http://sourceforge.net/projects/sweethome3d/files/SweetHome3D/SweetHome3D-5.5.2/SweetHome3D-5.5.2-windows.exe/download](#sweet-home-3d)|
|<img src="https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/81c6df0de9bb542ecc516c813101d10525c74e51/icons/tortoisesvn.png" width="32" height="32"/>|[tortoisesvn](https://chocolatey.org/packages/tortoisesvn/1.9.7.27907)|[1.9.7.27907](http://tortoisesvn.net/)|[1.9.7.27907](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/tortoisesvn)|[Bad content type 'text/html':https://sourceforge.net/projects/tortoisesvn/files/1.9.7/Application/TortoiseSVN-1.9.7.27907-win32-svn-1.9.7.msi/download](#tortoisesvn)|
|<img src="https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/edba4a5849ff756e767cba86641bea97ff5721fe/icons/tv-browser.svg" width="32" height="32"/>|[tv-browser](https://chocolatey.org/packages/tv-browser/4.0)|[4.0](http://www.tvbrowser.org/index.php)|[4.0](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/tv-browser)|[Bad content type 'text/html':https://sourceforge.net/projects/tvbrowser/files/TV-Browser%20Releases%20%28Java%208%20and%20higher%29/4/tvbrowser_4_win3 ...](#tv-browser)|
|<img src="https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/f47c573f12e0505f678bcdbe75624d128704f393/icons/ultradefrag.png" width="32" height="32"/>|[ultradefrag](https://chocolatey.org/packages/ultradefrag/7.0.2)|[7.0.2](http://ultradefrag.sourceforge.net/en/index.html)|[7.0.2](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/ultradefrag)|[Bad content type 'text/html':https://downloads.sourceforge.net/ultradefrag/ultradefrag-7.0.2.bin.amd64.exe](#ultradefrag)|
|<img src="https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/333ef9e0436d235bd3fa6b7ca2ed68cf799072d5/icons/wesnoth.png" width="32" height="32"/>|[wesnoth](https://chocolatey.org/packages/wesnoth/1.12.6)|[1.12.6](http://www.wesnoth.org/)|[1.12.6](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/wesnoth)|[Bad content type 'text/html':https://sourceforge.net/projects/wesnoth/files/wesnoth-1.12/wesnoth-1.12.6/wesnoth-1.12.6-win32.exe/download](#wesnoth)|

**Comment by majkinetor** [comment]
Probably due to this:

> The sourceforge.net website is temporarily in static offline mode.
Only a very limited set of project pages are available until the main website returns to service.

**Comment by majkinetor** [comment]
Looks like the issue is resolved upstream

**Comment by AdmiringWorm** [comment]
Seems like the sourceforge urls stopped working again 😢

**Comment by gep13** [comment]
https://twitter.com/sfnet_ops/status/913044025791467520?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Etweet
