### ISSUE TITLE
(winscp) Wrong release notes link

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-coreteampackages#855]
## Expected Behavior
Release notes for the WinSCP package should link to release notes for the version of the package.

## Current Behavior
For https://chocolatey.org/packages/winscp/5.11.1 release notes link is https://winscp.net/download/WinSCP-5.9.6-ReadMe.txt

## Possible Solution
Update release notes link in the AU script

## Steps to Reproduce (for bugs)
1. See https://chocolatey.org/packages/winscp/5.11.1

## Your Environment
* Package Version used: 5.11.1

**Comment by majkinetor** [comment]
I believe this is related to AU bug that was resolved (#853). It shouldn't happen in the next release. I will just leave this version like this.

**Comment by majkinetor** [comment]
Force test looks good: https://gist.github.com/gep13/b733b29e320a8c05bc99cc0bf59cd8d1/6bd782cdc535dd7dab448ee691a605ce75e1ab65#winscpinstall
