### ISSUE TITLE
(voicebot) Failed automated test

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#856]
Not obvious what is the problem:

* [Package](https://chocolatey.org/packages/voicebot/3.1)
* [Test Result](https://gist.github.com/choco-bot/e77af9122961465e59cfe8d6a7d28bc2)

/cc @AdmiringWorm /cc @The-Running-Dev

**Comment by majkinetor** [comment]
The same thing happens to [ClipboardFusion](https://chocolatey.org/packages/clipboardfusion/5.0) which also provides from `https://binaryfortressdownloads.com`.

**Comment by AdmiringWorm** [comment]
The installer probably changed or something (maybe missing dependencies, or something along those lines), as I see for both of those the installer is hanging for too long.

I'll try having a look at this later today.

**Comment by majkinetor** [comment]
Good catch, didn't see the timeout.

**Comment by AdmiringWorm** [comment]
found the reason for the voicebot timeout, it requires .NET Framework 4.6 now.
Don't know yet about the ClipboardFusion package, but it's probably the same with that one.

**Comment by AdmiringWorm** [comment]
Alright, found out how to work around the installation of .NET 4.6 during the installer.
After installing .NET 4.6, there is a need to reboot.
If that is done, the installer won't prompt to install .NET 4.6.

So basically out of our hands for now, I'll push out an updated version, and add an exemption to the package. (After I've checked out ClipboardFusion as well).
