### ISSUE TITLE
Packages that should get embedded

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#866]
[1.1.4 - Embed a package if allowed](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md#114-embed-a-package-if-allowed) means that there are number of packages here that could be enhanced in this manner.

## Packages that should get embedded

- [ ] SparkleShare (GNU)
- [x] Python2 (GPL)
---

- [x] bluegriffon (Mozilla Public License)
- [x] brackets (MIT)
- [x] freevideoeditor
  > You may install and use the free version of the Product, released under the brand VSDC Free Video Editor, free of charge for personal and educational use. In this case, you are granted the right to use and to make an unlimited number of copies of this software.
- [x] gimp (GPLv3)
- [x] cdburnerxp
  > You may also make copies and distribute the software according to requirements of section 2 below.
- [x] cdrtfe (GNU)
- [x] classic-shell 
  > You are permitted to distribute the Classic Shell installer or offer it for download on your website, as long as:
- [x] clipboardfusion
  >  Free versions available for download from Binary Fortress Software's website may be freely distributed with written permission from Binary Fortress Software 
- [x] clipgrab (GNU)
- [x] displayfusion
  >  Free versions available for download from Binary Fortress Software's website may be freely distributed with written permission from Binary Fortress Software 
- [x] djv
  > Redistributions in binary form must reproduce the above copyright notice, this list of conditions, and the following disclaimer in the documentation and/or other materials provided with the distribution.
- [x] encfs4win (LGPL)
- [x] Ext2Fsd (LGPL)
- [x] hostsman
  > The Licensor grants you the right to make this freeware available on an
internet site for the purpose of downloading, as long as NO FEE IS CHARGED for
said download.
- [x] inkscape (GPL2)
- [x] jitsi (GPL2)
- [x] LibreCAD  (GPL2)
- [x] maxima (GPL)
- [x] mixx (GPL)
- [x] mkvtoolinix (
- [x] mpchc (GPL)
- [x] MuseScore (GPL2)
- [x] Mumble
  > Redistributions of source code must retain the above copyright notice,  this list of conditions and the following disclaimer. can be distributed through non-commercial channels,
- [x] nircmd ([personal communication](https://github.com/majkinetor/au-packages/blob/master/nirlauncher/legal/redistribution.pdf))
- [x] notepadplusplus (GPL)
- [x] owncloud-client (GNU)
- [x] PDFCreator (AGPL)
- [x] Python3 (GPL)
- [x] Vagrant (MIT) [**too large > 450MB**]
- [x] WinCdEmu (GNU)
- [x] x2go (GPL)
- [x] mp3tag
- [x] Prey (GNU)
- [x] Scribus (GNU)
- [x] TightVNC (GPL)
- [x] Tribler (GPL)
- [x] PHP
- [x] TV Browser (GNU)
- [x] Ultradefrag (GNU)
- [x] WinPcap 
  >  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

**Comment by AdmiringWorm** [comment]
freecad can't be embedded, it is too large.

**Comment by AdmiringWorm** [comment]
clover may not be able to embedd, as we have stopped updating the package to the latest version because of positives on virustotal and because the author have removed older downloads of the software

**Comment by AdmiringWorm** [comment]
while the freevideoeditor allows use to make unlimited copies of the software, it does not mention that we are allowed to distribute them. As such I don't really think we can embed the package (I may be reading this wrong though)

/cc @ferventcoder @gep13

**Comment by majkinetor** [comment]
BTW, it stops after J because I didn't have time back then to complete it since it requires traversal of entire list. You can consider I checked all packages before J.

**Comment by majkinetor** [comment]
List is complete now.

**Comment by majkinetor** [comment]
https://github.com/chocolatey/chocolatey-coreteampackages/pull/897

**Comment by AdmiringWorm** [comment]
pdfcreator is now embedded, and list have been updated

**Comment by majkinetor** [comment]
Thx @jack1142 for finishing this.

**Comment by jack1142** [comment]
No problem :)

**Comment by gep13** [comment]
Well done to everyone involved in getting this work completed!  😄
