### ISSUE TITLE
(ruby) install directory parameter has $rubyDir added - parameter description conflict

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#867]
Package parameters description for the package:

* `/InstallDir` - Ruby installation directory, by default `c:\tools\RubyXY` where XY are major and minor version parts.

Note this logic:

~~~powershell
$installDir = if ($pp.InstallDir) { $pp.InstallDir } else { Get-ToolsLocation }
$installDir = Join-Path $installDir $rubyDir
~~~

Guess what happens when I pass `--params "/InstallDir:c:\ruby24`?

**Comment by AdmiringWorm** [comment]
I hoped to look into this issue today, unfortunately my computer broke down just now (thankfully not a hardware breakage). So I'll be busy setting up windows anew.

Hopefully I can check it out during the weekend.

**Comment by majkinetor** [comment]
Thanks for report @ferventcoder .
