### ISSUE TITLE
(ruby) NoPath parameter does not work appropriately

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#868]
Observe the following:

https://github.com/chocolatey/chocolatey-coreteampackages/blob/3dc9d447caca4251d4b2dd6d241c8a9f39b4430e/automatic/ruby/tools/chocolateyInstall.ps1#L16
 * note `modpath` - that modifies the path

Then later down:
https://github.com/chocolatey/chocolatey-coreteampackages/blob/3dc9d447caca4251d4b2dd6d241c8a9f39b4430e/automatic/ruby/tools/chocolateyInstall.ps1#L23

The work for path is being done twice. And if you want `/NoPath`, you are still going to have it added to path.

**Comment by majkinetor** [comment]
Fixed.
