### ISSUE TITLE
(VisualStudioCode) Package parameters are not working

### ISSUE THREAD

**Issue by myevan** [chocolatey/chocolatey-coreteampackages#869]
## Expected Behavior
It makes desktop icon, quick launch icon and context menus with default package parameters.

## Current Behavior
no icons and no context menus.

## Possible Solution
remove white spaces in MERGETASKS or quote them.

### Current Working(Bug)
```
VSCodeSetup-x64-1.17.0.exe /MERGETASKS=!runcode, desktopicon, quicklaunchicon, addcontextmenufiles, addcontextmenufolders, addtopath
```

### Fix1: no white spaces
```
VSCodeSetup-x64-1.17.0.exe /MERGETASKS=!runcode,desktopicon,quicklaunchicon,addcontextmenufiles,addcontextmenufolders,addtopath
```

### Fix2: quotes
```
VSCodeSetup-x64-1.17.0.exe /MERGETASKS="!runcode, desktopicon, quicklaunchicon, addcontextmenufiles, addcontextmenufolders, addtopath"
```

## Steps to Reproduce (for bugs)

1. install
2. check icons
3. check context menus

## Context

...
 

## Your Environment
* Package Version used: 1.17.0 
* Operating System and version: windows 10
* Chocolatey version: 0.10.8
* Install/uninstall gist: ...

**Comment by pascalberger** [comment]
This might be a related comment on the package page: http://disq.us/p/1ml0299
