### ISSUE TITLE
(pdfcreator) Newest version reports 404

### ISSUE THREAD

**Issue by jberezanski** [chocolatey/chocolatey-coreteampackages#871]
The newest `pdfcreator` package version [3.0.2](https://chocolatey.org/packages/pdfcreator/3.0.2) tries to download http://download.pdfforge.org/download/pdfcreator/3.0.2/PDFCreator-3_0_2_8419-Setup.exe?file=PDFCreator-3_0_2_8419-Setup.exe&download, which does not exist (404).

The PDFCreator download page (http://download.pdfforge.org/download/pdfcreator/list) does not list version 3.0.2. However, the page lists both stable and nightly builds, so perhaps 3.0.2 was a nightly build (the AU script does not seem to skip those), which recently got pulled.

I think we should 1) unlist package version 3.0.2, 2) fix the AU script so that it skips the nightly builds.

**Comment by majkinetor** [comment]
There was an error for that version - [status](https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e/96481e2463313c2c1af7c8ff9a0abd9a94538896#errors)

Artifacts from that build show:
```
pdfcreator - checking updates using au version 2017.9.28.180808
URL check
  http://download.pdfforge.org/download/pdfcreator/3.0.2/PDFCreator-3_0_2_8419-Setup.exe?file=PDFCreator-3_0_2_8419-Setup.exe&download
nuspec version: 3.0.1
remote version: 3.0.2
New version is available
Automatic checksum started
Print Spooler service state: Auto / Running
Downloading pdfcreator 32 bit
  from 'http://download.pdfforge.org/download/pdfcreator/3.0.2/PDFCreator-3_0_2_8419-Setup.exe?file=PDFCreator-3_0_2_8419-Setup.exe&download'

Download of PDFCreator-3_0_2_8419-Setup.exe (28.79 MB) completed.
Package downloaded and hash calculated for 32 bit version
Setting package description from README.md
Updating files
  $Latest data:
    Checksum32      (String)    f126b572350949cf4af52d5dceba1687ff552eee9315d8c3b2c93ff03e8599cf
    ChecksumType32  (String)    sha256
    FileType        (String)    exe&download
    NuspecVersion   (String)    3.0.1
    PackageName     (String)    PDFCreator
    URL             (String)    http://download.pdfforge.org/download/pdfcreator/3.0.2/PDFCreator-3_0_2_8419-Setup.exe?file=PDFCreator-3_0_2_8419-Setup.exe&download
    Version         (String)    3.0.2

  pdfcreator.nuspec
    setting id:  PDFCreator
updating version: 3.0.1 -> 3.0.2
  tools\ChocolateyInstall.ps1
    (^[$]url\s*=\s*)('.*') = $1'http://download.pdfforge.org/download/pdfcreator/3.0.2/PDFCreator-3_0_2_8419-Setup.exe?file=PDFCreator-3_0_2_8419-Setup.exe&download' 
    (^[$]checksum\s*=\s*)('.*') = $1'f126b572350949cf4af52d5dceba1687ff552eee9315d8c3b2c93ff03e8599cf' 
Attempting to build package from 'pdfcreator.nuspec'.
Successfully created package 'C:\projects\chocolatey-coreteampackages\automatic\pdfcreator\PDFCreator.3.0.2.nupkg'
Package updated
```

That is, vendor deleted it later.

Unlisting should be done
AU Script looks at the first link which is from what I see not nightly.

**Comment by AdmiringWorm** [comment]
I've taken the steps to unlist the `3.0.2` version of the package

**Comment by majkinetor** [comment]
As far as I can see there is nothing more to do here. Feel free to disagree.
