### ISSUE TITLE
Should I migrate my packages to this repo?

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-coreteampackages#872]
Should I migrate my own packages to this repo? Is this recommended? What are the requirements?

**Comment by majkinetor** [comment]
We judge on case by case basis. Each package you want to migrate should generally be separate PR that we will review.  

Any package you want to migrate must comply to [guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md).

The goal of this repository is generally not to be a pile of everything under the universe but to provide hi quality mostly automatic packages that are easy to maintain.

One way to approach this is to convert your entire repository to the same system we use here (AU + AV automation) and if that is solid, migrating is a matter of copying files between repositories.
