### ISSUE TITLE
(chocolatey-core.extension) Functionality not to load pre-defined functions is failing

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#898]
## Expected Behavior
If I'm using Chocolatey v0.10.8, it has `Get-PackageParameters`, so that function should not be loaded.

## Current Behavior
The core extension is loading its own `Get-PackageParameters` anyway.

## Possible Solution
Fix the check

Might be an issue in Chocolatey, but as of like 0.10.4 we are preloading all built-in functions, so it should be found on the a pre and post compare.

**Comment by majkinetor** [comment]
> Might be an issue in Chocolatey, but as of like 0.10.4 we are preloading all built-in functions, so it should be found on the a pre and post compare.

The check works fine, its just that the choco helper functions aren't defined in time of importing the module. I added this in core psm1 extension:

```powershell
$pre = ls Function:\*
$pre | Write-Host
```

and it doesn't show any functions with `import-module C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1`

**Comment by ferventcoder** [comment]
We expressly export them before loading up the extensions as of 0.10.4. That's weird that they wouldn't be showing up, I remember testing this. However, let me take another look. In the meantime, we are going to need to have chocolatey-core.extension `Get-PackageParameters` also look at `$env:PackageParametersSensitive` when one is not passed in.

**Comment by ferventcoder** [comment]
`ls Function:\*` doesn't show something as simple as `Write-Host`, yet it is there if you call `Get-Command`. I think there is more work to be done here, the doesn't quite work. I think there are changes likely in Chocolatey to be done as well.

**Comment by majkinetor** [comment]
I checked that too. If I import chocolatey helpers, `ls Function:\*` shows all of them. I don't have much time to troubleshoot that now more extensively.

**Comment by ferventcoder** [comment]
@majkinetor the module is already exported in the process, the script would require an explicit. That's likely why I went with the original scenario for loading up functions where the function checks if it is already exported before it loads itself. That is deferred until later and would have everything already there and ready to look through.

**Comment by ferventcoder** [comment]
I know you believed that was messy, but it appears it may be the only way it could work.

**Comment by ferventcoder** [comment]
What I mean about that - you called it "smelly code" - https://github.com/chocolatey/chocolatey-coreteampackages/issues/454#issuecomment-266270634. Well sometimes "smelly code" is best if it works. What we have now doesn't work. You would need to explicitly load the module. You can't do that, because the module loading process imports the extension modules.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/chocolatey-coreteampackages/pull/456/files

**Comment by majkinetor** [comment]
It can be done on psm1 level instead in each file.

**Comment by ferventcoder** [comment]
Whatever the solution, it needs to meet a couple of considerations:

* Do not load up Chocolatey module or functions itself
* This will be shared with others who are attempting to do this same thing
* It should allow us not to export the Chocolatey module twice (current behavior that seems to have no effect on having functions loaded for the local import).

**Comment by ferventcoder** [comment]
This needs to stop loading in versions of Chocolatey that have implemented `Get-PackageParameters`. Simply put. Please do whatever is necessary to make that happen.

**Comment by ferventcoder** [comment]
At least in 0.10.9 where we've fixed quite a bit and made things more compatible with this one. Please log any issues of incompatibility on chocolatey/choco.

**Comment by AdmiringWorm** [comment]
@ferventcoder I actually tried to look into this earlier this month; but was unable to get it working correctly.
The only way I found that did work, was to manually check the scripts located in `$env:chocolateyInstall\helpers` and make a decision based on that.

Anything else failed to detect the available commands loaded by choco.
