### ISSUE TITLE
(cmake) Migrate these from dtgm

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#903]
CMake is a very important package and should migrate over so that it can be maintained.

**Comment by ferventcoder** [comment]
Thanks for the migration label. I missed it (unless it did not exist).

**Comment by AdmiringWorm** [comment]
Looking into migrating the cmake packages, should have it ready some time today or tomorrow

**Comment by ferventcoder** [comment]
Did these migrate and change package source url in the nuspec?

**Comment by AdmiringWorm** [comment]
@ferventcoder yes they have, but no new version have been released since we merged it in here.
And never did a force push either, maybe I should do that?

**Comment by ferventcoder** [comment]
Okay, you saw what I saw - the update to the repo AFTER we brought over the code.

**Comment by AdmiringWorm** [comment]
I'll force out an update for all three cmake packages.

**Comment by ferventcoder** [comment]
👍
