### ISSUE TITLE
(firefox) Update from 56.0.2 to 57.0 installed second version

### ISSUE THREAD

**Issue by NicoHaase** [chocolatey/chocolatey-coreteampackages#905]
When updating firefox from 56.0.2 to 57.0 on my PC, chocolatey installed it a second time instead of updating the existing installation. It was already installed in the 64 bit edition and now got installed a second time in 32 bit.

## Expected Behavior
Update my existing installation

## Current Behavior
Two firefox installations, one in C:\Program Files in 64 bit (v56) and one in C:\Program Files (x86) in 32 bit (v57)

## Your Environment
* Package Version used: 56.0.2 updating to 57.0
* Operating System and version: Windows 10 Pro, 1703
* Chocolatey version: v0.10.8

**Comment by NicoHaase** [comment]
FYI: even through the updated package, this is not resolved:

```
C:\WINDOWS\system32>cup firefox --version 57.0.0.20171115
Chocolatey v0.10.8
Upgrading the following packages:
firefox
By upgrading you accept licenses for the packages.

You have Firefox v57.0 installed. Version 57.0.0.20171115 is available based on your source(s).
Progress: Downloading Firefox 57.0.0.20171115... 100%

Firefox v57.0.0.20171115 [Approved]
firefox package files upgrade completed. Performing other installation steps.
Detected the 32-bit version of Firefox on a 64-bit system. This package will continue to install the 32-bit version of Firefox unless the 32-bit version is uninstalled.
Firefox is already installed. No need to download an re-install again.
 The upgrade of firefox was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.
```

**Comment by gep13** [comment]
@NicoHaase as a test, could you uninstall Firefox that is currently installed.  Install a specific version for the 56.x variant, and then try upgrading again?

**Comment by NicoHaase** [comment]
Sorry, currently I don't have time for tests.

**Comment by gep13** [comment]
> Sorry, currently I don't have time for tests.

Understood.  I suspect though, that given that you have upgraded to the interim wrong version, you are going to need to uninstall it in order to get back to the place that you want to be.

/cc @majkinetor

**Comment by NicoHaase** [comment]
I uninstalled the x86 version, which I should do anyways. Lets wait for the next update to see whether this is a long-term solution

**Comment by gep13** [comment]
@NicoHaase I have just installed version 56.02 of Firefox using Chocolatey, and I have then ran `choco upgrade firefox` which correctly installs version 57.0.0.20171115.

No additional version is installed, so I am fairly sure that this is now correct.
