### ISSUE TITLE
(qbittorrent) Beta version support

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-coreteampackages#906]
qBittorrent's package currently lacks of beta-versions support. 

They are available here: https://www.fosshub.com/qBittorrent.html

**Comment by dimqua** [comment]
Is it even possible to grab them from FossHub?

**Comment by AdmiringWorm** [comment]
it probably is possible somehow, but the workarounds will probably just work for a short time, and will need to be updated quite often.

As such, it probably won't ever be added to the repo, as well as fosshub don't want automatic scripts to download files from their webpage.
