### ISSUE TITLE
(thunderbird) Beta version support

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-coreteampackages#907]
Currently there are no beta and nigthly (daily) versions of Thunderbird available at the community repository.

**Comment by majkinetor** [comment]
You shouldn't know that requests for packages are on the specialized repository ?

**Comment by majkinetor** [comment]
Sorry, forgot it is already here :)

**Comment by AdmiringWorm** [comment]
@majkinetor yup, that is why I asked him to post it here instead of the package request repository
