### ISSUE TITLE
(vlc) Add portable and meta package

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-coreteampackages#908]
1. [VLC package](https://chocolatey.org/packages/vlc) is not meta-package and points to the install version. I guess it should be renamed to ```vlc.install```.

2. [VLC Portable](https://chocolatey.org/packages/vlc.portable) package is outdated and probably should be migrated to this repository.

**Comment by majkinetor** [comment]
I added portable as a stream, but I wont add metapackage, it doesn't seem necessary and it isn't required by guidelines.

**Comment by dimqua** [comment]
Thx. I didn't aware about existence of streams at all, where can I read more about them?

**Comment by majkinetor** [comment]
Streams are new and not yet released feature. It will be available in next release, you can use ASAP however if you reference master AU branch - called [NEXT version](https://github.com/majkinetor/au/blob/master/CHANGELOG.md#next)

**Comment by majkinetor** [comment]
I am hesitant to add meta packages until they work correctly (seems to be a gallery issue). The 'non existent' bug happens behind a proxy and is a rule rather then exception.. It is particularly nasty with dependencies as you must manually install all that fail.

We don't have any rules in place about this. Is this actually a suggestion or a mandatory stuff ?

**Reference**: https://github.com/chocolatey/choco/issues/1004

/cc @AdmiringWorm @ferventcoder

**Comment by majkinetor** [comment]
Closing this due to lack of interest and bad public decisions (https://github.com/chocolatey/chocolatey-coreteampackages/pull/909)
