### ISSUE TITLE
(ext2fsd) Install/upgrade causes forced reboot

### ISSUE THREAD

**Issue by frankhalligan** [chocolatey/chocolatey-coreteampackages#914]
Upgrading or installing ext2fsd causes an unprompted reboot to occur. Presumably due to /NORESTART being removed from chocolateyInstall.ps1 in this commit https://github.com/chocolatey/chocolatey-coreteampackages/commit/c6a84f91ecb7a025139e222317a9202bc95642ca#diff-941d9cbb2673445f6a69ae7de8952b4a

**Comment by AdmiringWorm** [comment]
ops, looks like a mistake on my part.
Give me a few moments, and I'll have a new version pushed to chocolatey

**Comment by AdmiringWorm** [comment]
build have been queued, and should be pushed to chocolatey.org shortly.
Let me know if it doesn't happen though.

**Comment by AdmiringWorm** [comment]
had a typo when I queued ext2fsd for updating previously, corrected that now and an updated package have been pushed to chocolatey

**Comment by frankhalligan** [comment]
Cheers, all working now
