### ISSUE TITLE
(curl) Add package param to allow automatic removal of Powershell curl alias

### ISSUE THREAD

**Issue by MichaelGerhart** [chocolatey/chocolatey-coreteampackages#919]
## Expected Behavior
When running a 'curl' command after installing onto a Windows server, I expect it to call curl.exe.

## Current Behavior
By default, Powershell has an alias for curl, that instead calls Invoke-WebRequest.

## Possible Solution
Create a package param(/alias:remove ?) that will remove the curl alias for Invoke-WebRequest.

Command to be run if the remove option is present: Remove-Item alias:\curl

## Context
When end users deploy this package (Mostly Devs), they run curl and get prompted for a uri, as it defaults to the Invoke-WebRequest cmdlet. When the user install, I want them to be able to easily disable the alias so calling curl uses the package curl.exe instead of iwr.

## Your Environment
* Package Version used: 7.56.1
* Operating System and version: Windows 7/10, Server 2012 R2/2016
* Chocolatey version: 0.10.8

**Comment by AdmiringWorm** [comment]
Just using `Remove-Item alias:\curl` would just remove the curl alias for the current session, not permanently remove the alias.

To have it permanently removed would require manipulation of the windows profile script which is loaded whenever a powershell session is initialised.
To edit the powershell profile isn't something I personally would be interested in implementing though, as that isn't something a package should do unless it provides powershell scripts that requires that the profile to be edited (that's just my own opinion though).

As a workaround, you could just call `curl` with the file extension though: `curl.exe` to have the one you want to be picked up.

**Comment by majkinetor** [comment]
I agree with @AdmiringWorm. I do this in my ["profile.d"](https://github.com/majkinetor/powershell_profile.d/blob/master/99_general.ps1#L17).
