### ISSUE TITLE
(git) Add a package parameter to enable "Use the native Windows SChannel library"

### ISSUE THREAD

**Issue by mawl** [chocolatey/chocolatey-coreteampackages#922]
Hi,

Can you please add a package parameter for https://chocolatey.org/packages/git to enable "Use the native Windows SChannel library" (WinSSL). see: https://github.com/git-for-windows/build-extra/pull/135/files

Thanks a lot :)
Marco

**Comment by majkinetor** [comment]
Explanation?'

**Comment by AdmiringWorm** [comment]
fixed in PR #984
