### ISSUE TITLE
(displayfusion) Wrong installation directory

### ISSUE THREAD

**Issue by verglor** [chocolatey/chocolatey-coreteampackages#924]
DisplayFusion is installed in temp directory next to `DisplayFusionSetup-9.1.exe` probably due to double-dollar typo (```/DIR=`"$$programFiles`"```) in [chocolateyInstall.ps1#L12](https://github.com/chocolatey/chocolatey-coreteampackages/blob/5bcb04c/automatic/displayfusion/tools/chocolateyInstall.ps1#L12)

## Expected Behavior
Package should be installed in `%ProgramFiles(x86)%\DisplayFusion\`

## Current Behavior
Package is installed in `%TEMP%\chocolatey\displayFusion\9.1\programFiles\`

## Possible Solution
Fix  double-dollar typo (```/DIR=`"$$programFiles`"```) in [chocolateyInstall.ps1#L12](https://github.com/chocolatey/chocolatey-coreteampackages/blob/5bcb04c/automatic/displayfusion/tools/chocolateyInstall.ps1#L12)

## Steps to Reproduce (for bugs)
1. `cinst displayfusion --version 9.1`

## Your Environment

* Package Version used: 9.1
* Operating System and version: Win10 x64
* Chocolatey version: 0.10.8
* Install/uninstall gist: `cinst displayfusion --version 9.1`

**Comment by AdmiringWorm** [comment]
Thank you for reporting this, that double dollar sign is definitely the reason why the wrong installation folder is used.

I'll get right on it to get out a fix version of the latest version.

**Comment by AdmiringWorm** [comment]
@verglor an update for this package have been queued on the build server, and should be pushed to chocolatey.org shortly
