### ISSUE TITLE
(displayfusion) Installation of older version (8.1.2) failed

### ISSUE THREAD

**Issue by verglor** [chocolatey/chocolatey-coreteampackages#925]
Cannot install older version of package because the latest setup file is downloaded instead of specified version.

## Expected Behavior
Correct setup file should be downloaded from
https://binaryfortressdownloads.com/Download/BFSFiles/101/DisplayFusionSetup-8.1.2.exe

## Current Behavior
Incorrect (latest) version 9.1 is downloaded hence the hash check fails:
```
Downloading displayfusion
  from 'https://www.binaryfortress.com/Data/Download/?package=displayfusion&log=101'
Progress: 100% - Completed download of C:\Users\jako\AppData\Local\Temp\chocolatey\displayFusion\8.1.2\DisplayFusionSetup-9.1.exe (20.55 MB).
Download of DisplayFusionSetup-9.1.exe (20.55 MB) completed.
Error - hashes do not match. Actual value was '8F1CFAFDA844C018A87FC216B38BC38C69269A1A0798BDD1B41CCA17F9ED6C08'.
```
## Steps to Reproduce (for bugs)
1. `choco install -y displayfusion --version 8.1.2 --allow-downgrade`

## Your Environment
* Package Version used: 8.1.2
* Operating System and version: Win10 x64
* Chocolatey version: 0.10.8

**Comment by AdmiringWorm** [comment]
at the current time older versions of this package is unsupported, these versions are from before the package was migrated to this repository.

We'll keep this issue open though, but at the moment you'll need to use version `9.0` or higher (or buy a license for the pro edition of chocolatey, which enables the option to download from a CDN where the binary is cached).
