### ISSUE TITLE
360 TS Essentials

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#931]
Can anyone speak to this comment:

https://chocolatey.org/packages/360ts#comment-3644246855

This isn't a package that I use personally.

**Comment by AdmiringWorm** [comment]
I've never used the package, nor the software.
But I was under the impression that TS and TSE was the same thing.
Apparently not though, when going with the comment.

**Comment by majkinetor** [comment]
This is for RFP repossitory

**Comment by gep13** [comment]
@majkinetor is that true?  The reason that I raised this here is that the existing package is in this repository.  If it is indeed installing "crapware" then we may need to remove it, in favour of the other package version.

**Comment by majkinetor** [comment]
Yes it is. It is not directly related to the current package .

If the current package should be unlisted then it is a ticket for this repository.

If we need a new package that is for RFP. If that package should live here one should PR code for it. Deprecation of existing package we can handle.

**Comment by majkinetor** [comment]
We dont accept RFPs here as there is place for that. Any core maintainer or anybody else may choose to be maintainer of RFP/M available packages and do so here if he wishes to do so, using regular protocol.

Tickets are for existing packages, not related.

**Comment by majkinetor** [comment]
In order to get this ticket reopened remove 'essentials' from the title and request unlist/deprecation.
