### ISSUE TITLE
(firefox) Add a default locale to the variable

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#933]
It would be awesome if this package could set the $locale variable to a default of 'en-US' to allow the internalizer to work. Several folks have asked for this. Eventually an advanced version of the internalizer will be available that allows script execution, but for now it can do variable set/replacements for everything but script executions.

https://github.com/chocolatey/chocolatey-coreteampackages/blob/8f4456afe6658bb042cf880ab24acc6017aa3ff7/automatic/firefox/tools/chocolateyInstall.ps1#L27

would become:

~~~powershell
# adding default for internalizer
$locale = 'en-US'
$locale = GetLocale -localeFile "$toolsPath\LanguageChecksums.csv" -product $softwareName
~~~

**Comment by ferventcoder** [comment]
Updated to add notes to this:

It would be awesome if this package could set the $locale variable to a default of 'en-US' to allow the internalizer to work. Several folks have asked for this. Eventually an advanced version of the internalizer will be available that allows script execution, but for now it can do variable set/replacements for everything but script executions.

https://github.com/chocolatey/chocolatey-coreteampackages/blob/8f4456afe6658bb042cf880ab24acc6017aa3ff7/automatic/firefox/tools/chocolateyInstall.ps1#L27

would become:

~~~powershell
# adding default for internalizer
$locale = 'en-US'
$locale = GetLocale -localeFile "$toolsPath\LanguageChecksums.csv" -product $softwareName
~~~

**Comment by ferventcoder** [comment]
Thank you much!

**Comment by dfranciscus** [comment]
Just FYI, internalizing still doesn't seem to be working, at least for me:

 C:\Example> choco download firefox --internalize  --internalize-all-urls
Chocolatey v0.10.8 Business
Downloading existing package(s) to C:\Example\download

chocolatey-core.extension v1.3.3 [Approved]

Recompile not necessary. There is no install script. Use the nupkg file
 as is in 'C:\Example\download\chocolatey-core.extension'

Firefox v57.0.4 [Approved]
Found Install-ChocolateyPackage. Inspecting values for remote resources.
Unable to find value for variable '${locale}'. May not be able to download resource from url 'https://download-installer.cdn.mozilla.net/pub/firefox/rele
ases/57.0.4/win32/${locale}/Firefox%20Setup%2057.0.4.exe'.
Found 'https://download-installer.cdn.mozilla.net/pub/firefox/releases/57.0.4/win32/${locale}/Firefox%20Setup%2057.0.4.exe' for replacement.
Unable to find value for variable '${locale}'. May not be able to download resource from url 'https://download-installer.cdn.mozilla.net/pub/firefox/rele
ases/57.0.4/win64/${locale}/Firefox%20Setup%2057.0.4.exe'.
Found 'https://download-installer.cdn.mozilla.net/pub/firefox/releases/57.0.4/win64/${locale}/Firefox%20Setup%2057.0.4.exe' for replacement.

Encountered error downloading package firefox v:
System.Exception: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download-installer.cdn.mozilla.net/pub/firefox/
releases/57.0.4/win32/${locale}/Firefox%20Setup%2057.0.4.exe'.
  The remote server returned an error: (404) Not Found.
   at chocolatey.licensed.infrastructure.app.commandresources.RemoteDownloader.download_file(String url, String filePath, String userAgent)
   at chocolatey.licensed.infrastructure.app.commands.ProChocolateyDownloadCommand.process_downloaded_package(IPackage package, String downloadLocation,
ChocolateyConfiguration configuration)
   at chocolatey.infrastructure.app.nuget.NugetCommon.<>c__DisplayClass14.<GetPackageManager>b__11(Object s, PackageOperationEventArgs e)
   at NuGet.PackageManager.OnInstalled(PackageOperationEventArgs e)
   at NuGet.PackageManager.Execute(IPackage package, IPackageOperationResolver resolver)
   at NuGet.PackageManager.InstallPackage(IPackage package, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   at chocolatey.licensed.infrastructure.app.commands.ProChocolateyDownloadCommand.download_packages(String packageName, String packageVersion, String do
wnloadLocation, ChocolateyConfiguration configuration)

**Comment by ferventcoder** [comment]
@dfranciscus Likely something small we'll need to change in the internalizer code. We've heard back from another party that this doesn't work for them either. 

Basically we need to implement a fall back if the value was set without running code.
