### ISSUE TITLE
(libreoffice) Incorrect checksum for 32-bit installer

### ISSUE THREAD

**Issue by michaelray** [chocolatey/chocolatey-coreteampackages#944]
The SHA256 checksum for the 32-bit LibreOffice installer is incorrect, resulting in a checksum mismatch error when attempting to install/upgrade libreoffice on 32-bit machines.  After manually verifying the checksums on the 32-bit and 64-bit installers of LibreOffice 5.4.4, it appears that only the 32-bit installer checksum is incorrect.  The 64-bit checksum is correct, so this issue would only affect those on 32-bit systems.  This doesn't appear to affect any other prior versions of the libreoffice package, other than 5.4.4.

## Checksums:
LibreOffice_5.4.4_Win_x86.msi (doesn't match)
--------------------
Package checksum:
19051e438245160bb27e004a6c2dd63cdda1254900c1fe7f7025de2146dc27b7
Actual checksum:
7c56031fb5577edafd35153c0d284ecf2c0ec3773a72f3e2209271c44ba156a8

LibreOffice_5.4.4_Win_x64.msi (matches)
--------------------
Package checksum:
0738dd24b5ba9a9dab079df34db7543d9d8b9a7a2989c0a4934debbaea8a5c8f
Actual checksum:
0738dd24b5ba9a9dab079df34db7543d9d8b9a7a2989c0a4934debbaea8a5c8f

## Expected Behavior
Upgrades/installs for libreoffice 5.4.4 should succeed without failure because of checksum mismatches.

## Current Behavior
Upgrades/installs for libreoffice 5.4.4 fail on 32-bit machines.

## Possible Solution
Manually adjust the checksum for the 32-bit LibreOffice 5.4.4 installer to be correct or maybe re-run the automatic package so that it can get the correct checksum, since libreoffice looks to be an automatic package.. and, of course, re-push the updated package to chocolatey.

## Steps to Reproduce (for bugs)
1.  Install or update the libreoffice 5.4.4 package on a 32-bit machine.

## Context
I was doing typical chocolatey upgrades on a 32-bit machine and encountered this invalid checksum error.

## Your Environment
* Package Version used:  libreoffice 5.4.4
* Operating System and version:  Windows 10 Pro 32-bit (Version: 1709, OS Build: 16299.125)
* Chocolatey version:  0.10.8

**Comment by AdmiringWorm** [comment]
Thanks for opening this issue.
I was meaning to push out an updated package, but honestly never got around to it.

**Comment by AdmiringWorm** [comment]
I just pushed out a couple of new packages related to libreoffice ([libreoffice-fresh](https://chocolatey.org/packages/libreoffice-fresh) and [libreoffice-still](https://chocolatey.org/packages/libreoffice-still)).
I suggest using one of those when they have been approved, when they have the libreoffice and libreoffice-oldstable packages will be deprecated.

**Comment by AdmiringWorm** [comment]
The deprecation of those packages have been planned for quite some time, but just never gotten around to it.

**Comment by AdmiringWorm** [comment]
completely forgot about closing this one.
