### ISSUE TITLE
jre8 - JAVA_HOME= problems

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/chocolatey-coreteampackages#945]
I've noticed on multiple machines that JAVA_HOME= is not set to the current version of jre8 installed. I have not tested enough to figure out if it's an install problem or an upgrade problem. My guess is it's an upgrade problem as I've had JAVA_HOME= set to an older version's install dir.

## Expected Behavior
I expect JAVA_HOME= to point to the latest installation path of jre8.

## Current Behavior
JAVA_HOME= points to an older version of jre8

## Possible Solution
add error checking after line 53 of the chocolateyinstall.ps1

` $homepath = $version -replace "(\d+\.\d+)\.(\d\d)(.*)",'jre1.$1_$2'`

I'm ASSUMING this is where it's done, but I don't see $homepath defined.

## Context
Constantly causes openHAB to fail as it needs JAVA_HOME= set to the correct place to work. 

## Your Environment
Java SE Runtime Environment 8.0.151 and probably every previous version for the last two years.
Windows 10
Chocolatey v0.10.8 and at least going back to 0.10.7

**Comment by AdmiringWorm** [comment]
@bcurran3 wrong repository. The jre8 package isn't hosted here in this repo.
Try contacting the maintainers instead.
