### ISSUE TITLE
(7zip) vulnerabilities in RAR format with all versions except 18 (beta)

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#954]
Please see 

* https://groups.google.com/d/msgid/chocolatey/3efeec42-333c-44c7-a99e-1d3f0ff1e94a%40googlegroups.com
* https://landave.io/2018/01/7-zip-multiple-memory-corruptions-via-rar-and-zip/
* http://7-zip.org/
* https://sourceforge.net/p/sevenzip/discussion/45797/thread/628149a0/

**Comment by AdmiringWorm** [comment]
Working on adding streams to the package so we can support the beta releases.

**Comment by AdmiringWorm** [comment]
Pushed changes to add streams for the package, and the 18 beta release should be pushed to chocolatey shortly.

Not sure if we should keep this open until there have been a fixed stable version though.

**Comment by ferventcoder** [comment]
I'm not sure if we shouldn't push the beta as stable, Igor is not releasing 18 for 3 more weeks -
 https://sourceforge.net/p/sevenzip/discussion/45797/thread/628149a0/#7c18/5e30

**Comment by ferventcoder** [comment]
We can also post fix it with package release version notation.

**Comment by ferventcoder** [comment]
@AdmiringWorm thoughts?

**Comment by AdmiringWorm** [comment]
considering the `18.1` version was released now, I would consider this as closed as long as it isn't susceptible to the mentioned vulnerability.

**Comment by ferventcoder** [comment]
Yes, agreed.
