### ISSUE TITLE
(wesnoth) Beta version support

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-coreteampackages#958]
There are [beta versions](https://sourceforge.net/projects/wesnoth/files/wesnoth/) of the Battle for Wesnoth game, but they're not supported by the package.

https://chocolatey.org/packages/wesnoth

**Comment by AdmiringWorm** [comment]
I'll mark this as an up for grabs, however I doubt it will be added.

We'll need a way to tell the difference between stable and beta releases, in which case I could see no way to parse such information easily.

Feel free to point it out if you are able to see it though.

**Comment by dimqua** [comment]
Only beta releases are hosted here: https://sourceforge.net/projects/wesnoth/files/wesnoth/

Stable releases: https://sourceforge.net/projects/wesnoth/files/

**Comment by AdmiringWorm** [comment]
I see, I didn't notice the extra `wesnoth` in the path, in which case it will be added sooner or later, but I'm keeping it as an Up for grabs for now

**Comment by AdmiringWorm** [comment]
beta versions have now been included with the version check (Latest beta should be available on chocolatey.org shortly)
