### ISSUE TITLE
(nssm) package failing to install

### ISSUE THREAD

**Issue by steve-hawkins** [chocolatey/chocolatey-coreteampackages#959]
## Expected Behavior
executing `choco install nssm` should install the Non-Sucking Service Manager

## Current Behavior
executing `choco install nssm` results in error

## Possible Solution
I'm taking a look at the nssm.nuspec file as the errors suggest suspect package information

## Steps to Reproduce (for bugs)
1. `choco install nssm`

## Your Environment
* Package Version used: 2.24.101.20180116
* Operating System and version: Windows 10.0.16299.0
* Chocolatey version: 0.10.8
* Install/uninstall gist: [choco-nssm-install-error](https://gist.github.com/steve-hawkins/11b7770302cb77cd3879535806ca4e90#file-choco-nssm-install-error)

**Comment by majkinetor** [comment]
From your log it says:

> Unable to read package from path 'NSSM.2.24.101.20180116.nupkg'.
> - No package information as package is null.

which is before package script is executed.

**Comment by steve-hawkins** [comment]
strange how `choco install nssm --version 2.24.0` installs just fine

**Comment by majkinetor** [comment]
Definitelly some local problem.

**Comment by majkinetor** [comment]
cc @ferventcoder 

This looks like reported problem but package is in that case not found without the version.
