### ISSUE TITLE
uninstall of vcredist redistributables

### ISSUE THREAD

**Issue by matbech** [chocolatey/chocolatey-coreteampackages#96]
I have some concerns in regards with uninstalling of redistributables like vcredist2015 etc. Consider the following situation:
- the vcredist redistributable was installed as part of another application the user installed without choco.
- user installs a choco package X which has a dependency on vcredist
- choco decides to install vcredist. In reality the vcredist installation is skipped because it is already installed. vcredist has no reference count (http://stackoverflow.com/questions/18603313/how-to-avoid-uninstalling-previously-installed-exepackage-redistributables-whi)
- users decides to uninstall package X. Assuming there are no other packages which depend on vcredist, the choco reference count of the dependency (vcredist) reaches 0 and vcredist will be uninstalled.
- All applications depending on vcredist will fail to start

My recommendation is to mark the vcredist package as permanent, meaning it will never be uninstalled. If there is currently no such flag, no uninstall method should be included in the nuspec.

**Comment by gep13** [comment]
@matbech by derfault, uninstalling packages will leave the dependent packages in place.  You would need to pass the `-x` parameter in order to force the uninstallation of the dependencies.  See `choco uninstall /?` for more information.

Does that help with your concern?

**Comment by matbech** [comment]
Yes in that case the problem doesn't happen. I did assume that the dependencies were ref counted.

**Comment by gep13** [comment]
Cool, so sounds like we are ok :smile:
