### ISSUE TITLE
(wixtoolset) Installer broken. Download url changed, now hosted on Github

### ISSUE THREAD

**Issue by jordigg** [chocolatey/chocolatey-coreteampackages#960]
## Expected Behavior
Package should be able to download the installer. It does not because the URL changed and is not hosted on Github.

## Current Behavior
The installer fails.

## Possible Solution
Fix update script to get new urls from Github releases. The latest is at: https://github.com/wixtoolset/wix3/releases/latest -> https://github.com/wixtoolset/wix3/releases/download/wix3111rtm/wix311.exe

## Steps to Reproduce (for bugs)
`chocolatey install wixtoolset`

## Context
We can't install the tool via chocolatey. We use Puppet to automate the setup of machines. This package and it's dependencies won't get installed.

## Your Environment
* Package Version used: Latest (3.11.1)
* Operating System and version: Windows 10 Pro
* Chocolatey version: Latest (0.10.8)
* Install/uninstall gist: (update in this case) https://gist.github.com/jordigg/e01492baf73f2088112823b21aa7f8fc

**Comment by gep13** [comment]
@jordigg can you please confirm what version of wixtoolset you were trying to install?  The latest version of the wixtoolset package actually embeds the installer, so there is no requirement for it to download it at all.

**Comment by AdmiringWorm** [comment]
@jordigg I see from the log you posted that you're trying to install an older version, the older versions are unlikely to be updated.
Please install the latest version 3.11.1, which is as @gep13 said an embedded package and does not rely on downloading the installer during install.
