### ISSUE TITLE
(1password) if you allow upgrades to v6 (current), we'll need a v4 package as well (1password4)

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#968]
Discussion at https://chocolatey.org/packages/1password#comment-3703155464

**Comment by AdmiringWorm** [comment]
A package named `1password4` is in the process of getting pushed to chocolatey.org now, when it have been pushed I'll ask for an exemption of v6 of password that was previously pushed to chocolatey.org.

**Comment by gep13** [comment]
@AdmiringWorm the 1password4 package has been approved.

**Comment by AdmiringWorm** [comment]
@gep13 thank you. I've added an exemption for the 1password package now.
