### ISSUE TITLE
(apache-httpd) Make service installation optional

### ISSUE THREAD

**Issue by uiii** [chocolatey/chocolatey-coreteampackages#983]
## Expected Behavior

When installing apache there will be an option to disable service installation.

## Current Behavior

Apache service is installed by default and cannot be disable during install.

## Possible Solution

Add package parameter (e.g. `/noService`) to disable service installation

## Context

In my workflow I'm running the server manually (multiple instances) and don't want to run the service at all.

**Comment by AdmiringWorm** [comment]
Definitely something that could be added.

I've added this as an up to grabs for now, but it should be an easy addition to the package.

**Comment by uiii** [comment]
Thanks for implementation. But when it will be propagated to chocolatey database? https://chocolatey.org/packages/apache-httpd doesn't seem to be updated.

**Comment by AdmiringWorm** [comment]
it will be available when the next version of apache-httpd software is released, depending on the release cycle of the software we can force an update if it's truly urgent though.
