### ISSUE TITLE
(typescript) only redirects install to npm

### ISSUE THREAD

**Issue by trailmax** [chocolatey/chocolatey-coreteampackages#986]
TypeScript package only redirects install to npm. If npm is out of date or not available, the installation fails.

## Expected Behavior

Flawless installation of the package, not a bunch of errors that npm produces. Not requiring npm to be involved at all.

## Current Behavior

Current TypeScript package does not do anything other than calling `npm install -g typescript@2.7.2`

## Possible Solution

Well, choco packages are expected to carry all required files without needing to install unnecessary bloat of dependencies. Choco is not npm (did I tell have a distaste for npm?), if I wanted to use npm, I would not fire choco.
I did not nave npm configured and it was out of date, last time I used npm it was using a private feed. So instead of problem-less experience usually served by choco, I've wasted 40 minutes debugging the issues, updating my rusty npm and figuring out how it works so I can change the feed, etc. Not something I wanted to do to update my typescript.

## Steps to Reproduce (for bugs)

1. Not have npm installed (crazy, I know!)
2. Have out-of date npm version
3. Aliens ate my node?

## Your Environment

* Package Version used: TypeScript 2.7.2
* Operating System and version: Win10
* Chocolatey version: v0.10.9-beta-273-g3cb969b
* Install/uninstall gist: `choco upgrade typescript`

**Comment by gep13** [comment]
@trailmax I just had a quick look at the download section of the TypeScript site:

https://www.typescriptlang.org/#download-links

And it looks like their recommendation is to install through npm.  Did I miss something?  Can you install it another way?

Looks like this Chocolatey Package is essentially a wrapper around the recommended installation steps.

**Comment by trailmax** [comment]
@gep13 Seems like there is no other way to do it now. Back in v1.x time I remember there used to be a downloadable installation file, hence I was hoping for the same experience.

Oh, well, seems like we are all becoming victims of npm tyranny and choco can't really do anything else. 
Sorry about the skirmish.

**Comment by gep13** [comment]
>@trailmax said...
Sorry about the skirmish.

No need to apologise.

Are you happy for this to be closed?

**Comment by trailmax** [comment]
I don't think we can do much about it, so yeah, let's close it.

**Comment by AdmiringWorm** [comment]
@trailmax please do let us know if at any point in the future they start providing typescript through a normal installer, I would be happy to update the install and update scripts to change it to handle that instead.

**Comment by trailmax** [comment]
@AdmiringWorm thanks for the offer, but I'll probably be the last one to notice this change. I'm not really following JS/TS world closely.
