### ISSUE TITLE
(cmake) not in PATH

### ISSUE THREAD

**Issue by mcandre** [chocolatey/chocolatey-coreteampackages#987]
ay make sure cmake perists in PATH upon installation, so that project builds can find it

**Comment by AdmiringWorm** [comment]
you can already do this (or should anyhow).

install cmake like this to have it added to PATH for all users:
```console
choco install cmake.install --installargs '"ADD_CMAKE_TO_PATH=System"'
```

or the following to have it added to PATH for the current user only
```console
choco install cmake.install --installargs '"ADD_CMAKE_TO_PATH=User"'
```

There isn't any intention of adding it by default, as it isn't added by default in the installer.

**Comment by HakShak** [comment]
For other internet travelers:

@AdmiringWorm solution is *almost* correct, see https://github.com/dtgm/chocolatey-packages/issues/297

Note the double double quotes:

`choco install cmake --installargs 'ADD_CMAKE_TO_PATH=""User""'`

**Comment by manhnt9** [comment]
This is different from website. Which leads me to failure in adding CMake to PATH.

On Web: `choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

Effective: `choco install cmake.install --installargs '"ADD_CMAKE_TO_PATH=User"'`

Please update the website.

**Comment by AdmiringWorm** [comment]
@manhnt9 Just tested the example shown in the package, and everything works as it should.
After installing cmake, did you reload the environment variables? (either by using `refreshenv` or by closing and re-opening the command prompt)

**Comment by manhnt9** [comment]
Maybe it's because you already had the vars set. I tried uninstall CMake and reinstall several times. Choco didn't even warn me to refreshenv (and I did try that too).

The command here solved my problem.

**Comment by AdmiringWorm** [comment]
I did not. Whenever I test packages, this is done in a completely bare-bones VM with next to nothing installed in it. (The VM in question is: https://github.com/chocolatey-community/chocolatey-test-environment)

**Comment by manhnt9** [comment]
Well that's interesting though. Maybe there's something wrong with my environment.

**Comment by AdmiringWorm** [comment]
Well, everything is possible. You may also have had a typo, or maybe there is a difference in what command prompt was used (in my case, I tested it in powershell).

**Comment by manhnt9** [comment]
Probably there's difference between cmd and powershell.

**Comment by Groostav** [comment]
I ended up uninstalling and reinstalling cmake (and cmake.install --im not sure how choco packages work here) several times.

Turns out `refreshenv` simply wasnt doing its job. `choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"'` did indeed install cmake to `C:\Program files\CMake\` and it did update the System's `PATH` variable such that its last entry was `C:\Program Files\CMake\bin`.

The problem was that `refreshenv` was not adaquately refreshing my environment. Restarting the shell worked.

**Comment by Timmmm** [comment]
I had to uninstall CMake and then reinstall it with:

    choco install cmake --installargs 'ADD_CMAKE_TO_PATH=User'

Just reinstalling it with `--force` didn't work. Also this seems like a mad design. Does every package have a different variable to add it to the PATH? Do I have to look up `ADD_GIT_TO_PATH` too? It would be much better if it prompted you "Do you want to add CMake to the PATH: *system, *user, *no"

**Comment by CybershoesVR** [comment]
I ran into this problem today
I took me some time to figure it out
I would expect to be able to execute `cmake` after  installing `cmake`
can we have this as a default?

**Comment by saolof** [comment]
This. The entire point of a package manager is being just an "install x" away from being able to type "x args" in the command line, with sane defaults.

If I didn't want to add it to path, I'd look up flags. But the default with no flags should be a usable setup out of the box.

**Comment by Luvideria** [comment]
I agree on this. At least some way to add it after install, instead of having to uninstall and re-install with the `ADD_CMAKE_TO_PATH`.
But maybe it's not clear **why** it is not the default. Someone care to explain?
on the first response we see: 
from @AdmiringWorm 
> There isn't any intention of adding it by default, as it isn't added by default in the installer.
Why is this so?
Is it a requirement from choco itself?
I had expected that everything choco installs is automatically referenced somehow.

**Comment by AdmiringWorm** [comment]
> Why is this so?
> Is it a requirement from choco itself?

Not specifically a requirement, however in general chocolatey packages are expected to behave similar to the defaults of an installer.
There are a few exceptions, but this is unfortunately not one of them.

**Comment by aminya** [comment]
How can I do this in ChocolateyGUI? The default behavior should add cmake to the PATH.

**Comment by AdmiringWorm** [comment]
@aminya you can't, not until https://github.com/chocolatey/ChocolateyGUI/issues/545 is implemented.
Use the cli until then.
