### ISSUE TITLE
Add development version for GIMP to gimp package

### ISSUE THREAD

**Issue by TomOne** [chocolatey/chocolatey-coreteampackages#99]
See https://www.gimp.org/downloads/#development-snapshots.

The development builds executables are a 7-Zip SFX archive. Need to adapt the package to support that in addition to the official installer.

**Comment by majkinetor** [comment]
Closed for a lack of implementation after a year.

**Comment by rjt** [comment]
2.8.22 is the official version, but does not save MetaData and may delete existing metadata.  A dev option would be great.
