### ISSUE TITLE
(gnucash) Update required: latest stable version is 2.6.19

### ISSUE THREAD

**Issue by OlafHaag** [chocolatey/chocolatey-coreteampackages#992]
As of 2018-02-09, the latest stable version is 2.6.19. Thanks in advance for upating the package.

## Expected Behavior
up-to-date with stable release

## Current Behavior
not up-to-date with stable release

## Possible Solution
update to latest stable release

## Context
In v2.6.18 online banking isn't available when installed through chocolatey (probably has nothing to do with choco)

**Comment by AdmiringWorm** [comment]
Thanks for letting us now, seems like the package wasn't updated due to the incorrect update of the `2.7.1` version in the past, and the version in this repository was forgotten to be rolled back.

A new version should be available in a few hours if everything goes according to plan.
