### ISSUE TITLE
(Krita) 4.0.0 Release

### ISSUE THREAD

**Issue by jongalloway** [chocolatey/chocolatey-coreteampackages#994]
## Expected Behavior
Package update for new Krita 4.0.0 release

## Current Behavior
Comment on package discussion says waiting on 32 bit release. From Twitter, it appears that Krita has deprioritized and may have discontinued 32 bit releases.

## Possible Solution
Create a pre package with 64 bit only support, or create a new 64 bit package?

## Context
[Krita 4.0.0 was released on March 22](https://krita.org/en/item/krita-4-0-0-released/). [Discussion on the Chocolatey page](https://chocolatey.org/packages/krita#comment-3819948636) indicated that the core team is waiting on the 32 bit release. The Krita team tweeted yesterday that they have had very low demand for the 32 bit package and may be discontinuing it - [see Twitter thread](https://twitter.com/Krita_Painting/status/976907317462601729). Starting an issue per @gep13 request.

## Your Environment
N/A

**Comment by AdmiringWorm** [comment]
Since the authors have supplied 32bit binaries for krita, and the 4.0.0 package have been released, I believe we can close this issue now.
