### ISSUE TITLE
make: Please install shims for "gmake"

### ISSUE THREAD

**Issue by mcandre** [chocolatey/chocolatey-coreteampackages#998]
Some project builds invoke GNU make as "gmake", which breaks in environments where GNU make is provided only as "make".

Please add shims so that build scripts referencing "gmake" can run better in Windows.

A `gmake.bat` script would go far, though a `gmake` POSIX sh script is likely needed as well so that Cygwin environments can also find the shim. Or just make a `gmake.exe` that passes arguments to `make.exe`, whichever.

**Comment by AdmiringWorm** [comment]
I'm guessing you're talking about the `make` package?
If so, then you're unfortunately in the wrong repository, this repository doesn't maintain the make package.

Please contact the maintainer(s) of the package.
